### ISSUE TITLE
Error message 'The data could not be saved' is triggered if the user tries to delete an entity after filed validation is triggered

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9050] opened 2022-05-03 10:55 UTC
### Bug Description

When a user triggers a date field validation and tries to delete an entity afterwards, an error message is triggered and the entity is deleted without the user being informed of this again.

### Steps to Reproduce

I:
1. Open a case and change the 'Date of Report' to a date in the future;
2. Click 'Delete' at the bottom of the page;
-> 'Confirm Deletion' pop-up is triggered;
3. Click 'Yes' in the pop-up;
-> 'Unsaved changes' pop-up is triggered;
4. Click 'Save changes' in the pop-up;
-> 'Please check input data - Date of report can not be in the future' message is triggered;
5. Close the message and change the 'Date of Report' to the current date;
6. Click 'Save' at the bottom of the page.

II:
1. Action steps to reproduce 1 to 5 from flow I;
2. Click 'Delete' at the bottom of the page.

### Actual Behavior

An error message appears: 'A problem has occurred. The data could not be saved because it has been changed in the meantime'.

If the user closes the error message and refreshes the page, or navigates back to the main page of the directory, it is visible that the case was deleted and the 'Date of Report' inputted at step 5 is not saved.

### Expected Behavior

I: No error message is displayed; the case is saved after the user clicks 'Save' at the bottom of the page; the case is not deleted unless the user clicks 'Delete' again.

II: No error message is displayed; the case is deleted after the user clicks 'Delete' again at the bottom of the page.
 
### Screenshots

GIF of the steps to reproduce for flow I:
![Flow I](https://user-images.githubusercontent.com/96909231/166441122-dc10f5fe-1106-4bcf-85bf-d1cf84d5c962.gif)

GIF of the steps to reproduce for flow II: 
![Flow II](https://user-images.githubusercontent.com/96909231/166441139-81857025-6375-49ce-8987-2ea009136596.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(78596ba)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

**Comment by MateStrysewske** [comment] 2022-05-10 09:07
@adinaflorea9 I think this is a duplicate of #8607 (or would at least be fixed by it).

**Closed by MateStrysewske** 2022-05-10 09:07 UTC
Labels: bug, contacts, cases, events, immunizations, travel entries
