### ISSUE TITLE
longitude and latitude get mixed up for maps

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4936] opened 2021-03-29 09:28 UTC
### Bug Description
When the geo coordinates for the maps in Sormas are configured, the system mixes up longitude and latitude.
### Steps to Reproduce
1. Set the coordinates for the maps in Sormas
2. Check the case status map

### Expected Behavior
Sormas should use longitude and latitude in the correct way
### Screenshots
<img width="777" alt="Screen Shot 2021-03-29 at 11 19 09 AM" src="https://user-images.githubusercontent.com/70317594/112816324-90d52200-9081-11eb-8b39-d58833d785cf.png">

**This map display actually conforms to latitude: 10.53 and longitude: 52.21**

<img width="555" alt="Screen Shot 2021-03-29 at 11 12 04 AM" src="https://user-images.githubusercontent.com/70317594/112816341-9599d600-9081-11eb-9a58-f13027a92b70.png">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox, chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment] 2021-03-29 11:41
@kwa20 I can't reproduce this on my system, works perfectly fine there... Can you please verify that this bug exists on another test instance?

**Comment by kwa20** [comment] 2021-03-29 11:43
@MateStrysewske test1402.sormas-oegd.de displays the same location on the map.

**Comment by MateStrysewske** [comment] 2021-03-29 12:48
@kwa20 @vidi42 tested this on test-de1 and didn't encounter the problem there. Our guess is that this is associated with either an incorrectly configured .env file on these systems that mixes up latitude and longitude, or that the docker-compose.yml on these systems is assigning them wrong to the SORMAS properties. In any case, this seems like a configuration problem on the affected servers, not like a general SORMAS issue.

**Comment by kwa20** [comment] 2021-04-01 16:14
@MateStrysewske We investigated further and @nliakm and me noticed that the problem occurs under the following conditions:

- country.name = germany AND a region is active the coordinates are mixed up

other combinations work like:
- country.name = germany + archived regions
- country.name = switzerland (or else) + regions

**Comment by vidi42** [comment] 2021-04-06 06:32
The issue seems to be caused by a feature we have in SORMAS, which works like this:
* if the user is assigned to a region or a district which are part of the shapes files, it calculates the center and displays it
* if the region or district of the user don't have a match in the shapes file, it displays the coordinates configured in the properties file
* if the user doesn't have a region or district assigned it calculates the center of all the regions from the shapes file and displays that one

The situation reported by the issue seems to be the third scenario from above, which means that either the calculation is not correct, or the shapes file has some bug in how the regions are drawn.

**Comment by HolgerReiseVSys** [comment] 2021-04-08 13:52
It seems latitude and longitude are switched when creating `GeoLatLon`s in all center  calculations.
`y` should correspond to `latitude` and `x` to `longitude`, see `GeoShapeProviderEjb::buildCountryShape` and `GeoShapeHelper::polygonToGeoLatLons` vs. `lat += polygon.getCentroid().getX();`.

Also, maybe JTS could be levaraged to calculate the centroid of the regions instead of averaging the centroids:
``` java
	protected void updateCenterOfAllRegions() {
		if (regionMultiPolygons.isEmpty()) {
			regionsCenter = null;
		} else {
			Collection<MultiPolygon> multiPolygons = regionMultiPolygons.values();
			GeometryFactory factory = multiPolygons.iterator().next().getFactory();
			Point centroid = factory.buildGeometry(multiPolygons).getCentroid();
			if (centroid.isEmpty()) {
				regionsCenter = null;
			} else {
				regionsCenter = new GeoLatLon(centroid.getY(), centroid.getX());
			}
		}
	}
```

**Comment by vidi42** [comment] 2021-04-19 07:29
In order to test this issues:
* Import all default Continents, Sub-continents and Countries

**Comment by JonasCir** [comment] 2021-04-19 08:58
**How to test this?**
Use this properties file:

```
devmode=true
survnet.url=127.0.0.1
# SORMAS-Docker Deutschland:
country.locale=de-DE
#country.locale=en-US
csv.separator=;
country.epidprefix=DEU
country.name=germany
country.center.latitude=52.2109803
country.center.longitude=10.5314925
# createDefaultEntities=true
map.zoom=10
```
and follow the instructions by @vidi42 in the previous comment.

**Comment by DavidBaldsiefen** [comment] 2021-04-20 07:44
I think this issue is related to #5048

**Comment by DavidBaldsiefen** [comment] 2021-04-20 08:22
For me, the map was upside down _with_ this fix, and correct without it. So something is still fishy here :D

**Comment by DavidBaldsiefen** [comment] 2021-04-20 08:29
I think the actual issue here lies with `GeoShapeProviderEjb.updateCenterOfAllRegions`:
```Java

for (MultiPolygon polygon : regionMultiPolygons.values()) {
				lat += polygon.getCentroid().getX(); // Should be Y
				lon += polygon.getCentroid().getY(); // Should be X
				count++;
			}
```

**Comment by HolgerReiseVSys** [comment] 2021-04-20 09:33
@DavidBaldsiefen That's what my [comment ](#issuecomment-815843661)was about

**Closed** 2021-04-20 12:30 UTC
Labels: backend, bug, dashboard

**Comment by Marko-ilmkreis** [comment] 2021-05-18 04:17
@kwa20 @DavidBaldsiefen This issue is not completed fixed with 1.59.1 which was installed yesterday evening for our instance.
Before this issue occurs the map in the dashboard was centered to our district.
Now is centered to Göttingen, which is around 200 km away from us,
![grafik](https://user-images.githubusercontent.com/74791118/118589438-acff6080-b7a0-11eb-9f00-b6eaf5a82603.png)

**Comment by kwa20** [comment] 2021-05-18 05:20
@Marko-ilmkreis Judging from the Screenshot I'd suspect that the default coordinates are not correctly set in the properties. If it should be centered around Ilmenau (50.68N, 10.92E) a small difference could result in this display, especially with a high enough zoom.

@nliakm would you be able to verify this?

If my suspicion is incorrect there seems to be something off

**Comment by Marko-ilmkreis** [comment] 2021-05-18 05:23
@kwa20 This coukld be the reason, but then the question how to set these coordinates as we don't have access to it. Is this was set not properly for our instance during the update it might be affect other GAs as well.

**Comment by DavidBaldsiefen** [comment] 2021-05-18 07:04
@Marko-ilmkreis 

The coordinates are specified in the `sormas.properties` file, specifically parameters `country.center.latitude` and
`country.center.longitude`. In your case, I would assume you'd probably have to contact netzlink in that regard

**Comment by Marko-ilmkreis** [comment] 2021-05-18 07:10
@DavidBaldsiefen as they were set correctly in the past there might be a change with the last update which causes the wrong setting.

**Comment by kwa20** [comment] 2021-05-18 07:46
@Marko-ilmkreis @DavidBaldsiefen These are the properties on the ilmkreis system:

<img width="771" alt="Screen Shot 2021-05-18 at 9 36 31 AM" src="https://user-images.githubusercontent.com/70317594/118611989-a6cbad00-b7bd-11eb-9a68-cd63499a84fe.png">

When entering these coordinates in google maps they seem to be the correct ones.

**Comment by Marko-ilmkreis** [comment] 2021-05-18 07:51
@kwa20 @DavidBaldsiefen Yes, they are correct and pointing into our building :-)

The coordinates of the shown map are something like: 51.51312 10.25951 (for Duderstadt in the centre of the map).

**Comment by DavidBaldsiefen** [comment] 2021-05-18 08:06
On my instance, the coordinates from above center the map correctly:

![image](https://user-images.githubusercontent.com/4655486/118614859-776a6f80-b7c0-11eb-8c6d-53c2ce47cbf4.png)


@kwa20 Do you also have access to the servers geocoding-properties? 
(`geocodingServiceUrlTemplate`, `geocodingLongitudeJsonPath`, `geocodingLatitudeJsonPath`, `map.zoom`)

If yes, could you send them to me (per email) so I can look into them?

**Comment by kwa20** [comment] 2021-05-18 10:23
@DavidBaldsiefen This is what I got from Netzlink regarding the Ilmkreis system:

<img width="801" alt="Screen Shot 2021-05-18 at 12 20 16 PM" src="https://user-images.githubusercontent.com/70317594/118635223-a0e0c680-b7d3-11eb-948c-749c3878358a.png">

**Comment by DavidBaldsiefen** [comment] 2021-06-07 07:20
I've tried it again with the exact settings provided, and it still works for me

**Comment by kwa20** [comment] 2021-06-07 07:29
@DavidBaldsiefen Did you set the country.name? This seems to cause the problem (#5666)

**Comment by DavidBaldsiefen** [comment] 2021-06-07 07:43
@kwa20 I have set the `country.name` to `germany`

What users did you test it with? I've found some code that indicates the users region plays a role (for some reason). Currently the center is determined this way apparently:

- If User is of national user type OR does not have a region determined:
   - Calculate the center of all regions
- Else if the user has a region:
   - calculate the center of that region
- Else if both above methods fail (e.g. because of incorrect shapefiles):
   - Take the center defined in the sormas.properties

I will continue my investigation, but tbh this seems like very weird behavior, as it would make the property nearly obsolete. This would also explain why removing the country.name in your case leads to the map being centered according to the properties, as the shapefile-calculation might fail in that case. Can you check in the statistics tab if your shapefiles are correctly calculated, or even visible at all? (= districts being drawn on the map)

**Comment by kwa20** [comment] 2021-06-07 08:36
@DavidBaldsiefen The center of the map indeed changes depending on the user that is logged in. I initially tested with admin + national user and then with surveillance supervisor and surveillance officer. Judging on the assigned region, it seems to take the center of that region rather than the deposited coordinates, although I cannot clearly say if the center is definitely correct. If an officer is logged in, the district is not considered but the map is shown as seen for supervisor with the same assigned region.
