### ISSUE TITLE
Allow admin users to give certain users access to delete and merge duplicates [0.5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2316] opened 2020-06-12 15:32 UTC
### Situation Description
We have situations where some web users who are very good in data management but have limited performance as they can't delete or merge duplicates which can only be done by admins
### Feature Description
We could have a sub-menu within the users menu where we can choose users that will have special access to delete and merge duplicates, and also view list of users with such access @bernardsilenou @hzi-old @MateStrysewskeSym @MartinWahnschaffeSymeda

**Comment by MateStrysewskeSym** [comment] 2020-06-15 06:02
Could this be tied to user roles on the Nigerian server right now or is it on a per-user basis? We will have customisable user roles in the future which would make your proposed feature something that we would probably get rid of again afterwards, so a "quickfix" would maybe be desirable in this case.

**Comment by Iheanacho2027** [comment] 2020-06-15 06:31
@MateStrysewskeSym We would like it to be on a per user basis. Because we have some sets of people we would like to give access to delete and merge duplicates, but won't want to make them admins. And yes a quick fix would be highly appreciated

**Comment by bernardsilenou** [comment] 2020-08-02 08:05
@Iheanacho2027 Puting effort in developing something that will latter be thrown in the bin is not a wise decision to make.As Maté already mentioned, we are working towards user right configuration winch will sole problem like this one and others.

One walk around is to give the users the admin role also since you think they are very experienced. Can this be a solution for now? If yes then i will close the ticket.

**Comment by bernardsilenou** [comment] 2020-08-02 08:31
@Iheanacho2027  I added issue #2587. which is somehow a duplicate of this. Please add your comment

**Comment by Iheanacho2027** [comment] 2020-08-02 10:54
@bernardsilenou giving those specific users admin means they would be able to see all data on the system which opposes the reason as to why they are on the platform

**Comment by Iheanacho2027** [comment] 2020-08-02 10:56
@bernardsilenou we could design a merge duplicate user role and a delete user role just as we have an import user role. This can be quickly done i believe

**Comment by bernardsilenou** [comment] 2020-08-02 11:56
> @bernardsilenou we could design a merge duplicate user role and a delete user role just as we have an import user role. This can be quickly done i believe

I think you have not understood me. I will explain in another way:
1. I agree with you that supervisors should be able to delete and merge cases and that is why i created issue #2587. My question to you is if it is OK to add the right to merge duplicate and delete entities (all entities like cases, contacts,, samples, ...) to all supervisors.
2. User roles and rights seem easy but they need more time in reality

**Comment by bernardsilenou** [comment] 2020-08-02 12:02
@Iheanacho2027 I read your comment in issue #2587 and suggest we wait for a while and implement the user right module.

**Comment by bernardsilenou** [comment] 2020-08-02 12:03
I think in about 5 weeks from now, we may start working on it

**Comment by bernardsilenou** [comment] 2020-08-02 12:06
> @bernardsilenou we could design a merge duplicate user role and a delete user role just as we have an import user role. This can be quickly done i believe

This is not a good idea because merge duplicate uses data from all regions and certain users like supervisors are not allowed to see data from other regions.

**Comment by Iheanacho2027** [comment] 2020-08-02 12:23
> > @bernardsilenou we could design a merge duplicate user role and a delete user role just as we have an import user role. This can be quickly done i believe
> 
> This is not a good idea because merge duplicate uses data from all regions and certain users like supervisors are not allowed to see data from other regions.

we can restructure the merge duplicate to be specific to jurisdiction of user roles

**Comment by bernardsilenou** [comment] 2020-08-03 17:54
@Iheanacho2027  this issue will be handled by implementing issue #898  since they are the same thing.
can you not give on user per state admin right as a temporal solution?

**Comment by Iheanacho2027** [comment] 2020-08-03 18:14
Due to guidelines at the national, it's not advisable because they would see all data from the country

**Comment by bernardsilenou** [comment] 2020-08-03 19:50
ok perfect, i have added more refinement to issue #898

**Comment by bernardsilenou** [comment] 2020-10-14 21:49
@Iheanacho2027 @MateStrysewske can we give surveillance supervisors the right to delete cases and do merge duplicate for cases in their region?
@Iheanacho2027 Since we are working on having configurable user specific rights, it would not be possible to add a role with deletion and  merge right only for now. What do you suggest please?

**Comment by MateStrysewske** [comment] 2020-10-15 07:06
@bernardsilenou You can do that by configuring the user rights in the database of the respective server. I don't think it's a good idea to give the delete user right to surveillance supervisors by default.

**Comment by markusmann-vg** [comment] 2020-10-15 08:40
- [ ] create a new role: admin-supervisor who is able to merge and delete duplicates

This will be an exception (as it is urgent) and we are planning a new user rights management concept, where you can manage the user rights on your own.

**Comment by Iheanacho2027** [comment] 2020-10-15 08:53
@markusmann-vg thank you very much

**Comment by bernardsilenou** [comment] 2020-10-15 18:47
admin-supervisor will have these rights only for entities in their jurisdictions, so merge duplicate should only search for entities in the jurisdiction of the admin--user

**Comment by Iheanacho2027** [comment] 2020-10-15 18:52
@bernardsilenou I think we should leave it the was proposed by @markusmann-vg 
Its fine that way

**Comment by Iheanacho2027** [comment] 2020-10-15 23:25
@bernardsilenou pls can you throw more light as regards your last comment. Thank you

**Comment by bernardsilenou** [comment] 2020-10-16 20:57
@Iheanacho2027 
My last comment was not so important.
when the merge duplicate function is called, it looks for cases in all regions. For admin-supervisors account, the system will filter and consider only entities (cases) in the jurisdiction of the admin-sup.  This means if an admin-sup is assigned to region 1 and merge duplicate cases, duplicate cases in district 2 would not appear on their view.

**Comment by Iheanacho2027** [comment] 2020-10-21 12:48
@bernardsilenou pls can this be prioritized for 1.51.0. This is very important at this point in time due to the large chunk of duplicates currently on the system, and will help achieve a clean database at this point of the pandemic

**Comment by bernardsilenou** [comment] 2020-10-21 16:30
@Iheanacho2027 I absolutely agree with you. We have this issue on board for 1,51

**Comment by Iheanacho2027** [comment] 2020-10-29 01:47
@bernardsilenou pls can this be part of 1.51.0. This will be greatly appreciated as our users in Nigeria are looking forward to this @Chinedar

**Comment by AndyBakcsy-she** [comment] 2020-10-29 07:51
Reopening the issue as there seems to be a problem when clicking on the Merge button for an Admin Surveillance Supervisor an error message is displayed:

[Payara 5.194] [INFO] [] [] [tid: _ThreadID=38 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1603900331839] [levelValue: 800] [[
  E175211.834|     > java.lang.UnsupportedOperationException: User RCWV73-QF37CC-UYIHI3-OQ4ZCFPM is not allowed to delete cases.
 (de.symeda.sormas.ui.SormasErrorHandler.java:78)
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) (edited) 

![](https://files.slack.com/files-pri/TC4REAN2E-F01DB1THGAJ/image.png)

**Comment by Chinedar** [comment] 2020-10-29 10:04
Yes please. This is very much needed.

**Comment by AndyBakcsy-she** [comment] 2020-11-03 12:43
Verified issue on the latest version of SORMAS Version: 1.51.0-SNAPSHOT

**Comment by MateStrysewske** [comment] 2020-11-03 15:21
- [ ] Give the admin supervisor all user rights that the normal surveillance supervisor has

**Closed** 2020-11-04 08:46 UTC
Labels: Users & Rights, Verified by QA, feature

**Comment by AndyBakcsy-she** [comment] 2020-11-04 13:34
Verified Based on https://github.com/hzi-braunschweig/SORMAS-Project/commit/fbe810fba1aaf2b2c8e2280e75f141281df9cade  
The user has access to :
- the generation of Quarantine documents, 
- Line Listing under the Configuration tab
- the configuration of outbreaks 
- the aggregate reports
- all other places specified in the document
