### ISSUE TITLE
Climedo doesn't sync correctly (EJBAccessException)

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8807] opened 2022-04-13 06:50 UTC
### Bug Description

There seems to be a user rights or authentication problem when trying to sync climedo with SORMAS. 
The error in logs says: "Client not authorized for this invocation"

### Steps to Reproduce

Register SMS as well as by e-mail, enter the symptoms and submit. 
No error message, but the system does not show the entry, neither under "Follow-up" nor in the "Follow-up view".

Doesn't work with "ExternalVisitDto #personUUID: XXGMVF-AF3BDN-6D2DPY-ECW4KG2I" on https://test1402.sormas.netzlink.com/

### System Details

* Device: 
* SORMAS version: 1.70.2
* Android version/Browser: 
* Server URL: 1402
* User Role:

### Additional Information

Log excerpt [Climedo_User_Not_Authorized.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8479129/Climedo_User_Not_Authorized.txt)

```bash
Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2397)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2183)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy665.toDto(Unknown Source)
	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
	at de.symeda.sormas.backend.visit.VisitFacadeEjb.onVisitChanged(VisitFacadeEjb.java:622)
```

**Comment by FredrikSchaeferVitagroup** [comment] 2022-04-13 09:29
It seems to not be reproducible on other test systems and my local system. 
I noticed that some invalid custom user role configuration reappeared on https://test1402.sormas.netzlink.com/. So even though netzlink closed the related ticket in their support system, and the behaviour and log exception is different, the underlying problem probably is the same as in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8739.

Probably, netzlink has to fix the configuration there again (and persist the fix this time). This would mean that no changes in SORMAS are necessary.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-04-13 09:32
I will contact netzlink again. Once the config was fixed and the problem got resolved by that, I will discard this ticket.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-04-14 05:41
The related netzlink ticket got closed, netzlink stated that the config issue is resolved now.
@JaquM-HZI Because user acounts I login with got deactivated (again), I can not login to this instance to verify that the issue got resolved. Please do it yourself, and reopen this ticket if necessary.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-04-14 13:06
The problem seems to still exist on test1402.

**Comment by kwa20** [comment] 2022-04-14 15:07
@FredrikSchaeferVitagroup After some further investigation, we added the following rights to the user role `REST_EXTERNAL_VISITS_USER`:
- `CASE_VIEW`
- `CASE_EDIT`
- `CONTACT_VIEW`
- `CONTACT_EDIT`

sormas=# select * from userroles_userrights;
|                userright                |             sys_period             | userrole_id 
|:-|:-|:-
 SEE_SENSITIVE_DATA_OUTSIDE_JURISDICTION | ["2022-04-14 12:57:04.161582+00",) |           0
 SEE_PERSONAL_DATA_IN_JURISDICTION       | ["2022-04-14 12:57:04.161582+00",) |           0
 SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION  | ["2022-04-14 12:57:04.161582+00",) |           0
 SEE_SENSITIVE_DATA_IN_JURISDICTION      | ["2022-04-14 12:57:04.161582+00",) |           0
 SORMAS_REST                             | ["2022-04-14 13:54:33.2714+00",)   |           0
 EXTERNAL_VISITS                         | ["2022-04-14 13:54:40.855316+00",) |           0
 CONTACT_EDIT                            | ["2022-04-14 14:15:49.009616+00",) |           0
 CASE_EDIT                               | ["2022-04-14 14:15:54.771671+00",) |           0
 CASE_VIEW                               | ["2022-04-14 14:25:57.85049+00",)  |           0
 CONTACT_VIEW                            | ["2022-04-14 14:41:56.761425+00",) |           0


After adding those rights to the userrole, the REST call that you provided worked fine.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-04-20 04:55
The fix can only be tested locally. One should now be able to post a visit via `{{environmentUrl}}/sormas-rest/visits-external/` endpoint as a user only having the REST_USER and REST_EXTERNAL_VISITS user role.

**Closed** 2022-04-20 09:14 UTC
Labels: bug, backend, integration, hotfix, major

**Comment by mario-kuehne** [comment] 2022-04-21 10:06
**Reproduction**

Reproduction of error was possible locally with branch `master` (8db7b707b3b076c6eafee877802d5ded3292d91a) with mentioned [API call](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8807#issuecomment-1103470763) 

Response of the API call:
StatusCode: `200 OK`
Response Payload: `[ "TRANSACTION_ROLLED_BACK_EXCEPTION" ]`

![ExternalVisits-ClientNotAuthorized](https://user-images.githubusercontent.com/95228108/164430807-eb841fae-7a53-47eb-9a23-dc0bbe114efc.png)

**BugfixTest**
Succesfully tested bugfix locally with branch `hotfix-1.70.3` (b827119474b190b3d15e9fedb0d3461ea50a39f8) with mentioned [API call](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8807#issuecomment-1103470763) 

Response of the API call:
StatusCode: `200 OK`
Response Payload: `[ "OK" ]`

No Exception shown in serverlogs & corresponding entity created in database table 'visit'
