### ISSUE TITLE
Introduce new quarantine checkbox to mark quarantine extension + filter in directories [2]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2264] opened 2020-06-05 07:01 UTC
### Situation Description
Health deparments prolong the quarantine period in some instances and are looking for the option to document this. Futhermore, they want to have an overview of all contacts/ cases for which the quarantine order was prolonged.

### Feature Description
Introduce new checkbox 'Quarantine period extended?' below the following existing quarantine-related checkboxes (for cases and contacts):
![1](https://user-images.githubusercontent.com/63781233/83845954-18742d80-a70a-11ea-92bb-65acb1dc363a.PNG)

This checkbox would only make sense if the user would be able to search the case or contact directory for prolonged quarantine, so please include a checkbox in the case and contact directory.
Please also include these fields in the export sheets.

I think a checkbox is sufficent, and health departments could simply update the quarantine end date. What do you think?

**Comment by bernardsilenou** [comment] 2020-06-05 09:27
@max-hzi I have 2 suggestions: 
1, Why designing 2 variables that capture the  same thing twice? We can reduce the number of questions by using drop-downs. 
For example
Use: "Means of quarantine order" : Verbal, officially documents, Other, Unknown.  Followed by "date of  order".  By doing this you already reduce the number of variables by 2. Other countries might have more means of ordering quarantine and we will not be able to list them all.

3 Concerning the filter for extended quarantine, I will  say  suggest that we do not add another box for it but store this information is the db and add a filter for it.
If the date of quarantine is changed, we show a pup up to the user asking if they are extending it, if they choose yes, then we tag this in the db and use it fro filter. 

My only worry is that we need reduce the number of check boxes we have as much as we can because we already have enough.
Let me know hat you think please

**Comment by max-hzi** [comment] 2020-06-05 13:13
>1, Why designing 2 variables that capture the same thing twice?

I think this is a very valid point, but unfortunately, all of the current fields are necessary. Step 1 is the oral order, step 2 the written order. E.g. Berlin needs this info independently. Step 3 would be the lifting of the quarantine, for which there is no possibility to document yet. That's a different issue though. 

We had some discussion concerning the implemented fields and I don't think we should change them - because they work.

> I will say suggest that we do not add another box for it but store this information is the db and add a filter for it.
If the date of quarantine is changed, we show a pup up to the user asking if they are extending it, if they choose yes, then we tag this in the db and use it fro filter.

I think this solution is a very good idea. Health departments could comment in the comment fields in case they want to see if quarantine was prolonged later.

**Comment by bernardsilenou** [comment] 2020-06-05 20:28
@max-hzi Thanks for explaining, I now get it, so a single contact can have both quarantine orders (verbal and document).

**Comment by markusmann-vg** [comment] 2020-07-27 12:33
Todo:
- [ ] add field as checkbox
- [ ] Store the information of extended quarantine in the db and add a filter for it.
- [ ] If the date of quarantine is changed, we show a pup up to the user asking if they are extending it, if they choose yes, then we tag this in the db and use it from filter.

**Comment by bernardsilenou** [comment] 2020-07-27 14:51
@markusmann-vg  Few comments:

> Todo:
> 
> * [ ]  add field as checkbox, e.g. retrospective data entry

- Do the users need to specify this? We already retrieve this by comparing the date of creations and the date of report of the entity.  What is the motivation for adding this field pls? are we going to add it as attribute to all entities?. My suggestion is to only add a filter it only if needed by users.

> * [ ]  Store the information of extended quarantine in the db and add a filter for it.

- This should apply to reduced quarantine also as some countries used 10 days for quarantine rather than the normal incubation period of the disease.

> * [ ]  If the date of quarantine is changed, we show a pup up to the user asking if they are extending it, if they choose yes, then we tag this in the db and use it from filter.

-Add a corresponding pop up message if quarantine days is reduced

**Comment by markusmann-vg** [comment] 2020-07-28 13:26
in scope for this ticket: Extending the quarantine
out of scope: Reducing the quarantine (If this is wanted, pls. add another issue)

**Comment by bernardsilenou** [comment] 2020-08-11 17:37
@leventegal-she I did a test on this issue and did not understand how the variable is implemented. I could not manually set the variable to true which it fine. However, changing the end of quarantine date to any day does not affect the variable.
Expected behavior:
- When quarantine end date is after end of follow up date, then show pup up asking users if they  want to set quarantine end after end of follow up. If they accept then set "quarantine period extended " to True.
version 1,46

**Comment by bernardsilenou** [comment] 2020-08-11 18:09
@leventegal-she I spent some time and understood how it is implemented. I think the cause of the misunderstanding was from the specification of the issue. I explain why.
This request came in at a time where the end of quarantine was the same as end of follow up, so users did not have the possibility to change and tag entities with extended quarantine end date from the expected end date (fixed reference date == end of followup date == date of last contact with case (for contacts) / date of report or symptom onset (for cases) + d, where d== incubation period of disease == 14 for COVID). 
- Te current implementation uses the reference date == previous date in the sequence. This is erroneous because if the user make an error the fist time they register the end date, the system will tag it as extended quarantine when they latter correct the error. I will create another ticket for refinement

**Comment by bernardsilenou** [comment] 2020-08-11 18:15
Associated details are explained in #2235 and #2233

**Closed by bernardsilenou** 2020-08-11 18:15 UTC
Labels: Case Surveillance, Contact management & follow-up, feature, sormas-app, sormas-ui
