### ISSUE TITLE
Archiving of many cases at once (3000+) does not work

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2894] opened 2020-09-16 13:31 UTC
### Bug Description
- Under 1000 cases, archiving time is short and all works fine. For about 50000 cases, system takes works for some time and return error message.
### Steps to Reproduce
1.
2.

### Expected Behavior
- Archiving should be possible in max 3 min for 100000 cases.
- Maybe we archive cases immediately and latter archive the associated entities like contacts at back-end so users do  not need to wait for log
### System Details
* Device:
* SORMAS version:1,48
* Android version/Browser:

**Comment by bernardsilenou** [comment] 2020-09-16 13:55
This belong to the same improvement story with #2889

**Comment by StefanKock** [comment] 2020-09-29 11:58
The cause for the problem: The archiving by selection in the UI calls _CaseFacade.archiveOrDearchiveCase(String caseUuid, boolean archive)_ for every case in the same JTA transaction. Internally only _Case.archived:boolean_ is changed but by loading the JPA entity. This results for too much entities in a blown up transaction with entities in the hibernate cache.

Possible solution: Reuse the approach of _CaseFacadeEjb.archiveAllArchivableCases_ by enable to build another _where_ clause by _caseUuids_ (maybe batched and not 1000+ at once and beware of parameter limit, see #2193). But the implicit change would be that the _Case.changeDate_ will not by updated anymore.

**Comment by MateStrysewske** [comment] 2020-09-30 07:16
Adding a _CaseFacade.archiveOrDearchiveCases(List<String> caseUuids, boolean archive)_ method that does this with a where clause should still update the changeDates while getting rid of the individual transactions, shouldn't it?

**Comment by StefanKock** [comment] 2020-09-30 10:07
Clarified with @MateStrysewske what to do:
- [ ] Move the CriteriaUpdate-Logic of _CaseFacadeEjb.archiveAllArchivableCases_ to _CaseService_ to enable JTA Tx separation per batch.
- [ ] Enhance this new method: set _Case.changeDate = now()_
- [ ] Introduce a layer before this method to separate the uuids into batches with batch size less than parameter limit.
- [ ] Change the archiving feature of the UI to sent all Case uuids at once.
- [ ] Change the single archiving method also to new pattern.

**Comment by StefanKock** [comment] 2020-09-30 15:19
I did the work but was not able to test it in the sormas-ui since I did not find how to archive cases.
Also I started on start after 1.49.0 since I had problems with development HEAD.

**Comment by StefanKock** [comment] 2020-10-01 06:28
Newly considered improvements:

1. Log execution times to debug the performance
2. Make batchSize configurable in sormas.properties
3. Reduce batchSize because 32k uuids result in roughly 1.2MB sql statement

**Comment by StefanKock** [comment] 2020-10-01 07:59
Discussed with @HolgerReiseVSys: Taking a smaller batchSize (something like 100 to 1000) would made better testable for us to calculate the performance.

**Comment by StefanKock** [comment] 2020-10-05 08:10
Discussed with @MateStrysewske: 
> Newly considered improvements:
> 
>     1. Log execution times to debug the performance
Yes, on debug level after all batches are executed.

>     2. Make batchSize configurable in sormas.properties
No, because next point should figure out a good batch size.

>     3. Reduce batchSize because 32k uuids result in roughly 1.2MB sql statement
Yes, test with batchSizes between 100 and 1000 to find out a performant batchSize.

**Comment by StefanKock** [comment] 2020-10-05 09:16
I tested the execution time in the backend with some sample data on my DEV system:
```
batchSize = 1000
caseCount = 2002
durations  = 255ms, 235ms, 243ms


batchSize = 1000
caseCount = 1191
durations  = 166ms, 145ms, 143ms

batchSize = 1000
caseCount = 400
durations = 67ms, 51ms

batchSize = 100
caseCount = 2002
durations  = 273ms, 277ms

batchSize = 2000
caseCount = 1999
durations  = 276ms, 244ms, 235ms
```

I decided to select a batchSize = 1000 to have a reasonable query size.

I expect linear behaviour here, so it will take approx. 15s for 100_000 cases to archive/unarchive for the backend.
Not considered is the work in the sormas-ui to handle the amount of cases in the grid to select and extracting the _uuid_ of each case. And the performance will also be dependent on the CPU and RAM the host can provide.

**Comment by StefanKock** [comment] 2020-10-05 11:38
Assigned @MateStrysewske for reviewing.

**Comment by StefanKock** [comment] 2020-10-07 07:45
Was already merged yesterday by @MateStrysewske

**Closed by StefanKock** 2020-10-07 07:45 UTC
Labels: Case & Outbreak Management, SSD, bug, performance, sormas-backend, sormas-ui

**Comment by raghupola-vg** [comment] 2020-10-13 14:17
Tested with approx 3800 cases on (test.sormas.netzlink environment) and archiving them took less than 3 seconds.
