### ISSUE TITLE
Surveillance Officer is not able to export aggregate reports

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9747] opened 2022-07-06 12:09 UTC
### Bug Description

Surveillance Officers should be able to export aggregated reports based on #9052, where it was specified that they should be given the AGGREGATE_REPORT_EXPORT user right.

### Steps to Reproduce

1. Log into the vaadin-app with a Surveillance Officer user;
2. Navigate to the mSERS directory.

### Actual Behavior

The 'Export' button is not visible for the Surveillance Officer user.

In the 'Export User Roles' table, the Surveillance Officer still has the AGGREGATE_REPORT_EXPORT set to NO.

### Expected Behavior

The 'Export' button is visible for the Surveillance Officer user in the mSERS directory.

In the 'Export User Roles' table, the Surveillance Officer still has the AGGREGATE_REPORT_EXPORT set to YES.

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(551f50b), 1.73.0
* Android version/Browser: Chrome
* Server URL: local machine, TEST; Not RELEASE/PROD
* User Role: Surveillance Officer

**Comment by StefanKock** [comment] 2022-07-11 06:42
Is this reproducable on a released version?

**Comment by adinaflorea9** [comment] 2022-07-11 07:42
From what I am able to find this is the situation:

- on https://release-international.sormas.netzlink.com, where SORMAS version is 1.73.1, the Surveillance Officer user has the 'Export' button in the mSERS directory;

- on test.sormas.netzlink.com, where SORMAS version is 1.74.0-SNAPSHOT(c17daa0), the Surveillance Officer does not have the 'Export' button in the mSERS directory;

- on my local machine, where SORMAS version is also 1.74.0, the Surveillance Officer does not have the 'Export' button in the mSERS directory.

**Comment by StefanKock** [comment] 2022-08-01 08:01
The problem discussed here is two-fold:
1. There is no automatic update of user rights of default user roles since #4461, and #9052 was merged after that and delivered in the same version.
2. If the user roles where migrated with #4461 with countryLocale A (fallback: none means EN), but the system is now running with countryLocale B the user roles are not found anymore by name (to be mitigated by #9645 in the future).

**Comment by MartinWahnschaffe** [comment] 2022-08-01 08:21
Looks like my specification for the migration was wrong. SHould have considered CASE_EDIT instead of CASE_EXPORT. Stefan will add more details

**Comment by StefanKock** [comment] 2022-08-01 08:24
Update: Commit 4bb95bf did run a user rights migration as defined in #9052 but did not consider that the mentioned user roles does noch have `CASE_EXPORT` right. It will need to be based on `CASE_EDIT`. It's not a problem for release to release updates, but a problem for DEV/TEST.

**Comment by StefanKock** [comment] 2022-08-01 08:33
Lowered severity because the feature is not broken on released versions.

**Closed** 2022-08-02 08:19 UTC
Labels: bug, vaadin-app, import & export, reporting, minor
