### ISSUE TITLE
medical facility and hospital wrongfully filled on many forms

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4120] opened 2021-01-24 21:04 UTC
### Bug Description
When opening forms that have facility category and facility type fields, medical facility and hospital are filled for existing entities. It also seems as if old entries were overwritten. This includes cases creation form and place of stay, home address on person forms, event location, user address (potentially more).
### Steps to Reproduce
1. Go to any form that has facility fields.
2. Check overwritten or prefilled entries.

### Expected Behavior
Fields should not be prefilled or overwritten with medical facility and hospital
### Screenshots
<img width="465" alt="addressFieldBug" src="https://user-images.githubusercontent.com/70317594/105643338-95b60380-5e8f-11eb-971d-68767f33c710.PNG">

### System Details
* Device:
* SORMAS version: 1.54.0
* Android version/Browser: firefox 
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment] 2021-01-24 22:43
@kwa20 This is not a bug, it was specified like this.
The reason is that for most instances, the cases are identified in a hospital, thus user only need to change if otherwise. In addition, in some countries in Africa, this is the only combination of options that applies.
Do you think we should add a configuration for this? did the users complain?

**Comment by bernardsilenou** [comment] 2021-01-24 22:50
@kwa20 How I got it, its a bug
- But when creating a case we prefill but not transfer to other entities linked to the case, right?

**Comment by kwa20** [comment] 2021-01-25 07:08
@bernardsilenou it just pops up here and there, it does not specifically occur upon case creation. You can easily check this when e.g. editing existing users. They all have these fields filled in their address section.

**Comment by MateStrysewske** [comment] 2021-01-25 08:48
@kwa20 This is fine for the case creation form because it's just the default value, and it is also fine for events and exposures that were formerly assigned to the type of place "hospital" that is now removed, but it is definitely not okay for things like person address. We'll fix this for the upcoming hotfix, but the data on test systems will likely stay "corrupted".

**Comment by kwa20** [comment] 2021-01-25 10:47
@MateStrysewske I checked again and it does not seem to occur for exposures if nothing was entered before. For events, the type of place and facility have indeed changed for every event, regardless of hospital being entered previously or not.

**Comment by StefanKock** [comment] 2021-01-28 13:30
The problem was caused by #3617 and #3680 due to a wrong sql migration script.

**Closed** 2021-01-28 15:10 UTC
Labels: backend, bug, events, hotfix

**Comment by AndyBakcsy-she** [comment] 2021-02-01 11:01
Validated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the test.sormas.netzlink.com environment.
