### ISSUE TITLE
Additional upload field option for contacts and cases

### ISSUE THREAD

**Issue by Mimsel** [hzi-braunschweig/SORMAS-Project#1811] opened 2020-04-14 22:37 UTC
### Situation Description
German version: health departments want a feature where they can upload additional word/pdf files to the according case/contact
### Feature Description
The upload option should be possible for both, contacts and cases and should be connected to the contact/case.

**Comment by MateStrysewskeSym** [comment] 2020-04-15 09:06
Duplicate of #1771

**Closed by MateStrysewskeSym** 2020-04-15 09:06 UTC
