### ISSUE TITLE
Bug on SORMAS dashboard

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1331] opened 2019-10-03 09:25 UTC
The section on details about sample results shows null values on the dashboard

![dashboard bug](https://user-images.githubusercontent.com/50739609/66115134-22b4b980-e5c8-11e9-8e60-5c28fe8adc8e.JPG)

**Comment by MateStrysewskeSym** [comment] 2019-10-04 06:18
@Iheanacho2027 This is not a bug, but an unfortunate side effect of the changes in #1302. Samples now track the date their final laboratory results have been changed and this date is used to calculate how many new test results actually came in (because we don't have another reliable way of detecting which test results are the ones that are relevant for this calculation). Since this date is by default empty for all existing samples, you will get 0s for all currently existing samples. I fear that there's no real way around this unless we use a fallback mechanism, but since this is, I suppose, more of a surveillance mechanism I'd believe that it's not that grave? Starting now, for all new samples, you will have correct numbers on your dashboard.

**Comment by Iheanacho2027** [comment] 2019-10-04 09:26
What do we do about the previous samples because viewing all sample information is important for observers who want to get quick and first hand details about the cases and samples on the dashboard

**Comment by MateStrysewskeSym** [comment] 2019-10-04 12:42
@Iheanacho2027 I'm afraid there's no way to display past information "correctly", i.e. according to the new specifications in #1302. I could theoretically re-instate the old logic for previous samples, but I doubt that would be helpful for you at all since #1302 was opened because the old logic was wrong in the first place. What do you suggest?

**Comment by MateStrysewskeSym** [comment] 2019-11-11 16:58
This has been resolved in #1349.

**Closed by MateStrysewskeSym** 2019-11-11 16:58 UTC
Labels: Laboratory, discuss
