### ISSUE TITLE
User Role: Complete Problem Message

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10340] opened 2022-09-12 11:49 UTC
### Bug Description

In order for the admin to make an informed decision, he lacks information. In addition to the required right, the rights causing the message should also be displayed. This way the admin can decide whether to add the required right again or to remove the causing rights as well. 

### Steps to Reproduce

1.  Create a user roll from the Admin (Default) template
2.  Remove the e.g. the "View existing cases" right
3.  Try to save 
4.  Have a look at the message

![image](https://user-images.githubusercontent.com/101708230/189642559-f6a9e710-9c5d-4493-a652-3da5a583efa9.png)

### Expected Behavior

The causing / selected rights are mentioned.  
A problem has occurred: The user right(s) [...] are required based on the selected ones:  [  **- List of rights  -** ]

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrom
* Server URL:  https://test1401.sormas-oegd.de/
* User Role: Admin

**Comment by MateStrysewske** [comment] 2022-09-13 07:48
Duplicate of #10339.

**Closed by MateStrysewske** 2022-09-13 07:48 UTC
Labels: duplicate
