### ISSUE TITLE
S2S_quick filters 'pending' and 'accepted' fails on 1.74.3 in one health department

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10552] opened 2022-10-05 14:40 UTC
### Bug Description

Health department Mühldorf a Inn. reports that the quick filters _pending_ and _accepted_ on share request directory on 1.74.3 are not working. By pressing the buttons an error message appears and no shared request is shown anymore. 

### Steps to Reproduce

1. open the share request directory on 1.74.3 
2. Click on the quick filters

I cannot reproduce this bug on SchniSchu. Health Department will send the timestep an NLI will provide the logs.
### Expected Behavior

Shared cases/contacts/events are shown.
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/194088146-8e117996-7145-4518-ac96-0d48df0946d8.png)

### System Details

* Device:
* SORMAS version: 1.74.3
* Android version/Browser:
* Server URL: 
* User Role:

### Additional Information

Logs show that sorting by `actions` was tried, and that's not implemented. 
```
Caused by: java.lang.IllegalArgumentException: actions
	at de.symeda.sormas.backend.sormastosormas.share.sharerequest.SormasToSormasShareRequestFacadeEJB.getIndexList(SormasToSormasShareRequestFacadeEJB.java:134)
```

Relevant code: https://github.com/hzi-braunschweig/SORMAS-Project/blob/v1.74.3/sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/sharerequest/SormasToSormasShareRequestFacadeEJB.java

**Comment by StefanKock** [comment] 2022-10-12 07:35
I checked the [relevant code](https://github.com/hzi-braunschweig/SORMAS-Project/blob/v1.74.3/sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGrid.java): It appears that sorting on the column with the buttons was not disabled and if you click on the header, the backend fails to sort the data by the "buttons". Workaround: Don't try to sort the view by clicking above the action buttons.

The code was changed in #9755 and sorting of the `actions` column was disabled. 

Since there is an easy workaround and the problem is already fixed in current development, I discard this ticket.

**Closed by StefanKock** 2022-10-12 07:35 UTC
Labels: bug, vaadin-app, minor, s2s
