### ISSUE TITLE
Pathogen test time can be set before the sample collection time

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#3968] opened 2021-01-11 20:40 UTC
### Bug Description
The system is able to detect error of earlier sample test date to sample collection date. However, it does not detect earlier sample test time to sample collection time for the same date.
### Steps to Reproduce
1. Create a sample for a case.
2. Choose the same date for sample collection and a pathogen test. 
3. Choose a pathogen test time as 00:30 and a sample collection time as 02:00. (Thus, testing sample before collecting it.)

### Expected Behavior
There should be an error alert stating that: "Pathagen test time cannot be earlier than sample collection time"
### System Details
* Device: MacBook Pro
* SORMAS version:1.53.0
* Android version/Browser:Safari
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/#!cases/data/XZLUTD-TKACZM-L3EGWV-G7HASKWY* 
* User Role: Surveillance Supervisor

**Comment by bernardsilenou** [comment] 2021-01-11 20:48
This is followup of #3684

**Comment by MateStrysewske** [comment] 2021-01-12 08:20
Duplicate of #3808

**Closed by MateStrysewske** 2021-01-12 08:20 UTC
Labels: bug
