### ISSUE TITLE
Sorting of `Primary Phone Number` & `Primary Email Address` columns error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#10687] opened 2022-10-19 13:29 UTC
### Bug Description

Clicking on the column headers `Primary Phone Number` (Persons, Cases, Contacts) and `Primary Email Address` (Persons) results in an error.

### Steps to Reproduce

1. Persons > Primary Phone Number
2. Persons > Primary Email Address
3. Cases > (Detailed View) > Primary Phone Number
4. Contacts > (Detailed View) > Primary Phone Number 

### Expected Behavior

Columns ordered on each directory, no error message shown.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/196701845-1fd67999-de6a-4e9f-b493-7caa11f05452.png)

### System Details

* Device: Desktop
* SORMAS version: 1.76.0
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: admin, national user

### Additional Information

May be (or not) related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/10674 as email address and telephone number are used to register in symptom diaries.  Could also be unrelated and just a stand-alone occurrence as in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4927.

**Comment by ChristopherRiedel** [comment] 2022-10-24 13:22
I've taken a look into this: The problem is a PSQLException: `FEHLER: bei SELECT DISTINCT müssen ORDER-BY-Ausdrücke in der Select-Liste erscheinen`.
According to @BarnaBartha, it looks very much like the problem is related to PersonFacadeEjb lines 1332 and 1370 -1374.
It need a deeper dive to locate the actual problem.

**Comment by AndyBakcsy-she** [comment] 2022-10-28 07:54
Closing ticket as already merged into the hotfix branch

**Closed by AndyBakcsy-she** 2022-10-28 07:54 UTC
Labels: bug, contacts, cases, backend, hotfix, persons, major

**Comment by adinaflorea9** [comment] 2022-10-28 11:54
Verified ticket on the latest SORMAS version from the hotfix branch - 1.76.1-SNAPSHOT(64df5dc).
