### ISSUE TITLE
Contact dashboard taking more than 10 minutes to load n Nigeria Server

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1841] opened 2020-04-17 05:36 UTC
### Steps to Reproduce
1. open the application, surveillance dashboard loads fast
2. click on contact dashboard and wait forever on Nigeria server

### Expected Behavior
Should open in less than a second or two
### Screenshots
![image](https://user-images.githubusercontent.com/19344651/79535536-0c5ede80-807e-11ea-8e82-fcc8226aa1a1.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-04-17 06:25
Duplicate of #1839

**Closed by MateStrysewskeSym** 2020-04-17 06:25 UTC
Labels: bug
