### ISSUE TITLE
Detail import for cases refinement

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2136] opened 2020-05-18 13:51 UTC
### Bug Description
The detained import for cases takes very long to import.
1. The import process takes very long
2, Reactivity occurs when the user click on either "create new case",  "override existing case ..." or "on pick an existing case". We should limit reactivity only when the user click on "confirm" after choosing the right options.
3. When the option pick new case is selected, the system still goes forward and keep the imported case. Import this template, update the imported data in sormas  and import again. While importing again, choose "override existing case ....". The new case is imported also.
4. Perhaps replace "override existing case  with changes from the imported case" with  "Retain existing case and replace missing data in existing case with that of the case being imported"

[template.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4644350/template.xlsx)

4. Column names index of imported case can be organised to  match that of existing case to easy comparison between imported case and existing cases

5, The caption "Health facility name" in "imported case information" is replaced by the name of the health facility
### Steps to Reproduce
1. Import the attached file on .symeda server using detailed import
2. Do it multiple times, for each time, pick the existing case 
3, Go the Case directory and confirm is the case is not imported twice

### System Details
* Device:
* SORMAS version:1.40.1
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-05-19 08:54
@bernardsilenou 

1.) What do you mean by "reactivity"? We need to e.g. disable the list when the users click on "Create a new case" and re-enable it when they click on "Pick an existing case". I don't see a problem with that because this reactivity should not slow down anything.
2.) I don't quite get what's wrong here. I imported the file you've provided multiple times and actually encountered a bug while doing it, but I've never received duplicate cases in this process.
3.) That would be a wrong description of the mechanic because existing data is actually overridden when the imported case has different data for the respective field.
4.) Please open a new issue for this request. I think it makes sense, but it doesn't belong in a bug issue.
5.) I'll open a new bug issue for this one and fix it.

**Comment by bernardsilenou** [comment] 2020-05-19 13:44
> 1.) What do you mean by "reactivity"? We need to e.g. disable the list when the users click on "Create a new case" and re-enable it when they click on "Pick an existing case". I don't see a problem with that because this reactivity should not slow down anything.
This is what i mean by reactivity, clicking on an icon trigger some back and method. Normally this should not a affect the process as you said, but the current implementation it showsup and takes about 40 second for any icon that i click. Maybe we only monitor the "event" when the user click on "confirm"

> 2.) I don't quite get what's wrong here. I imported the file you've provided multiple times and actually encountered a bug while doing it, but I've never received duplicate cases in this process.
I do not also know why, colleagues in France also observed the same thing. 
> 3.) That would be a wrong description of the mechanic because existing data is actually overridden when the imported case has different data for the respective field.

I thought it does the opposite ! So if i understand you well, the reference data is the imported data, not the data already existing in the database? I will create an issue about this and we discuss further

> 4.) Please open a new issue for this request. I think it makes sense, but it doesn't belong in a bug issue. OK Sir
> 5.) I'll open a new bug issue for this one and fix it. Ok

**Comment by MateStrysewskeSym** [comment] 2020-05-19 14:02
@bernardsilenou 

1) The issue here very likely actually comes from the problem fixed in #2075. The clicks in the duplicate selection screen are fine. We'll see whether this is resolved in the next release.
2) Please attach some screenshots showing the problem to this issue.
3) No, it's been like this since we added the feature.

**Comment by bernardsilenou** [comment] 2020-05-19 15:49
@MateStrysewskeSym 
2. Difficult to have a screen, infinite loading time, just import a case twice and see that both  cases will be in the database even when you choose the option to do merge.
3. I will contact  the French colleagues and hear from them also if we maintain it as it is. My expectation is that we use the data already in the database as the reference and complete missing values from the one being imported. @Chinedar @foyiri, @Iheanacho2027 what about Nigeria

**Comment by MateStrysewskeSym** [comment] 2020-05-20 06:46
@bernardsilenou As I said, this problem does not occur for me, which is why I need screenshots from you to be able to reconstruct the issue. Specifically, I need a screenshot showing the pick or create dialog with the options that you've selected, and a screenshot of the case grid showing the duplicate entries.

**Comment by Iheanacho2027** [comment] 2020-05-20 09:04
@bernardsilenou i agree with all your suggestions

**Comment by bernardsilenou** [comment] 2020-05-20 12:04
@MateStrysewskeSym I cannot take a screenshot when there is no screen to shot. The moment i start loading the file, the system goes to an infinite loop and stay there forever. Lets have a short call when you are free today and I will demonstrate to you. I am available any time

**Comment by Iheanacho2027** [comment] 2020-05-20 12:34
@bernardsilenou i believe @MateStrysewskeSym is aware of this infinite loop issue from #1300

**Comment by MateStrysewskeSym** [comment] 2020-05-20 12:43
@Iheanacho2027 Yes, I am, and that's fine because we're already taking care of that in a different issue. What I'd like to see is a screenshot from the case directory depicting the duplicate imported cases, and that should be no problem @bernardsilenou

**Comment by bernardsilenou** [comment] 2020-05-21 12:07
@MateStrysewskeSym I had a second look and maybe i understand better now.

6. In the import guide  we did not explain the option: "override existing case with changes from imported case". In addition, at the top page of the dialog that appears, we have the following text " One of the cases you tried to import is similar ...... if duplicate, **select the case and confirm**" This main instruction does not tell the user to choose "Override existing case with changes from imported case". This might be the cause of the duplicate importation after the user have followed the instructions given.
Here is my suggestion:
6.1 If a user choose a duplicate case in the dialog box and click confirmed, the system should do when is explained in 7 below.
6.2 If user choose a case, additional choose "Override existing case with changes from imported case" and click on confirmed, the system should do a merge but using the case being imported as reference and complete missing values in the case being imported with that in the db if available and clone the case in db with same uuid.
6.3 Add in import guide the meaning and difference of 6,1 and 6,2

7. Can we change the logic when merging duplicate cases? you mentioned that the default is "Override existing case with changes from imported case", I think we should give priority to the data that already exist in the database rather than the data that is being imported. For duplicate cases, we can only complete the missing variable for that case in the db if those variables are available for the duplicate case being imported. We can add a variable in the import report where users can then download, filter the duplicate cases and do further changes if they want. The French users also agree with this logic, since they use SORMAS mainly by importing cases, they are blocked from using the system now. There can also be duplicate in the data being imported and the last one will be the final recorded in the database which we cannot trust. 

If you agree with this model, It will be good we solve this before the new release.


![image](https://user-images.githubusercontent.com/12996724/82554687-b55d9500-9b66-11ea-811c-11cd054fcd8a.png)

![image](https://user-images.githubusercontent.com/12996724/82555177-96133780-9b67-11ea-9596-2f76b8712a4c.png)

**Comment by bernardsilenou** [comment] 2020-05-21 12:32
@MateStrysewskeSym From import guide you find this text "Check the check box
stating “Override existing case with changes from the imported case?” if you want to **update
the case you selected with the information from the import template**." My comprehension of this text is in agreement with my point 3, saying 
"Perhaps replace "override existing case with changes from the imported case" with "Retain existing case and replace missing data in existing case with that of the case being imported""

Please can you check the logic of the method for us to know what is programmed?

Assuming we have a merge by completing the missing data for the case in the db with available data from the case being imported, why do we then need the user to choose the option "Override existing case with changes from the imported case?" in order to do a merge? can we not do this by default?

I thought this button should be optional and selected only if the user want to use the case being imported as a reference in the merging process

If the user choose a duplicate case from the suggested options and do not click on the "Override existing case with changes from the imported case?" the system import a duplicate case. Please have a look at the figures, we can discuss it on Monday before sprint, I am still confused.

![image](https://user-images.githubusercontent.com/12996724/82558923-04a7c380-9b6f-11ea-9ddb-65c5ec9b6174.png)

![image](https://user-images.githubusercontent.com/12996724/82558957-14270c80-9b6f-11ea-83ee-46ed694d01a6.png)

**Comment by bernardsilenou** [comment] 2020-05-21 13:03
@MateStrysewskeSym I did the test again and found a completely different result, all works fine today which did not work last week. Have some improvement been done on the server? 

See attached screen shots.file:
[importTestReport.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4662535/importTestReport.docx)

**Comment by MateStrysewskeSym** [comment] 2020-05-25 05:28
@bernardsilenou No, we didn't do anything.

As I've said before, the logic will not only update missing information of the existing case, it will also override information that is specified in both the existing and the imported case. That's why the sentence you've proposed does not reflect the current logic.

**Closed** 2020-05-25 12:38 UTC
Labels: worksforme

**Comment by bernardsilenou** [comment] 2020-05-25 13:50
@MateStrysewskeSym OK,
one more question pls. Which option should i choose then if i want to keep the data in the database and only complete missing values using the data being imported? 
From my thinking and also from the French users, they do not want to override existing information in the db but complete missing values using data being imported. Is there any motivation for keeping the current logic?

**Comment by MateStrysewskeSym** [comment] 2020-05-25 15:16
@bernardsilenou That's currently not possible. Since it's a new feature request and not a bug though, I'd ask you to open a new issue for it. We could then add it as a second option when picking a case.

**Comment by bernardsilenou** [comment] 2020-05-25 15:17
Super, thanks

**Comment by Iheanacho2027** [comment] 2020-06-27 21:43
The detailed import for cases is now slower than previous. I feel the previous algorithm is better @bernardsilenou  Importing case is now slower than before
