### ISSUE TITLE
Deleting an Event Group results in endless loading of the page and the server connection is lost

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8851] opened 2022-04-18 14:34 UTC
### Bug Description
When the user deletes an Event Group, the action results in endless loading of the page. Even if the user reloads the page, he cannot access the app. If the user reloads the page, the server connection appears lost and the server is trying to reconnect;

~Logs for this issue from my local env~ (deleted, were not related)

### Steps to Reproduce

1. Create an Event and an EventGroup from it.
2. Open the Events Directory and select the 'Groups' tab;
3. Open an Event Group and click on 'Delete';
-> The 'Confirm Deletion' pop-up appears;
4. Click on 'Yes';

### Actual Behavior
The Event Group is not deleted and the page is endlessly loading;

### Expected Behavior
The Event Group is deleted in a reasonable amount of time;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/163821591-680e79da-969f-42d0-a101-c86e8065c0a2.png)

![image](https://user-images.githubusercontent.com/89522688/163822758-a235f9b3-1322-405e-9dde-e09a3d1ee9bc.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.2 and Sormas 1.71.0-SNAPSHOT (s2s-testbed)
* Android version/Browser: Chrome
* Server URL: local env and test1401.sormas-oegd.de
* User Role: Admin NatUser

### Additional Information

- The log seemed to show some successful calls after clicking the delete button, but did not log any exception. Payara and Postgres did not show high CPU or RAM load, it's currently not clear what's happening.
- Cause: #7857

**Comment by MateStrysewske** [comment] 2022-04-20 06:57
The exception linked in the initial issue is likely not the cause of this problem; it's closely linked to #8847 though and will be taken care of there. This problem here is probably caused by something else.

**Comment by StefanKock** [comment] 2022-04-20 07:48
Updated the ticket description: Problem still reproducable, but without any StackTrace related to the problem. It seems that the session is idling, no heavy resource load, other session can be started and work with the system.

**Comment by MateStrysewske** [comment] 2022-04-21 10:07
Moved from the hotfix in favour of #8915 because there's no easy fix for this problem.

**Comment by StefanKock** [comment] 2022-04-26 10:34
In conjunction with #7931 @MateStrysewske and I found out that `deletePermanent(List<String> uuids)` causes `deletePermanent(ADO ado)` to also start a new JTA tx. We are going to prevent this by not using the same method name for the `List` use case.

**Closed** 2022-04-26 11:46 UTC
Labels: bug, events, backend, major

**Comment by roxanamlendea** [comment] 2022-04-27 05:53
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (98dcdef) from the development branch.
