### ISSUE TITLE
A user with only "View User Roles" is able to change user rights

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#11484] opened 2023-02-10 07:13 UTC
### Bug Description

A user with only 'View existing users' and 'View existing user roles' is able to change the User rights by applying a new role template. The button "Apply user role template" is active and allows the user role template to be changed. The Save button is not active but if the user leaves the page the pop-up window with "Unsaved changes" is displayed. All buttons on the pop-up window are active and the changes can be saved.

#### Steps to Reproduce

1. Log in the app with a user that has rights to view existing users and existing user roles (no other rights selected in the 'Users' section of the user role configuration page);
2. Click on the 'Users' directory and then on the 'User roles' tab.
3. Open a User role
4. Click "Apply user role template"
5. Select new User Role with the same jurisdiction level
6. Check the changes among the user rights
7. Leave the page
8. "Unsaved changes" pop-up window is displayed
9. Save changes

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

In case the user has only 'View existing users' and 'View existing user roles' the button "Apply user role template" should be readOnly

**Comment by adinaflorea9** [comment] 2023-02-10 07:35
Closing the ticket as duplicate of #11476.

**Closed by adinaflorea9** 2023-02-10 07:35 UTC
Labels: bug, users, major
