### ISSUE TITLE
Case Import showing "wrong file type" error. 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#695] opened 2018-07-17 12:18 UTC
File format was saved as CSV UTF-8 (comma delimited) but kept returning error mentioned above. 

![image](https://user-images.githubusercontent.com/35563508/42816756-c022dd58-89c3-11e8-8d75-5a1f5c02a7f3.png)

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-17 13:08
This is likely caused by the sormas.symeda server working with semicolon as delimiter.
We should make sure the sormas hzi server is set to comma.

**Comment by Chinedar** [comment] 2018-07-18 09:56
I've tested with the sormas.org Nigeria server and it still does not accept
the file type (CSV Comma- delimited). Maybe this has not been changed yet?

Thanks.

**Comment by Chinedar** [comment] 2018-07-18 17:32
Ok thanks much.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-19 15:29
@Chinedar Server is updated. Please have another try with the import now.

**Comment by Chinedar** [comment] 2018-07-20 12:02
Thanks @Martin Wahnschaffe <m.wahnschaffe@symeda.de> so I still got the
same error message. Can you try an upload and advice if it works from your
own end? Thanks.

**Comment by Chinedar** [comment] 2018-07-23 15:20
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> I tried to do the import on
the Nigerian server with test data and it is still giving me the error
"wrong file type". What might be the cause still?

Thanks.

**Comment by Chinedar** [comment] 2018-07-23 15:30
Yes I even reduced data entered to just basic details without dates I
wasn't sure of enoms to put in. I was expect the system to accept the file
type first and then it can flag any other entry-dependent errors.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-23 15:38
That's strange. I just create a .csv file with the exact content I posted above and imported it on sormas.org.ng.
The system says "import successful: The import has been successful, but some cases could not be imported due to malformed data...".

I have no idea what you are doing differently.

In additon I don't think it's a good idea to import test data to the productive server. You should use the HZI server instead.

@dta16 Have you already updated the HZI server?

**Comment by Chinedar** [comment] 2018-07-23 15:45
Ok thanks. I'll wait for the update of the test server and try again.

Am about to get real data from the folks here and will need to import on
the productive server. Exactly the same file I sent is what I tried to
import and still got the error (strange).

**Comment by Chinedar** [comment] 2018-07-23 15:48
also is your delimiter comma or semi colon for your .csv file when you
created it on your system?

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-23 15:56
It's comma, as you can see above: https://github.com/hzi-braunschweig/SORMAS-Project/issues/695#issuecomment-407098460

**Comment by Chinedar** [comment] 2018-07-23 16:07
Ok thanks I'll get @Ferdinand to try when Tom updates the HZI server.

Thanks much.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-13 15:48
@Chinedar is this working now?

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-23 13:56
@Chinedar any news on this one? If it's working please comment and close this issue.

**Comment by Chinedar** [comment] 2018-08-23 14:47
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> somehow this has not worked
on my system.

@Ferdinand Oyiri <skidomamu12@gmail.com> please try this out on your system
and confirm it works so we can close this issue. Thanks.

**Comment by faatihi** [comment] 2021-02-12 15:41
Hello, all
I see I'm late to the discussion

We're having this issue in Ghana
Some users are able to import csv files, others are unable to

We observed that users with MS Office (especially MS Excel) installed on their PCs are able to import

I went on to confirm this by installing a Virtual Machine
Initially, I did not install MS Office on the VM
I tried importing and had the "Wrong file type" error
I tried about 5 times to be sure I'll get the same error
Then I installed MS Office including MS Excel
And voila! I imported the csv successfully

I think a functionality somewhere depends on the user's system
I debugged and found out the mimetype that comes with the uploaded csv is 'text/plain'
This is true for files coming from users that don't have MS Office installed
However, if the user has MS Office installed, the mimetype is rightly 'text/csv'

**Comment by MateStrysewske** [comment] 2021-02-12 16:30
@faatihi Please don't reopen existing issues. If you're having problems with anything - even if it's already been worked on in an existing issue - please create a new issue.

**Closed by MateStrysewske** 2021-02-12 16:30 UTC
Labels: important
