### ISSUE TITLE
[Events] Custom Export - some fields are misleading

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4704] opened 2021-03-09 21:37 UTC
### Steps to Reproduce
1. Open Test.sormas.netzlink.com ad navigate to Events
2. Select Export and choose custom export.
3. Observe how multiple fields are called Event Id

### Expected Behavior
 As seen in the screenshot, each field represents different entities. These should be reflected also when selecting different checkboxes from the custom export popup
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/110541120-022f4e00-8130-11eb-83ac-2dd2fccfe515.png)

### System Details
* Device:Windows
* SORMAS version: !.58.0-snapshot
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: NatUser

### Additional Information
this might be related to #4647 and #4043

**Comment by DavidBaldsiefen** [comment] 2021-07-22 11:12
Duplicate of #4929 / fixed in #4993

**Closed by DavidBaldsiefen** 2021-07-22 11:12 UTC
Labels: bug
