### ISSUE TITLE
History for changes on the cases/contacts/eps/person

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5272] opened 2021-04-29 06:25 UTC
### Situation Description

Currently, it is not possible to trace which user has made which changes to a case/contact/EP/person. 
If a user has accidentally edited the wrong case or clicked the incorrect entry, they cannot be asked because the changes are not tracked.

Especially with the implementation of SurvNet and sending data to other health offices, changes may have a direct impact on reported data.

### Feature Description

Tracing all changes made by the user for an case, contact and ep, specially the data which are used by SurvNet and sormas2sormas should be traced.

For that tracing an new tab is generated and shown for the ep/contact/case.

![grafik](https://user-images.githubusercontent.com/74791118/116509933-6a92e400-a8c4-11eb-9674-de69435ba26d.png)

The changes of the person are merged into this and shown in an own tab if you open the person by the person directory.

**Comment by MateStrysewske** [comment] 2021-04-29 11:00
Duplicate of #1842

**Closed by MateStrysewske** 2021-04-29 11:00 UTC
Labels: feature
