### ISSUE TITLE
Add case followup information on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5237] opened 2021-04-26 17:50 UTC
### Bug Description

- There is not case followup information on the mobile app
-  I do not know know if this feature was not just added to the mobile app.
### Steps to Reproduce

1.
2.

### Expected Behavior

Add a followup tab to cases on the mobile app, similar to that of contacts

### System Details

* Device: Android 7
* SORMAS version: 1.59
* Android version/Browser:
* Server URL:
* User Role: surveillance officer + contact officer

**Comment by MateStrysewske** [comment] 2021-04-27 07:21
Duplicate of #2650

**Closed by MateStrysewske** 2021-04-27 07:21 UTC
