### ISSUE TITLE
App Validator Exceptions

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#961] opened 2019-02-11 13:48 UTC
> 
> . | NullPointerException  - Root cause: java.lang.NullPointerException: Attempt to invoke virtual  method 'boolean java.util.Date.after(java.util.Date)' on a null object  reference - Stack trace:  de.symeda.sormas.app.contact.edit.ContactValidator$2:call:59 ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateRequiredPropertyEditFields:70  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateRequiredPropertyEditFields:77  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateFragmentRequirements:49  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validate:38  -> de.symeda.sormas.app.contact.edit.ContactNewActivity:saveData:154  -> de.symeda.sormas.app.BaseEditActivity:onOptionsItemSelected:120  -> android.app.Activity:onMenuItemSelected:3272 ->  androidx.fragment.app.FragmentActivity:onMenuItemSelected:371 ->  androidx.appcompat.app.AppCompatActivity:onMenuItemSelected:197 ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  -> androidx.appcompat.app.ToolbarActionBar$2:onMenuItemClick:64 ->  androidx.appcompat.widget.Toolbar$1:onMenuItemClick:204 ->  androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback:onMenuItemSelected:781  ->  androidx.appcompat.view.menu.MenuBuilder:dispatchMenuItemSelected:840  -> androidx.appcompat.view.menu.MenuItemImpl:invoke:158 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:991 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:981 ->  androidx.appcompat.widget.ActionMenuView:invokeItem:625 ->  androidx.appcompat.view.menu.ActionMenuItemView:onClick:151 ->  android.view.View:performClick:5676 ->  android.view.View$PerformClick:run:22647 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - Root cause stack trace:  de.symeda.sormas.app.contact.edit.ContactValidator$2:call:59 ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateRequiredPropertyEditFields:70  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateRequiredPropertyEditFields:77  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validateFragmentRequirements:49  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validate:38  -> de.symeda.sormas.app.contact.edit.ContactNewActivity:saveData:154  -> de.symeda.sormas.app.BaseEditActivity:onOptionsItemSelected:120  -> android.app.Activity:onMenuItemSelected:3272 ->  androidx.fragment.app.FragmentActivity:onMenuItemSelected:371 ->  androidx.appcompat.app.AppCompatActivity:onMenuItemSelected:197 ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  -> androidx.appcompat.app.ToolbarActionBar$2:onMenuItemClick:64 ->  androidx.appcompat.widget.Toolbar$1:onMenuItemClick:204 ->  androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback:onMenuItemSelected:781  ->  androidx.appcompat.view.menu.MenuBuilder:dispatchMenuItemSelected:840  -> androidx.appcompat.view.menu.MenuItemImpl:invoke:158 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:991 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:981 ->  androidx.appcompat.widget.ActionMenuView:invokeItem:625 ->  androidx.appcompat.view.menu.ActionMenuItemView:onClick:151 ->  android.view.View:performClick:5676 ->  android.view.View$PerformClick:run:22647 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - User:  SV3XT7-A7VC7Y-BWCIBM-TOON2PME - System:  https://sormas.org.ng/sormas-rest/

> . | NullPointerException  - Root cause: java.lang.NullPointerException: Attempt to invoke virtual  method 'android.view.View  androidx.databinding.ViewDataBinding.getRoot()' on a null object  reference - Stack trace:  de.symeda.sormas.app.component.validation.FragmentValidator:validateFragmentRequirements:48  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validate:38  -> de.symeda.sormas.app.task.edit.TaskNewActivity:saveData:192 ->  de.symeda.sormas.app.BaseEditActivity:onOptionsItemSelected:120 ->  android.app.Activity:onMenuItemSelected:3356 ->  androidx.fragment.app.FragmentActivity:onMenuItemSelected:371 ->  androidx.appcompat.app.AppCompatActivity:onMenuItemSelected:197 ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  -> androidx.appcompat.app.ToolbarActionBar$2:onMenuItemClick:64 ->  androidx.appcompat.widget.Toolbar$1:onMenuItemClick:204 ->  androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback:onMenuItemSelected:781  ->  androidx.appcompat.view.menu.MenuBuilder:dispatchMenuItemSelected:840  -> androidx.appcompat.view.menu.MenuItemImpl:invoke:158 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:991 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:981 ->  androidx.appcompat.widget.ActionMenuView:invokeItem:625 ->  androidx.appcompat.view.menu.ActionMenuItemView:onClick:151 ->  android.view.View:performClick:5647 ->  android.view.View$PerformClick:run:22465 ->  android.os.Handler:handleCallback:761 ->  android.os.Handler:dispatchMessage:98 -> android.os.Looper:loop:156  -> android.app.ActivityThread:main:6577 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:986 ->  com.android.internal.os.ZygoteInit:main:876 - Root cause stack trace:  de.symeda.sormas.app.component.validation.FragmentValidator:validateFragmentRequirements:48  ->  de.symeda.sormas.app.component.validation.FragmentValidator:validate:38  -> de.symeda.sormas.app.task.edit.TaskNewActivity:saveData:192 ->  de.symeda.sormas.app.BaseEditActivity:onOptionsItemSelected:120 ->  android.app.Activity:onMenuItemSelected:3356 ->  androidx.fragment.app.FragmentActivity:onMenuItemSelected:371 ->  androidx.appcompat.app.AppCompatActivity:onMenuItemSelected:197 ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  ->  androidx.appcompat.view.WindowCallbackWrapper:onMenuItemSelected:109  -> androidx.appcompat.app.ToolbarActionBar$2:onMenuItemClick:64 ->  androidx.appcompat.widget.Toolbar$1:onMenuItemClick:204 ->  androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback:onMenuItemSelected:781  ->  androidx.appcompat.view.menu.MenuBuilder:dispatchMenuItemSelected:840  -> androidx.appcompat.view.menu.MenuItemImpl:invoke:158 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:991 ->  androidx.appcompat.view.menu.MenuBuilder:performItemAction:981 ->  androidx.appcompat.widget.ActionMenuView:invokeItem:625 ->  androidx.appcompat.view.menu.ActionMenuItemView:onClick:151 ->  android.view.View:performClick:5647 ->  android.view.View$PerformClick:run:22465 ->  android.os.Handler:handleCallback:761 ->  android.os.Handler:dispatchMessage:98 -> android.os.Looper:loop:156  -> android.app.ActivityThread:main:6577 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:986 ->  com.android.internal.os.ZygoteInit:main:876 - User:  R5C2FZ-JJZ4HE-5HEBL2-KGDCCF3Q - System:  https://sormas.org.ng/sormas-rest/

**Comment by MateStrysewskeSym** [comment] 2019-02-13 11:53
I fixed the first bug, but couldn't reproduce the second one which is not really associated with validation but more with the fragment binding not being available in the BaseFragment for some reason. Maybe this bug is fixed already by another update of the TaskNewActivity?

**Comment by MateStrysewskeSym** [comment] 2019-02-13 14:26
Second bug will be fixed with #967

**Closed by MateStrysewskeSym** 2019-02-13 14:26 UTC
Labels: bug, sormas-app
