### ISSUE TITLE
[Climedo integration ] New registration error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#7684] opened 2022-01-14 14:16 UTC
### Bug Description

Cases > Every now and then when trying to register a new case with Climedo, an error message appears. It is not an isolated case, but also not a large number of cases in which this message occurs.

### Steps to Reproduce

1. Cases > Open Case
2. Click "Register in Symptom Diary" (top right corner)
3. Error message appears

### Expected Behavior

Error message appears with specific reason on why this error occurs and possibly also how to fix it.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/149525403-cf40fdfb-6205-4cc1-90c2-eba7f91a856f.png)

### System Details

* Device: PC
* SORMAS version: 1.66.4
* Android version/Browser: Chrome
* Server URL: Productive DE server
* User Role: Admin

### Additional Information

Internal: SORMASDE-13983

Logs obtained by the GA from their server:

```
{"Timestamp":"2022-01-13T18:21:12.710+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"84361","ThreadName":"http-thread-pool::http-listener-1(16)","TimeMillis":"1642094472710","LevelValue":"800","LogMessa
ge":"D182112.710|     > requestUri = /sormas-rest/visits-external/person/TOGVYV-5WLPUQ-3M765Z-FXSUKHZE (de.symeda.sormas.rest.logging.RequestResponseLogger.java:71)\n"}
{"Timestamp":"2022-01-13T18:21:12.793+0100","Level":"INFO","Version":"Payara 5.2020","LoggerName":"org.keycloak.adapters.KeycloakDeployment","ThreadID":"84361","ThreadName":"http-thread-pool::http-listener-1(16)","TimeMillis":"1642094472
793","LevelValue":"800","LogMessage":"Loaded URLs from https://[GA URL here]/keycloak/auth/realms/SORMAS/.well-known/openid-configuration"}
{"Timestamp":"2022-01-13T18:21:13.574+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"84369","ThreadName":"http-thread-pool::http-listener-1(24)","TimeMillis":"1642094473574","LevelValue":"800","LogMessa
ge":"W182113.573|     > Could not create new patient diary person: Person mit UUID: 'TOGVYV-5WLPUQ-3M765Z-FXSUKHZE' ist nicht im eDiary registriert (de.symeda.sormas.backend.externaljournal.ExternalJournalService.java:319)\n"}
{"Timestamp":"2022-01-13T18:22:00.083+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"228","ThreadName":"__ejb-thread-pool4","TimeMillis":"1642094520083","LevelValue":"800","LogMessage":"D182200.083|
> calculateCaseCompletion finished. 3 cases, 0 s (de.symeda.sormas.backend.common.CronService.java:92)\n"}
{"Timestamp":"2022-01-13T18:22:15.946+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"84361","ThreadName":"http-thread-pool::http-listener-1(16)","TimeMillis":"1642094535946","LevelValue":"800","LogMessa
ge":"D182215.946|     > requestUri = /sormas-rest/visits-external/person/TOGVYV-5WLPUQ-3M765Z-FXSUKHZE (de.symeda.sormas.rest.logging.RequestResponseLogger.java:71)\n"}
{"Timestamp":"2022-01-13T18:22:16.029+0100","Level":"INFO","Version":"Payara 5.2020","LoggerName":"org.keycloak.adapters.KeycloakDeployment","ThreadID":"84361","ThreadName":"http-thread-pool::http-listener-1(16)","TimeMillis":"1642094536
029","LevelValue":"800","LogMessage":"Loaded URLs from https://[GA URL here]/keycloak/auth/realms/SORMAS/.well-known/openid-configuration"}
{"Timestamp":"2022-01-13T18:22:16.787+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"81","ThreadName":"http-thread-pool::http-listener-1(2)","TimeMillis":"1642094536787","LevelValue":"800","LogMessage":
"W182216.786|     > Could not create new patient diary person: Person mit UUID: 'TOGVYV-5WLPUQ-3M765Z-FXSUKHZE' ist nicht im eDiary registriert (de.symeda.sormas.backend.externaljournal.ExternalJournalService.java:319)\n"}
{"Timestamp":"2022-01-13T18:22:35.959+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"79","ThreadName":"http-thread-pool::http-listener-1(1)","TimeMillis":"1642094555959","LevelValue":"800","LogMessage":
"D182235.958|     > requestUri = /sormas-rest/visits-external/person/TOGVYV-5WLPUQ-3M765Z-FXSUKHZE (de.symeda.sormas.rest.logging.RequestResponseLogger.java:71)\n"}
{"Timestamp":"2022-01-13T18:22:36.038+0100","Level":"INFO","Version":"Payara 5.2020","LoggerName":"org.keycloak.adapters.KeycloakDeployment","ThreadID":"79","ThreadName":"http-thread-pool::http-listener-1(1)","TimeMillis":"1642094556038"
,"LevelValue":"800","LogMessage":"Loaded URLs from https://[GA URL here]/keycloak/auth/realms/SORMAS/.well-known/openid-configuration"}
{"Timestamp":"2022-01-13T18:22:36.799+0100","Level":"INFORMATION","Version":"Payara 5.2020","LoggerName":"","ThreadID":"82","ThreadName":"http-thread-pool::http-listener-1(3)","TimeMillis":"1642094556799","LevelValue":"800","LogMessage":
"W182236.799|     > Could not create new patient diary person: Person mit UUID: 'TOGVYV-5WLPUQ-3M765Z-FXSUKHZE' ist nicht im eDiary registriert (de.symeda.sormas.backend.externaljournal.ExternalJournalService.java:319)\n"}
```

@FredrikSchaeferVitagroup - would it be possible to see if this is a SORMAS, Climedo or server/configuration error, please?

**Comment by FredrikSchaeferVitagroup** [comment] 2022-01-17 11:07
I could find the same problem with this [case on ga1](https://ga1.sormas-oegd.de/sormas-ui/#!cases/data/XSF6MB-3FA77F-YFWWVH-FCGGKGAA).

Maybe that's something we could investigate in tomorrows debugging session, @DraganMileski?

**Comment by FredrikSchaeferVitagroup** [comment] 2022-01-21 11:57
For the reproduced example in the test system, the problem was the following: the person was not marked as SymptomJournalStatus.REGISTERED or SymptomJournalStatus.ACCEPTED in SORMAS, but was actually registered in Climedo.

To resolve this: 

1. Open Climedo and search for the UUID of the person that can not be registered. 
2. If a patient can be found this way, take note of all data that you don't want to lose.
3. In climedo, delete the patient. 
3. In SORMAS, try to register the person again. It should work now.

@Candice-Louw Can you please forward this solution to the concerned users and report back whether this helped?

As there is a reasonable way to get to such a broken state through user behaviour, I currently don't see a need to change anything in the SORMAS code.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-01-24 08:11
The misleading error message comes from climedo, I asked its developers if whether they can do something about it.

**Comment by FredrikSchaeferVitagroup** [comment] 2022-02-09 09:02
The Climedo developers seem to have fixde the misleading error message.
@Candice-Louw  Was the issue resolved with the affected health departments?

**Comment by FredrikSchaeferVitagroup** [comment] 2022-02-16 08:44
Due to lack of feedback, I am closing this issue now.
The problem should be resolved/resolvable.

**Closed by FredrikSchaeferVitagroup** 2022-02-16 08:44 UTC
Labels: bug, cases, backend, integration, feedback, major

**Comment by FredrikSchaeferVitagroup** [comment] 2022-02-16 08:46
For QA: It could be tested whether the misleading error message really got removed by climedo. This should be possible on https://ga1.sormas-oegd.de/

**Comment by AndyBakcsy-she** [comment] 2022-02-16 17:12
Verified issue on ga1.sormas environment. 
Was not able to reproduce the error message when registering new cases.
