### ISSUE TITLE
Source tracing for cases

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#389] opened 2017-11-07 15:35 UTC
Where is the source coming from?

@dta16 This probably means that we should add a new task type "source tracing" to the system for CASES, right? Who will create this task and how will be assigned?

**Comment by hzi-braunschweig** [comment] 2017-11-07 22:19
@MartinWahnschaffeSymeda 
The issue is that we do contact tracing between the source case and the contacts. But there exists no relationshipi between the source case and his primary source of infection. The system allows source tracing to see the relationships between source cases as contacts to an index or primary case which they were once contacts to but not visible in the SORMAS system. 
The surveillance supervisor can assign this task to any officer but the source tracing should be an automatic task to surveillance officers to look for ofurther information and people who are source cases to the source case within SORMAS.
Is this clear?

**Comment by MartinWahnschaffeSymeda** [comment] 2017-11-14 14:09
We need to discuss and define this after the outbreak.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-01-24 12:48
This is from the monkey pox questions #401:

QUESTIONS TO ADD TO SORMAS
EXPOSURES:
• During the three weeks preceding the onset of symptoms, did the patient have contact with one or more persons who had with similarnsymptons?
Yes No Do not know
• If yes, respond to the following questions concerning these additional ill people (indicate all of the ill people). There is additional space for multiple contact at the end of this form.
• Last name _______________________ First name __________________________
• Relationship with the patient ___________________________________________
• First date of contact with the ill person ___/ ___/ ____

• Interaction with this person (choose all that apply)

    Family contact / Live together
    Prepared food together
    Shared a bed / slept together
    Took care of this sick person
    Friend at school or for play
    Met at the market
    Hunted together
    Friend / social acquaintance
    Were at the church, assisted at a religious service together
    Other __________________________________________________

• Other information about the contact

**Comment by MartinWahnschaffeSymeda** [comment] 2018-05-31 13:02
For proper automatic case classifcation it would be very good to have source tracing.

I have created mockups:

![sourcetracinglist](https://user-images.githubusercontent.com/23217632/40783673-7e02f5f2-64e3-11e8-9723-b2c2d43d7f0f.jpg)

![sourcetracingcreate](https://user-images.githubusercontent.com/23217632/40783678-81844104-64e3-11e8-9841-8bddbf240b24.jpg)

![sourcetracingfindcase](https://user-images.githubusercontent.com/23217632/40783681-83408b88-64e3-11e8-9f27-dbb00a0b7113.jpg)

The last mockup is basically for a custom field to select a case (#76)

**Comment by MartinWahnschaffeSymeda** [comment] 2018-09-24 05:05
We are removing automatic (un)assignment of resulting cases, so this is even more important. The system could propose possible source contacts to the user.

**Comment by bernardsilenou** [comment] 2020-08-03 19:30
@MartinWahnschaffeSymeda @markusmann-vg @Iheanacho2027
More refinements in preparation for implementation. 

1 In terms of infectious disease, a source case (person A) can infect another person (person B) which then result to another case (resulting case) through a contact. Thus contact is the bridge between a source case and a resulting case.  Contact information is needed to move from case A to resulting case B and vice versa.

2 Add caption “Contact to potential source case” as attribute of epid data to all cases (see mockup). When a contact is converted to a case, add a copy of the contact here.

3 Add a tab “+ LINK SOURCE CASE” to the case information form . First mockup that Martin proposed suggested to add this tab under epi data. But with linking events to cases, we have it under the case information form . Do you agree we keep it under case information although there are some questions in epi data asking fro contacts with other cases? More clarification is needed here.

4 When users click on + LINK SOURCE CASE, 
 open dialog box to select / find existing case

4.1 If existing case found,
- search if there exist and show all contacts with the source case using duplicate person method. Also, allow users to search for contacts among source case only using duplicate contact method.
-If contact found, link resulting case as resulting from contacts.
-If contact is not found, give the option for users to create contact + automatically link contact to resulting case

4.2 If existing case not found
-Allow users to create source case
-Allow users to create contact + convert contact to resulting case
- OR simply tell users to stop and create case before linking all over

- We maintain the relationship between contact and resulting case ie n:1

**Comment by bernardsilenou** [comment] 2020-08-04 07:13
Implementing this isseue will solve this issues also:
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/33

**Comment by Iheanacho2027** [comment] 2020-08-04 10:10
I like the suggestions @bernardsilenou

**Comment by bernardsilenou** [comment] 2020-10-28 15:38
@markusmann-vg @MateStrysewske  can we have a look in to this in preparation for 1,52?

**Comment by MateStrysewske** [comment] 2020-10-29 07:37
@bernardsilenou I think this is (at least partially) covered by the current refactoring of the epi data, isn't it?

**Comment by bernardsilenou** [comment] 2020-10-30 00:12
> @bernardsilenou I think this is (at least partially) covered by the current refactoring of the epi data, isn't it?

Absolutely Ja

**Comment by kwa20** [comment] 2020-12-18 08:03
@bernardsilenou @MateStrysewske I also agree that this is now possible through the epi data. #3628 would be a further refinement and related to this issue.

**Comment by bernardsilenou** [comment] 2020-12-18 20:19
@MateStrysewske I think we can close this ticket since the new epi data addressed this need. 
We continue refinement in  #3628

**Closed** 2021-01-04 09:20 UTC
Labels: duplicate
