### ISSUE TITLE
Poe Supervisor cannot create new cases via 'Create new Cases' and via creating a Case for an Event Participant

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#8820] opened 2022-04-13 14:03 UTC
### Bug Description
The bug is reproducible via:
- Create new Case from the Case Directory
- Creating a Case for an Event Participant

### Steps to Reproduce

1. Log in with Poe Supervisor and go to Cases Directory
2. Click on new Case and fill in all mandatory data
3. On the Pick or Create Person page select Create a new person
4. Click on Save button

### Expected Behavior
The user should be able to view and create cases

### Actual Behavior
There is an error displayed:
"You have no rights for changing Symptom journal Status"

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/163198388-18aeb3b2-f593-428b-bd53-8a44e25a8c5c.png)

### System Details

* Device:
* SORMAS version: 1.71.0-snapshot
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: Poeinfo

**Comment by AndyBakcsy-she** [comment] 2022-04-19 14:26
new Server error log :
[server error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8513848/server.error.txt)

**Comment by roxanamlendea** [comment] 2022-04-20 09:17
Besides the POE Supervisor, it is reproducible also with POE National User

**Comment by roxanamlendea** [comment] 2022-04-21 08:56
Tested the ticket on my local environment using the latest version of Sormas 1.71.0-SNAPSHOT (d16a724) from the development branch and I'm reopening the ticket because there's displayed an 'A problem has occurred' message when the POE Supervisor user creates a Case for an Event Participant.

**Comment by abrudanancuta** [comment] 2022-04-21 09:24
The issue appears also for National Clinician when creating a Case from Event Participant

**Comment by roxanamlendea** [comment] 2022-05-04 14:44
I'm reopening the ticket because the issue is still reproducible with Lab Officer user when creating a Case for an Event Participant.

![image](https://user-images.githubusercontent.com/89522688/166706111-5d9ade71-b51d-4e6e-acd3-565f35784089.png)

I attach the stack trace:
[stack trace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8621328/stack.trace.txt)

**Comment by vidi42** [comment] 2022-05-05 15:10
> I'm reopening the ticket because the issue is still reproducible with Lab Officer user when creating a Case for an Event Participant.

This issue doesn't seem to be related to any of the causes of the original ticket. @roxanamlendea I suggest closing 8820 and reopening a new ticket for this specific issue

**Closed** 2022-05-06 07:02 UTC
Labels: bug, cases, backend, vaadin-app, major

**Comment by roxanamlendea** [comment] 2022-05-06 08:57
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (04faaf1) from the development branch.
