### ISSUE TITLE
User with rights TASK_VIEW and TASK_DELETE leads to endless loading when opening the task directory

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10541] opened 2022-10-05 08:14 UTC
### Bug Description

Opening the task directory leads to endless loading and server connection lost when user is logged in with a user role which has the rights TASK_VIEW and TASK_DELETE. Same happens when trying to open a task, if page loads beforehand. For example with standard user roles like admin, opening the task directory does not lead in endless loading or server connection lost.

### Steps to Reproduce

1. Configure user role with right TASK_VIEW and TASK_Delete
2. Create user with configured user role from Step 1
3. Log in with created user from Step 2
4. open task directory or open an existing task. 

### Expected Behavior

Task directory and task itself opens without endless loadn
### Screenshots
![Endless Loading](https://user-images.githubusercontent.com/98821699/194012922-6dd13eff-55df-4db8-81c2-d39ae77aa48a.gif)

### System Details

* Device:
* SORMAS version: 1.75.3
* Android version/Browser:
* Server URL: release-international 
* User Role:

**Comment by ChristopherRiedel** [comment] 2022-10-06 14:23
duplicate of #10426

**Closed by ChristopherRiedel** 2022-10-06 14:23 UTC
Labels: bug, tasks, hotfix, performance
