### ISSUE TITLE
Absence of "presumptive positive" variable for yellow fever test results

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1151] opened 2019-05-24 19:21 UTC
The results for yellow fever samples should have a variable for "presumptive positive" on the results section of the SORMAS platform. This is because all samples tested positive for yellow fever in Nigerian laboratories have their results tagged as "presumptive positive" and not "positive", they are then tagged as "positive" after their confirmation at IP,Dakar laboratory in Senegal.  @Chinedar @bernardsilenou @SeriousMartin @foyiri

**Comment by MateStrysewskeSym** [comment] 2019-05-27 07:08
@Iheanacho2027 I think that's what the "Verified by lab supervisor" field should be used for. As long as a pathogen test is marked as positive, it should be be perceived at presumptive positive. Should we maybe add a description to the "Verified by lab supervisor" field that includes the requirement of the test being confirmed by the Dakar lab (but in a more generalized way because other countries could use a different lab)? Do you have a suggestion on what this description should be like?

**Comment by Iheanacho2027** [comment] 2019-05-27 09:48
Thanks @MateStrysewskeSym, after discussions with @Chinedar and @foyiri, we have decided to work with what's already on the platform.

**Comment by MateStrysewskeSym** [comment] 2019-05-27 09:54
@Iheanacho2027 Alright, thanks for the update!

**Closed by MateStrysewskeSym** 2019-05-27 09:54 UTC
Labels: discuss
