### ISSUE TITLE
[Performance] Merging of duplicate cases in SORMAS UI is slow

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4202] opened 2021-02-01 14:20 UTC
### Bug Description
Observed in a live testing session: Opening of the duplicate view takes very long a system with 18.000 cases. After a couple of minutes it opens the page, however, there are a couple a errors in between.

### Expected Behavior
The request finishes in a reasonable amount of time without errors.

### Additional Information
Screenshots and dump of the network request which shows the problem are available on request, I cannot share them publicly.

### System Details
* Device: Docker
* SORMAS version: 1.54.1
* Android version/Browser: Firefox
* Server URL: ITZ Bund hosted
* User Role: admin ??

**Comment by MateStrysewske** [comment] 2021-02-01 14:39
Duplicate of #2227

**Closed by MateStrysewske** 2021-02-01 14:39 UTC
Labels: bug
