### ISSUE TITLE
Disabled user roles can be found in the User Role List when Filter set to Enabled

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10572] opened 2022-10-06 15:05 UTC
### Bug Description

A disabled user role can be found in the User Role List when the  filter is set to enabled. 

### Steps to Reproduce

1. create a new user role or choose an existing one
2. Click disable
3. Set filter to enable in the User Roles List
4. Search for disabled user role

### Expected Behavior

The filter works correctly and disabled user roles can not be found when filtering for enabled user roles. 

### System Details

* Device:
* SORMAS version: 1.75.3
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment] 2022-10-06 17:35
Duplicate of #10538

**Closed by roxanamlendea** 2022-10-06 17:35 UTC
