### ISSUE TITLE
Setting quarantine end and follow-up until to different dates triggers a popup message

### ISSUE THREAD

**Issue by nliakm** [hzi-braunschweig/SORMAS-Project#2943] opened 2020-09-22 15:04 UTC
### Bug Description
Setting the quarantine end date and the follow-up until date to different values, a popup window will pop up every time the case is opened.
### Steps to Reproduce
1. Set quarantine start- & end date in a case
2. Check the "Overwrite follow-up until date" checkbox
3. Set the "Follow-up until" date to a different value than the end date of the quarantine.
4. Save the case.
5. Pop up message should occur (see screenshot). Click on "No".
6. Leave the case and open the case again. Message pops up again.

### Expected Behavior
When click on "No" on the popup-message, this popup-message shouldn't be appearing everytime the case is opened.

### Screenshots
![Screenshot from 2020-09-22 16-42-23](https://user-images.githubusercontent.com/22243466/93900220-6cc10e80-fcf5-11ea-9af0-43af7a32e1f4.png)

### System Details
* Device: Webapp
* SORMAS version: 1.48.2
* Android version/Browser: All Browsers

**Comment by bernardsilenou** [comment] 2020-09-23 01:34
@nliakm This is not a bug, it was defined like this to remind users to always match both dates because it is only for special people that the two date may be different. 
Your solution is that the pop up should not appear every time, so what is the frequency you think will be good?
thanks

**Comment by vlad-ciucescu** [comment] 2020-09-23 06:56
Duplicate of #2868

**Comment by vlad-ciucescu** [comment] 2020-09-23 10:09
@bernardsilenou It is true that the pop-up should appear every time **when the follow-up period is extended beyond the quarantine end date**. That is the original intended behaviour.
The actual problem is that, even after pressing 'No' on the pop-up, it will keep reappearing when the case is opened later.

**Closed** 2020-09-24 13:00 UTC
Labels: bug, important, sormas-ui

**Comment by AndyBakcsy-she** [comment] 2020-09-25 07:37
Verified issue on  SORMAS Version: 1.49.0-SNAPSHOT
The behaviour of this functionality is working as described in the feature + the normal logic when clicking on the No button
