### ISSUE TITLE
Usability / UI: Display testtype (PCR/Antigen) on main case page

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#3962] opened 2021-01-11 09:36 UTC
Hello!

This is my first post here.
I'm working with the Gesundheitsamt Berlin Friedrichshain-Kreuzberg. We've been using SORMAS since April 2020 and are currently implementing SORMAS as our main database. 
Some of my coworkers have limited experience working with computers or databases, so we need our workflows to be as easy as possible.
Some of our current issues stem from information being "hidden" in SORMAS, eg. not being easily visible.

One important piece of information is the kind of test that has been performed on the sample (PCR test or rapid antigen test) b/c it decides how we proceed with the case.

### Proposed Change

Include information on the test type on the main case page. (Section: Samples)

**Comment by kwa20** [comment] 2021-01-11 12:05
@ophcode Thank you for your contribution! I think this issue is technically a duplicate of #3890. I've attached a mock-up there as well. Feel free to give feedback and comment.

**Closed by kwa20** 2021-01-11 12:05 UTC
Labels: Case Surveillance, Laboratory, change, sormas-ui

**Comment by ophcode** [comment] 2021-01-12 12:31
Thank you!
Yes, it's basically the same issue.
