### ISSUE TITLE
Lab officers should have full access to entities whose sample was assigned to the lab officers lab [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4694] opened 2021-03-09 11:04 UTC
### Bug Description
These if following issue 4346 and related to international instance.
### Steps to Reproduce
1. Log in with a lab officer account
2. case directory is pseudonymized: should not be the case
3. case form and sample are read access only
4. you can only edit pathogen test through the sample directory but not through the case, contact or ep
5. associated case person name are hidden in sample directory: Should have a name beside the id as when logged in with national user
6. associated contact and ep columns person names are missing in sample directory: Should be present with names
7. event + ep + contact menu items + directories are missing: should be provided just as we did for cases because samples can come from ep or contacts
8. For samples linked to event participant, lab officer can not edit pathogen and additional pathogen test: thy should have full assess
9. For samples linked to a contact that is also linked to an event, 
    *   the lower part of sample information form can be edited :+1: 
    *   but the the upper part, specifically purpose of sample can also be edited thus resulting to a bug :-1:  Purpose of sample should be read only as long as the lab user is not the reporting user or has full access to the sample.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/110460779-ef386180-80ce-11eb-91e4-57f43fd5cdcb.png)

### System Details
* Device: 
* SORMAS version: 1.58
* Android version/Browser:
* Server URL: https://test.sormas.netzlink.com/sormas-ui/
* User Role: lab officer

### Development Specifications
- [x] #5950
- [x] Grant users on laboratory level the user right to create cases
- [x] Allow users on laboratory level to see the personal and sensitive details of cases, contacts, and event participants (+ their associated events) with samples that are assigned to their laboratory
- [x] Allow users on laboratory level to edit cases, contacts and event participants with samples that are assigned to their laboratory
- [x] Make sure that only the reporting user and users with the user right SAMPLE_EDIT_NOT_OWNED can edit the sample purpose, reason for sampling/testing and field sample ID

**Comment by MateStrysewske** [comment] 2021-03-09 11:07
@bernardsilenou I know that we designed it like this on purpose because at some point there was the specific request that lab officers should NOT have full access to the entities the samples are associated to - mainly because there's no real reason in regards to data minimalism and data privacy. Can you tell me why lab officers need access to these details?

**Comment by bernardsilenou** [comment] 2021-03-09 11:13
@MateStrysewske  
- For the DE instance, the lab officer has  pseudonymized person information but still full access to the samples.
- The reason for giving the lab officer full access to entities is that they also take part in case creation and classification. If they happen to get a positive test for a disease, then they immediately create the case, If the sample is a linked to a contact, then they convert the contact to a case.

**Comment by bernardsilenou** [comment] 2021-03-09 11:16
This is partially the reason whey they got the case tab initially.
For the DE instance, we can also take away the case tab from them. I think they either have all 3 tab or nothing and focus only on sample for the DE instance. What do you think?

**Comment by bernardsilenou** [comment] 2021-03-09 11:19
> @bernardsilenou I know that we designed it like this on purpose because at some point there was the specific request that lab officers should NOT have full access to the entities the samples are associated to - mainly because there's no real reason in regards to data minimalism and data privacy. Can you tell me why lab officers need access to these details?

@MateStrysewske  You are right and this decision was for DE only.

**Comment by bernardsilenou** [comment] 2021-03-09 11:23
@MateStrysewske The point that they can not edit samples of  ep or contact linked to an event seam to me as a bug.

**Comment by MateStrysewske** [comment] 2021-03-09 11:34
@bernardsilenou If I recall it correctly, it wasn't meant to be for DE instances only and we made the decision long before SORMAS was introduced in Germany. Lab officers, in the original sense in SORMAS, are people who are receiving samples, perform pathogen tests on them and then document their results. Creating and managing cases was not part of that, and because of that there's no reason why they should be allowed to see any personal details or edit the cases at all. If a lab officer is supposed to do that, they should rather be combined with an additional user role (e.g. surveillance officer).

The reason they got the case tab is because they might still need read-only access to the basic and unsensitive information of the case.

I agree that it should be possible to directly enter a sample from wthin a case. Unfortunately, that's really not trivial with our current UI technology though, so I'm not sure whether it's worth investing a lot of time into that right now, but that's for you to decide.

**Comment by bernardsilenou** [comment] 2021-03-09 14:20
@MateStrysewske 
I think we can combine lab officers with national users because the lab officers are mainly  linked to reference labs and get samples from all over the country. For labs that have more staffs, they even classify cases as confirmed if there is a positive lab test.  Among all users, then lab officer has autonomy in classifying cases as confirmed i suppose.

I do not understand how it would work when we combine lab + surveillance supervisor. If the lab user get a sample from a case, contact, ep in another region, would they still have full access to the case?

**Comment by bernardsilenou** [comment] 2021-03-09 14:32
> @bernardsilenou If I recall it correctly, it wasn't meant to be for DE instances only and we made the decision long before SORMAS was introduced in Germany. Lab officers, in the original sense in SORMAS, are people who are receiving samples, perform pathogen tests on them and then document their results. Creating and managing cases was not part of that, and because of that there's no reason why they should be allowed to see any personal details or edit the cases at all. If a lab officer is supposed to do that, they should rather be combined with an additional user role (e.g. surveillance officer).
> 
Often it is the lab that detect an outbreak. They get a positive test for a case that is not even on SORMAS, thus is their duty to create the case. This is what they told us in a training.  
@Chinedar @faatihi Are lab officers suppose to create cases?

> The reason they got the case tab is because they might still need read-only access to the basic and unsensitive information of the case.

If this is true, then they may also need for contacts also, eg convert contact to case, or not?
> 
> I agree that it should be possible to directly enter a sample from wthin a case. Unfortunately, that's really not trivial with our current UI technology though, so I'm not sure whether it's worth investing a lot of time into that right now, but that's for you to decide.

I also think we should not invest effort here

**Comment by bernardsilenou** [comment] 2021-03-09 14:35
@MateStrysewske lab offer can create a case and the case immediate disappear from their view, we tither block them from creating cases or give them the option to create. Since the lab officer is the reporting user, then the case stays in their directory

**Comment by bernardsilenou** [comment] 2021-03-23 00:15
@Chinedar @iheanacho
In NG, are lab officers suppose to see the names of the cases or not?
should they have right to edit the case data or only add results to the sample data?
Should it appear like this?
![image](https://user-images.githubusercontent.com/12996724/112073537-a1af0080-8b74-11eb-844d-fdd44dd9b7f0.png)

![image](https://user-images.githubusercontent.com/12996724/112073734-f5214e80-8b74-11eb-8788-7c8cb83e43d0.png)

If this is not the case, then we would need a configuration for this.

**Comment by bernardsilenou** [comment] 2021-03-26 17:15
@MateStrysewske @markusmann-vg 
I discusses with Nigeria and the current implementation of the lab officer does not apply to them. Please can we add in the hotfix for 1.58?
To change:
- Give lab officer full access to all entities assigned to their lab
- Remove psuedonimization from lab officer role

**Comment by MateStrysewske** [comment] 2021-03-29 06:02
@bernardsilenou Since the hotfix is very urgent and this issue would require some extensive code changes and testing, I'm afraid it will have to wait until 1.59.0.

**Comment by bernardsilenou** [comment] 2021-04-07 12:03
@markusmann-vg @MateStrysewske  
Please can we tag this to 1.59 in order not to  forget?
Must I add on the prio table?

**Comment by MateStrysewske** [comment] 2021-04-07 12:08
@bernardsilenou Yes, as this is not a bug. Please discuss it with the people responsible for making the priorities.

**Comment by MateStrysewske** [comment] 2021-05-04 09:25
Prerequisite: #3254

**Comment by StefanKock** [comment] 2021-05-05 10:41
I changed the functional label because this effects not how laboratory items are shown, but cases, contacts and event participants.

**Comment by BarnaBartha** [comment] 2021-06-03 06:42
@MateStrysewske @bernardsilenou FYI this will allow the lab user to see also the child entities that dependent on case / contact / event participant. For example SuirvellanceReport / Visits / Prescription etc.. entities whose jurisdiction is dependent on their respective case / contact.

**Comment by BarnaBartha** [comment] 2021-06-03 06:42
Prerequisite: #5644

**Comment by AndyBakcsy-she** [comment] 2021-06-24 10:44
@MateStrysewske I have tested this ticket and found out that for Cases where the sample is assigned to other laboratory than the default one, When I log in with the Lab Officer I am able to see the TASK that was automatically created for that case. 
Is this a bug and the fix should be added to this ticket? or is it expected behavior? 
![image](https://user-images.githubusercontent.com/70562142/123250023-49302c00-d4f2-11eb-96ac-ee022e53b96e.png)

**Comment by AndyBakcsy-she** [comment] 2021-06-24 11:42
Reopening ticket as per the discussions with Mate and Barna.
A lab officer should only see cases to whose samples they have access too. 
Also, a lab officer should not see pseudonymized cases that have samples assigned to a different laboratory.

**Comment by StefanKock** [comment] 2021-06-24 12:46
@AndyBakcsy-she found also a performance problem related to this on https://test.sormas.netzlink.com (LabOff, view contacts). The LEFT JOINs on samples let the result set explode to over 9 million rows. The data with 2.7 GB is then sorted and shrunk on disk. https://explain.dalibo.com/plan/uRb .

**Comment by StefanKock** [comment] 2021-06-25 09:42
Update on the performance problem: @BarnaBartha found a solution to reduce excessive joins on samples that let the result set explode, and there was also a condition missing that caused to fetch too much data. The verification showed a good query performance: https://explain.dalibo.com/plan/t4f

The code is not yet fully implemented and reviewed, but at least we see a solution on the horizon.

**Closed** 2021-06-28 13:58 UTC
Labels: backend, cases, change, contacts, events, vaadin-app

**Comment by StefanKock** [comment] 2021-07-01 09:02
> Update on the performance problem: @BarnaBartha found a solution to reduce excessive joins on samples that let the result set explode, and there was also a condition missing that caused to fetch too much data. The verification showed a good query performance: https://explain.dalibo.com/plan/t4f
> 
> The code is not yet fully implemented and reviewed, but at least we see a solution on the horizon.

Retested on test.sormas: performance problem is solved, total roundtrip took about 1.2s
