### ISSUE TITLE
Allow user to select the new case date type for the surveillance dashboard [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3352] opened 2020-11-01 19:37 UTC
### Change Description
Cases are displayed in the epidemiological curve by the symptom onset date rather than the report date. This especially includes cases that were converted from contacts since these contacts might start having symptoms days before they're eventually converted into cases.

This then leads to case numbers differing per epi weeks from what health departments actually report to higher health authorities.
### Steps to Reproduce
1. Create a case whose report date is set in the epi week after their symptom onset date.
2. Check where the case gets displayed on the epidemiological curve. 

### Expected Behavior
The epidemiological curve should display cases by their onset date by default and report date as an option .

### Screenshots
<img width="774" alt="Screen Shot 2020-11-01 at 8 20 49 PM" src="https://user-images.githubusercontent.com/70317594/97812405-65403e00-1c81-11eb-8c5e-8ff029cf6b1c.png">

### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
related to #3353

**Comment by MateStrysewske** [comment] 2020-11-02 08:51
@bernardsilenou Correct me if I'm wrong, but I think we can't simply do this because this is intended behaviour for Nigeria, right? I.e. looking at the symptom onset date first if it exists and then falling back to the report date. If simply changing this isn't an option (which I guess), we may need to introduce a property that controls this behaviour; however, that would be out of scope for the upcoming release.

**Comment by MateStrysewske** [comment] 2020-11-02 09:21
@Chinedar Can you confirm/falsify my assumption?

**Comment by Chinedar** [comment] 2020-11-02 09:35
@MateStrysewske this is confirmed. The symptom onset date is the date set for the Epi-curve. It falls back to the report date when the earlier date is missing.

**Comment by bernardsilenou** [comment] 2020-11-03 01:07
Both options are correct, it all depends on what the user need the epi curve for. If the goal is to use the epi curve for epidemiological study of the disease, then the symptom onset date is the right date to use. 
@MateStrysewske I agree with you that we should add the 3 reference date options just as we have on the case directory.
Some of the other indicators related to the case may also need to be computed based on the date type chosen by the user. @kwa20 I think we need to specify this further

**Comment by kwa20** [comment] 2020-11-22 21:48
@bernardsilenou  @MateStrysewske  I guess we should add a filter where you can choose by which case reference date you want to display the data. Since this will influence other indicators like 'Disease Burden Information', 'Difference in Number of Cases', 'New Cases', as mentioned by @bernardsilenou, this filter should be applied to the whole dashboard.

<img width="882" alt="Screen Shot 2020-11-22 at 10 43 32 PM" src="https://user-images.githubusercontent.com/70317594/99917980-3f540980-2d14-11eb-8ff9-3920ed7463ea.png">

**Comment by bernardsilenou** [comment] 2020-11-23 23:34
@kwa20  
- We also need the most relevant date option in the drop-down list and this would be the default chosen option.
- Since the surveillance dashboard also include other entities other that cases (eg avents), what about using:
 Reference date: most relevant date/ report date/ symptom onset date
- No matter the date type chosen, we will always use the report date to filter events
- We would encourage users not to use the most relevant date when reporting since it mixes two date types which is not the best thing to do, but still nice to have it as default to be sure that all entities are shown on the dashboard
- This change only apply to surveillance dashboard

**Comment by bernardsilenou** [comment] 2021-01-25 14:46
This ticket fall in the same group as #3004, thus good to implement in one step.

**Comment by bernardsilenou** [comment] 2021-02-24 22:12
@StefanKock This ticket is the second phase of #3004. I think it would be wise to begin working on #3004 before coming to this.

**Comment by StefanKock** [comment] 2021-02-25 08:08
@alexcaruntu-vita @MateStrysewske please check together next week whether this ticket makes sense even before #3004. As far as I know this was about adding an option to select another date for the statistics.

**Comment by bernardsilenou** [comment] 2021-02-25 20:40
@StefanKock @MateStrysewske @alexcaruntu-vita 
There is no technical limitation whey we can not implement this issue before #3004. But there may be misinterpretation of the results.
- The dashboard currently uses the most relevant date which gives priority to the symptom onset date as default filter. 
- Visualizing epi curve by report date wothout being able to filter by report date only may results in counts not appearing in the tight bars (weeks),  thus not solving the main cause why this issue was created.
- We can implement this issue firs conditioned that we include the option to filter the dashboard using 3 date types:
     - most relevant date: default
     - onset date
     - report date
- When the dashboard and epi cure are all filtered using the same date types, then all would align, if not then we have slight misalignment.

**Comment by bernardsilenou** [comment] 2021-02-25 20:53
@StefanKock I just reaised that I already added comments and the last one was not needed. I did not read the comment after initial creation of the issue. Please we can implement this now and it is independent of  #3004. Sorry for that.

**Closed** 2021-03-04 15:08 UTC
Labels: change, dashboard, vaadin-app

**Comment by raghupola-vg** [comment] 2021-03-05 15:46
verified on version 1.58.0-Snapshot
