### ISSUE TITLE
[DRAFT] SORMAS 2 SORMAS Interface for cases and contacts 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2576] opened 2020-07-30 08:57 UTC
### Situation Description
The German health departments want to be able to share data between them. 

### Feature Description for brainstorming
There should be an option to either include the senstitive data or pseudonymize sensitive data.
There should be an option to decide wether the case or contact can be edited by the recipient or just viewed.
There should be an option to handover the ownership to the full case or contact or keep the ownership and allow the recipient to just view or edit.
If the ownership of the case or contact is given to the recipient, we could either:
- keep the contact or case
- delete the case or contact

If the ownership stays with the sender and the recipient is able to edit the case or contact, we should also allow to update the case or contact with the latest changes.  

This process can be triggered manually but should also include a possibility to be triggered automatically.

### Possible Alternatives
Improving the export / import functionality

**Comment by MateStrysewskeSym** [comment] 2020-07-30 09:46
* The decision whether or not to include sensitive data should probably be linked to the decision whether or not ownership should be handed over or whether or not editing should be allowed for the receiving instance
* When we allow to update cases/contacts in other servers, we need to be really careful with merging; we have an automatic merge process for app/web transfer, but the web always has priority in these cases and just overrides fields that have been changed in both the app and web; for servers, this logic would transfer to servers with ownership overriding changes from other servers, but that could be a problem and might not be acceptable
* What happens if the case/contact already exists on the other server? Do we do duplicate detection or do we blindly push the case/contact, which might not be a good idea? If we do duplicate detection, this is linked to issue #2516
* How do we know that a case/contact is the same on two individual SORMAS instances? Can we use the UUID for that or do we need an additional field? We can't use externalId because that's supposed to be the ID of the case/contact in another system than SORMAS
* In general, it should probably be possible to use the normal ReST API for this purpose and extend its functionality because pushing cases from one SORMAS instance to another should theoretically not be much different than pushing from app to web

**Comment by GabrielePoggensee** [comment] 2020-07-31 09:53
The IfSG regulations are very clear who is in charge for a given case (ownership): 

IfSG
5) The processed data on notifiable diseases and evidence of pathogens will be transmitted to the public health department on a case-by-case basis, together with the data on the investigations carried out and measures taken in this case and the knowledge gained from them,
1. in whose district the person concerned has or last had his principal residence, or
2. in whose district the person usually resides, if a principal residence cannot be established or if the data subject does not usually reside there.

A Gesundheitsamt might get knowledge of a case in its jurisdiction (e.g. person living in a hotel in Warnemünde), however, the competent authority lies with the Gesundheitsamt where the person lives - sensitive data need to be sent to the competent Gesundheitsamt (owner).

If the ownership is handed over to the competent Gesundheitsamt, the case should not be deleted in the GA Warnemünde because this case might have had contact to persons in town who might develop the disease.

**Comment by GabrielePoggensee** [comment] 2020-08-02 08:57
![image](https://user-images.githubusercontent.com/68693446/89119446-f3542f00-d4ae-11ea-8978-bd36963204d5.png)

**Comment by GabrielePoggensee** [comment] 2020-08-02 09:00
Some thoughts in the figure on how the migration from one Gesundheitsamt to another could work.

Übermittlung an ein anderes Gesundheitsamt zuständigkeitshalber
Was wird übermittelt?
-	Unbestätigter Kontakt: gegenseitige Unterrichtung über durchgeführte Ermittlungen (§ 25  IfSG –  Ermittlungen bei kranken, krankheitsverdächtig, ansteckungsverdächtigen Personen; § 25 IfSG – gegenseitige Unterrichtung )
-	Bestätigter Kontakt (wie oben)
-	Fall: namentliche Meldung an zuständiges Gesundheitsamt (§9  IfSG)
-	Verknüpfung von einem Fall (Kontakt) mit Ausbruch (§ 9 IfSG – Erkennbare Zugehörigkeit zu einer Krankheitshäufung)

**Comment by bernardsilenou** [comment] 2020-08-02 09:04
Danke Gaby. Dieser Zweig ist nur für Englisch. Können Sie beim Übersetzen helfen?

**Comment by GabrielePoggensee** [comment] 2020-08-02 09:06
Sorry, now the translation:

Transfer to another public health authority for reasons of competence
What is being transmitted?
- Unconfirmed contact: mutual information about investigations carried out (§ 25 IfSG - investigations of sick, suspected sick, suspected infectious persons; § 25 IfSG - mutual information)
- Confirmed contact (as above)
- Case: report by name to the responsible public health authority (§9 IfSG)
- Linking of a case (contact) with an outbreak (§ 9 IfSG - recognisable affiliation to a disease cluster)

**Comment by JonasCir** [comment] 2021-11-22 09:08
@markusmann-vg @leventegal-she I think this is done?

**Comment by Jan-Boehme** [comment] 2022-06-27 09:21
Closed this issue. It is no longer needed as we have started the implementation of S2S and have detailed issues about it.

**Comment by Jan-Boehme** [comment] 2022-06-27 09:22
Closed this issue. It is no longer needed as we have started the implementation of S2S and have detailed issues about it.

**Closed by Jan-Boehme** 2022-06-27 09:22 UTC
Labels: feature, SSD, s2s
