### ISSUE TITLE
Confirmed cases from Lagos region still appearing in other regions

### ISSUE THREAD

**Issue by chukwuemekauzoho** [hzi-braunschweig/SORMAS-Project#2256] opened 2020-06-04 11:30 UTC
Bug Description
Confirmed cases from Lagos are still showing in other regions like Ogun and Osun State. These confirmed cases are seen in the case directory and dashboard of other states altering the data in these states. I know this has been logged before but it has not stopped.
 @Chinedar  @MartinWahnschaffeSymeda @MateStrysewskeSym

Steps to Reproduce
Log in as the surveillance supervisor of Ogun or Osun state
Filter out the confirmed cases and you will see the confirmed case of Lagos state popping up in the  state

Expected Behavior-  The cases below are reflecting for Ogun State
WZ5YR7-2U6K2B-JX53TM-OCRKCHFE
SFOJ6O-BNSD2G-LEEB5L-CNDASBSQ
V6RQMT-A65O4Z-VEENHR-WE53KENQ

Screenshots - I have also attached the case reflecting in Osun State.

System Details
Device:
SORMAS version:
Android version/Browser:

**Comment by bernardsilenou** [comment] 2020-06-04 17:48
@chukwuemekauzoho  Please can you delete the image, it has real data with name of the case. For the case to now show up again in the other regions, Open the case  and  make a change and save the  data again and see if it stops.

**Comment by MateStrysewskeSym** [comment] 2020-06-05 06:54
@chukwuemekauzoho Are you referring to the dashboard or the case directory?

**Comment by Chinedar** [comment] 2020-06-05 12:57
@MateStrysewskeSym this is appearing both in the dashboard and in the case directory for most of the states. 
@bernardsilenou Opening a case and making a change is impossible because these cases are not editable by users in other regions (which is a good thing). But having the cases appear in the case directory count and dashboard of other regions is a huge challenge. It throws off the epi-curve and counts for these regions.

**Comment by bernardsilenou** [comment] 2020-06-05 17:38
@Chinedar That is true; I was talking of a national user account to do so as a walk around solution.

**Comment by MateStrysewskeSym** [comment] 2020-06-08 06:49
@Chinedar The counts on the dashboard should be fixed; how exactly are you confirming that they're still appearing there? For the directories, we have issue #2137

**Comment by chukwuemekauzoho** [comment] 2020-06-12 12:48
> @MateStrysewskeSym this is appearing both in the dashboard and in the case directory for most of the states.
> @bernardsilenou Opening a case and making a change is impossible because these cases are not editable by users in other regions (which is a good thing). But having the cases appear in the case directory count and dashboard of other regions is a huge challenge. It throws off the epi-curve and counts for these regions.

Thank you @Chinedar @bernardsilenou @MateStrysewskeSym any update on this yet?

**Comment by MateStrysewskeSym** [comment] 2020-06-12 13:45
Still waiting for a confirmation that this is 100 % still occurring on the dashboard and not only in the case directories. Ideally, I'd need a basic scenario to reproduce this.

**Comment by Iheanacho2027** [comment] 2020-07-05 07:11
@MateStrysewskeSym It has been resolved in the dashboard by #2053, the problem is in the case directories as raised in #2137

**Comment by MateStrysewskeSym** [comment] 2020-07-06 07:26
@Iheanacho2027 Thanks!

**Closed by MateStrysewskeSym** 2020-07-06 07:26 UTC
Labels: bug
