### ISSUE TITLE
Letters should not be deleted when typing in text search fields

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3877] opened 2020-12-28 10:15 UTC
### Bug Description
By entering character strings in the search fields, certain typed letters appear briefly then disappear just afterwards (probably linked to a refresh of the form that is triggered when nothing is typed for a given time: if you type a new letter stack at that moment it disappears. 

This bug is general to the application and affects the "case", "contacts" and "event" parts in the same way.

### Steps to Reproduce
1. Enter a character string in the search field of the event part for example
2. Certain letters are not taken into account preventing the user from finding the event (or cases / contact) sought.

### Expected Behavior
All characters entered must appear.

### System Details
* Device:
* SORMAS version: 1.53 (and 1.52.1)
* Android version/Browser:
* Server URL: https://test1401.sormas-oegd.de/
* User Role: admin

### Additional Information
@ftavin @bernardsilenou @olivierleuci

**Comment by kwa20** [comment] 2020-12-28 15:40
@carolinverset @bernardsilenou This issue might be related to #3835?

**Comment by bernardsilenou** [comment] 2020-12-28 15:46
The goal of #2225 and #2542 was to solve this issue. However, letters are deleted when system  does the lazy loading.
- I do not know the best solution rather than recommending that we keep all the letters typed by the user on the screen and only activate the filter when the user press the "Enter" or apply filter icon key
- This is also needed for sub directories like event participants, contacts (within a case), ...

**Comment by bernardsilenou** [comment] 2020-12-28 15:55
The same as #3835

**Comment by bernardsilenou** [comment] 2020-12-28 15:57
Duplicate of #3835

**Comment by StefanKock** [comment] 2020-12-31 12:04
#3835 will address this.

**Comment by StefanKock** [comment] 2021-01-14 08:44
I reviewed this ticket and see now, that it is not a duplicate to #3835.

**Comment by StefanKock** [comment] 2021-01-14 08:46
The reported behaviour is not reproducable on 1.54.0-SNAPSHOT, presumably due to always present "Apply filters" button.

**Comment by ftavin** [comment] 2021-01-15 07:11
@StefanKock 

I reproduced the bug this morning on https://test.sormas.netzlink.com (Version: 1.54.0-SNAPSHOT)

I think you just don't understand how to reproduce it (it is tricky to explain, it took me several try before reproducing it the first time)

The timing must be really precise to see it...

I will try to show it to @bernardsilenou in our next meeting

**Comment by StefanKock** [comment] 2021-01-15 07:32
@ftavin At least tell me which view and input field (click path, screenshots) and what you did.

**Comment by ftavin** [comment] 2021-01-15 07:39
@StefanKock 

<img width="1115" alt="Capture" src="https://user-images.githubusercontent.com/15834125/104695280-c74f0200-570c-11eb-832f-45915ae79148.PNG">

I did my test using the search field on this capture.
I reproduced it typing alternatively the letters "t" and "e" with a timing like, I think, a little less than a second between each letter (and as a result I have "teee" instead of "tetete")

**Comment by StefanKock** [comment] 2021-01-15 15:23
It seems that even when the "Apply Filter" button is shown, there is a `TextChangeListener` with a delay/idle time of about 1s is still reacting on text changes. It seems to be `AbstractFilterForm:153` that sets `TextChangeListener` generically.
```
		if (TextField.class.isAssignableFrom(field.getClass())) {
			((TextField) field).addTextChangeListener(e -> field.setValue(e.getText()));
		}
```

In a similar case on another product, we triggered an event with the searchText instead of setting the value in the `TextChangeListener` to avoid input loss while updating the UI with search results.

**Comment by StefanKock** [comment] 2021-01-15 15:25
I am not sure if the `TextChangeListener` is still needed or if all views now should only listen to the "Apply Filter" button, this needs to be clarified within the team

**Comment by bernardsilenou** [comment] 2021-01-17 22:32
My understanding is that we added the "Apply Filter" button because the TextChangeListener did not function well. I would vote that we take the TextChangeListener out.

**Comment by Candice-Louw** [comment] 2021-01-20 10:50
Further reports of this happening on the CH servers too - extract from test.sormas.ch provided where 'zuiopü' is entered, but only 'zuopü' is displayed.  The 'i' is removed after the top bar loads.

![LU_typingerror](https://user-images.githubusercontent.com/65529128/105164144-10d88c00-5b15-11eb-86f3-3d76a664d84a.gif)

**Comment by ftavin** [comment] 2021-01-20 11:17
And here is a gif for a better readability (I'm typing tetetete...) :
![02](https://user-images.githubusercontent.com/15834125/105167738-61ea7f00-5b19-11eb-9ba5-082087831a76.gif)

**Comment by StefanKock** [comment] 2021-01-20 11:35
@ftavin @Candice-Louw the defect is understood and now reproducable for us, thanks.

**Closed** 2021-02-08 15:19 UTC
Labels: SSD, bug, code quality, general, vaadin-app

**Comment by raghupola-vg** [comment] 2021-02-09 17:53
Tested on version 1.57.0-snapshot and issue is Fixed
