### ISSUE TITLE
Choosing an disabled user role in the user role template when createing a new user role

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10571] opened 2022-10-06 15:02 UTC
### Bug Description

When creating a new user role it is possible to choose in the user role template an disabled user role. But when saving the field gets cleared. 

### Steps to Reproduce

1. create a new user role oder open an existing one
2. Click on diables
3. Go back and create a new user role
4. Search in the drop down User Role Template for the disabled user role and select it. 
5. Click save
6. Observe the field "User Role Template"

### Expected Behavior

A disabled user role should not appear in the drop down User Role Template.

### Screenshots

![User Role](https://user-images.githubusercontent.com/98821699/194348029-70ce41e8-2d77-4ff1-b02a-d0f3f6932768.gif)

### System Details

* Device:
* SORMAS version: 1.75.3
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment] 2022-10-06 17:36
Duplicate of #10563

**Closed by roxanamlendea** 2022-10-06 17:36 UTC
Labels: duplicate
