### ISSUE TITLE
Delete duplicate vaccinations when merging cases/contacts

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#8011] opened 2022-02-15 11:23 UTC
### Feature Description

When merging a case/contact only copy non-duplicate vaccinations.

### Problem Description

In #7452 was introduced the copy of the immunization when the case/contact is merged. That leads to the problem that there are a lot of duplicate vaccinations.

### Proposed Change

Don't copy a vaccination if the date and vaccine is the same.

**Comment by ChristopherRiedel** [comment] 2022-04-01 08:43
duplicate of #8333

**Closed by ChristopherRiedel** 2022-04-01 08:43 UTC
Labels: duplicate
