### ISSUE TITLE
Region and district filters in contacts directory should also include the new responsible region/district fields

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1708] opened 2020-03-31 16:21 UTC
### Problem Description
The current filters only rely on the region and district of the source case.

### Proposed Change
Also include the new responsible region/district fields of the contact.

**Comment by MateStrysewskeSym** [comment] 2020-04-01 06:02
Duplicate of #1665

**Closed by MateStrysewskeSym** 2020-04-01 06:02 UTC
Labels: Contact management & follow-up
