### ISSUE TITLE
Create a user role that is able to delete cases, so admins no longer need to do this

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1035] opened 2019-04-02 14:37 UTC
Admin cannot see cases created by other users from the server unless he has an added role of national user.

**Comment by hzi-braunschweig** [comment] 2019-04-02 15:30
We need to create a "system manager" who should have access to admin and national user role by default and let admin be used only for technical stuff and not manage cases. (e.g delete cases etc)

**Comment by MartinWahnschaffeSymeda** [comment] 2019-05-09 15:13
Important: Deleting should no longer delete the actual entity and instead mark it as deleted. This is necessary when we want to be able to push & update cases to third party systems.

**Comment by MateStrysewskeSym** [comment] 2019-05-10 06:42
@MartinWahnschaffeSymeda From my understanding, deleting in SORMAS should basically be used to correct mistakes (wrong data entry, duplicate case entries, ...) - these should actually not be pushed to third party systems because they're incorrect data. Everything else should be archived. However, we should definitely think about disabling deletion of e.g. burials and gatherings for normal users.

**Comment by MateStrysewske** [comment] 2021-01-26 13:30
Duplicate of #2316

**Closed by MateStrysewske** 2021-01-26 13:30 UTC
Labels: duplicate
