### ISSUE TITLE
Adding an "Apply filter" button to directories

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2566] opened 2020-07-29 08:28 UTC
### Feature Description
With the "Apply filter" button, the system would allow users to comfortably type and select their options in filters, before bringing out results. The results of selection will be displayed after the user types or selects, then click on the "Apply filter" button. The "Apply filter" button should be besides "Reset filter" button. This would solve #2225

**Comment by bernardsilenou** [comment] 2020-07-29 10:31
duplicate of #2542

**Closed** 2020-07-29 10:31 UTC
Labels: feature

**Comment by Iheanacho2027** [comment] 2020-07-29 10:36
Pls kindly reopen or restructure #2542 to accomodate directories. #2542 only speaks about the dashboard and not directories

**Comment by Iheanacho2027** [comment] 2020-07-29 13:53
Pls kindly re-open @bernardsilenou

**Comment by bernardsilenou** [comment] 2020-07-29 16:02
OK, this means II have to merge all 3 issues to one.

**Comment by bernardsilenou** [comment] 2020-07-29 16:07
@Iheanacho2027 I closed 2 issues and move the additional comment to #2225

**Comment by Iheanacho2027** [comment] 2020-07-29 16:45
@bernardsilenou this is fine
