### ISSUE TITLE
Add feature configuration for automatically setting responsible officers for cases and contacts [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6075] opened 2021-07-06 14:20 UTC
### Situation Description

Currently, the responsible officers get set automatically upon the creation or saving of cases and contacts as long as their are responsible officers present in the respective jurisdictions. This can also not be continuously changed when the user removes the officer from the field because the system keeps setting it again.
Users would like to be more flexible in assigning a responsible user to cases and contacts without the system automatically setting users as responsible officer/user.
### Feature Description

* Add a new boolean feature type property called `AUTOMATIC_RESPONSIBILITY_ASSIGNMENT`
* Add the new property to the `CASE_SURVEILANCE` feature, default value true
* Use the new property to decide whether surveillance officers are automatically set when creating/editing cases; only automatically set them if the property is enabled - this involves both the web as well as the android app
### Additional Information

also see https://github.com/hzi-braunschweig/SORMAS-Project/issues/5656 as a related issue

**Comment by bernardsilenou** [comment] 2021-07-06 16:34
@kwa20 
If AUTOMATIC_RESPONSIBILITY_ASSIGNMENT_CASES== false and automatic task assignment is activated, then all automatic task would get lost since there is no responsible user. Hope this is fine by you?

I think this is a bug `This can also not be continuously changed when the user removes the officer from the field because the system keeps setting it again.`
System should only automatically assign a user if the field == NA  and there is a user account in the district of the entity

**Comment by kwa20** [comment] 2021-07-06 16:40
@bernardsilenou Would that mean the automatic task would just not be generated? I think this would be fine then.

> System should only automatically assign a user if the field == NA and there is a user account in the district of the entity

That's the cause because removing means the field is set to NA every time

**Comment by bernardsilenou** [comment] 2021-07-06 17:05
@kwa20  
- Task wold be generated and sent to the surveillance supervisor. Users should just remember to turn the automatic task management off also.
- `That's the cause because removing means the field is set to NA every time` Why users want to keep this field as NA?
- Is it not better to have a user assign to each entity and they can change if needed ?

**Comment by kwa20** [comment] 2021-07-06 17:11
@bernardsilenou I think the main issue is that it's restricted to officers which does not quite fit how german systems are organized. This might be handled with #5656 but then it is not quite clear with what logic assignments are done besides roughly equal distribution.

**Comment by bernardsilenou** [comment] 2021-07-06 17:22
- In the district of the entity, system `randomly choose with replacement among surveillance officers` each time a new entity is created either manually or imported.  If there is only one surveillance officer, then this user is chosen all the time.
- If there is no surveillance officer, it randomly choose among surveillance supervisors in the region of the entitiy.
- Users can then manually reassign it to any surveillance officer or supervisor in the region of the entity.
- I would have a look at #5656 and if not well specified, link this comment to it.

**Comment by StefanKock** [comment] 2021-12-07 10:33
Rethink the naming and if it should be using the feature details pattern.

**Comment by MateStrysewske** [comment] 2021-12-14 11:19
@kwa20 I don't think there's any automatic assignment of contact officers to contacts. Have you observed such an automatism or did you add this to the issue on suspicion?

**Comment by kwa20** [comment] 2021-12-14 12:58
@MateStrysewske I think I mentioned it on suspicion. Just tried to produce this behaviour on 1.66.2 but I can't seem to let the system set a contact officer automatically.

**Closed** 2021-12-15 13:23 UTC
Labels: android-app, contacts, cases, backend, feature, configuration
