### ISSUE TITLE
Error on type of contact selection

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1685] opened 2020-03-28 12:01 UTC
### Bug Description
The list of contact types that is shown on the page when creating a new contact at the case contacts page isnt the same number shown after the contact is created e.g if Airplane is selected on the contact information page which is displayed at initial creation of the contact, it becomes unavailable after creation

## Screenshots

![contact a bug](https://user-images.githubusercontent.com/50739609/77822555-2c8d2480-70f4-11ea-93f9-36778e031d65.JPG)

![contact bug b](https://user-images.githubusercontent.com/50739609/77822558-344cc900-70f4-11ea-82fd-c0ed10ccd65a.JPG)

**Comment by bernardsilenou** [comment] 2020-03-28 12:06
@Iheanacho2027  We are working on this. The problem is that the certain type of contacts were defined and used only only in Germany, like "airplane". The options fro Nigeria are what appears after a contact is created,

**Comment by Iheanacho2027** [comment] 2020-03-28 14:21
For Nigeria, airplane contact is also needed and should be seen after a
contact is created

**Comment by MateStrysewskeSym** [comment] 2020-03-30 05:28
This is already fixed on the development branch and will be part of the next release.

**Closed by MateStrysewskeSym** 2020-03-30 05:28 UTC
Labels: bug
