### ISSUE TITLE
Editing selected disease on mobile app

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1461] opened 2020-01-19 05:25 UTC
Currently users aren't allowed to edit the disease they selected previously for a case. Mobile users should be allowed to edit selected data on disease just like it is on the web app

**Comment by foyiri** [comment] 2020-01-20 09:46
Do you mean changing the disease type

**Comment by Iheanacho2027** [comment] 2020-01-20 10:14
Yes

**Comment by MateStrysewskeSym** [comment] 2020-01-20 10:38
Duplicate of #1433

**Closed by MateStrysewskeSym** 2020-01-20 10:39 UTC
