### ISSUE TITLE
Add event management status to events

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4255] opened 2021-02-04 14:27 UTC
### Feature Description

Following the various comments on the issue #4167 an alternative may be proposed. 
It is described below

The management of an event consists of several stages:
-	receipt of information relating to an event leading to registration in SORMAS then designation of the person in charge of the investigation
-	Investigation process during which the responsible user formalizes the various actions taken to collect all the people involved and to limit the spread by insisting on the actions to be taken. As soon as the investigation is completed, the user informs the coordinator that the investigation is complete and proposes the closure of the event.
-	The coordinator checks the elements and closes the event when he thinks that no evolution of the event is to be expected. It is only after a few weeks that the event is archived (which causes it to disappear from the events directory)

### Problem Description

The entire event workflow is not described by the investigation status variable

### Proposed Change

To date, the investigation status variable concerns only the second phase of the life of an event, namely the investigation. In order to be able to follow the entire event workflow, we suggest adding two additional modalities:
- Request for closure of the event
- Event closed.

In the event that these modalities do not correspond to the needs of the entire SORMAS community, it is possible to make the list of modalities for this variable configurable;

### Additional Information
@bernardsilenou @ftavin @emond @MateStrysewske

**Comment by MateStrysewske** [comment] 2021-02-08 08:39
@Chinedar Do you think adding these two additional values to the event investigation status without a configuration to turn them off would be okay for Nigeria? Or does that disrupt your process too much?

**Comment by Chinedar** [comment] 2021-02-08 11:22
@MateStrysewske I'll say we add with a configuration to turn them off. Investigation operation modalities may deffer from event to event over here.

**Comment by ftavin** [comment] 2021-02-08 12:51
@MateStrysewske @Chinedar I don't think a configuration to turn off the additional values makes sense. I think we should add the values for everybody **or** propose a mechanism to let each server configure the whole set of values for the field (as described at the end of the issue by @carolinverset )

**Comment by MateStrysewske** [comment] 2021-02-08 12:56
@ftavin We definitely need such a mechanism for a lot of fields, but such a solution would need to be very thought-through. Ideally, if you'd like to work on such an approach, it would maybe be good to have a joint refinement session with some of your and some of our developers?

**Comment by bernardsilenou** [comment] 2021-02-09 17:56
@ftavin This your idea is ingenious!
What i do not understand is how this would work with the current filters + statistics. Are the current fighters generic enough to work with the different categories on each server or we would need to update them.

**Comment by bernardsilenou** [comment] 2021-02-09 18:09
@carolinverset  Please can you validate if this is right?
- Change investigation status for event only.
**Old:** pending| ongoing| done| discarded
**New:** pending| ongoing| Ready for closure| done | discarded

Request for closure of the event == Ready for closure
Event closed == done

**Comment by ftavin** [comment] 2021-02-10 08:20
@bernardsilenou I don't know about "statistics", we never had to work on this aspect of the app before
for the filters on the directory that's not a problem, we would change them as well (there already are dynamic filters on Sormas)

**Comment by bernardsilenou** [comment] 2021-02-10 12:30
@ftavin Super! I had a quick look at statistics but found nothing related to investigation status, so we are fine with adjusting only filters I suppose. Variable used in statistics:
![image](https://user-images.githubusercontent.com/12996724/107510137-d4440180-6ba3-11eb-8835-c7486649f5ab.png)

**Comment by carolinverset** [comment] 2021-02-19 14:24
> @carolinverset Please can you validate if this is right?
> 
> * Change investigation status for event only.
>   **Old:** pending| ongoing| done| discarded
>   **New:** pending| ongoing| Ready for closure| done | discarded
> 
> Request for closure of the event == Ready for closure
> Event closed == done


Sorry to only answer now.
I almost agree with you. With the exception of one modality which remains missing: 
Bernard, you only propose one "done" modality. However, in France, we have to differentiate the investigation and the event: the investigation can be finished while the event itself is not yet closed.

I suggest differentiating between the investigative process and the more general process of managing the event. 
We could therefore keep the following modalities:
(for investigation) pending | ongoing | done | (for the event) event ready for closure | event closed | discarded

what do you think of this proposal ?

**Comment by bernardsilenou** [comment] 2021-02-19 18:37
@carolinverset  @ftavin @MateStrysewske @kwa20 
- Based on @carolinverset  last comment, it would be good not to use these options: `(for investigation) pending | ongoing | done | (for the event) event ready for closure | event closed | discarded` as categories of a single variable since some of the options are related to the investigation of the event while others are related to the followup or management of the event. This is a similar situation we have for cases, investigation is completed once we confirmed that the case is a true case and followup and management continues till outcome of the case.  We can apply the same token for event, I can think of 2 options:
1. Using the change as initially proposed #4167
2. To keep the system as it is an add another variable to represent the followup status of the event. 
    - event investigation status: pending | ongoing | done |discarded, we keep this as it is.
    - We can call it a name like `event followup status` or `event management status`:     none| ongoing| ready for closure | closed 

What do you think also pls?

**Comment by kwa20** [comment] 2021-02-21 15:55
@bernardsilenou @carolinverset @MateStrysewske I think you have very good points and I agree that the main problem we have from a usability point of view is the differentiation between investigation and management status while investigation is basically nested inside of the management. The meaning of the investigation status seems to be unclear for users quite often.
My suggestions:
- event management status: pending|ongoing|done|closed
- investigation status: pending|ongoing|done

The investigation status can therefore have any of the statuses while the event management status is ongoing since the investigation is only one part of the ongoing management. 

I'm thinking that "done" as a management status would be more generic than "ready for closure" because the latter to me sounds more like a task and might not fit all users use cases globally.
Separating statuses would also give us the option to hide one or the other if necessary for whatever reason.

**Comment by carolinverset** [comment] 2021-02-22 08:54
@bernardsilenou @ftavin @MateStrysewske @kwa20 
Indeed, having two different variables is very probably the best solution. This corresponds to the initial request of French users :)
I subscribe to kay's analysis and agree with the modalities proposed for these two variables

**Comment by MateStrysewske** [comment] 2021-02-22 15:14
@carolinverset @kwa20 No objections from me as well

**Comment by bernardsilenou** [comment] 2021-02-22 17:30
@ftavin

**Comment by ftavin** [comment] 2021-02-23 07:49
@bernardsilenou @carolinverset @MateStrysewske @kwa20 

So I believe we went back to the original issue #4167 

I suggest we close this one and reopen the former, the devs may be lost if we continue with this one...

Alternative is to close this one, leave #4167 closed and create a new, clean one with the final specification (and links to these two issues)

**Comment by bernardsilenou** [comment] 2021-02-23 10:23
@ftavin  I think option 2 is better so that we can trace back and validate all points from both issues are considered.
@MateStrysewske @kwa20 @Candice-Louw  do you agree with this point  from  #4167 `rename “event status” to “event category” `

**Comment by MateStrysewske** [comment] 2021-02-23 12:42
@ftavin @bernardsilenou I think it's fine to keep this issue open and use it, as long as we rename it and update the initial issue description with what has been decided. What do you think?

**Closed** 2021-03-04 14:05 UTC
Labels: change, fr
