### ISSUE TITLE
Inconsistent display of approximate age in database export

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7702] opened 2022-01-18 11:36 UTC
### Bug Description

The approximate age in database exports diverges from the display in e.g. detailed case exports. It is not clear which unit the respective number has. Differences occur when cases have an age below 1 year. Days are displayed as numbers > 0 while months have a 0 entered.
### Steps to Reproduce

1. Create cases that have ages below 1 year
2. Export the cases via the detailed case export and cases/persons database export
3. Compare the approximate age columns of the files

### Expected Behavior

The database export should also display the unit of the approximate age. Otherwise it should somehow be clear how the approximate age is entered without having to check the respective age.
### Screenshots

database cases
<img width="214" alt="approxAgeDatabaseExport2" src="https://user-images.githubusercontent.com/70317594/149930234-c9dfb37f-4058-45f5-a7fc-544bd0b11225.PNG">

database persons
<img width="638" alt="approxAgeDatabaseExport" src="https://user-images.githubusercontent.com/70317594/149930224-7704d049-007e-4f0f-a7c9-01d08742112c.PNG">

detailed cases
<img width="433" alt="approxAgeDatabaseExportCaseDetailed" src="https://user-images.githubusercontent.com/70317594/149930229-73197384-0e6b-4456-b944-5e7121b3caca.PNG">

### System Details

* Device:
* SORMAS version: 1.66.4
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment] 2022-01-18 11:37
@MartinWahnschaffe We might want to check if this has been changed after https://github.com/hzi-braunschweig/SORMAS-Project/issues/6951 was implemented

**Comment by leventegal-she** [comment] 2022-01-28 07:21
The case age field is always in years
Persons database export has another column called `approximateagetype` that specifies the unit of the approximate age.

I would suggest to create 2 change requests and close this ticket as not a bug:
1) Change DB export to enforce `approximateage` and `approximateagetype` columns near each other
2)  Rename the field `caseage` to `caseAgeYears`

@kwa20 @MateStrysewske @MartinWahnschaffe

**Comment by kwa20** [comment] 2022-01-28 07:42
@leventegal-she Sounds good overall. However, as long as we have a unit for the approximate age, I think it's good to show the respective number and not 0 because it's related to years. I think the numbering is just not consistent n DB export and detailed exports?

**Comment by leventegal-she** [comment] 2022-01-28 08:03
@kwa20 DB export and DB export are different things:
* `DB export` is a kind of csv export from the database, having the same structure as the database.
* `Detailed export` is a user friendly and highly customised csv

So it doesn't have to be consistent

`caseAge` is not the age of the person linked to the case, but it's calculated based on the age of the person and it is used only for statistics. It was introduced in https://github.com/hzi-braunschweig/SORMAS-Project/issues/585. @MateStrysewske or @MartinWahnschaffe can tell you more about that field.

**Comment by kwa20** [comment] 2022-01-28 08:20
@leventegal-she I see, does that mean that differing numbers in the database are expected? Days are written as numbers in days but moths are displayed as a 0 in the unit years. If we have an `approximateagetype`, shouldn't months also display the respective number of months instead of a 0?

**Comment by leventegal-she** [comment] 2022-01-28 08:47
@kwa20 

In **persons.csv** from DB export `approximateage` is the same number what you see on the UI or in the detailed export in the column `approximateagetype` is *YEARS, MONTHS* or *DAYS* depending on the age of the person.

The `caseAge` in **cases.csv**  from DB export is always in years and it can be different then the age of the case person.
 It is used only for statistics when you select `Age stratification` for rows or columns there is enough to see 0 for the few day/month old cases.

**Comment by MateStrysewske** [comment] 2022-01-28 08:47
@leventegal-she Agreed. I'd leave the final decision to Kay though.

@kwa20 I believe that Levi answered all your questions :)

**Closed** 2022-01-28 08:50 UTC
Labels: bug, cases, backend, import & export, minor
