### ISSUE TITLE
Hide "NEW ..." buttons if the right to create is not selected

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10631] opened 2022-10-13 12:43 UTC
### Bug Description

Although the user does not have permission to create a prescription, treatment or clinical assessment the buttons are displayed. 
![Nwe-Button](https://user-images.githubusercontent.com/101708230/195598550-b2b30cca-ebab-4471-80ca-c2785a619812.gif)

![image](https://user-images.githubusercontent.com/101708230/195598596-bc649d40-aee3-43ef-a1dd-64748ed66207.png)

### Steps to Reproduce

1.   Create a user role without the rights to create or edit  prescription, treatment or clinical assessment 
2.   Assign it to a user  and login with this user
 

### Expected Behavior

Please hide the buttons. 

### System Details

* Device: Laptop
* SORMAS version: 1.75.4
* Android version/Browser: Chrome
* Server URL:   release-international.sormas.netzlink.com     -     On the previously mentioned test1401 the functions will be disabled via Feature Configuration.  
* User Role: Admin and individual role

**Comment by andrei7bal** [comment] 2022-10-25 10:58
Hello!

To be consistent with other rights actions, I've disabled this buttons in case the right to create is missing.
Let me know if it's ok like this, or I should hide the buttons.

Regards,

**Comment by roxanamlendea** [comment] 2022-11-16 07:27
Reopening the ticket because the Prescriptions are not editable.

1. Log in with an Admin + National User;
2. Open a Case and navigate to the Therapy tab;
3. Create a Prescription;
4. Then open the Prescription from step 3;
-> the Prescription is read-only, but it should be editable;

**Comment by roxanamlendea** [comment] 2022-11-16 10:06
Apparently the bug was actually caused by ticket #8463 and will be fixed there.

**Closed by roxanamlendea** 2022-11-16 10:06 UTC
Labels: bug, cases, vaadin-app, minor

**Comment by roxanamlendea** [comment] 2022-11-16 14:44
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (fa25496).
