### ISSUE TITLE
documents not deletable 

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11052] opened 2022-11-29 17:47 UTC
### Problem Description

Although the user has all necessary rights an attached document is not deletable.
![image](https://user-images.githubusercontent.com/100844689/204600141-7b289b19-ea8e-4103-bd93-53beb2ed1dc2.png)

If you share the case/contact with ownership _then_ the document becomes deletable. 
#### Steps to Reproduce

1. attach a document to a case /contact
2. observe if the document is deletable 
3. share the case/contact with ownership
4. accept in target system
5. observe in source system if document is deletable now

#### Screenshots

![finding doc delete](https://user-images.githubusercontent.com/100844689/204603157-8d4a4222-899b-4d3d-a4fc-879c1bd1dcbe.gif)

#### System Details

* Device:
* SORMAS version: 1.77 d20e85915
* Android version/Browser: Edge
* Server URL: test-de1 to test-de2
* User Role: admin

### Expected Behavior

documents are already deletable in step 2

### Additional Information

refers to #11018

**Comment by roxanamlendea** [comment] 2022-11-30 09:37
Caused by #8463. Will be fixed there.

**Closed by roxanamlendea** 2022-11-30 09:37 UTC
Labels: duplicate
