### ISSUE TITLE
Quarantine start/end date plausibility not checked

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3318] opened 2020-10-28 12:01 UTC
### Bug Description

For quarantine, it is possible to choose an end date before the start date

### Steps to Reproduce
1. Select quarantine "Häuslich" or "Institutionell"
2. Choose a start date and an end date which is before this start date

### Expected Behavior
Plausibilty end date >= start date should be checked at least when saving

### Screenshots
![image](https://user-images.githubusercontent.com/5616564/97433349-a2bd6800-191d-11eb-8402-cb83640d85e4.png)

### System Details
* Device: local
* SORMAS version: 1.51.0-SNAPSHOT
* Android version/Browser: Firefox
* User Role: Case Supervisor

**Comment by alexcaruntu-vita** [comment] 2021-03-03 12:53
Duplicate of #4559. Fixed in [this](https://github.com/hzi-braunschweig/SORMAS-Project/pull/4594) PR.

**Closed** 2021-03-03 12:59 UTC
Labels: duplicate
