### ISSUE TITLE
Unsaved changes popup is displayed after confirming entity deletion

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#9435] opened 2022-06-07 09:15 UTC
### Bug Description

When changes are made to an entity and then the entity is deleted without saving, I am asked if I want to save the changes.
### Steps to Reproduce

1. Open a case/contact/event
2. edit data
3.  DON'T SAVE
4. Delete the case/contact/event
5. After edeletion you get ask if you want to "Discard Changes" or "Save Changes"

### Expected Behavior

Show the "unsaved changes" popup as soon as the user clicks on "Delete", and only after a decision was made process the deletion.
### Screenshots

![deletion_saving](https://user-images.githubusercontent.com/96547924/172343682-6b1916b2-9f7f-461e-adbf-322120a64d2a.gif)

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser:
* Server URL: test1402
* User Role: admin

### Additional Information

Applies to all entities

**Comment by kwa20** [comment] 2022-06-07 11:13
@cmeyerhzi Do you know if this happens for any entity type? I can't remember. If this is the case, it should be fixed everywhere.

**Comment by cmeyerhzi** [comment] 2022-06-07 11:25
@kwa20 i checked again and it happens for all entity type. i updated the initial post.

**Comment by adinaflorea9** [comment] 2022-07-06 07:31
I am reopening the ticket due to the following:

1. Event Groups:
- open an existing event group;
- make a change on the event group;
- click 'Delete';
- click 'Yes' in the 'Confirm deletion' pop-up;
- click 'Save changes' in the 'Confirm navigation' pop-up
=> event group is not deleted

2. Travel Entries:
2.1:
- open an existing travel entry;
- make a change on the travel entry page;
- click 'Delete';
- click 'Discard' in the 'Confirm navigation' pop-up;
- pick a reason for deletion in the 'Confirm deletion' pop-up and click 'Yes';
=>'Confirm navigation' pop-up is triggered a second time.
- click 'Save changes';
- error message appears:
![image](https://user-images.githubusercontent.com/96909231/177494180-52bac72e-1692-46c0-a652-e219f8aef519.png)

2.2:
- open an existing travel entry;
- make a change on the travel entry page;
- click 'Delete';
- click 'Discard' in the 'Confirm navigation' pop-up;
- pick a reason for deletion in the 'Confirm deletion' pop-up and click 'Yes';
=>'Confirm navigation' pop-up is triggered a second time.
- click 'Discard changes';
=> 'Confirm navigation' pop-up is triggered 2 more times.

**Expected behavior**: 'Confirm navigation' pop-up should be triggered consistently, right after the user makes changes on a page, and then clicks the 'Delete' button.

**Comment by StefanKock** [comment] 2022-07-12 07:34
>     * I can confirm this on https://test-de1.sormas.netzlink.com/ with [fdc98e9](https://github.com/hzi-braunschweig/SORMAS-Project/commit/fdc98e9c93a36abb9e854223c78cf7fb584c9075) but it has nothing to do with the delete function. It also happens when you just change data and try to switch to another directory.
Documented as #9811

**Closed** 2022-07-12 11:13 UTC
Labels: bug, cases, vaadin-app, major

**Comment by adinaflorea9** [comment] 2022-07-12 14:06
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(08db1fc).

The behavior reported in comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/9435#issuecomment-1175880462 regarding travel entries has been moved to ticket #9811.
