### ISSUE TITLE
[Cases] Error message appears when the user tries to save a case with 'Case Origin' - 'Point of Entry'

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8280] opened 2022-03-08 09:19 UTC
### Bug Description

An error message appears when a user tries to save a case that has the 'Case Origin' set to 'Point of Entry' and no value selected for the 'Place of stay'.

The error message is reproducible only on the test instance: test-de3.sormas.netzlink.com.

### Steps to Reproduce

1. Open the 'Create new case' form;
2. Set the 'Case origin' to 'Point of Entry';
3. Fill in the mandatory fields;
4. Do not select any value for the 'Place of stay';
5. Click 'Save'.

### Actual Behavior

An error message is displayed and the user can not save the case.

### Expected Behavior

No error message appears and the user is able to successfully save the new case.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/157205763-f323e51d-728a-41d3-bb22-0e33fe7b8cde.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(a43fa81)
* Android version/Browser: Chrome
* Server URL: test-de3.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

The logs for the error message:
[test-de3-logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8204466/test-de3-logs.txt)

The DB for this test instance was checked and this was the response:
![image](https://user-images.githubusercontent.com/96909231/157206354-1b080ff5-ab2f-41bd-b4b1-52130fc42e56.png)

**Comment by dinua** [comment] 2022-03-09 08:26
@adinaflorea9 
as far I can see "Place of stay" is marked as mandatory field
 
![image](https://user-images.githubusercontent.com/4202109/157401821-afb1adba-6130-4b2b-ba29-7a486dc4b4bf.png)

Should I make this field no longer mandatory ? or should I close the ticket ?

**Comment by adinaflorea9** [comment] 2022-03-09 08:30
@dinua if the 'Case origin' is set to 'Point of Entry' in the 'Create new case' form, the 'Place of stay' is not a mandatory value.

**Comment by adinaflorea9** [comment] 2022-03-09 08:31
@MateStrysewske Could you please take a look over the proposed solution? Or @dinua Could you please discuss it with Mate?

**Comment by dinua** [comment] 2022-03-09 13:05
@StefanKock 
I analyze the logs and the systems for this bug.
The error we get is "Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "healthfacility_id" violates not-null constraint"
It seems there is an inconstancy with the DB corresponding to server test-de3.sormas.netzlink.com.
In all others systems the column public.cases.healthfacility_id allow null values , but in this DB it does not . Someone with access to this DB should make the change to allow null values and I think after the bug will be fixed

**Comment by MateStrysewske** [comment] 2022-03-09 13:51
@dinua Absolutely correct, thanks for figuring this out!

**Closed by MateStrysewske** 2022-03-09 13:51 UTC
Labels: bug, cases, vaadin-app, major
