### ISSUE TITLE
Clicking on add New campaign throws an error message

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3146] opened 2020-10-12 16:27 UTC
### Bug Description
When logged in as National coordinator and Campaign directory is selected, Trying to add a new campaign using "New Campaign" button  throws an error message

### Steps to Reproduce
1. Login to APMS as National Coordinator
2. Select Campaigns to access campaign directory
3. Click on "New Campaign" button present at the top right corner.

### Expected Behavior
New Campaign form has to be displayed.

### Screenshots
![Afghanistan- add new campaign](https://user-images.githubusercontent.com/62763628/95769553-5b49a180-0cb8-11eb-8e35-eb5fd8b16c93.PNG)

### System Details
* Device: 
* SORMAS version: 1.50.0-snapshot
* Android version/Browser: Chrome/firefox
* Server URL: https://test-afghanistan.sormas.netzlink.com/
* User Role: National Coordinator

**Comment by MateStrysewske** [comment] 2020-10-13 07:15
Duplicate of #3140

**Closed by MateStrysewske** 2020-10-13 07:15 UTC
Labels: af, bug, sormas-ui
