### ISSUE TITLE
Configuration > Countries > Initial "Data Import" screen not updating

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3709] opened 2020-12-07 01:15 UTC
### Bug Description
When initially importing default countries (Configuration > Countries), the import screen appears, but does not update progress as the imports are made.  After a while, the user has to click "Cancel" to close the popup screen.  When the popup and other screens close, the countries are imported none the less.

### Steps to Reproduce
1. Configuration > Countries
2. Import default countries (on server where this has not been done before)
3. Wait
4. Cancel after some time and close popups
5. Countries imported none the less

### Expected Behavior
Progress screen updates

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/101298950-8ec82880-3830-11eb-9a78-c1766a7d5808.png)

### System Details
* Device: Web/PC
* SORMAS version: 1.52.+
* Android version/Browser: Chrome
* Server URL: https://release-ch.sormas.netzlink.com/
* User Role: admin

**Comment by syntakker** [comment] 2021-03-26 20:47
Duplicate of #4905.

**Closed by syntakker** 2021-03-26 20:47 UTC
Labels: bug
