### ISSUE TITLE
Generation of CIFs and IDSR-001A from data entered on SORMAS 

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1305] opened 2019-09-15 21:51 UTC
It would be very wonderful if the nigerian Case Investigation Form (CIF) and IDSR-001A could be generated from data entered on SORMAS to enable the surveillance officers and other users download the filled form both on the mobile and web platforms. This would enable a quick transition to full time acceptance and use of SORMAS @hzi-braunschweig @Chinedar @foyiri @bernardsilenou

**Comment by MateStrysewskeSym** [comment] 2019-09-17 10:29
This is probably a duplicate of #1105?

**Comment by Iheanacho2027** [comment] 2019-09-17 10:31
Yes it is

**Closed** 2019-09-17 11:20 UTC
Labels: duplicate
