### ISSUE TITLE
Investigate possibility of additional test creation without a sample ID

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3436] opened 2020-11-09 14:58 UTC
### Bug Description
* When a user is logged-in to 1,50 and server is later upgraded to 1,51. 
   - App does not inform user of the new version
   - App present errror message when synchroniziing data and does not synchronze
* After closing the app and reopen it again, auto update pop  up message appeared, information user of the new version on server. 
App upgrade to to 1,51 and app still could not sync with server after the upgrade. Re-sync also fails.
### Steps to Reproduce
1.
2.

### Expected Behavior
- app should always sync data with server if version on app on mobile device is the same or younger than version on server
- if user is logged-in on app and server is later upgraded, app should sync data and also inform the user of the new version after the sync process. Users must not close app in order to get informed on the latest version
### System Details
* Device: Samsung galaxy, android 9
* SORMAS version:  1,51
* Android version/Browser:
* Server URL: connected to https://test1401.sormas-oegd.de/sormas-ui/#!users
* User Role: surveillance + contact officer

**Comment by MateStrysewske** [comment] 2020-11-10 10:58
@bernardsilenou Tested it on my system by ugrading from 1.50.0 to 1.51.0 and had no problems with synchronization or the upgrade itself. Could you please verify it with another device (and ideally on another system as well)?

Regarding your first point, this was done on purpose to not disrupt users in their work. If a user is currently in an area with very bad internet connection, they might want to delay the app update. Getting the prompt to download and install the new update every time they synchronize would be very annoying, which is why it only appears on startup. We could however think about adding a "Check for updates" button to the settings that would allow users to manually trigger the update process without having to close the app.

**Comment by bernardsilenou** [comment] 2020-11-10 23:30
@MateStrysewske Thanks for the information. I will test with the coming release.
It is a good decision that we should not force the user to upgrade each time they sync. However it will be good to inform them of  the new update as you suggested as long as the app is on. We can also add a warning message that good internet connectivity is needed to do the upgrade.

**Comment by bernardsilenou** [comment] 2020-11-11 17:32
@MateStrysewske 
I did dug further by testing with another device with Fresh installation of 1,51.
1. Fresh installation connected to server and pull infrastructure data, cases,event, samples, ...  But not contacts. I confirmed on the wen that contacts existed but were not pulled. There seam to be something wrong happening with contacts and their responsible jurisdictions during sync process.
2. Subsequent sync after the initial pull display "sync failed, please try  again"
3. Navigation and creating on entities on both tablets work fine but no sync is possible with server
One of the devices is logged to https://test1401.sormas-oegd.de/sormas-ui/#!users with user account bsiSOBayern

**Comment by MateStrysewske** [comment] 2020-11-12 08:37
@bernardsilenou Looks like the test server contains at least one additional test that does not have a sample_id assigned, which leads to a database insertion problem in the mobile app which then in turn leads to the synchronisation problem. I.e., there is corrupt data in the database. I don't know how that happened, but it's definitely not a general problem with the mobile app.

**Comment by bernardsilenou** [comment] 2020-11-12 10:11
@MateStrysewske I got it. So what is the logic we need to put in place  to correct this king of issues? 

 In a workshop with the Nigerian users last week, they mentioned synchronization challenges as their main challenge. Things like this may appear in their systems also.

How can i test further?

**Comment by MateStrysewske** [comment] 2020-11-12 10:23
@bernardsilenou I guess we'll have to investigate how it's possible that an additional test is created that doesn't have a sample ID. I'll reopen this issue and relabel it accordingly so we can have a look at it in the current sprint.

**Comment by MateStrysewske** [comment] 2020-12-14 13:24
@bernardsilenou I made a few adjustments that MIGHT have an impact on this although I think it's unlikely. I can't produce an additional test without a sample ID on my system. I'll close this issue for now.

**Comment by bernardsilenou** [comment] 2020-12-14 19:33
@MateStrysewske Super, I would test with 1,53 and give you feedback

**Comment by bernardsilenou** [comment] 2020-12-17 15:23
@fhauptmann @MateStrysewske  @kwa20 
We discussed to further investigate the cause of this issue in the first place

**Comment by fhauptmann** [comment] 2020-12-17 15:31
We still need to figure out, how it happened to corrupt the database. Can this happen on production environments, too?

**Comment by bernardsilenou** [comment] 2020-12-17 15:38
I reopened because we want to keep track and test further

**Comment by fhauptmann** [comment] 2020-12-17 16:02
I got a dump of the database from test1401: I didn't find a sample without UUID.

**Comment by MateStrysewske** [comment] 2020-12-17 16:41
@fhauptmann The problem is not that there's a sample without a UUID, but that there are additional tests without a sample_id.

**Comment by StefanKock** [comment] 2020-12-21 08:10
This ticket was solved by @MateStrysewske, merged and closed to the released version

**Closed by StefanKock** 2020-12-21 08:10 UTC
Labels: Laboratory, SSD, bug, sormas-api, sormas-backend
