### ISSUE TITLE
Error request via Rest-API for some cases

### ISSUE THREAD

**Issue by geo-hf** [hzi-braunschweig/SORMAS-Project#7703] opened 2022-01-18 11:38 UTC
### Bug Description
We are using the SORMAS-REST-API.
We are sending data like cases as request in a json-body via post-method, e.g. “{{baseUrl}}/cases/push”. 
In most cases it works.
In this context, we detected few problems in sending cases via push. 
The error of these problems is “400 Bad Request”; 
“The server detected a syntax error in your request. Check your request and all parameters.”.
Therefore we checked the reason of the error. 
If there is entered an end-date for an exposure (in UNIX), we will receive this error. 

As soon as we remove the property “endDate” for the exposure from the JSON-body, it works and the response would be “OK”. 
Is there a possibility to fix this problem or are there rules for the values of the property “endDate”?

Thank you.

### Screenshots
Reqest in json-body:
![request](https://user-images.githubusercontent.com/97951571/149930039-09e9d832-aa5c-4283-b38d-e6da1a101087.png)

Response in html:
![Unbenannt](https://user-images.githubusercontent.com/97951571/149930842-a921464d-0083-4b6a-bb46-f7296bd651e6.png)

### System Details

* Hosting from ITZBund (Germany)
* SORMAS version: 1.66.4
* User Role: ReST-User

**Comment by MateStrysewske** [comment] 2022-01-18 13:02
@geo-hf Can you show us the whole request with either blurred or altered personal details/other information that could be used to identify the person (or at least the whole section of the request that relates to exposures)?

**Comment by geo-hf** [comment] 2022-01-18 14:02
Thank you.
Here is the section with an exposure ("endDate": 1640646000000,")
![exposure_1](https://user-images.githubusercontent.com/97951571/149951624-8038167d-a286-4cab-ac81-8834d40d902e.png)
![exposure_2](https://user-images.githubusercontent.com/97951571/149951642-7a57a4f1-76ac-4edb-b949-931753fbfc74.png)
:

**Comment by FredrikSchaeferVitagroup** [comment] 2022-01-19 08:37
On a test system, I could not yet reproduce the error. In approximation to the provided example, I tried around this, but never got back a `400 Bad Request`:
```
[
  {    
    "disease": "CORONAVIRUS",
    "reportingUser": {
        "uuid": "UOTDRG-SSTQ46-BWKKTK-UCWFSMWM"
    },
    "person": {
      "uuid": "TKQ4A2-MNL4MH-BNEQNZ-C5NDKIRY"
    },
    "caseClassification": "SUSPECT",
    "epiData": {
        "exposures": [
                        {
                        "creationDate": 1640870345994,
                        "changeDate": 1642578100852,
                        "uuid": "UOTDDG-SSTQ46-BWKWSK-UCWFSM2M",
                        "pseudonymized": false,
                        "reportingUser": {
                            "uuid": "UOTDRG-SSTQ46-BWKKTK-UCWFSMWM"
                        },
                        "probableInfectionEnvironment": true,
                        "startDate": 1640646000000,
                        "endDate": 1640646000000,
                        "description": "Familie",
                        "exposureType": "HABITATION",
                        "location": {
                            "region": {
                                "uuid": "TN6ZRW-DHOMWY-5ZEXS2-ULKYSGJA"
                                },
                            "district": {
                                "uuid": "TG6DJM-F7SFOV-5RMJ5X-2ALC2NHE"
                                }
                            }
                        }
                    ]
                },
                "responsibleRegion": {
                    "uuid": "TN6ZRW-DHOMWY-5ZEXS2-ULKYSGJA"
                    },
                "responsibleDistrict": {
                    "uuid": "TG6DJM-F7SFOV-5RMJ5X-2ALC2NHE"
                    },
                "healthFacility": "SORMAS-CONSTID-ISNONE-FACILITY",
                "investigationStatus": "PENDING"
  }
]

```

Also, neither the [ExposureDto.getEndDate()](https://github.com/hzi-braunschweig/SORMAS-Project/blob/f17183d93fc39dd8e1c72adf3a11803c83da9ac1/sormas-api/src/main/java/de/symeda/sormas/api/exposure/ExposureDto.java#L303), nor the [Exposure.getEndDate()](https://github.com/hzi-braunschweig/SORMAS-Project/blob/f17183d93fc39dd8e1c72adf3a11803c83da9ac1/sormas-backend/src/main/java/de/symeda/sormas/backend/exposure/Exposure.java#L170) seem to get called for any validation. I am a little out of ideas at the moment...

**Comment by geo-hf** [comment] 2022-01-19 09:31
attached another complete example (personal data has been redacted):
```
[
    {
        "creationDate": 1641452321837,
        "changeDate": 1642583441843,
        "uuid": "SWWXGI-MWP2T4-WA4FU4-BTUYSM7M",
        "pseudonymized": false,
        "disease": "CORONAVIRUS",
        "diseaseVariant": {
            "value": "B.1.1.529",
            "caption": "B.1.1.529 (Omicron)",
            "hasDetails": true
        },
        "person": {
            "uuid": "RXWAME-ATMTWH-G7RA2K-OQYESMDY",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "firstName": "▇▇▇▇▇▇▇▇▇",
            "lastName": "▇▇▇▇▇▇▇▇▇"
        },
        "reportDate": 1641510000000,
        "reportingUser": {
            "uuid": "R5BKAB-PK4YRG-T57GH4-KP6FCF34",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "firstName": "▇▇▇▇▇▇▇▇▇ ",
            "lastName": "▇▇▇▇▇▇▇▇▇"
        },
        "caseClassification": "CONFIRMED",
        "caseIdentificationSource": "SCREENING",
        "screeningType": "SELF_ARRANGED_TEST",
        "classificationUser": {
            "uuid": "R6CR6Q-ZINMPC-L34RRD-AGC3KOMM",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "firstName": "▇▇▇▇▇▇▇▇▇",
            "lastName": "▇▇▇▇▇▇▇▇▇"
        },
        "classificationDate": 1641544952230,
        "laboratoryDiagnosticConfirmation": "YES",
        "investigationStatus": "DONE",
        "investigatedDate": 1641510000000,
        "outcome": "RECOVERED",
        "outcomeDate": 1642287600000,
        "responsibleRegion": {
            "uuid": "TJR5QB-UPSGMG-YYUYCZ-YM4DSMUU",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "externalId": "▇▇▇▇▇▇▇▇▇"
        },
        "responsibleDistrict": {
            "uuid": "RBIQ55-KFCARV-FZFGY4-6GDBCOLA",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "externalId": "▇▇▇▇▇▇▇▇▇"
        },
        "responsibleCommunity": {
            "uuid": "UXO6GP-JS6WE7-2TKP2W-JWKJKGKU",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "externalId": "▇▇▇▇▇▇▇▇▇"
        },
        "healthFacility": {
            "uuid": "SORMAS-CONSTID-ISNONE-FACILITY",
            "caption": "Zuhause oder anderer Ort",
            "externalId": null
        },
        "pregnant": "NO",
        "vaccinationStatus": "VACCINATED",
        "surveillanceOfficer": {
            "uuid": "XNRMEA-TGXT4X-BCV4XS-XU54SJ5A",
            "caption": "▇▇▇▇▇▇▇▇▇",
            "firstName": "▇▇▇▇▇▇▇▇▇",
            "lastName": "▇▇▇▇▇▇▇▇▇"
        },
        "hospitalization": {
            "creationDate": 1641452321841,
            "changeDate": 1642583476244,
            "uuid": "TNSBFN-EIYC5U-PTCLEN-W35JSBCA",
            "hospitalizedPreviously": "NO",
            "previousHospitalizations": []
        },
        "symptoms": {
            "creationDate": 1641452321844,
            "changeDate": 1641551186189,
            "uuid": "SEP5A4-P6N3RO-4TBFJA-P2QJKG3M",
            "pseudonymized": false,
            "chillsSweats": "NO",
            "cough": "YES",
            "diarrhea": "NO",
            "difficultyBreathing": "NO",
            "fever": "NO",
            "headache": "NO",
            "musclePain": "NO",
            "nausea": "NO",
            "onsetDate": 1641078000000,
            "otherNonHemorrhagicSymptoms": "NO",
            "rapidBreathing": "NO",
            "runnyNose": "NO",
            "soreThroat": "YES",
            "symptomatic": true,
            "acuteRespiratoryDistressSyndrome": "NO",
            "pneumoniaClinicalOrRadiologic": "NO",
            "lossOfTaste": "NO",
            "lossOfSmell": "NO",
            "respiratoryDiseaseVentilation": "NO",
            "feelingIll": "NO",
            "fastHeartRate": "NO",
            "oxygenSaturationLower94": "NO",
            "shivering": "NO"
        },
        "epiData": {
            "creationDate": 1641452321841,
            "changeDate": 1642583476245,
            "uuid": "XXCRZI-TBNMXP-SV7I2M-IKLFKMQI",
            "pseudonymized": false,
            "exposureDetailsKnown": "YES",
            "activityAsCaseDetailsKnown": "NO",
            "contactWithSourceCaseKnown": "YES",
            "highTransmissionRiskArea": "NO",
            "largeOutbreaksArea": "NO",
            "exposures": [
                {
                    "creationDate": 1641554385096,
                    "changeDate": 1642583476245,
                    "uuid": "XYC7NI-NVWMIZ-WXUBVG-6SZB2AQM",
                    "pseudonymized": false,
                    "reportingUser": {
                        "uuid": "VE636N-VCRGTE-J3PTTQ-ENFQKFSA",
                        "caption": "▇▇▇▇▇▇▇▇▇",
                        "firstName": "▇▇▇▇▇▇▇▇▇",
                        "lastName": "▇▇▇▇▇▇▇▇▇"
                    },
                    "probableInfectionEnvironment": false,
                    "startDate": 1640473200000,
                    "endDate": 1640991600000,
                    "description": "▇▇▇▇▇▇▇▇▇",
                    "exposureType": "TRAVEL",
                    "location": {
                        "creationDate": 1641554385097,
                        "changeDate": 1641554385097,
                        "uuid": "UUYSYO-AXAZ2U-4MAFKW-DW24SH6Q",
                        "pseudonymized": false,
                        "region": {
                            "uuid": "TJR5QB-UPSGMG-YYUYCZ-YM4DSMUU",
                            "caption": "▇▇▇▇▇▇▇▇▇",
                            "externalId": "▇▇▇▇▇▇▇▇▇"
                        },
                        "district": {
                            "uuid": "RBIQ55-KFCARV-FZFGY4-6GDBCOLA",
                            "caption": "▇▇▇▇▇▇▇▇▇",
                            "externalId": "▇▇▇▇▇▇▇▇▇"
                        }
                    }
                }
            ],
            "activitiesAsCase": []
        },
        "therapy": {
            "creationDate": 1641452321844,
            "changeDate": 1641452321844,
            "uuid": "VLAN5P-OFJJJB-UZHG35-35PZ2M2Y"
        },
        "clinicalCourse": {
            "creationDate": 1641452321840,
            "changeDate": 1641452321840,
            "uuid": "SRYLJI-IF3MRW-QJJOSN-2MSNSNDI",
            "healthConditions": {
                "creationDate": 1641452321840,
                "changeDate": 1641551227474,
                "uuid": "UAQ3TL-RRFDFH-7AIEPK-BMIXKDEU",
                "pseudonymized": false,
                "diabetes": "NO",
                "chronicLiverDisease": "NO",
                "malignancyChemotherapy": "NO",
                "chronicPulmonaryDisease": "NO",
                "chronicKidneyDisease": "NO",
                "chronicNeurologicCondition": "NO",
                "cardiovascularDiseaseIncludingHypertension": "NO",
                "immunodeficiencyIncludingHiv": "NO",
                "otherConditions": "▇▇▇▇▇▇▇▇▇"
            }
        },
        "maternalHistory": {
            "creationDate": 1641452321842,
            "changeDate": 1641452321842,
            "uuid": "QZLI2D-IEIFZG-2LWK6E-7WTXCGBI",
            "pseudonymized": false
        },
        "portHealthInfo": {
            "creationDate": 1641452321843,
            "changeDate": 1641452321843,
            "uuid": "WNB2T7-IWZYXG-2L3AKZ-I6QBSKLU"
        },
        "caseOrigin": "IN_COUNTRY",
        "additionalDetails": "▇▇▇▇▇▇▇▇▇",
        "externalID": "{5af2722b-9a15-49a7-abeb-99938a263ba6}",
        "externalToken": "▇▇▇▇▇▇▇▇▇",
        "internalToken": "▇▇▇▇▇▇▇▇▇",
        "sharedToCountry": false,
        "nosocomialOutbreak": false,
        "quarantine": "HOME",
        "quarantineFrom": 1641337200000,
        "quarantineTo": 1642201200000,
        "quarantineOrderedVerbally": true,
        "quarantineOrderedOfficialDocument": false,
        "quarantineOrderedVerballyDate": 1641510000000,
        "quarantineHomePossible": "YES",
        "quarantineHomeSupplyEnsured": "YES",
        "quarantineExtended": false,
        "quarantineReduced": true,
        "quarantineOfficialOrderSent": false,
        "postpartum": "NO",
        "followUpStatus": "FOLLOW_UP",
        "followUpComment": "▇▇▇▇▇▇▇▇▇",
        "followUpUntil": 1642201200000,
        "overwriteFollowUpUntil": true,
        "ownershipHandedOver": false,
        "prohibitionToWork": "NO",
        "reInfection": "NO",
        "bloodOrganOrTissueDonated": "NO",
        "notACaseReasonNegativeTest": false,
        "notACaseReasonPhysicianInformation": false,
        "notACaseReasonDifferentPathogen": false,
        "notACaseReasonOther": false,
        "dontShareWithReportingTool": false,
        "caseReferenceDefinition": "FULFILLED",
        "previousQuarantineTo": 1642201200000
    }
]
```

Error:
```
<html>
<head>
<base href="/error_path/">
<title>400 Bad Request</title>
</head>
<body>
<h1>Bad Request</h1>
<p>The server detected a syntax error in your request.<br>
Check your request and all parameters.</p>

<p>Your request ID was: YefVwGtyS4pkDmDM66airgAAAqk</p>
```

after some further tests the above assumption remains that the property "endDate" of Exposures is responsible for the error. Once this is removed, the JSON is accepted by the REST API.
All input is done by the frontend of SORMAS, so you could actually exclude a wrong UNIX date...

**Comment by cazacmarin** [comment] 2022-01-27 09:05
@geo-hf question. Do you have access to server.log file which usually is placed under /opt/domains/sormas/logs folder?
If yes, can you please simulate this problem(described in  the ticket) again on your system and then attach to ticket approximately simulation time + server.log file? 
It will be really helpful information. Thanks!

**Comment by geo-hf** [comment] 2022-01-27 09:48
@cazacmarin we do not have access to the log files, because the server is not hosted by us, but by HZI/Netzlink. Maybe you can access it: our instance is listed under "Kreis Herford". I executed the request again today at 10:43:01 (again with errors).

**Comment by cazacmarin** [comment] 2022-02-02 12:12
As no answer from Ricky and we need to move on, for QA guys:
Was introduced a new rest endpoint method. http://localhost:6080/sormas-rest/cases/push-detailed
(of  course  basic auth method need to be specified  with username and password)
The stack-trace will be returned as well as an answer.
![image](https://user-images.githubusercontent.com/6985315/152151219-b63e3a45-e8d4-4be7-9d37-e02c2a936fbf.png)

**Comment by cazacmarin** [comment] 2022-02-02 15:20
This issue now went to QA board as it was approved and merged. After the moment when QA will test it, it should go to Waiting column. When customer will use the 2nd endpoint `rest api` which will give to us more information, we will work on this ticket again, and will fix the route cause of the problem. 
(PS. @vidi42  recommended to go through this flow).

**Comment by vidi42** [comment] 2022-02-03 08:36
> This issue now went to QA board as it was approved and merged. After the moment when QA will test it, it should go to Waiting column. When customer will use the 2nd endpoint `rest api` which will give to us more information, we will work on this ticket again, and will fix the route cause of the problem. (PS. @vidi42 recommended to go through this flow).

@geo-hf  After some internal discussions we decided to close this ticket even if the original issue was not solved.
We couldn't reproduce the issue mentioned in the ticket and also don't have enough information to go by so we implemented an alternative endpoint which could give us the information needed if used. (`/cases/push-detailed`)

My suggestion is that you test this out and open a new ticket with the information provided from the new endpoint, which could give us hints on how to solve the issue.

Also, please mention this ticket in the new one

**Closed** 2022-02-03 08:57 UTC
Labels: bug, cases, integration

**Comment by abrudanancuta** [comment] 2022-02-04 08:09
Validated the new endpoint which provides more details in the cases mentioned about VALIDATION_EXCEPTION,
TRANSACTION_ROLLED_BACK_EXCEPTION
