### ISSUE TITLE
Cases can not be saved

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10446] opened 2022-09-26 09:35 UTC
### Bug Description

If you press the save button in cases, the spinner appears. Is is still present even after waiting for more than 10 minutes.    

### Steps to Reproduce

1. open a case
2. click on the "Save" 

### Screenshots

![image](https://user-images.githubusercontent.com/101708230/192242401-27380bc8-9111-4d4a-91ba-cfc99a614f51.png)

### System Details

* Device: Laptop
* SORMAS version: 1.76.0 - f0e7ab4
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/ and https://test-auto.sormas.netzlink.com/
* User Role:Admin

### Additional Information

![image](https://user-images.githubusercontent.com/101708230/192242979-1acc8d63-42e1-4093-9628-f2c8cda7a48a.png)
[log.txt.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9644944/log.txt.txt)

**Comment by MateStrysewske** [comment] 2022-09-26 10:36
@KernB Likely the issue that was fixed in #8502. Please check back whether this issue still exists tomorrow.

**Comment by KernB** [comment] 2022-09-27 06:57
The issue still exists.  
test-auto and test-de 
1.76.0  e586c0e 
Chrom - Incognito and normal mode

After several minutes the spinner disappear and the following message appears: 
![image](https://user-images.githubusercontent.com/101708230/192454751-0d8e10cc-b4d9-48d1-a849-d090e1d9442f.png)

**Comment by roxanamlendea** [comment] 2022-09-28 14:26
> The issue still exists. test-auto and test-de 1.76.0 [e586c0e](https://github.com/hzi-braunschweig/SORMAS-Project/commit/e586c0e11f8525c96f1dbd1a45ec23817463566f) Chrom - Incognito and normal mode
> 
> After several minutes the spinner disappear and the following message appears: ![image](https://user-images.githubusercontent.com/101708230/192454751-0d8e10cc-b4d9-48d1-a849-d090e1d9442f.png)

@KernB Can you please check again? On my local machine is not reproducible anymore. I also cannot reproduce it on test-de.

**Comment by StefanKock** [comment] 2022-09-30 06:44
> > The issue still exists. test-auto and test-de 1.76.0 [e586c0e](https://github.com/hzi-braunschweig/SORMAS-Project/commit/e586c0e11f8525c96f1dbd1a45ec23817463566f) Chrom - Incognito and normal mode
> > After several minutes the spinner disappear and the following message appears: ![image](https://user-images.githubusercontent.com/101708230/192454751-0d8e10cc-b4d9-48d1-a849-d090e1d9442f.png)
> 
> @KernB Can you please check again? On my local machine is not reproducible anymore. I also cannot reproduce it on test-de.

It was merged after that commit but on the same day. Still likely a duplicate to #8502

**Closed** 2022-09-30 07:03 UTC
Labels: duplicate
