### ISSUE TITLE
Add option to link case with source case in mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4180] opened 2021-01-29 21:40 UTC
### Bug Description
- The development of #2946 permit cases to be link to their source cases through epidemiological data tab. On mobile app, contact with source case can be set to yes but there is no means to link the case to the source case.
- When creating contact through the contact directory, the icon "choose case" is missing.
### Steps to Reproduce
1. Create a covid case on mobile app
2. set "Contacts with Source Case" == yes
3. Icon for "new contact" is missing
### Expected Behavior
- When "Contacts with Source Case" == yes, provide an option to create a contact with source case
- Add an icon "choose case" to search all cases in the db of the tablet with the same disease and difference in report date == 2*incubation period of disease. The reason for adding this time constrain is to  improve performance. We can drop the time constrain if there is no need and just compare diseases
### System Details
* Device: Tecno + Samsung
* SORMAS version: 1.53
* Android version/Browser: version 7 and 9
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2021-02-01 12:47
Duplicate of #3540

**Closed by MateStrysewske** 2021-02-01 12:47 UTC
Labels: bug
