### ISSUE TITLE
'A problem has occurred' message is thrown when the user changes the jurisdiction of a Case that was created from a Travel Entry

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9321] opened 2022-05-24 13:15 UTC
### Bug Description
When a user wants to change the jurisdiction (Responsible Region/District/Community) of a Case that was created by opening a Case for a Travel Entry, he cannot successfully save the page, because 'A problem has occurred. You have to specify a valid point of entry' message is thrown. The 'Point of Entry' is read-only, so basically the user is not able to change the jurisdiction.

### Steps to Reproduce

1. Open or create a Travel Entry;
2. Create a Case for the Travel Entry;
3. Change the Responsible Region and District and Save;

### Expected Behavior
Needs to be discussed;

### Actual Behavior
'A problem has occurred. You have to specify a valid point of entry' message is thrown. The 'Point of Entry' is read-only, so basically the user is not able to change the jurisdiction.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/170041767-013e8d0f-c7db-47de-ba51-60031d8a74f9.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.73.0-SNAPSHOT (also reproducible on 1.71)
* Android version/Browser: Chrome
* Server URL: local environment and test1402.sormas.netzlink.com
* User Role: Admin, National User

**Comment by MateStrysewske** [comment] 2022-05-25 07:34
Duplicate of #9023

**Closed by MateStrysewske** 2022-05-25 07:34 UTC
Labels: bug, cases, travel entries
