### ISSUE TITLE
Add countries drop-down to person home address

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3102] opened 2020-10-07 19:16 UTC
### Situation Description
Users would like to select countries under home address when foreigners become cases.
### Feature Description
The home address section in the person information should give the option to select a country. This will be applicable if foreigners become a case but have a home address outside of the country. They will still have to be taken care of. Depending on where the SORMAS instance resides, this field should be pre-selected so it only has to be changed where applicable.
### Additional Information
<img width="920" alt="Screen Shot 2020-10-07 at 9 09 55 PM" src="https://user-images.githubusercontent.com/70317594/95377162-798f5600-08e2-11eb-8f5a-937af0a6a656.png">

**Comment by bernardsilenou** [comment] 2020-10-07 22:17
@kwa20 Are there many foreigners who are cases? 
I think this is over-killing the address entity since more than 98% of cases will have a home address in the country of the sormas server instance.

**Comment by ChristopherRiedel** [comment] 2020-10-08 06:52
duplicate of #2994

**Closed by ChristopherRiedel** 2020-10-08 06:52 UTC
Labels: duplicate
