### ISSUE TITLE
Add a "sampling reason" field in the sample part [3]

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4555] opened 2021-02-26 09:11 UTC
Implementation specifications: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4555#issuecomment-789585894

### Situation Description
There are many reasons for people to take tests (in anticipation of travel or hospitalization for an operation, professional reasons, personal choice, etc.). Not all people who take a test are symptomatic. It would be good if we could define in SORMAS the reasons that led people to carry out a test

### Feature Description
For the cases, add a field in "sample" allowing to define the reasons which led the cases to carry out the test.
The modalities would be as follows:

- Contact of a confirmed case
- Evocative clinical signs
- Before hospitalization
- Trip
- Professional reason
- Voluntary process
- Moving/Returning into Retirement Home
- Not specified

refined description here : https://github.com/hzi-braunschweig/SORMAS-Project/issues/4555#issuecomment-789585894

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by Marko-ilmkreis** [comment] 2021-02-26 09:50
I would ask to add
* Moving/Returning into Retirement Home

**Comment by carolinverset** [comment] 2021-02-26 09:53
Yes, good idea. I'm agree with you :-)

**Comment by bernardsilenou** [comment] 2021-02-26 13:36
@carolinverset @Marko-ilmkreis
1. Which entity do you think users would  create for these people: case, contact; ep ?
2. If case, then how do we classify them while the test result is not out: not yet classified ?

**Comment by carolinverset** [comment] 2021-02-26 13:42
@bernardsilenou @Marko-ilmkreis @emond-fuseau
1. yes French users want this field for cases only.
2. this field could appear only for cases for which a test result is available?
What do you think of ?

**Comment by bernardsilenou** [comment] 2021-02-26 13:50
@Candice-Louw 
- Since the test result is available at the time of creating the case, then we can easily determine the case classification from the test result: Negative == not a case, positive == confirmed case.
-  If result is not available, then we can still create a case with classification  == not yer classified

**Comment by bernardsilenou** [comment] 2021-02-27 12:39
Can we call it "Reason for sample collection" or "Reason for testing"? not to get confused with the epidemiological meaning of sampling.

**Comment by ftavin** [comment] 2021-02-27 17:33
@carolinverset @bernardsilenou 
I understand this field should only be visible when the sample is linked to a case, am I right ?

should this new data also appear in the samples directory as a new column ? as a filter ? in the exports ?
on the case screen, should this information be displayed on the samples bloc ?

**Comment by bernardsilenou** [comment] 2021-02-28 02:05
@ftavin  Nice questions, My suggestions pls,
> @carolinverset @bernardsilenou
> I understand this field should only be visible when the sample is linked to a case, am I right ?
> 
Since samples are shared among entities (when we convert ep or contact to case), it would be better to add the variable to the sample entity for all: cases, contact, ep. 
More then one of the options can be the reason, thus multiple check box  may be good when Vaadin is history.
> should this new data also appear in the samples directory as a new column ? as a filter ? in the exports ?
 
Absolutely Yes, thanks
> on the case screen, should this information be displayed on the samples bloc ?

Not needed I suppose since the box is already crowded

**Comment by Marko-ilmkreis** [comment] 2021-03-01 05:29
@bernardsilenou for us its more needed for cases then for contact/ep. We have a lot of cases classified as "no case", because e.g. we have to test the elderly people comingback from a hospital into the retirement home or the other way.  So it would be helpful if this field not only shows for confirmed cases. The reason why "no cases" were tested could be also very interesting.

**Comment by carolinverset** [comment] 2021-03-01 09:42
@ftavin @bernardsilenou @emond-fuseau
I agree with Bernardss proposals except for the last one :-)
I understand that the block is already loaded but maybe we will find a way to make it appear in this space?This would make it easier to read for users who would not have to navigate between the case and sample directories.

Another question, is it possible to integrate this data in the detailed export of cases?

**Comment by MateStrysewske** [comment] 2021-03-02 09:44
I agree that this should be added to samples in general, not only for cases.

**Comment by Candice-Louw** [comment] 2021-03-02 09:52
Additional reasons (not on the current list) that are recorded in CH include -
'Sample/test collected/performed on the grounds of:'
* Outbreak (in area)
* Cohort screening
* Work screening (similar to 'Professional reason'?)
* App notification
* During Quarantine
* Convenience (similar to 'Voluntary Process'?)

**Comment by carolinverset** [comment] 2021-03-02 12:44
@Candice-Louw  @ftavin 
I think it is quite possible a list of modalities combining the needs of Swiss and French users. We can easily rename "Professional reason" and "Voluntary Process".
have a nice day :-)

**Comment by bernardsilenou** [comment] 2021-03-02 17:11
@All
I have combined the comments in this summary. Please check if all is right or if your agree with the changes.
Minor naming can be corrected in translation but we should agree on the same semantics.

- Add variable `Reason for sample collection` to sample
enums: 
old name = newname + comments
Contact of a confirmed case = `Contact with a confirmed case`
Evocative clinical signs = `Presenting clinical signs and  symptoms`
`Before hospitalization`
`Trip` = Planning to travel ? or returning traveler ? What does this mean please?
`Professional reason` (I think work is subset of professional reason, so can we keep this option only?)
Voluntary process = Convenience (similar to 'Voluntary Process'?). Can we call this `Personal reason`?
`Moving/Returning into Retirement Home`
App notification # If this is about the warning apps, then the reason behind this option is same as Contact of a case , so can we keep only contact of a case?
During Quarantine== `Quarantine regulations` # this do not match the other reasons because quarantine is a consequence of the reason for testing. Being is quarantine is as a result of either contact, trip, ... 
Outbreak (in area)  == `Exposed to an outbreak area` or `visited or live in an outbreak area`
Cohort screening == `Screening`; to encompass screenings that are not cohort
Other + free txt
Not specified == `Unknown`

- Activate for COVID only

**Comment by carolinverset** [comment] 2021-03-03 07:33
> * area)  == `Exposed to an outbreak area` or `visited or live in an outbreak area`
>   Cohort screening == `Screening`; to encompass screenings that are not cohort
>   Other + free txt
>   Not specified == `Unknown`

Contact with a confirmed case : ok to keep this syntax

Presenting clinical signs and symptoms : ok to keep this syntax

Trip : Keep both options ? Planning to travel & returning traveler

Professionnel reason : ok to keep this syntax

Personal reason : ok to keep this syntax

Quarantine regulations : I also think that this constitutes a motive for carrying out a test. In France, people who live in the same household as a positive case and who are therefore in quarantine must take a test before the end of isolation. I therefore agree with Candice's idea which consists in making it an independent reason for sampling

Exposed to an outbreak area : ok to keep this syntax

Screening : ok to keep this syntax

Unknown : ok to keep this syntax

@bernardsilenou @ftavin @emond-fuseau @Candice-Louw

**Comment by carolinverset** [comment] 2021-03-03 07:33
@ftavin @bernardsilenou @emond-fuseau

After validation by all of these modalities, I will update the initial description of the ticket to facilitate the work of the developer

**Comment by MateStrysewske** [comment] 2021-03-03 08:59
There is already a field called `CovidTestReason` for cases that is Switzerland only. I don't really know why that field was added to the case and not the sample, but it's basically what we should use, rename and extend here. My hope would be that we can get rid of the field in the case, but I'll have to check that.

**Comment by Candice-Louw** [comment] 2021-03-03 09:01
@carolinverset - you would find an existing enum "CovidTestReason.X" for cases already exists.  It is only visible on Swiss servers, though.  The question now is whether this enum can be hidden on CH servers or if a merging should be done? @MateStrysewske - please could you assist?

**Comment by carolinverset** [comment] 2021-03-03 09:03
@Candice-Louw @MateStrysewske @bernardsilenou @emond-fuseau 

Perhaps it will suffice to activate it in France also in the case directory ?  this would meet the needs of the users. Could you tell us the modalities of this variable, if it is ever a predefined drop-down list ?

**Comment by MateStrysewske** [comment] 2021-03-03 09:17
@Candice-Louw The CovidTestReason should be removed from cases because it doesn't make any sense there. We heavily prefer to get rid of it in favour of the SamplingReason that will be introduced by this issue, and migrate the CovidTestReason value to the latest sample of the respective case.

**Comment by MateStrysewske** [comment] 2021-03-03 09:50
Suggestion for implementation:

* Rename the `CovidTestReason` enum to `SamplingReason`
* Add new values to the enum:
    * `CONTACT_CONFIRMED_CASE` ("Contact to confirmed case")
    * `PLANNING_TO_TRAVEL` ("Planning to travel")
    * `RETURNING_TRAVELER` ("Returning traveler")
    * `PERSONAL_REASON` ("Personal reason/Convenience")
    * `MOVING_RETURNING_RETIREMENT_HOME` ("Moving/returning into retirement home")
    * `UNKNOWN` ("Unknown")
* Rename existing enum values and their captions (needs to be migrated in the database as well):
    * `REQUIREMENT_OF_EMPLOYER` => `PROFESSIONAL_REASON` ("Professional reasons")
    * `DURING_QUARANTINE` => `QUARANTINE_REGULATIONS` ("Quarantine regulations")
    * `COHORT_SCREENING` => `SCREENING` ("Screening")
    * `OUTBREAK_INVESTIGATION_SCREENING` => `OUTBREAK` ("Exposed to an outbreak area")
* Add a new field called `samplingReason` with this enum type to samples (enabled for all countries)
* Add a new field called `samplingReasonDetails` (type text; `@SensitiveData` annotation in Dto) to samples that is enabled when `OTHER_REASON` is selected (enabled for all countries)
* Write an SQL migration script that fills the `samplingReason` field of the latest sample of a case with the content of the case's `covidTestReason` (if it's filled in) and the `samplingReasonDetails` (also of the latest sample) with the `covidTestReasonDetails`
* Remove the `covidTestReason` and `covidTestReasonDetails` fields from cases (both in the web and mobile app; in the mobile app it's enough to add the `@Deprecated` annotation to the field and remove all other traces of it, e.g. in the DtoHelper class, since SQLite doesn't support statements to drop individual columns)
* Add the new fields to the user interface (sample creation and edit forms and fragments)
* Extend `SampleListEntry` to contain the sampling reason (or the details if `OTHER_REASON` is selected)
* Add the new fields to relevant exports

@carolinverset @Candice-Louw Any objections?

**Comment by MateStrysewske** [comment] 2021-03-03 09:52
@Candice-Louw Could `AFTER_CONTACT_TRACING` be merged with `CONTACT_CONFIRMED_CASE` or does it serve an individual purpose?

**Comment by carolinverset** [comment] 2021-03-03 10:15
> Suggestion for implementation:
> 
> * Rename the `CovidTestReason` enum to `SamplingReason`
> * Add new values to the enum:
>   
>   * `CONTACT_CONFIRMED_CASE` ("Contact to confirmed case")
>   * `PLANNING_TO_TRAVEL` ("Planning to travel")
>   * `RETURNING_TRAVELER` ("Returning traveler")
>   * `PERSONAL_REASON` ("Personal reason/Convenience")
>   * `MOVING_RETURNING_RETIREMENT_HOME` ("Moving/returning into retirement home")
>   * `UNKNOWN` ("Unknown")
> * Rename existing enum values and their captions (needs to be migrated in the database as well):
>   
>   * `REQUIREMENT_OF_EMPLOYER` => `PROFESSIONAL_REASON` ("Professional reasons")
>   * `DURING_QUARANTINE` => `QUARANTINE_REGULATIONS` ("Quarantine regulations")
>   * `COHORT_SCREENING` => `SCREENING` ("Screening")
>   * `OUTBREAK_INVESTIGATION_SCREENING` => `OUTBREAK` ("Exposed to an outbreak area")
> * Add a new field called `samplingReason` with this enum type to samples (caption: "Reason for sampling/testing"; enabled for all countries)
> * Add a new field called `samplingReasonDetails` (type text; `@SensitiveData` annotation in Dto) to samples that is enabled when `OTHER_REASON` is selected (caption: "Sampling reason details"; enabled for all countries)
> * Write an SQL migration script that fills the `samplingReason` field of the latest sample of a case with the content of the case's `covidTestReason` (if it's filled in) and the `samplingReasonDetails` (also of the latest sample) with the `covidTestReasonDetails`
> * Remove the `covidTestReason` and `covidTestReasonDetails` fields from cases (both in the web and mobile app; in the mobile app it's enough to add the `@Deprecated` annotation to the field and remove all other traces of it, e.g. in the DtoHelper class, since SQLite doesn't support statements to drop individual columns)
> * Add the new fields to the user interface (sample creation and edit forms and fragments)
> * Extend `SampleListEntry` to contain the sampling reason (or the details if `OTHER_REASON` is selected)
> * Add the new fields to relevant exports
> 
> Additionally:
> 
> * The enum value `SWISS_COVID_APP_NOTIFICATION` should only be visible for Switzerland
> 
> @carolinverset @Candice-Louw Any objections?

OK for me. Thank you

**Comment by Candice-Louw** [comment] 2021-03-03 10:32
@carolinverset - these values are specified by the CH BAG and have some very specific requests, yes.

Requests from CH and supporting documents: 
MED Stand 2020-12-22:
[Metadata_MED_16122020_fin_de_V2.xlsx](https://github.com/hzi-braunschweig/SORMAS-Switzerland/files/5735438/Metadata_MED_16122020_fin_de_V2.xlsx) (de-CH)
[Metadata_MED_16122020_fin_fr_V2.xlsx](https://github.com/hzi-braunschweig/SORMAS-Switzerland/files/5735521/Metadata_MED_16122020_fin_fr_V2.xlsx) (fr-CH)

1. Cases:
![image](https://user-images.githubusercontent.com/65529128/109789860-0d0a5000-7c11-11eb-9a1d-89cf014a3b5d.png)

2. Contacts:
![image](https://user-images.githubusercontent.com/65529128/109789970-29a68800-7c11-11eb-97f2-ee53bf4c0412.png)

@bernardsilenou @carolinverset  - I would recommend keeping the "App notification" seperate as this implies a contact to an **unknown** case.  Keeping only "Contact to a Case" my imply contact to a **known** Case.  If no feedback from you, we go with @MateStrysewske suggestion of `SWISS_COVID_APP_NOTIFICATION` being visible only on CH servers.

What is not clear from this issue is whether this is only for Cases?  Or Cases and Contacts? The entries for Contacts should certainly be different from those of Cases and these lists should not simply be reused (similar to follow-up time not being the same).

**Comment by MateStrysewske** [comment] 2021-03-03 10:36
@Candice-Louw This field will be part of samples, so it's gonna be visible for cases, contacts and event participants. Which entries do you think don't make sense for cases or contacts?

I think the values that I outlined above allow us to map every value that's necessary for BAG, and the only problem I see with the contacts is that they have two different values for quarantine management, but we could solve that by introducing another enum value called `QUARANTINE_END` that is also only available for Switzerland.

**Comment by Candice-Louw** [comment] 2021-03-03 10:49
@MateStrysewske - thank you. 👍 

AFTER_CONTACT_TRACING is an old variable. (Full change history of MED CH: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/168)

Old MED (10.12.2021):
![image](https://user-images.githubusercontent.com/65529128/109793173-9c653280-7c14-11eb-915a-b9c5ffefa94b.png)

New MED (22.12.2021):
![image](https://user-images.githubusercontent.com/65529128/109793249-b3a42000-7c14-11eb-866a-4781eae58314.png)

Please map/merge/migrate as proposed to CONTACT_CONFIRMED_CASE.

**Comment by carolinverset** [comment] 2021-03-03 11:17
> @carolinverset @bernardsilenou
> I understand this field should only be visible when the sample is linked to a case, am I right ?
> 
> should this new data also appear in the samples directory as a new column ? as a filter ? in the exports ?
> on the case screen, should this information be displayed on the samples bloc ?

i'm agree with @bernardsilenou : Not needed since the box (sample box) is already crowded

**Comment by bernardsilenou** [comment] 2021-03-03 12:11
@MateStrysewske @Candice-Louw @carolinverset  @kwa20 
I think programming  what the users recommend directly would result in categories of the same variable that are dependent on each other and this would not be good.  Our categories should only focus on the captions and be independent.
- For example instead of using quarantine start, quarantine end, during quarantine, after quarantine etc, we should use names that tell us something about the reason for sampling,  not the status of the reason, for this case: quarantine management. If users need to know about if it was a quarantine end, then they can look at the quarantine variable dates.
- If testing is only done at quarantine end, then we can keep only quarantine end. Quarantine end is some how a sub category of quarantine management, thus not good to keep both.
- The other point is related to `"App notification" separate as this implies a contact to an unknown case`. in order not to have contact * case classification leading to 5 other categories. We can just use `contact to a case` in the place of `contact to a confirmed case`  and `App notification` because sample collection can happen when the case is still suspected. Having both contact to confirmed case and contact to unknown case is not a good way to go. In addition, why do we documenting contact to unknown case and do not document contact to other case classification types.
- @Candice-Louw we have the variable called `contact identification source` to tell us how the contact was identified. Maybe we communicate to the Swiss users to use this variable for `SWISS_COVID_APP_NOTIFICATION` because this sounds like the information source rather than the reason for sampling. 

@Candice-Louw  If the users disagree to go with this suggestion, then it  fine that we add a configuration as you suggested.

**Comment by bernardsilenou** [comment] 2021-03-03 12:13
@markusmann-vg Please can you comment if we can assign this ticket to the French dev team for 1.59?

**Comment by leventegal-she** [comment] 2021-03-03 12:15
@bernardsilenou I've already started to work on this ticket

**Comment by MateStrysewske** [comment] 2021-03-03 12:18
@bernardsilenou I agree with your third point and have changed the enum name and caption accordingly (to remove the "confirmed" part). I also agree with your fourth point and would also like @Candice-Louw to confirm that this could be used because it makes a lot more sense than to have it as a sampling/testing reason.

Concerning the quarantine topic, I guess for the Swiss users it's relevant to differentiate between doing routine test during quarantine and doing a final test at the end of the quarantine to confirm that the quarantine can indeed be ended? At least I see a valid reasoning behind that, but I'm of course always open to make the system as simple as possible :D

@leventegal-she Please consider the update (CONTACT_CONFIRMED_CASE => CONTACT_TO_CASE), and I'll let you know whether something about these specifications changes (especially in terms of the SWISS_COVID_APP_NOTIFICATION value)

**Comment by MateStrysewske** [comment] 2021-03-03 12:19
@bernardsilenou @carolinverset Just to clarify, Switzerland needs this feature for the upcoming release which is why we've already picked up development on it.

**Comment by bernardsilenou** [comment] 2021-03-03 15:31
@MateStrysewske Thanks for the explanation. :+1:  to your last 2 comments.
@Candice-Louw would verify with the Swiss users and decide if we must have a configuration for  SWISS_COVID_APP_NOTIFICATION

**Comment by bernardsilenou** [comment] 2021-03-03 15:34
@carolinverset  @ftavin 
Our team is working on this issue.
> @bernardsilenou I've already started to work on this ticket

**Comment by AndyBakcsy-she** [comment] 2021-03-06 19:11
validated ticket on the latest version of 1.58.0-snapshot

**Comment by Candice-Louw** [comment] 2021-03-11 16:09
@MateStrysewske @AndyBakcsy-she - feedback from CH users - they do NOT create samples.

In CH systems, this field is currently on the Case form for example, and will now be moved to the sample of the Case.  But how will the system respond if this value is moved to a sample that does NOT exist?  Will the value disappear?  Cause a conflict?  Some other unforeseen behaviour?

**Comment by bernardsilenou** [comment] 2021-03-11 19:41
@Candice-Louw I think for each migration, the system would create a sample, date of sample can be date of report for case and sample type can be blood or better still other + unknown

**Comment by MateStrysewske** [comment] 2021-03-12 08:35
@Candice-Louw @bernardsilenou There's no such migration right now - we can implement it however if it's necessary.

Values for the created samples:
* Sample purpose: Internal/in-house testing
* Date: Report date of the case
* Type of sample: Other
* Type of sample details: "Unknown"
* Comment: "[System] Automatically generated sample due to covid test reason migration"

**Comment by bernardsilenou** [comment] 2021-03-12 11:12
@MateStrysewske 
- You mean the sampling reason that was initially an attribute of the case would remain attached to the case?
- If yes, then can we hide it from the front end on the case form? because it is not good to collect the same data in 2 places if they are not linked.

**Closed** 2021-03-15 11:14 UTC
Labels: android-app, backend, cases, feature, fr, important, laboratory, vaadin-app, verified by qa
