### ISSUE TITLE
Error is thrown when logging into the Android App

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9317] opened 2022-05-24 10:44 UTC
### Bug Description

After doing a build and running the Android Studio Emulator, when logging in with a user (Surveillance Officer, Case Officer) an error is thrown and none of the directories are displayed in the mobile app.

### Steps to Reproduce

1. Log into the mobile app;
2. Observe the sidebar where the directories should be displayed, and the logs from the Android Studio Emulator.

### Actual Behavior

Only the 'Settings' directory is displayed; an error appears in the logs.

### Expected Behavior

The directories that the user has rights for are displayed; no error in the logs.

### System Details

* Device: Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(3721438)
* Android version/Browser: Android 11
* Server URL: local machine
* User Role: Surveillance Officer, Case Officer

### Additional Information

[logsandroidstudio.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8761904/logsandroidstudio.txt)

**Comment by MateStrysewske** [comment] 2022-05-24 12:16
@adinaflorea9 I can't reproduce this error on my local machine with the current development state. Is it possible that you for some reason have a user in your database that does not have ANY user role attached to them?

**Comment by adinaflorea9** [comment] 2022-05-24 12:46
@MateStrysewske I can see a previously created 'Rest User' that now does not have any user role attached to it, as this role was removed from the user roles list. I have deleted the user from the DB and restarted my server - now the error is not reproducible anymore and the logged in user can see the directories in the app.

**Comment by MateStrysewske** [comment] 2022-05-25 07:29
@adinaflorea9 Ah, great, thanks for the clarification! This is related to #4461 then and should be fixed there. :)

**Closed by MateStrysewske** 2022-05-25 07:29 UTC
Labels: bug, android-app, feedback, major
