### ISSUE TITLE
[Cases] Error appears when navigating between the tabs of a shared case

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10957] opened 2022-11-18 08:51 UTC
### Bug Description

If a case is shared with handover ownership, on the sending system, an error appears when navigating between the tabs of the case.

### Steps to Reproduce

1. on test-de2 create a case (with an associated person);
2. on test-de3 create a case with the exact same details as the case from step 1 (and the exact person details as well);
3. from test-de2 share with ownership handover the case into tehst-de3;
4. on test-de3 accept the case;
5. on test-de2, go and open the case that was shared, and navigate between it's tabs.
###Actual Behavior

An error appears:
![image](https://user-images.githubusercontent.com/96909231/202660633-4f2c23a3-6093-4683-bc3b-b9eed37be126.png)

### Expected Behavior

No error should appear.

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0-SNAPSHOT(6aa9136)
* Android version/Browser: Chrome
* Server URL: https://test-de2.sormas.netzlink.com/ and https://test-de3.sormas.netzlink.com/
* User Role: Admin+NatUser

### Additional Information

Ticket 'Finding' was created so that this could be investigated as it is reproducible on the current SORMAS version. 
It was initially believed that it may be due to #5606  but the error is reproducible when the persons are NOT merged so that ticket is not the cause.

**Comment by StefanKock** [comment] 2022-11-22 09:11
Retry this after commit https://github.com/hzi-braunschweig/SORMAS-Project/commit/964827ff3f01d0c36a6413dc3194c274e200be89 is deployed on TEST stage.

**Comment by leventegal-she** [comment] 2022-11-22 09:26
Can't reproduce on my local environment

**Comment by leventegal-she** [comment] 2022-11-23 13:21
@adinaflorea9 The logs doesn't contain any error

Can you please re-test it and provide the logs with the exception stack trace?

**Comment by adinaflorea9** [comment] 2022-11-23 13:42
Unfortunately, as mentioned in the comment with the other logs, Graphana does not show the logs as completely as we see them on our local machines. I have re-tested this but the error is never caught in the logs or displayed there and I have no other way of getting logs from the testing instances.

Logs from today:
[logs 23.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10076009/logs.23.txt)

**Comment by StefanKock** [comment] 2022-11-24 08:57
Reproduced with @adinaflorea9. The StackTrace points to #8463 on test-de2 following the given step above. @sergiupacurariu could you please look into this?

```
java.lang.NullPointerException
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.lambda$disable$1(LayoutWithSidePanel.java:78)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.disable(LayoutWithSidePanel.java:74)
        at de.symeda.sormas.ui.caze.CaseDataView.initView(CaseDataView.java:220)
        at de.symeda.sormas.ui.caze.AbstractCaseView.enter(AbstractCaseView.java:245)
```

<details>
<summary>Full Stack Traces</summary>

```bash
# Happens when navigating from Case Directory to Case Data
[2022-11-24T09:40:25.845+0100] [Payara 5.2021.10] [SCHWERWIEGEND] [] [com.vaadin.server.DefaultErrorHandler] [tid: _ThreadID=491 _ThreadName=http-thread-pool::http-listener-1(15)] [timeMillis: 1669279225845] [levelValue: 1000] [[

java.lang.NullPointerException
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.lambda$disable$1(LayoutWithSidePanel.java:78)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.disable(LayoutWithSidePanel.java:74)
        at de.symeda.sormas.ui.caze.CaseDataView.initView(CaseDataView.java:220)
        at de.symeda.sormas.ui.caze.AbstractCaseView.enter(AbstractCaseView.java:245)
        at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
        at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
        at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
        at com.vaadin.navigator.View.beforeLeave(View.java:79)
        at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
        at de.symeda.sormas.ui.caze.CaseController.navigateToView(CaseController.java:504)
        at de.symeda.sormas.ui.caze.CaseController.navigateToCase(CaseController.java:482)
        at de.symeda.sormas.ui.caze.AbstractCaseGrid.lambda$new$1(AbstractCaseGrid.java:102)
        at de.symeda.sormas.ui.utils.ShowDetailsListener.handleItemClick(ShowDetailsListener.java:98)
        at de.symeda.sormas.ui.utils.ShowDetailsListener.itemClick(ShowDetailsListener.java:84)
        at jdk.internal.reflect.GeneratedMethodAccessor3473.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190)
        at com.vaadin.ui.Grid.access$500(Grid.java:145)
        at com.vaadin.ui.Grid$GridServerRpcImpl.itemClick(Grid.java:668)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)
        at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor862.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at jdk.internal.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy937.doFilter(Unknown Source)
        at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
        at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
]]
```

```bash
# Happens when switching from Case Person to Case Data
[2022-11-24T09:41:44.010+0100] [Payara 5.2021.10] [INFORMATION] [] [] [tid: _ThreadID=482 _ThreadName=http-thread-pool::http-listener-1(6)] [timeMillis: 1669279304010] [levelValue: 800] [[
  E094144.009|     > Unable to invoke method popstate in com.vaadin.shared.ui.ui.UIServerRpc (de.symeda.sormas.ui.SormasErrorHandler.java:84)
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method popstate in com.vaadin.shared.ui.ui.UIServerRpc
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)
        at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor862.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at jdk.internal.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy937.doFilter(Unknown Source)
        at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
        at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
        ... 78 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method uriFragmentChanged in com.vaadin.navigator.Navigator$UriFragmentManager$$Lambda$2608/0x0000000802607840 failed.
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:726)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
        at com.vaadin.server.Page.fireEvent(Page.java:723)
        at com.vaadin.server.Page.updateLocation(Page.java:1158)
        at com.vaadin.ui.UI$1.popstate(UI.java:201)
        ... 83 common frames omitted
Caused by: java.lang.NullPointerException: null
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.lambda$disable$1(LayoutWithSidePanel.java:78)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at de.symeda.sormas.ui.utils.LayoutWithSidePanel.disable(LayoutWithSidePanel.java:74)
        at de.symeda.sormas.ui.caze.CaseDataView.initView(CaseDataView.java:220)
        at de.symeda.sormas.ui.caze.AbstractCaseView.enter(AbstractCaseView.java:245)
        at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
        at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
        at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
        at de.symeda.sormas.ui.utils.AbstractDetailView.showUnsavedChangesPopup(AbstractDetailView.java:90)
        at de.symeda.sormas.ui.utils.AbstractDetailView.beforeLeave(AbstractDetailView.java:83)
        at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
        at com.vaadin.navigator.Navigator$UriFragmentManager.lambda$setNavigator$567eee34$1(Navigator.java:209)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
        ... 88 common frames omitted
]]
```

</details>

**Comment by sergiupacurariu** [comment] 2022-11-25 14:40
fixed with https://github.com/hzi-braunschweig/SORMAS-Project/pull/11027

**Closed by sergiupacurariu** 2022-11-25 14:40 UTC
Labels: cases, vaadin-app, major, s2s, finding
