### ISSUE TITLE
Events are not linked to the merged contact 

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5700] opened 2021-06-08 08:24 UTC
### Bug Description

All events that have been linked to the discarded  contact are not linked to the merged contact. 

### Steps to Reproduce

1.  Create two contacts with a similar name, same date of birth and sex and link both to the same Source Case
2. For the first contact: Link events to the contact or don't link any event 
3. For the second contact: Link multiple events to the case / contact
4. Merge the contacts 

### Expected Behavior

Events that have been linked to the discarded contact should be linked to the merged contact 
### Screenshots

Contact 1: Remaining contact
![image](https://user-images.githubusercontent.com/83459190/121149043-99489680-c842-11eb-8920-500eae8320a3.png)

Contact 2: Discarded contact
![image](https://user-images.githubusercontent.com/83459190/121148771-5b4b7280-c842-11eb-8749-235ea2283dc4.png)

Merged Case: Linked events of contact 2 are missing 
![image](https://user-images.githubusercontent.com/83459190/121149043-99489680-c842-11eb-8920-500eae8320a3.png)

### System Details

* Device: 
* SORMAS version: 1.59 / 1.60
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de/
* User Role: Admin, National User

**Comment by MateStrysewske** [comment] 2021-06-15 11:08
Duplicate of #5529

**Closed by MateStrysewske** 2021-06-15 11:08 UTC
Labels: bug
