### ISSUE TITLE
Duplicate person detection does not return the correct duplicate persons  (web app only)

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2777] opened 2020-09-01 21:47 UTC
### Bug Description
- Non similar persons are recommended as duplicate during case creation
- Test using import and see if the the same issue exist

### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/91909466-84d0df80-ecad-11ea-9b5c-7b1ad558caf0.png)

### System Details
* Device:
* SORMAS version: 1.47
* Android version/Browser:

**Comment by MateStrysewske** [comment] 2020-09-02 06:49
Duplicate of #2764 

Please look for similar issues before creating new ones.

**Closed by MateStrysewske** 2020-09-02 06:49 UTC
Labels: bug
