### ISSUE TITLE
Hide other countries hides Bavaria, Bremen and Berlin

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5930] opened 2021-06-24 05:25 UTC
### Bug Description

If you select "hide other countries" in the map of the dashboard it also hides Bavaria, Bremen and Berlin:

![image](https://user-images.githubusercontent.com/74791118/123207066-14ee4880-d4bd-11eb-9224-13222c6456ce.png)

### Steps to Reproduce

1. Open the map
2. choose the layer "Hide other countries"
![image](https://user-images.githubusercontent.com/74791118/123207138-32231700-d4bd-11eb-84fc-a2a16342d311.png)

### System Details

* SORMAS version: 1.59.2

**Comment by MateStrysewske** [comment] 2021-06-24 07:21
I guess that's because the shape files might be missing - but @JonasCir and @DavidBaldsiefen might be able to provide more insight here.

**Comment by JonasCir** [comment] 2021-06-24 07:59
Well...

**Comment by DavidBaldsiefen** [comment] 2021-06-24 11:35
@Marko-ilmkreis can you check if the same problem appears on the statistics map? Are all federal states correctly displayed there?

**Comment by Marko-ilmkreis** [comment] 2021-06-24 11:37
@DavidBaldsiefen Its the same on statistics maps, but it is a very minor issue. I don't think that anyone uses this button to hide other countries.

![image](https://user-images.githubusercontent.com/74791118/123256473-4a148e00-d4f1-11eb-9e1f-95f6b49d1c70.png)

**Comment by DavidBaldsiefen** [comment] 2021-06-24 11:39
![image](https://user-images.githubusercontent.com/4655486/123256550-60bae500-d4f1-11eb-9336-64fd31ec2fbe.png)

I can reproduce a very similar issue, but on my instance the missing states are Berlin, Baden-Württemberg and Bremen... interestingly enough, all affected states start with a B 

Agreed that it is minor, but I would still investigate it

**Comment by DavidBaldsiefen** [comment] 2021-06-29 09:12
I started working on this, but the solution is much more complex than I hoped and to be honest I think this is quite low priority, so I will pause working on this for now.

The situation can be improved by simply "rendering" all regions instead of calculating the countries borders, however that leads to problems where a region is inside another region (e.g. Berlin inside of Brandenburg). Implementing an algorithm that determines weather one region is inside another is relatively complicated, but pre-existing libraries can also not be used because of the unique implementation of the maps.

In my opinion a complete overhaul of the map system when we have time makes more sense that fixing these bugs.

**Comment by Marko-ilmkreis** [comment] 2021-06-29 09:38
@DavidBaldsiefen Thanks for your work. Maybe we close this issue and re-open it later?

**Comment by DavidBaldsiefen** [comment] 2021-06-29 09:45
I don't think we should close this, as it is a real issue and not necessary a `wontfix`. What do you think @MateStrysewske ?

**Comment by MateStrysewske** [comment] 2021-06-29 09:53
@Marko-ilmkreis @DavidBaldsiefen Agreed - moving it out of the sprint is sufficient. We should still tackle it at some point.

**Closed** 2022-03-24 11:02 UTC
Labels: bug, vaadin-app, dashboard, minor

**Comment by richardbartha** [comment] 2022-03-25 13:11
Ticket was verified on local environment with version 1.70.0-snapshot(3309a9fef81ab5c233d3a5c94e58a6e184849a45)
