### ISSUE TITLE
[DEMIS2SORMAS] Navigation on the lab message form reloads the website in the back

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4206] opened 2021-02-01 19:27 UTC
### Bug Description
When either clicking "pathogen test" or "sample" in the "summary of the pathogen test", the webpage reloads in the background (opens dashboard) which does not seem to make sense.
### Steps to Reproduce
1. Process a lab message.
2. Click either "pathogen test" or "sample" inside of summary of the pathogen test.
3. check the reloaded background.

### Expected Behavior
Clicking the fields should merely navigate on the form but not reload the webpage in the background.
### Screenshots
<img width="485" alt="labMessageNavigationBug" src="https://user-images.githubusercontent.com/70317594/106507825-de8f3d00-64cb-11eb-8147-e18ce117ac9f.PNG">
<img width="960" alt="labMessageNavigationBug2" src="https://user-images.githubusercontent.com/70317594/106507831-e0590080-64cb-11eb-8646-be7fe47466d2.PNG">

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment] 2021-03-01 19:25
@FredrikSchaeferVitagroup @JaquM

**Comment by FredrikSchaeferVitagroup** [comment] 2021-03-02 06:30
This issue was already solved in a time where there was no tracking of DEMIS issues in github. 
That's why it is a duplicate of https://jira.vitagroup.ag/browse/SOR-645 and should be resolved with https://git.vitasystems.dev/sormas/sormas-demis-adapter/-/merge_requests/8.

The bug should not exist anymore in the adapter version 1.2.0, which comes along with SORMAS 1.57.0.

**Closed by FredrikSchaeferVitagroup** 2021-03-02 06:30 UTC
Labels: duplicate
