### ISSUE TITLE
Editing the own User (Administrator) leads to error message or loss of connection

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10104] opened 2022-08-11 10:31 UTC
### Bug Description

When editing the own user (Adminsitrator) the sever connection gets lost or a error message appears. 

### Steps to Reproduce

1. Log in with the userrole Administrator
2. Make changes on phone number, jurisdiction or E-Mail
3. Click Save

### Expected Behavior

The own user (Administrator) can be edited and saved correctly wihtout sever connection lost or error messages. 

### System Details

* Device:
* SORMAS version: 1.74, 1.73.3
* Android version/Browser:
* Server URL:
* User Role: Administrator

**Comment by JonasCir** [comment] 2022-08-28 14:02
This might be a duplicate of https://github.com/hzi-braunschweig/SORMAS-Project/issues/9711

**Comment by adinaflorea9** [comment] 2022-09-02 10:35
Tried to reproduce the behavior reported on my local machine (where SORMAS version is 1.76.0-SNAPSHOT(5780aa8)) and on https://release-international.sormas.netzlink.com/sormas-ui/ (where SORMAS version is 1.75.0) - the behavior is no longer reproducible and was likely fixed by #9999. Therefore, I will close the ticket as a duplicate.

@KristinaBorch if the behavior is reproducible for you on 1.75.0 or 1.76.0 please reopen the issue.

**Closed by adinaflorea9** 2022-09-02 10:35 UTC
Labels: bug, backend, users, major
