### ISSUE TITLE
Unsaved changes never disappears 

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#9212] opened 2022-05-17 07:05 UTC
### Bug Description
Unsaved changes triggers and never disappears when creation of a new case is triggered by creation of a new sample with different disease for and event participant

### Steps to Reproduce

1. Create and event
2. Add an event participant
3. Add a new sample for event participant with a pathogen test with a different disease to trigger creation of a new case upon saving this sample
4. Fill out and create new case
5. Unsaved changed appears after the confirmation of a new case and stay in infinite loop and keep appearing no matter if you save or discard changes

### Expected Behavior
Unsaved changes should only be triggered when there is some actual change

### Screenshots
https://drive.google.com/file/d/1l3csjo5hi0UKcXWpmfgF6R7z9JT2m1Pe/view?usp=sharing

### System Details

* Device: Windows 10
* SORMAS version: 1.72.0
* Android version/Browser: Chrome
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: NatUser

### Additional Information
Event, person, case are created via API

**Comment by MateStrysewske** [comment] 2022-05-18 10:04
@richardbartha I can't reproduce this locally. Could you maybe create a screen recording of how exactly this bug appears for you?

**Comment by richardbartha** [comment] 2022-05-18 10:25
The screenshot in the bug description is a *.gif file is that not good enough ?

**Comment by MateStrysewske** [comment] 2022-05-18 11:10
@richardbartha Ah sorry, missed that

**Comment by MateStrysewske** [comment] 2022-05-18 11:13
Okay, that's really interesting. I don't have this behaviour at all. Do you also experience it in e.g. the case person form or so?

**Comment by richardbartha** [comment] 2022-05-18 11:19
No it only occurs at event participant for contacts and cases this does not happen at all. Also important to notice is that the test uses API to create the event, API to create a case, API to create  a person and then adds this person as participant for the given event.

**Comment by MateStrysewske** [comment] 2022-05-18 11:22
@richardbartha Okay, I think we have to have a more detailed look into this in the next sprint.

**Comment by BarnaBartha** [comment] 2022-06-14 07:13
Can no longer reproduce it on local system or https://test-auto.sormas.netzlink.com/.

**Comment by markusmann-vg** [comment] 2022-06-15 09:04
I will remove the milestone

**Comment by syntakker** [comment] 2022-07-20 13:42
Cannot reproduce either.

**Comment by syntakker** [comment] 2022-07-25 20:25
QA could not reproduce the error either, so I close the issue.

**Closed by syntakker** 2022-07-25 20:25 UTC
Labels: bug, events, vaadin-app, major
