### ISSUE TITLE
Business logic  for final lab result of a case .

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2031] opened 2020-05-09 12:27 UTC
### Situation Description
Since in real life, a case can have many samples and each of these samples can have many test results, we need to define the logic that SORMAS will use in determining the final lab result that should be used to classify the case.
### Additional Information
We invite everyone to comment on how they think this should work considering the following points in mind:
1. Which test result should be considered as the final test result of the sample? Currently, when there are more than one sample result for the same disease as that the case, SORMAS ask the user to choose which of them should be used as the final lab result of the sample.
2. When there are more than one sample for a case and each sample has a final lab result, What should SORMAS  do to determine the final lat result of the case? 
  2,1 Automatically choose the sample with positive result? If there are more than one samples with 
  positive final sample result, then:
  2,2 Ask the user to choose one of the final sample result as the sample result of the case?
  2.3 Automatically calculate the majority result (in case there are more than 2 samples) and use this 
  as the result of the case?

**Comment by MateStrysewskeSym** [comment] 2020-05-11 05:54
Duplicate of #1860. I've added the last part of this issue to the already existing one.

**Closed by MateStrysewskeSym** 2020-05-11 05:54 UTC
