### ISSUE TITLE
Make events public to supervisors and officer roles

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5176] opened 2021-04-21 12:59 UTC
### Feature Description

In order to link events across regions, then users need to see events outside their jurisdiction, thus prevent the creation of duplicate events.
### Problem Description

jurisdictional users can only see events in their jurisdiction thus may result in creation of duplicate events in other to link cases to events across jurisdiction.
### Proposed Change

It would be good for certain user roles that are responsible for managing events to have read access to events that are not in their jurisdiction. Either make  events public to all users or to officers (surveillance, contact, community) and supervisor roles (surveillance + contact)

**Comment by bernardsilenou** [comment] 2021-04-21 13:01
@kwa20 @JaquM   @carolinverset 
- Is this change fine by you all?

**Comment by MateStrysewske** [comment] 2021-04-21 13:29
Duplicate of #5169

**Closed by MateStrysewske** 2021-04-21 13:29 UTC
Labels: change
