### ISSUE TITLE
Merging of cases fails for all cases created since 1.69.1

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#8498] opened 2022-03-23 07:44 UTC
### Bug Description

Since 1.69.1 the merging of cases fails for every cases which was created after the update to 1.69.1. It also fails even if only one of the duplicates was created after the upgrade:

![image](https://user-images.githubusercontent.com/74791118/159646636-7baf9aee-dfac-470d-99d9-838ffdce5a38.png)

Here is a detailed export of a sample (personal data are changed for data protection):
[sormas_fälle_2022-03-23_ not_working.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8330840/sormas_falle_2022-03-23_.not_working.csv)

I tested it with different user with different roles.

As a lot of health office are having multiple duplicate I request a hotfix plz.

### System Details

* Device:
* SORMAS version: 1.69.1
* Android version/Browser: Edge
* Server URL: local instance
* User Role User 1: Admin, National user, national clinician
* User Role User 2: Admin, surv supervisor, contact superv., clinician

**Comment by Marko-ilmkreis** [comment] 2022-03-23 07:51
@MateStrysewske @kwa20

**Comment by Marko-ilmkreis** [comment] 2022-03-23 08:19
further invesigations leads to the point that the merge fails if a vaccination is in the duplicate case. It seems there is a problem to copy it into the leading case.

The error occures also when in the leading case is no vaccination.

**Comment by MateStrysewske** [comment] 2022-03-23 08:28
Will tackle this together with #8333

**Comment by MateStrysewske** [comment] 2022-03-23 10:24
@Marko-ilmkreis I can't reproduce this on my system (running 1.70.0). If this happens on a loca instance, could you please attach the exceptions that are logged when the bug occurs on your system?

**Comment by Marko-ilmkreis** [comment] 2022-03-23 10:27
@MateStrysewske No it is on ITZ-Bund. I had contact to a developer from HZI which was an the was to ask Netzlink for the logs.

It happens on every case with a vaccination in the duplicate case. When deleting the vaccination it can be merged into the leading case.

**Comment by Marko-ilmkreis** [comment] 2022-03-23 10:31
@MateStrysewske I can also confirm that this error happens also for contact with vaccinations.

**Comment by MateStrysewske** [comment] 2022-03-23 10:48
@Marko-ilmkreis Okay, that makes it pretty impossible to work on this problem - I don't think we can do anything without error logs here. I'll reopen the issue though.

**Comment by cmeyerhzi** [comment] 2022-03-23 10:51
I was able to verify the problem on our test server 1402 with version 1.69.1. i am getting the logs from netzlink atm.

**Comment by Marko-ilmkreis** [comment] 2022-03-23 12:26
[logs_ilm_kreis.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8332956/logs_ilm_kreis.txt)

Here is our log as well

**Comment by MateStrysewske** [comment] 2022-03-24 10:33
@cmeyerhzi @Marko-ilmkreis I expect this problem to be fixed in 1.70.0 which is scheduled to be released soon. Based on discussions with HZI (@JaquM-HZI, tagging you here for information), I don't believe there will be another hotfix for 1.69. Correct me if I'm wrong. ;)

**Closed by MateStrysewske** 2022-03-24 10:33 UTC
Labels: bug, contacts, cases, backend, feedback, major

**Comment by cmeyerhzi** [comment] 2022-03-24 10:34
@MateStrysewske correct no hotfix for 1.69. fixing in 1.70 is fine. thx
