### ISSUE TITLE
Campaign statistics error- Does not open

### ISSUE THREAD

**Issue by danieltomaba** [hzi-braunschweig/SORMAS-Project#5114] opened 2021-04-16 13:20 UTC
### Steps to Reproduce

1. open the APMIS system, click on the campaigns tab
2. Click on campaigns statistics, it throws an error

### Expected Behavior
[error logs-apmis.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6325285/error.logs-apmis.txt)

### Screenshots

![D2CBAAD1-E45B-4E56-88D5-6829974224E0](https://user-images.githubusercontent.com/50736373/115030285-ea688980-9e94-11eb-809d-972ef75eb98f.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2021-04-16 13:21
Duplicate of #5055

**Closed by MateStrysewske** 2021-04-16 13:21 UTC
Labels: bug
