### ISSUE TITLE
Make the figures in the dashboard clickable

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4484] opened 2021-02-22 06:59 UTC
### Feature Description

The dashbord is undergping a redesign.  It would be nice if the text of the figures would be clickable and results in opening the directory with the right filter so see the cases/contacts behind this figures.

So in example, in our dashboard shows today:

![grafik](https://user-images.githubusercontent.com/74791118/108673248-a6d04f80-74e3-11eb-8fbb-d6db3c140784.png)

It would be nice if the user can click on “35 New Cases” and the case directory opens and shows that cases, the same for the new events, new test results and so on.

Maybe this could be made withe the angular-interface?

### Problem Description

Ths user must currently set and know the filter which are used to generate the figures.

### Possible Alternatives

Leave it like it is.

**Comment by bernardsilenou** [comment] 2021-02-22 13:17
- Similar to what we have on the map, to open on a new tab
- We also need to think of performance issues since this number can be large

**Comment by MateStrysewske** [comment] 2021-02-22 15:44
Duplicate of #823

**Closed by MateStrysewske** 2021-02-22 15:44 UTC
Labels: change
