### ISSUE TITLE
Edit and create user roles [8]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4463] opened 2021-02-18 13:27 UTC
### Situation Description
Source: #898 (comment)

Depends on #4461 and #4462 and #5058

#### Mockups

* Create user role: https://www.sketch.com/s/32266e24-8c84-4006-8e1c-27263b30bdb4/a/8ygaJR8

![grafik](https://user-images.githubusercontent.com/23217632/162695418-6a211c36-5238-4cb4-84fe-6391d7c71c49.png)

* Edit user role rights: https://www.sketch.com/s/32266e24-8c84-4006-8e1c-27263b30bdb4/a/25V4WaA
![grafik](https://user-images.githubusercontent.com/23217632/162695552-e1e210cc-14be-48bd-ae83-e225060586ae.png)

* Edit user role notifications: https://www.sketch.com/s/32266e24-8c84-4006-8e1c-27263b30bdb4/a/paMlYxA
![grafik](https://user-images.githubusercontent.com/23217632/162695618-c08c064e-bdc4-4434-a6e3-798f98aa9d35.png)

#### Implementation

- [x] Allow creation of new user roles as in mockup
- [x] Name and jurisdiction are required fields
- [x] Trimmed name should be unique
- [x] Add USER_ROLE_EDIT, USER_ROLE_DELETE user rights. Give it to the admin default user. For migration give those rights to every user role that is allowed to edit users.
- [x] As first step of creation allow to select a template user role: List all active user roles and all default user roles. The new user role copies all settings of the selected user role. Note: Since we are creating a UserRole entity for each DefaultUserRole when the system is setup, by default all user roles would be listed twice. I'd suggest to have the DefaultUserRole entry in the list extended with a "(default)". E.g. "Surveillance officer (default)".
- [x] Build edit forms as in mockups. Below the description field add checkboxes for the following three attributes providing tooltips:
  * hasOptionalHealthFacility: Allows to associated a user to a health facility even though the user is not on health facility jurisdiction level.
  * hasAssociatedDistrictUser: Allows to associated a user to another user on district jurisdiction level which will be used for weekly reports.
  * portHealthUser: User is a port health user, so created cases and other data will be associated to a point of entry.
- [x] hasAssociatedDistrictUser should only be available for users on community and health facility jurisdiction level
- [x] portHealthUser should automatically be set to true and read-only when the jurisdiction is POINT_OF_ENTRY
- [x] Needed fix in UserEditForm: userDistrict in UserEditForm.updateFieldsByUserRole should be true when hasOptionalHealthFacility is true
- [x] Introduce a UserRightGroup enum that defines how to group the user rights in the UI. The groups are listed below.
- [x] Same for NotificationType. The groups are Cases, Contacts, Events, Samples, Tasks. Rename VISIT_COMPLETED to CONTACT_VISIT_COMPLETED and DISEASE_CHANGED to CASE_DISEASE_CHANGED.
- [x] Use it to edit existing user roles
- [x] Allow disabling of user roles -> can no longer be selected for users, but stays where it has been assigned to users
- [x] Allow deletion of user roles -> is removed from all users that are currently using it. Not possible when at least one user will have no user role afterwards -> implement confirmation popup "Are you sure you want to remove this user role, used by X users"
- [x] When a user right is selected automatically select needed user rights (#5058)
- [x] When one of those needed user rights is de-selected by the user an error message will be shown when saving (based on the validation implemented in #5058).

To make sure admins don't loose the ability to administer user & user roles (added 29/06/22):

- [x] when a user that has the USER_ROLE_EDIT right is editing himself, he needs to keep at least one user role that still gives him the USER_ROLE_EDIT right and one user roles that gives him the USER_EDIT right.
- [x] when a user that has the USER_ROLE_EDIT right is editing user roles, he needs to keep at least one user role that still gives him the USER_ROLE_EDIT right and one user roles that gives him the USER_EDIT right.

### User right groups

Name of user right groups for the user role edit form, followed by the list of user rights that should be contained.

* GENERAL - General: SORMAS_REST, SORMAS_UI, PERFORM_BULK_OPERATIONS, QUARANTINE_ORDER_CREATE
* DATA_PROTECTION - Data Protection: SEE_PERSONAL_DATA_, SEE_SENSITIVE_DATA_
* PERSON - Persons: PERSON_
* CASE - Case Surveillance: CASE_
* CASE_MANAGEMENT - Case Management: CASE_CLINICIAN_, THERAPY_, PRESCRIPTION_, TREATMENT_, CLINICAL_COURSE_, CLINICAL_VISIT_
* PORT_HEALTH: Port Health: PORT_HEALTH_
* CONTACT - Contact Surveillance: CONTACT_
* VISIT - Follow-Up: VISIT_
* SAMPLE - Sample Testing: SAMPLE_, PATHOGEN_TEST_, ADDITIONAL_TEST_,
* IMMUNIZATION - Immunization: IMMUNIZATON_
* TRAVEL_ENTRY - Travel Entries: TRAVEL_ENTRY_
* TASK - Tasks: TASK_
* EVENT - Events: EVENT_, EVENTPARTICIPANT_, EVENTGROUP_, ACTION_, PERFORM_BULK_OPERATIONS_EVENT, PERFORM_BULK_OPERATIONS_EVENTPARTICIPANT
* AGGREGATED_REPORTING - Aggregated Reporting: WEEKLYREPORT_, AGGREGATE_REPORT_
* CAMPAIGN - Campaigns: CAMPAIGN_, CAMPAIGN_FORM_DATA_
* DASHBOARD - Dashboard: DASHBOARD_
* STATISTICS - Statistics: STATISTICS_
* EXPORT - Export: DATABASE_EXPORT_ACCESS, BAG_EXPORT, EXPORT_DATA_PROTECTION_DATA
* EXTERNAL - External Systems: EXTERNAL_MESSAGE_, PERFORM_BULK_OPERATIONS_EXTERNAL_MESSAGES, SEND_MANUAL_EXTERNAL_MESSAGES, MANAGE_EXTERNAL_SYMPTOM_JOURNAL, EXTERNAL_VISITS, SORMAS_TO_SORMAS_SHARE, SORMAS_TO_SORMAS_CLIENT
* USER - Users: USER_
* INFRASTRUCTURE - Infrastructure: INFRASTRUCTURE_, POPULATION_MANAGE
* CONFIGURATION - Configuration: MANAGE_PUBLIC_EXPORT_CONFIGURATION, DOCUMENT_TEMPLATE_MANAGEMENT, LINE_LISTING_CONFIGURE, OUTBREAK_, DEV_MODE

### Refine

- [x] Introduce "readOnly" property to forbid editing of technical user roles in the frontend? -> no!

**Comment by MartinWahnschaffe** [comment] 2022-04-07 07:38
@kwa20 An idea on how to address your question on how to deal with "technical" user roles like S2S and Climedo:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4461#issuecomment-1084655733

We could give the user role a property "readOnly" or "backendOnly" that prevents it from being edited in the UI. We could still list it and allow the user to look into it, but it can only be adjusted from the database.

**Comment by vidi42** [comment] 2022-04-12 11:48
Since this is a big ticket we could split it:
1. create / edit user role
2. delete and archive user role

@MartinWahnschaffe FYI

**Comment by kwa20** [comment] 2022-04-12 12:27
> @kwa20 An idea on how to address your question on how to deal with "technical" user roles like S2S and Climedo: [#4461 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/4461#issuecomment-1084655733)
> 
> We could give the user role a property "readOnly" or "backendOnly" that prevents it from being edited in the UI. We could still list it and allow the user to look into it, but it can only be adjusted from the database.

@MartinWahnschaffe A problem we currently have is that technical users don't have unique roles associated with them, e.g. the survnet user is a combination of Admin, Officer/Supervisor and Rest user roles. Thus, we probably can't make them partially read-only.
We might be able to introduce dedicated user role templates for technical users to make them independent from other roles. I don't know if we could change existing technical users, though, or tell users to change the roles of their respective technical users.
I think the overall idea to introduce a property for such users is a good idea, however, editing technical users via the UI might also be useful if adjustments are necessary without someone having direct database access. We could think of also adding a featureconfig to allow editing technical users.

Maybe that topic is worth a separate discussion?

**Comment by MartinWahnschaffe** [comment] 2022-04-25 07:17
@bernardsilenou 

1. Yes, I don't see a problem with that. It may be very helpful to give user roles the exact names of what the role's are about in the real world and sometimes users may need the exact same rights to do different things.
2. When merging instances I wouldn't recommend to take over user-roles as-well. Instead there should be a clear definition which user roles the users from the merged system should have in the new system.
3. Yes, those are also valid jurisdictions. Not sure what you are referring to - maybe those are missing in some of the mockups?
4. Yes, we have done extensive refactorings to cover this (see #898). Most of it is handled by #2802, #2805, #2804 and #8318

**Comment by MartinWahnschaffe** [comment] 2022-04-25 09:24
Just had a discussion on the readOnly/backendOnly question and decided that it's ok to make those user roles available and editable by the "normal" admin - no need for addition user rights.

Issues to be create as result of our discussion.

- [ ] Check whether we already have an issue to restrict access to the UI (e.g. to forbid technical users to access the user interface)
- [ ] Define default user roles needed for the interfaces to external surveillance tools, the symtpoms diary and sormas to sormas
- [ ] Add descriptions of default user roles to the system

**Comment by MartinWahnschaffe** [comment] 2022-04-25 15:03
@kwa20 Just thought about this again and I'm not sure what the purpose of not allowing technical users to access the UI is. Anything they are allowed to do in the UI, they can also do via ReST, so technically and from data protection perspective there is probably no difference.

**Comment by MartinWahnschaffe** [comment] 2022-06-20 11:32
@kwa20 Would be great if you could review the user right groups I have defined in the issue description. Maybe you have suggestions on how to group the user rights in a different way. If it's not clear at this point we can also review this when the edit form has been created - changing this later in the code will be easy.

**Comment by leventegal-she** [comment] 2022-07-04 12:28
Waiting for [#5058](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5058)

**Comment by MateStrysewske** [comment] 2022-08-01 08:40
@leventegal-she You've removed at least one user right from the UserRight enum in this issue (CONTACT_ASSIGN - I suppose you might've also removed more, but I didn't check) without making sure that the database does not contain this right or these rights, which leads to users that do have these rights not being able to log in anymore. I'm reopening this issue and would like you to fix that both in the web as well as the mobile app.

**Comment by MateStrysewske** [comment] 2022-08-01 08:41
Update: Same issue with CONTACT_CLASSIFY

**Comment by leventegal-she** [comment] 2022-08-01 08:44
There is a merge issue in the sormas_schema.sql it didn't conflict but my migrations scripts had smaller versions then the last one on the development branch so the migrations for this ticket didn't run.

**Comment by kwa20** [comment] 2022-08-02 08:20
I tested this feature test-de2.sormas.netzlink.com (https://github.com/hzi-braunschweig/SORMAS-Project/commit/98aa280ddf0d5ec59a02ada422c0248962430531) and noticed the following:

- When Editing the user role notifications, pressing discard does not actually deselect the selected checkboxes when they have not been saved. However, in the backend this seems to happen because navigation after discarding does not trigger the unsaved changes prompt and re-opening the tab does not display selections.
1. Create a new user role
2. Open the notifications tab
3. Select all options
4. Press discard
5. Navigate away from the form and re-open it to check the selections

![userRoleNotificationsDiscardError](https://user-images.githubusercontent.com/70317594/182327466-b87155e7-2068-45c2-9c91-7551c8cd6076.gif)

**Comment by ChristopherRiedel** [comment] 2022-08-02 09:37
@leventegal-she I found some more problems (tested on test-de2):
1. When I want to delete a new UserRole, I am asked if I am sure. When I confirm this nothing happens.
2. Newly created UserRoles do not appear in the list of UserRoles.

**Comment by ChristopherRiedel** [comment] 2022-08-02 10:01
@leventegal-she As noticed by @kwa20, sorting the uuid column of the roles grid leads to an error.

**Comment by abrudanancuta** [comment] 2022-08-02 11:02
Creating a new User role and assigning it to a new User, is not possible to logging with the new created user

Steps to reproduce
1. Create a new User Role having access to Case management
2. Make user the new Role is enable
3. Create a new User and assign only the new Role created at step 1
4. Try to login with the new user

Actual result : A pop-up error is received at the login screen
Expected result: User should be able to login and see the Case directory

**Comment by abrudanancuta** [comment] 2022-08-02 11:08
Cannot save changes if doing an enable or disable for the Role

Steps to reproduce:
1. Edit a Role
2. Change some rights for it
3. Make a enable/disable => at this point the pop-up for unsaved changes appear
4. Choose Save changes

Actual results: A warning pop-up appears
Expected results: Changes before making a Enable/disable should be saved, and also the change of the status for the role(Enable or Disable)

**Comment by abrudanancuta** [comment] 2022-08-02 12:54
The checkbox "Has associated district user" is not saved at editing

Steps to reproduce:
1. Create a new Role without having checked the "Has associated district user"
2. Edit the role created above
3. Select the checkbox for "Has associated district user"
4. Open again the Role and check if the change was saved

Actual result: The change is not saved
Expected result: The selected checkbox should be saved

**Comment by abrudanancuta** [comment] 2022-08-02 13:03
New Role is not appearing in the list if has no User rights selected

Steps to reproduce:
1. Create a new Role
2. Select the role to be Enable
3. Save the change
4. Don't select any of the user rights
5. Go back to the list of User Roles
6. Look for the new Role created
7. Go at the User Management Tab
8. Select the Create New User and look for the Role created at step 1

Actual results: In the list, the new Role created cannot be found at any of the status Enable/Disable. But in the Create New User, this new Role created is displayed
Expected results: The new Role created should appear in the list to be able to edit it.

**Comment by abrudanancuta** [comment] 2022-08-02 13:04
Should be possible for a New Role to be Enable without having no Rights assigned to it?

**Comment by ChristopherRiedel** [comment] 2022-08-02 13:11
@abrudanancuta 

> Should be possible for a New Role to be Enable without having no Rights assigned to it?

Since validation was no where specified here, it's ok.

**Comment by leventegal-she** [comment] 2022-08-02 13:25
> Creating a new User role and assigning it to a new User, is not possible to logging with the new created user
> 
> Steps to reproduce
> 
> 1. Create a new User Role having access to Case management
> 2. Make user the new Role is enable
> 3. Create a new User and assign only the new Role created at step 1
> 4. Try to login with the new user
> 
> Actual result : A pop-up error is received at the login screen Expected result: User should be able to login and see the Case directory

To be able to login with a user it should have `Access Sormas UI` right.

**Comment by leventegal-she** [comment] 2022-08-02 13:47
> New Role is not appearing in the list if has no User rights selected
> 
> Steps to reproduce:
> 
> 1. Create a new Role
> 2. Select the role to be Enable
> 3. Save the change
> 4. Don't select any of the user rights
> 5. Go back to the list of User Roles
> 6. Look for the new Role created
> 7. Go at the User Management Tab
> 8. Select the Create New User and look for the Role created at step 1
> 
> Actual results: In the list, the new Role created cannot be found at any of the status Enable/Disable. But in the Create New User, this new Role created is displayed Expected results: The new Role created should appear in the list to be able to edit it.

This is related to the user role list ticket.
It was not specified that a user role must have at least one right.

**Comment by ChristopherRiedel** [comment] 2022-08-02 14:08
> > New Role is not appearing in the list if has no User rights selected
> > Steps to reproduce:
> > 
> > 1. Create a new Role
> > 2. Select the role to be Enable
> > 3. Save the change
> > 4. Don't select any of the user rights
> > 5. Go back to the list of User Roles
> > 6. Look for the new Role created
> > 7. Go at the User Management Tab
> > 8. Select the Create New User and look for the Role created at step 1
> > 
> > Actual results: In the list, the new Role created cannot be found at any of the status Enable/Disable. But in the Create New User, this new Role created is displayed Expected results: The new Role created should appear in the list to be able to edit it.
> 
> This is related to the user role list ticket. It was not specified that a user role must have at least one right.

And its already a known problem there.

**Comment by abrudanancuta** [comment] 2022-08-02 18:11
> > New Role is not appearing in the list if has no User rights selected
> > Steps to reproduce:
> > 
> > 1. Create a new Role
> > 2. Select the role to be Enable
> > 3. Save the change
> > 4. Don't select any of the user rights
> > 5. Go back to the list of User Roles
> > 6. Look for the new Role created
> > 7. Go at the User Management Tab
> > 8. Select the Create New User and look for the Role created at step 1
> > 
> > Actual results: In the list, the new Role created cannot be found at any of the status Enable/Disable. But in the Create New User, this new Role created is displayed Expected results: The new Role created should appear in the list to be able to edit it.
> 
> This is related to the user role list ticket. It was not specified that a user role must have at least one right.

This test case will be moved in the #4462

**Comment by abrudanancuta** [comment] 2022-08-03 13:12
> > Creating a new User role and assigning it to a new User, is not possible to logging with the new created user
> > Steps to reproduce
> > 
> > 1. Create a new User Role having access to Case management
> > 2. Make user the new Role is enable
> > 3. Create a new User and assign only the new Role created at step 1
> > 4. Try to login with the new user
> > 
> > Actual result : A pop-up error is received at the login screen Expected result: User should be able to login and see the Case directory
> 
> To be able to login with a user it should have `Access Sormas UI` right.

I created a Change request ticket about this right https://github.com/hzi-braunschweig/SORMAS-Project/issues/10034

**Comment by abrudanancuta** [comment] 2022-08-03 13:14
> > New Role is not appearing in the list if has no User rights selected
> > Steps to reproduce:
> > 
> > 1. Create a new Role
> > 2. Select the role to be Enable
> > 3. Save the change
> > 4. Don't select any of the user rights
> > 5. Go back to the list of User Roles
> > 6. Look for the new Role created
> > 7. Go at the User Management Tab
> > 8. Select the Create New User and look for the Role created at step 1
> > 
> > Actual results: In the list, the new Role created cannot be found at any of the status Enable/Disable. But in the Create New User, this new Role created is displayed Expected results: The new Role created should appear in the list to be able to edit it.
> 
> This is related to the user role list ticket. It was not specified that a user role must have at least one right.

A new Change request ticket was created for this case https://github.com/hzi-braunschweig/SORMAS-Project/issues/10033

**Comment by abrudanancuta** [comment] 2022-08-04 12:08
The checkbox for "hasOptionalHealthFacility" is not visible all the time. It appears only when Jurisdiction by Community or Facility are selected for Role edit form

**Comment by abrudanancuta** [comment] 2022-08-05 13:11
Some existing Roles from the system canot be used as template when creating a new Role, a pop-up warning appears for missing some rights

- Admin Surveillance Supervisor
- National User
- Contact Supervisor
-

**Closed** 2022-08-09 10:03 UTC
Labels: backend, vaadin-app, users, feature

**Comment by abrudanancuta** [comment] 2022-08-10 14:02
Validated on local env with the version 1.75.0-SNAPSHOT (d312652)

**Comment by dbe21** [comment] 2022-08-16 10:36
I tried to test this issue on test de1 and test de2 both on branch (9615efc) and found the following issues: 
1. Can't log in with the created user role ('Access Sormas UI' checked)
2. New created users with already existing user roles (e.g. Admin), are also not able to log in 
Both times, an 500 internal server error message is thrown when you try to log in 

I assume, that the issue might be linked to KeyCloak due to the non accessibility with new created users with 'old' user roles.
As this issue might be blocking for the release of 1.75, please check if KeyCloak might be the reason for it.

**Comment by leventegal-she** [comment] 2022-08-17 13:06
I also get 500 on my local environment but it seems to be a keycloak configuration issue.

@dbe21 Can you please post a screenshot with the 500 error?

I would like to see if you encounter the same issue.

**Comment by leventegal-she** [comment] 2022-08-17 14:17
Created ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10155 because the issue does not relate to this ticket.

**Comment by AliciaRaber** [comment] 2022-09-28 08:56
Tested with test1402.sormas.netzlink.com 1.75.2
Copied user roles has been applied accordingly.
Groupings applied. Also including port health user and user with different jurisdiction level.
