### ISSUE TITLE
[DEMIS2SORMAS] Messages are assigned to me without active saving

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10122] opened 2022-08-12 19:10 UTC
### Bug Description

For better consistency it should be mandatory to press the button "save" after pressing "assign to me" if you want to assign a physician report/ lab message to yourself. 

### Steps to Reproduce

1. Open the message directory
2. Press assign
3. Press assign to me
4. Wait

### Expected Behavior

The name of the user should be written in the field "assignee". The text "assign to me" is greyed out. The user have to press "save" to confirm the entry. If the user select another user bevor saving, the text "assign to me" becomes blue again.
### Screenshots

![Rank 11_window closes without saving](https://user-images.githubusercontent.com/100844689/184427175-d12b4713-4054-4b78-b0ba-100f585de8e6.gif)

### System Details

If the "greyed out" thing is a change and not part of a bugfix just leave the field blue

**Comment by SahaLinaPrueger** [comment] 2022-08-12 19:26
@JaquM-HZI

**Comment by FredrikSchaeferVitagroup** [comment] 2022-08-19 07:54
I am wondering about the use case of this ticket. 

@SahaLinaPrueger What Do you mean with better consistency? From my understanding, elements displayed like the `Assign to me` function (blue text color and underlined) directly lead to the action. For example, for a converted contact, clicking on `Open case of this contact person` directly forwards to the case (without need to click any further button). So I see the current implementation of the `Assign to me` functionality as the most consistent one.

When you want it necessary to click the `Save` button afterwards, the caption should probably be changed to `Select me`.
This would be a change, not a bug. Additionally, it has the downside of making another click necessary. So what's the benefit?

**Comment by SahaLinaPrueger** [comment] 2022-08-26 11:49
@FredrikSchaeferVitagroup You're right, it should be a change. We have not received any complaints so far, so let's leave it as it is. I will close this issue.

**Closed** 2022-08-26 11:50 UTC
