### ISSUE TITLE
Use case duplicate detection when creating a case from an event person

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2187] opened 2020-05-26 17:56 UTC
### Bug Description
When creating a case that already existed from an event person, the system does not trigger the duplicate case detection method but create an independent case. This makes it impossible to convert a person from an event to a case that already existed.
### Steps to Reproduce
1. when creating a person in an event, choose a persons that is associate to a case when duplicate person detection suggest to you
2. Convert this person to the same case 
3. System create a new case
### Expected Behavior
Whenever the case creation method is called, this should always trigger the duplicate case detection method also.
### System Details
* Device:web
* SORMAS version:1,40,1
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-05-28 05:56
@bernardsilenou This is not a bug, but rather a missing feature. It's closely associated to #2033.

**Comment by JaquM** [comment] 2021-06-21 14:05
@bernardsilenou I think this issue is done, what do you think?

**Comment by kwa20** [comment] 2021-12-12 22:31
I'm closing this as a duplicate of https://github.com/hzi-braunschweig/SORMAS-Project/issues/2394 since it has already been implemented

**Closed by kwa20** 2021-12-12 22:31 UTC
Labels: events, feature
