### ISSUE TITLE
Add an Activity Log to Cases and Contacts

### ISSUE THREAD

**Issue by flix-123** [hzi-braunschweig/SORMAS-Project#4825] opened 2021-03-18 13:27 UTC
### Situation Description
At the moment, it isn’t possible to retrace which user has changed, removed or added data in a contact or case. This feature is especially useful, to retrace the steps to find a mistake. 
### Feature Description
Add an Activity Log for supervisors, to both cases and contacts, to see which person has changed, removed or added data. See mockup below. 

![Activity Log](https://user-images.githubusercontent.com/55978646/111628800-e5aaaa00-87f0-11eb-8b7f-5d58e155e0af.PNG)

**Comment by MateStrysewske** [comment] 2021-03-19 09:30
Duplicate of #1842

**Closed by MateStrysewske** 2021-03-19 09:30 UTC
Labels: feature
