### ISSUE TITLE
See the status of Symptomtagebuch registration status in SORMAS

### ISSUE THREAD

**Issue by o-frietsch** [hzi-braunschweig/SORMAS-Project#3037] opened 2020-09-30 15:09 UTC
### Situation Description

In https://github.com/hzi-braunschweig/SORMAS-Project/issues/1970, an API interface was developed to allow an external Symptomtagebuch to transmit registration statuses to SORMAS. By now, this is visualized nowhere AFAIK, making it difficult to debug the feature.

### Feature Description

We'd like to see the registration status in the SORMAS ui.

### Possible Alternatives

- The status could be visible as text somewhere.
- The status could be visible in the upper-right button, launching the Symptomtagebuch

**Comment by MateStrysewske** [comment] 2020-10-01 06:50
Duplicate of #2083

**Closed by MateStrysewske** 2020-10-01 06:50 UTC
Labels: feature
