### ISSUE TITLE
Allow linking event particpants to contacts

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2727] opened 2020-08-27 10:28 UTC
### Situation Description
Currently it's not possible to link event participants to contacts.
Having contacts out of event participants and vice versa, there are at least 2-3 stories needed. This issue is the starting point to achieve this.

### Feature Description
As we did for cases, we would need to add the same functionality for contacts
=> Add option "convert to contact"
=> Create a contact out of event participant 
=> Link the contact to the event (backend-wise)

**Comment by bernardsilenou** [comment] 2020-08-27 10:46
@markusmann-vg I discussed with Christin and others and realized the goal is to be able to followup on event participants just as we do for contacts.
That is why we have been reluctant to specify this issue in addition to the complexity we this design since we do not operate on person based.
More information about follow up of event participate is here #1631, @faatihi at GCNet opt to work on it this sprint but still not clear to me it he will be able to deliver the complete package before September 9.

**Comment by Candice-Louw** [comment] 2020-09-05 13:06
REF: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/5

**Further specifications:**

Event Participant follow-up visits should have the same follow-up mask/questionnaire as for Contact follow-up visits and Case follow-up visits.

This means that when an Event Participant is opened and "follow-up visit" is selected, the same form that appears for Contact follow-up visits and Case follow-up visits should appear for the Event Participant follow-up visit.

All follow-up masks/questionnaires at Cases, Contacts and Event Participants should thus be identical.

**Comment by bernardsilenou** [comment] 2020-09-16 20:25
We keep this in backlog for now. Series of discussions with users favours issue #1631

**Comment by kwa20** [comment] 2021-12-12 22:43
Closing this issue as a duplicate of https://github.com/hzi-braunschweig/SORMAS-Project/issues/3035 since it was already implemented

**Closed by kwa20** 2021-12-12 22:43 UTC
Labels: discuss, android-app, vaadin-app, feature, ch
