### ISSUE TITLE
default import windows for subcontinents and countries are infinitely loading 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4905] opened 2021-03-26 16:32 UTC
### Bug Description
when importing the default subcontinents and countries, the import windows are infinitely loading although the imports have been successfully performed.
### Steps to Reproduce
1. go to configurations and perform default imports for subcontinents and countries
2. wait a while and eventually cancel the import
3. check the list for entries

### Expected Behavior
the import windows should display the proper result of the action: error, partially successful, successful
### Screenshots
<img width="462" alt="subcontinentsInfiniteImportloading" src="https://user-images.githubusercontent.com/70317594/112663477-2a6dbb00-8e59-11eb-85f9-408c1aab69d3.PNG">
<img width="606" alt="countryInfiniteImportloading" src="https://user-images.githubusercontent.com/70317594/112663490-2f326f00-8e59-11eb-806c-2eced810ce05.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment] 2021-03-26 16:56
@kwa20 This might be a tricky one because it's associated with Vaadin and how the UI is accessed. I didn't have this problem when I used the import on my system, so it's likely not easy to reproduce for our developers.

**Comment by kwa20** [comment] 2021-03-26 17:01
@MateStrysewske I see, I also noticed this on release-de.sormas.netzlink.com. Not sure if that helps. Otherwise, let me know if I can make it more clear in any way.

**Comment by syntakker** [comment] 2021-03-26 18:51
Could not reproduce locally. However, observed bug also on test-de.sormas.netzlink.com.

**Comment by Candice-Louw** [comment] 2021-03-26 19:34
Related: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3709

If fixed, please close both tickets.

**Comment by syntakker** [comment] 2021-03-28 22:39
**Note: ** test system and SORMAS version are different in #3709:
release-ch.sormas.netzlink.com/
SORMAS version: 1.52.+
However given the date of this issue (7 Dec 2020) there will be hardly any logs or other hints to inspect now.

**Comment by vidi42** [comment] 2021-06-17 09:17
This issue seems to only be reproducible sometimes and it seems to be caused by the polling mechanism of Vaadin getting messed up sometimes when it comes to long running processes.

There is a **workaround** at the moment which is dragging and moving a bit the progress window which will restart Vaadin's polling mechanism.

The more generic solution here would be to enable pushing from the server side. This however has to be done as a separate improvement task  and it was already proposed in #516.

@kwa20 If this is indeed required please open a new change request or reopen ticket with a new decision on why to enable the pushing mechanism in Vaadin.

I suggest closing this ticket.

FYI @syntakker @MateStrysewske @Candice-Louw

**Comment by MateStrysewske** [comment] 2021-06-17 09:20
@vidi42 I agree and I'm gonna close this issue.

**Closed by MateStrysewske** 2021-06-17 09:20 UTC
Labels: bug, feedback, import & export, infrastructure, vaadin-app
