### ISSUE TITLE
Exclude "not a case" classification from total case counts on Dashboard

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4099] opened 2021-01-21 12:39 UTC
### Bug Description

In our dashboard are the fatalities not counted correctly. It shows 0 fatalities for the current epi-week:

![grafik](https://user-images.githubusercontent.com/74791118/105351863-6b451b80-5bed-11eb-9c74-7563b74b5028.png)

But unfortunately few person died by C19 and are registered as dead in SORMAS:

![grafik](https://user-images.githubusercontent.com/74791118/105351887-75ffb080-5bed-11eb-8e8e-d5235ad26da1.png)
![grafik](https://user-images.githubusercontent.com/74791118/105352110-c70fa480-5bed-11eb-8d09-7583da24d0cc.png)

Maybe it's not a bug or already fixed, but I only found this issue #1792, closed 9 months ago.
 
I tested it with different users (e.g. national user, Clinician, admin), but no change so far.

**Comment by DavidBaldsiefen** [comment] 2021-01-21 12:53
Is the field "Verlauf der Erkrankung des Falls" (Case outcome) set to "Verstorben" (Deceased)? (I'm unable to replicate the issue on my local system with 1.54)

What happens if you try setting the dashboard filter to "today" instead of "this epi week"?

**Comment by Marko-ilmkreis** [comment] 2021-01-21 13:05
@DavidBaldsiefen Yes, its set to deceased:

![grafik](https://user-images.githubusercontent.com/74791118/105354091-5ddd6080-5bf0-11eb-9674-202f16ebbbc4.png)

If I set the filter on today its still 0, If i set it on "this year" instead it counts 19, but this is also not the amount we have. It unfortunately higher.

But I found the error. If I set the report date of the deceased person on today, it shows 1 died person for today. So the counting should be by the outcome, not by the report date. The report is usually many days before the person dies.

I tested it on https://test.sormas.netzlink.com and could confirm it.

**Comment by MateStrysewske** [comment] 2021-01-21 13:11
@Marko-ilmkreis The Dashboard indeed shows cases that were reported (or, if available, had their symptom onset) during the time frame that is specified in the date filters. Altering this behaviour would be a pretty significant change that would require coordination and refinement with the HZI. @bernardsilenou

**Comment by Marko-ilmkreis** [comment] 2021-01-21 13:23
@MateStrysewske But the question for the public and for the health office itself is "How many persons died today/this week". In that cases it doesn't matter when they were reported.

In my opinion also cases placed in quarantine and converted to case should show the count of the week, not when the report date were. 
![grafik](https://user-images.githubusercontent.com/74791118/105356587-e14c8100-5bf3-11eb-88cc-ee90b2b67d0a.png)

So if you have a contact from Sunday, which has a positiv test on Tuesday should be counted as converted contact for Tuesday and reported contact for Sunday.

**Comment by kwa20** [comment] 2021-01-21 13:50
@bernardsilenou I agree that indicators mentioned by @Marko-ilmkreis should be referenced by what dates the dashboard is filtered by because they are independent of when the case was reported or when the case initially started showing symptoms. If this is indeed the case, we need to change it. We might also want to check that test results are counted, even if the report or symptom onset date of the case is outside of the filtered date period.

**Comment by MateStrysewske** [comment] 2021-01-21 13:59
@kwa20 Can you please use this issue to refine this request? Please consider that the current way the data is displayed is still needed because it's crafted towards the needs in Nigeria.

**Comment by bernardsilenou** [comment] 2021-01-21 19:43
@Marko-ilmkreis @kwa20 
As @MateStrysewske mentioned, the time filter on the surveillance dashboard focuses on the date of report of the cases and contact dashboard is based on report date of the contacts, NOT the date of the outcome of all cases in the system. The reason is that we can have more fatalities in a day than new cases.

With the exception of cases in quarantine and placed on quarantine, all other indicators are conditioned on the amount of cases reported within the time interval specified by the user. I think we need to apply this constrain to "cases in quarantine" also in a new issue. 

For all other indicators linked to cases like: test results, fatalities, ... this time filter does not apply to them. For example if your filter today on the dashboard is from Jan 1 to Jan 14, 2021. The system would give you all cases reported in this interval and how many have died, irrespective of the day the person died, some may have died in Jan 20, 2021.

If your goal is to know how many cases dies on Jan 20, 2020, you then first specify your denominator (n) of cases. The number of death only make sense when compared to n, else it would give a false information to the public.

The need to know how many cases that died in a week was raised and solved here #2920
A followup issue to know how many that died in a day would be addressed here #3802  

- "contact converted to cases" should only show on contact dashboard. 
- On surveillance dashboard we add "cases resulting from contact"== unique (cases resulted from contact)

@Marko-ilmkreis hope this helps and would be happy if you can add more comments in case you find something that is not as you want.

**Comment by bernardsilenou** [comment] 2021-01-21 19:50
> @MateStrysewske But the question for the public and for the health office itself is "How many persons died today/this week". In that cases it doesn't matter when they were reported.

This is possible is statistic section but for a week, we would add for a day soon.

> In my opinion also cases placed in quarantine and converted to case should show the count of the week, not when the report date were.

This is true when we would have a dashboard with focus on quarantine alone. On a case dashboard, quarantine is a subset of cases.
> ![grafik](https://user-images.githubusercontent.com/74791118/105356587-e14c8100-5bf3-11eb-88cc-ee90b2b67d0a.png)
> 
> So if you have a contact from Sunday, which has a positiv test on Tuesday should be counted as converted contact for Tuesday and reported contact for Sunday.

You are right. This is already the logic on the contact dashboard since focus is on contacts and date of contact, but not the date the contact was converted to case.

**Comment by DavidBaldsiefen** [comment] 2021-01-22 10:51
Couldn't this be somehow similar to #3352 ?

**Comment by Marko-ilmkreis** [comment] 2021-01-25 06:31
In my opinion its still necessary that the numbers showed in the dashboard are based on the date of outcome. Its rarely that a case is reported this week and dies in the same period. Very often it is a long fight against Covid19 before they pass away. I never had the situation that in our dashboard was shown fatalities for the current week.

Even all statistics from the RKI are shown the died person by the current day. doesn't matter when they were reported.

Maybe that could be a question to ask in the weekly "Erfahrungsausstausch" with the other health offices this week? I will keep the in mind.

**Comment by Marko-ilmkreis** [comment] 2021-01-28 09:16
I have just asked for their opinion on the subject at the Exchange of Practice (Erfahrungsaustausch) with about 100 participants from health offices. The overall opinion was that the figures in the dashboard must always refer to the selected period. If there are fatality figures, this must be the number of deceased in the period, the number of converted cases must be related to the period of conversion, and so on. Anything else was said to be confusing.  Maybe this is a good opportunity to adjust all the information on the dashboard?

Translated with www.DeepL.com/Translator (free version)

**Comment by Marko-ilmkreis** [comment] 2021-01-28 09:17
I have just asked for their opinion on the subject at the Exchange of Practice (Erfahrungsaustausch) with about 100 participants from health offices. The overall opinion was that the figures in the dashboard must always refer to the selected period. If there are fatality figures, this must be the number of deceased in the period, the number of converted cases must be related to the period of conversion, and so on. Anything else was said to be confusing. Maybe this is a good opportunity to adjust all the information on the dashboard?

**Comment by bernardsilenou** [comment] 2021-01-29 01:09
@Marko-ilmkreis Thanks for the feedback and I wish to ask if you can have a look at my comment to #3004 on January 23, 2021 and tell us what you think.
Based on you comment above, I have this question pls:
Assume new cases in a region from January 1, 2021 to January 22, 2021 are 10000.  Out of these 10000 cases, two case people died each day from 24 to 28 Jan, resulting to 10 deaths. The date of outcome of these cases would be 24 to 28 Jan in the system.
If I now filter the dashboard form January 1, 2021 to January 22, 2021, I would see 10000 cases (this is OK).
According to your definition, The dashboard should show 0 death. Is this what you want to see?
Of there was just 5 new cases from 24 to 28 Jan, then if i filter from 24 to 28 Jan, according to your specification, the dashboard should show 5 cases (because they were reported from 24 to 28 Jan) and 10 fatalities (because they were reported from 24 to 28 Jan). More death than cases?

The current dashboard would show you 10000 cases (because they were reported in the time of you filter) and 10 deaths (because 10 cases out if the 10000 has died, even if the date of death does not fall in the time you specified).

To know how many people died in a day/week/ (eg Jan 24) of the 10000 cases, you can not get this statistics on the current dashboard, but from the statistic section of the application by filtering + tabulating by outcome date

I know this may not be what you mean, but my goal for writing this scenario was to get some clarifications please.

The challenge here is that fatality is always dependent/ conditioned on the number of cases and the time of fatality is always the same of after the case report time thus making difficult to have one time filter for both.

**Comment by Marko-ilmkreis** [comment] 2021-01-29 05:54
@bernardsilenou Thank you for taking your time for the answer and I hope you found time to sleep. ;-)

> If I now filter the dashboard form January 1, 2021 to January 22, 2021, I would see 10000 cases (this is OK).
> According to your definition, The dashboard should show 0 death. Is this what you want to see?

Yes, Thats excactly what I want to to have and what in my opinion is the right way to show the figures. This means that in the period January 1, 2021 to January 22, 2021 nobody died by Covid19 in the selected area. To compare the total amount of current active cases with the deaths, you can then take a look how many persons are in isolation at the present. 

I will make further comments in #3004.

**Comment by bernardsilenou** [comment] 2021-01-29 11:11
@Marko-ilmkreis My clone was up not me, lol.
@kwa20 @MateStrysewske What do you suggest please, it it necessary to have a configuration for fatality?
Both computations are right, it all depends on the interpretation you give to the numbers.

**Comment by bernardsilenou** [comment] 2021-01-29 11:41
Activating this configuration would not only apply to fatality but to also "quarantine", "resulting from contact", etc

**Comment by MateStrysewske** [comment] 2021-04-21 12:32
@bernardsilenou You'll have to define how exactly this issue should be implemented. I can't really judge that because it's an epidemiological topic that I don't have that much insight into.

**Comment by bernardsilenou** [comment] 2021-04-21 16:47
@Marko-ilmkreis  This is in reply to this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/4099#issuecomment-810189877
I only saw the comment when @MateStrysewske asked  me to have a look. Sorry for not responding.
For anything that is a bug, we make sure to implement it immediately no matter how busy we are.
The reason whey you end up having different counts is because you are using different date types probably. On the surveillance dashboard, there are 3 date types: 
 - report date = date the case was made know to the GE by the lab, doctor, etc
 - onset date = date the case person  got the first symptom = this is the date used by default on the epi-curve
 - most relevant date = combination of onset the report date, ie if onset date is missing for a case, then report date is used
 
If you choose the onset date as your date type on either dashboard or in statistics section, then cases with missing values for onset date are excluded from the count. Please can you verify that this is the cause.
![image](https://user-images.githubusercontent.com/12996724/115590721-9533da00-a2d1-11eb-8270-3b7e2bdae234.png)

**Comment by bernardsilenou** [comment] 2021-04-21 17:07
@Marko-ilmkreis We can also use the meeting time tomorrow to discuss the other point that may still need to be implemented.
Thanks

**Comment by Marko-ilmkreis** [comment] 2021-04-22 06:24
@bernardsilenou shame on me, that I have not realised the menu to set the date type :-/

I now set the date for the dashboard on case report date and get this figures:

![grafik](https://user-images.githubusercontent.com/74791118/115665371-8259ed80-a343-11eb-8c75-37b315350da5.png) ![grafik](https://user-images.githubusercontent.com/74791118/115665381-87b73800-a343-11eb-9546-af3338b41536.png)

I know that the difference are the "no cases", but then they should not count into the total amount of 189 or the should maybe be a figure like: 189 total (out there XX "No cases").

Yes, we can discuss it tomorrow as well. Thanks!

**Comment by bernardsilenou** [comment] 2021-04-22 17:38
@Marko-ilmkreis 
I agree with you, on the overall count, we should exclude "not a case" counts. On the disease specific dashboard, we can keep it since there is a category for it.

**Comment by bernardsilenou** [comment] 2021-04-23 12:27
This is what we can change in this issue:
- Exclude "not a case" categories before computing these indicators: total counts (info box on upper dashboard), fatalities (both upper and lower dashboard), difference in number of cases (bar graph)
- Not a case would then only show up in the lower disease specified dashboard and contribute to the counts for "New cases only" but not in fatalities.

**Comment by bernardsilenou** [comment] 2021-04-23 13:07
Since this is very close to the #3004, I would migrate the last comment there and close this one.

**Closed by bernardsilenou** 2021-04-23 13:07 UTC
Labels: change, dashboard, refine, vaadin-app
