### ISSUE TITLE
[Climedo Integration] Cases & Contacts > Telephone number(s) not updated

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5233] opened 2021-04-26 09:39 UTC
### Bug Description

Changing (setting new, editing existing, removing current) 'Telefon' values (Landline and Mobile) in SORMAS, do not reflect in Climedo.

For email, it works.

### Steps to Reproduce

1. Cases/Contacts > Case/Contact Person > Add/Edit Phone details & Save
2. Open Climedo > Changes not displayed

### Expected Behavior

Telphone values should be updated/sent to Climedo to display updated values.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/116061342-07fed580-a683-11eb-9973-128315ccd668.png)

### System Details

* Device: Web
* SORMAS version: 1.60 Snapshot
* Android version/Browser: Chrome
* Server URL: https://ga1.sormas-oegd.de/
* User Role: admin

### Additional Information

@FredrikSchaeferVitagroup @vlad-ciucescu @DraganMileski

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-26 09:48
@Candice-Louw Thank you for the clear examples. In the second example (the one in the middle), the transmission of the phone number is not intended behaviour, because the according contact detail is not marked primary. Once there is a primary contact detail, just that one should be synced to climedo.
In the third case (the one on the right), the phone number should be transferred to climedo, though.

**Comment by Candice-Louw** [comment] 2021-04-26 09:54
@FredrikSchaeferVitagroup - perfect, thank you for the explanation.  I tried all the combinations to make sure that nothing went missing in the process.

To summarise -
Picture 1 (L): transfer not expected, not happening = pass
Picture 2 (M): transfer not expected, not happening = pass
Picture 3 (R): transfer expected, not happening = fail

**Comment by Alexandru-Pirvu** [comment] 2021-04-29 13:39
After digging into the issue, I found two problems:
1) The reason the phone number does not get synchronized is because the number is not a correct MOBILE phone number. Everything works as expected if the number is a correct mobile phone number. More specifically, even though SORMAS sends the phone number 
The proposed way to solve this issue is to validate the phone number when saving the person contact details, the same as it is done when registering a new person in patient diary. In order to do this, we would need an API from CLIMEDO that will do the validation.

2) The way the synchronization works currently is that a singular non-primary contact detail(phone or email) will always be sent. So the behavior from picture 2 is correct just because the phone number synchronization does not work because of 1). If a correct mobile phone number will be specified, it will be synchronized with CLIMEDO even though it is not set as primary.

I will proceed with fixing 2) as we have no dependency there and will come back to 1) when will have more details about the validation API.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-05-07 09:58
As to 1), this probably is the solution:

Whenever relavant data changes, SORMAS sends a request to climedo like so: `PUT [interface.patientdiary.probandsurl]/external-data/[personUUID]`. Climedo's response has a body that looks like so:
```
{
    "success": true,
    "message": "Personeninformationen erfolgreich aktualisiert",
    "errors": {}
}

```

"errors" will contain messages as string when just parts of the changes could successfully be saved in climedo. For example, if there is a new email address and a new phone number and the email could be saved, but the phone number has an invalid format:

```
{
    "success": true,
    "message": "Personeninformationen erfolgreich aktualisiert",
    "errors": {
        "phone": "Ungültige Mobiltelefon-Nummer"
    }
}
```

When no change could be saved in climedo, the response looks like:

```
{
     “success”: false,
     “message”: 'Sowohl E-Mail als auch Handynummer sind nicht gültig! Bitte geben Sie mindestens eine gültige Kontaktmöglichkeit an ...',
}
```

So I suggest the following:

When synchronizing data for an already registered person, SORMAS checks the response body of the PUT request.
- When success == true and no errors are reported, show a popup stating: `The relevant changes were successfully synchronized to the external journal.`.
- When success == true but there errors list is not empty, show a popup stating: `The relevant changes were partially synchronized to the external journal. Please take care of  the following error(s), otherwise the external journal will have different data than SORMAS` + the message strings from errors, each separated by a newline.
- When success == false, state:  `The relevant changes could not be synchronized to the external journal. Please take care of  the following error(s), otherwise the external journal will have different data than SORMAS` + the message string from the body.

The downside of this approach is that the person data is still saved on SORMAS and climedo can still be out of sync. It relies on the user to fix the problem. One could also think about adding a externalJournalSyntStatus and persisting the error messages.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-05-08 12:23
Once there is an implementation for this issue, it probably is necessary to extend the [workflow documentation for the external visits API](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/src/main/resources/workflow-documentation.properties).

**Comment by MateStrysewske** [comment] 2021-05-18 12:09
Saving persons is no longer possible on a server that is not connected to an external journal. The PersonController.savePerson method contains quite some code that assumes that such a journal is configured and used. E.g. it accesses the responseDto without a null check, and it even displays a notification message irrespective of whether there was actually any kind of synchronization at all.

**Comment by vidi42** [comment] 2021-05-21 10:36
This issue is already part of 1.60. Please open a different ticket for the new fixes

**Closed by vidi42** 2021-05-21 10:36 UTC
Labels: backend, bug, cases, contacts, integration
