### ISSUE TITLE
decimals for cq/ct values produce error or get deleted upon saving

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4844] opened 2021-03-22 10:07 UTC
### Bug Description
When decimals are entered in the cq/ct value field in pathogen tests, either an error occurs or the decimal separator gets deleted upon saving.
### Steps to Reproduce
1. Add a pathogen test to samples.
2. Select a test type that enables the ct value field (e.g. PCR).
3. enter a number with decimals.
4. separate them with "." and "," respectively.
5. save the pathogen test a check entries.

### Expected Behavior
It should be possible to either use ",' or "." while none of them should lead to an error. Both should also not get deleted upon saving.
### Screenshots
<img width="235" alt="Screen Shot 2021-03-22 at 11 00 06 AM" src="https://user-images.githubusercontent.com/70317594/111973260-97eab600-8afe-11eb-8ef5-dd7b0efc1914.png">
<img width="491" alt="Screen Shot 2021-03-22 at 10 59 41 AM" src="https://user-images.githubusercontent.com/70317594/111973330-aafd8600-8afe-11eb-905f-47f065b47ab1.png">

### System Details
* Device:
* SORMAS version: 1.57.2
* Android version/Browser: chrome, firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
The browser language does not seem to have a huge impact on the overall behaviour except deciding which character is the one being accepted.

**Comment by Marko-ilmkreis** [comment] 2021-03-22 11:20
This is a duplicate of #4479 . We are hoping to get it solved soon, specially as in the future the ct value is shown directly at the case/contact.

**Closed** 2021-03-22 11:39 UTC
Labels: bug
