### ISSUE TITLE
Access to the contact directory KO for administrator

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#6163] opened 2021-07-20 05:55 UTC
### Bug Description

The contact directory is not accessible with the admin profile

### Steps to Reproduce
1. adopt the admin profile (only admin -> selecting admin + national user solves the problem and makes it possible to access the directory)
2. click on "contact" in the blue band on the left
3. click on "contact" in the blue band on the left

### Expected Behavior
Access to the contact directory must be possible for the administrator

### Screenshots
![image](https://user-images.githubusercontent.com/65449450/126267915-e3eb917c-9bca-4545-b35a-846f18292534.png)

### System Details
* Device: 
* SORMAS version: 1.57.2 & 1.59.1 & 1.60.2 & 1.61.2
* Android version/Browser: PC
* Server URL: exemple : https://test1401.sormas-oegd.de/sormas-ui/#!about
* User Role: admin

### Additional Information
@bernardsilenou @emond-fuseau @ftavin @olivierleuci

**Comment by bernardsilenou** [comment] 2021-07-20 07:30
@carolinverset 
I think its not a bug since admins role only does not permit the user to see infrastructure data and users only.
What we may need to change is the message that appears when a user does not have the right to see the entity.
Please can you check if admins only role can see other entities like cases, events, samples? If yes, then this is definitely a bug

**Comment by carolinverset** [comment] 2021-07-20 07:33
@bernardsilenou 
Admin alone allows easy access to case, sample or event directories :-)

**Comment by DavidBaldsiefen** [comment] 2021-07-20 07:40
I cannot reproduce this locally. Maybe it's related to some specific data in the directory?

@bernardsilenou it's still a but because in either case, no error message should appear. Also, the admin should usually be able to see the directory, but everything is pseudonymized

**Comment by carolinverset** [comment] 2021-07-20 07:50
@DavidBaldsiefen 
Ah yes possible. But in this case, why am I reproducing it at the same time on two different French servers and the HZI server indicated in the issue? strange ...
Thank you for all !!

**Comment by DavidBaldsiefen** [comment] 2021-07-21 07:11
@carolinverset We don't have access to these servers, and without logs there is sadly no way we can help. Do you have access?

**Comment by carolinverset** [comment] 2021-07-21 10:14
@DavidBaldsiefen @bernardsilenou 
The same is observed on the url : https://test.sormas.netzlink.com
The data dictionnary :
![image](https://user-images.githubusercontent.com/65449450/126472764-3ba78dd9-f180-4673-9576-d67faf76baa9.png)


We found a workaround: by associating the national user profile, the problem is solved. We will associate this role with each admin so as not to be embarrassed

**Comment by syntakker** [comment] 2021-08-10 11:26
I could not reproduce the issue. I tried to reproduce it
- as admin on https://test1401.sormas-oegd.de/sormas-ui/
- as admin on https://test1401.sormas-oegd.de/sormas-ui/ after removing admin's Nation User rights
- as a newly created admin user on https://test1401.sormas-oegd.de/sormas-ui/
- as admin on a fresh local instance
- as admin on a fresh build of version 1.62.1 on a local instance

@carolinverset https://test1401.sormas-oegd.de/sormas-ui/ is at version 1.62.1 now. Do you continue to observe this error on versions beyond 1.61.2?

If not so, I would close this issue.

**Closed** 2021-09-20 12:15 UTC
Labels: discarded
