### ISSUE TITLE
Cases showing up on the case listen do not show up when filtered by district name on muster server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1718] opened 2020-04-01 15:28 UTC
### Bug Description
On the play server, there are cases on LK Gießen, SO logged in on tablet can see the cases. When case listing is filtered by Hessen  and district LK Gießen, they cases do not show up. I check the system and there is only one district called "LK Gießen",
### Steps to Reproduce
1. Create a case on muster server in "LK Gießen" on the web 
2, login with a SO account in LK Gießen on a tablet.  the case does not appear on tablet, right?
3, Create a case on mobile device in LK Gießen, it appears normally on web
2. Filter case listing by "LK Gießen", not all the cases in LK Gießen show up in the case listing right? This may be caused by duplicate district name called LK Gießen in the system, and when one of them was archived, the web app does not see the user longed in on the tablet as belonging to the same district even though the old district does not exist anymore in the system.

### Expected Behavior
Cases created on web should appear on tablet for all districts. 
maybe the fact that duplicates  infrastructure data is no longer allowed will resolve this issue,
### System Details
* Device:
* SORMAS version: 1,32,6
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-04-02 06:24
"Archiving" a district does not mean that it doesn't exist in the system anymore. It's still there, and if any cases or users are assigned to it, those cases won't appear in the duplicate district and those users won't have access to cases created in the duplicate district.

If that's the issue, it's not a bug - please make sure that the system is set up appropriately. If I didn't get the issue right and there's another problem, please re-open this issue.

**Closed by MateStrysewskeSym** 2020-04-02 06:24 UTC
Labels: bug
