### ISSUE TITLE
Samples of event participants are not editable by officers or supervisors other than the reporting user

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3095] opened 2020-10-07 15:10 UTC
### Bug Description
When samples are created for event participants, only the reporting user is able to edit such samples. Other supervisors or officers belonging to the same region or district are unable to edit (e.g. enter test results). This problem likely occurs because there is no responsible region or district assigned to event participants. The entered region and district for the related event might be used for now. When the event participants are refined, the to be added fields in the event participant information should be used as reference (cf. #3003).
### Steps to Reproduce
1. Create and event plus participants and samples for these participants as surveillance officer.
2. Log in with another user having the same jurisdiction and try editing the samples previously created for these participants.
3. Compare with possibility to edit samples of cases and contacts.

### Expected Behavior
Supervisors or Officers belonging to the same region or district should be able to edit samples of event participants as seen for cases and contacts.
### Screenshots
<img width="1235" alt="Screen Shot 2020-10-07 at 3 38 18 PM" src="https://user-images.githubusercontent.com/70317594/95349689-a3835100-08bf-11eb-959d-2d5c72d12253.png">

### System Details
* Device:
* SORMAS version: 1.49.1
* Android version/Browser:Chrome
* Server URL: test1401
* User Role: Surveillance Officers, Supervisors

**Comment by MateStrysewske** [comment] 2020-10-08 06:39
This is basically a duplicate of #2902 because it will use the same logic. Right now we've disabled pseudonymization for event participants, so users with the general rights to edit event participants AND samples will also be able to edit samples in this case.

**Closed by MateStrysewske** 2020-10-08 06:39 UTC
Labels: bug
