### ISSUE TITLE
Other users than the admin can perform bulk actions

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4281] opened 2021-02-06 13:28 UTC
### Bug Description
Usually, only the admin or admin surveillance supervisor role can use the bulk action function. However, the bulk action is also available for other users which might lead to some unintentional actions made by some users. This behaviour seems to be applicable only for servers where interfaces (SurvNet, DEMIS, Climedo, SORMAS2SORMAS) are configured since I could not reproduce it on a test system without interfaces.

Examples here (but not limited to) are: National User (TestUser1), Surveillance Supervisor (TestUser2), Surveillance Officer (TestUser3)
### Steps to Reproduce
1. Log in as any user besides admin and admin surveillance supervisor.
2. Go to a directory and enable the bulk action function.

### Expected Behavior
Only the admin or admin surveillance supervisor role should have access to the bulk action functionality
### Screenshots
<img width="111" alt="bulkEdit" src="https://user-images.githubusercontent.com/70317594/107119259-cf6f0d00-6886-11eb-9da0-cb14085868ce.PNG">
<img width="278" alt="bulkEdit2" src="https://user-images.githubusercontent.com/70317594/107119260-d138d080-6886-11eb-9117-57b47006abd1.PNG">
<img width="98" alt="bulkEdit3" src="https://user-images.githubusercontent.com/70317594/107119266-d4cc5780-6886-11eb-9e99-157ca5640721.PNG">
<img width="107" alt="bulkEdit5" src="https://user-images.githubusercontent.com/70317594/107119267-d564ee00-6886-11eb-9877-6b203eeddc52.PNG">
<img width="99" alt="bulkEdit4" src="https://user-images.githubusercontent.com/70317594/107119264-d39b2a80-6886-11eb-9aa0-79cbee8de932.PNG">

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: see above

**Comment by bernardsilenou** [comment] 2021-02-06 14:35
@kwa20 I could not find the bulk edit mode tab when logged in as surveillance + contact supervisor role. Can you check again and give feedback?
However, it would not  be good to hide the bulk edit tab completely from the supervisors but to only show options that corresponds to their right. 
e.g surveillance supervisors can only have the edit as bulk action not delete and archive, etc

**Comment by kwa20** [comment] 2021-02-06 14:37
@bernardsilenou did you check on the test1402.sormas-oegd.de server?

**Comment by bernardsilenou** [comment] 2021-02-06 14:41
@kwa20  no, I did on 1401 + release-international
I do it now on 1402 and comment

**Comment by bernardsilenou** [comment] 2021-02-06 15:01
@kwa20 On test 1402, I could find bulk action but the only options are share + send to SurvNet, Is this problematic?
- I expect that both surveillance supervisor and  admin surveillance supervisors should have the bulk action with their default rights (edit + transfer)
- Surveillance supervisor would not have delete or archive right.
- Admin surveillance sup only would then have the right to delete, archive, etc
- What i can see that is lacking is bulk action with edit right for surveillance sup. If they can edit, then why should they not have bulk action for edit?
- Bulk action icon now depends on the server wick should not be.
Is this different from what you expect?

**Comment by kwa20** [comment] 2021-02-06 15:05
@bernardsilenou these were also my findings. The main thing I'm worried about is performance when many users try to use the bulk action function. This is already a problematic subject when only admins use this function and a lot of entities are selected.

**Comment by bernardsilenou** [comment] 2021-02-06 16:04
@kwa20 Since the surveillance supervisors are limited to data in one region, then performance should normally not be an issue when using bulk edit mode. In practice, all the users would not click at the same time. If there are performance issues, then may be cause by something else i suppose.
Let hear from @MateStrysewske before concluding what to change.

**Comment by bernardsilenou** [comment] 2021-02-06 16:12
If there is any action that needs about 60 min or more to complete, then I think we should inform the GE users to not do such activities during the day when other users are using the system. We received a report where heavy duty activities during working hours (e.g export/ import of data that requires hours) on the server has affected performance at end users. This is not an issue of the application but doing the right thing at the wrong time.

**Comment by kwa20** [comment] 2021-02-06 16:25
@bernardsilenou Exactly because this happened already we cannot be sure that users will do the right thing, even if we have informed them. Therefore, I'd be very careful. Imagine health departments with over 300 staff members being supposed to follow such instructions.

**Comment by bernardsilenou** [comment] 2021-02-06 16:34
@kwa20 Yea, you have a valid point.
Then your solution is better then, take bulk action away from surveillance supervisors.

**Comment by syntakker** [comment] 2021-02-09 22:24
This behaviour is not reproducible anymore. Restrictions to bulk edit have been intriduced /adapted in #4087,  #3904 and #3871.

Users with bulk editing rights are now:
- admin on cases, contacts, samples and events
- admin surveillance supervisor on cases and samples (see  #3904)

**Comment by StefanKock** [comment] 2021-02-19 08:04
Fixed with other tickets

**Closed by StefanKock** 2021-02-19 08:04 UTC
Labels: bug, general, vaadin-app
