### ISSUE TITLE
Duplication of the contacts follow up module to cases entity

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2407] opened 2020-06-29 13:58 UTC
### Situation Description

Dedicated unit are in charge of the follow-up of COVID+ patients and of their contacts placed in isolation. 
Difficulty : SORMAS offers different functionalities for cases and contacts’ management.

The major difficulty is related to the lack of follow-up functions for cases, such as : 
-	Follow-up end date ;
-	Functionality allowing to suspend or cancel the follow-up ;
-	Visualization of completed follow-up.

### Feature Description

Expression of need : 
-	Duplicate for cases the functionalities available for contacts to standardize follow-up and monitoring for those two categories and  this way to facilitate data entry by contact-tracing teams.

[for further information](https://github.com/GIP-GRADeS-BFC/SORMAS-Project/issues/6)

**Comment by MateStrysewskeSym** [comment] 2020-06-30 06:04
Duplicate of #1886

**Closed by MateStrysewskeSym** 2020-06-30 06:04 UTC
Labels: feature
