### ISSUE TITLE
Can't create a case if the desease was not filled while creating an event

### ISSUE THREAD

**Issue by benchaabaner** [hzi-braunschweig/SORMAS-Project#2507] opened 2020-07-20 17:01 UTC
### Bug Description
If while creating an event, you don't specify a desease ( which is optional ), creating a case is impossible because the desease attribute can't be filled.
The same scenario happens when you try to create a sample for an event participant and you didn't specify the desease while creating the event.

### Steps to Reproduce
1. creating a new event without specifying a desease
2. browse to event particpants 
3. select or create a new person
4. create a case : the desease attibute is disabled ( because it takes automatically the desease value of the event ) and you can't change it And the case can't be created.

second scenario : 
1. creating a new event without specifying a desease
2. browse to event particpants 
3. select or create a new person
4. see person attributes
5. create sample and create a new test
6. create a test result and set to "positive"
7. we are asked if we want to create a new case : the desease attibute is disabled ( because it takes automatically the desease value of the event ) and you can't change it and the case can't be created.
 

### Expected Behavior
The ability to change the desease attribute even though it was not added when creating the event

### Screenshots
scenario 1:
![event capture](https://user-images.githubusercontent.com/68555878/87961584-36c59b00-cab6-11ea-9064-669b350e6ca9.PNG)
![event participant capture](https://user-images.githubusercontent.com/68555878/87961591-39c08b80-cab6-11ea-80ae-31253f60680f.PNG)
![event case capture](https://user-images.githubusercontent.com/68555878/87961751-755b5580-cab6-11ea-9138-fc5930edcfdc.PNG)

scenario 2:
![event participant sample capture](https://user-images.githubusercontent.com/68555878/87964609-c2d9c180-caba-11ea-8ef7-f4fb4840fffb.PNG)
![event participant new sample capture](https://user-images.githubusercontent.com/68555878/87964914-37146500-cabb-11ea-9f20-d72a12eb7c65.PNG)
![event participant new sample  test capture](https://user-images.githubusercontent.com/68555878/87964962-498e9e80-cabb-11ea-8e5c-fe567f8e9532.PNG)
![event participant new sample pending capture](https://user-images.githubusercontent.com/68555878/87965004-5ca16e80-cabb-11ea-8a45-8023445eab1a.PNG)

### System Details
* Device: web
* SORMAS version: V1.44.0
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-07-21 06:09
Duplicate of #2110

Thanks for the amount of details and the screenshots though!

**Closed by MateStrysewskeSym** 2020-07-21 06:09 UTC
Labels: bug

**Comment by bernardsilenou** [comment] 2020-07-21 09:36
The system only allow one disease per event or case. If the event has no disease, before linking a case to the event, you must first give a disease to the event.
This validation is necessary because we do not want a case of cholera to be linked to an event of covid.

**Comment by benchaabaner** [comment] 2020-07-21 12:59
Ok, so we have to add manually the disease to the event before creating a case. 
Thank you for your responses !
