### ISSUE TITLE
Review of algorithm for spotting duplicate person when creating contacts

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1703] opened 2020-03-31 11:56 UTC
### Feature Description
There is a need to change the algorithm as to which the system uses to check for similar persons when creating a contact, for contact person duplicate check, the sensitivity should be reduced by also considering age, sex, first name and last name. As it stands, it seems the system only uses one variable name and brings out multiple non-relative similarities at the instance of creating a contact @bernardsilenou @SeriousMartin @MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment] 2020-04-01 07:51
Duplicate of #1644

**Closed by MateStrysewskeSym** 2020-04-01 07:51 UTC
