### ISSUE TITLE
Special Characters are not interpreted correctly 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3114] opened 2020-10-08 13:28 UTC
### Bug Description
Special Characters from the german language for example are not interpreted correctly when switching the language to German.
### Steps to Reproduce
1. Open test.sormas.netzlink.com
2. Change the language to german 

### Expected Behavior
The Words should be displayed correctly and the special character should be also accepted on the page. 
###Actual Behavior:
Check the german version of the sormas web-app. 
Some words have no meaning and this is not as expected

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/95464751-fd991a80-0982-11eb-960b-f36bf4001868.png)

### System Details
* Device:
* SORMAS version: SORMAS-Version: 1.50.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com
* User Role:

### Additional Information
This issue might be linked to  #2859

**Comment by MateStrysewske** [comment] 2020-10-09 06:53
Duplicate of #3109

**Closed by MateStrysewske** 2020-10-09 06:53 UTC
Labels: bug, sormas-ui

**Comment by AndyBakcsy-she** [comment] 2020-10-09 10:51
verified on SORMAS Version: 1.50.0-SNAPSHOT
