### ISSUE TITLE
Reminder notification when users edit a form and migrate without saving changes

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2699] opened 2020-08-25 16:24 UTC
### Situation Description
- 
### Feature Description
- When users edit a form and want to move to another tap with out saving changes, Show a reminder pop up to ask if they want to save the changes.
- First on web and later on mobile

**Comment by ChristopherRiedelSymeda** [comment] 2020-08-26 05:43
duplicate of #1613

**Closed by ChristopherRiedelSymeda** 2020-08-26 05:43 UTC
Labels: duplicate
