### ISSUE TITLE
Add a bulk action in the task directory to change the status of multiple tasks in bulk

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4500] opened 2021-02-22 13:57 UTC
### Situation Description
To date, changing the status of a task is done task by task by editing the task  and changing the status.

### Feature Description
We propose a development allowing to:
- open the task directory in bulk edit mode
- select several tasks
- modify the status of all selected tasks.

### Additional Information
@ftavin @bernardsilenou @emond

**Comment by bernardsilenou** [comment] 2021-02-22 15:22
We can use the same `--edit...` module that we have for cases

**Comment by bernardsilenou** [comment] 2021-02-22 15:24
Duplicate of #3430. Better we continue there

**Closed** 2021-02-22 15:27 UTC
Labels: feature
