### ISSUE TITLE
Symptom journals do not work without contact details marked as primary

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4941] opened 2021-03-29 16:20 UTC
### Bug Description
When trying to register persons for the symptom journals, single contact details per type are not enough for the registration. However, the attempt results in a generic error, so users don't know what went wrong and that they have to set the contact details to primary.
### Steps to Reproduce
1. Create a case or contact
2. Enter contacts details without setting them as primary
3. Try registering the person in Climedo and PIA

### Expected Behavior
The error message should be meaningful and inform the user that they need to define contact details as primary before registering persons in the symptom journals. 

Otherwise, if only one contact detail exists for the respective type, use this information as long as it belongs to the person without specifically having to check them as primary.
### Screenshots
<img width="881" alt="piaError" src="https://user-images.githubusercontent.com/70317594/112867736-8d5e8c80-90bb-11eb-945d-2a7a33a884b3.PNG">
<img width="830" alt="climedoError" src="https://user-images.githubusercontent.com/70317594/112867744-8f285000-90bb-11eb-84ea-0e8a7710c8a5.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox, chrome
* Server URL: test1402.sormas-oegd.de (climedo), release-de.sormas.netzlink.com (PIA)
* User Role: admin, national user

**Comment by kwa20** [comment] 2021-03-29 16:43
@jkheise @soja-hzi @irinajanzen-hzi

**Comment by AndyBakcsy-she** [comment] 2021-04-05 20:01
Reopening ticket as it is not yet fixed as requested. 
![image](https://user-images.githubusercontent.com/70562142/113620246-befac900-9662-11eb-9e0e-2babd804d946.png)
This is the error message that is displayed for email addresses that are not Primary. 
Once the email is set to Primary, the synchronization works as expected.

**Comment by AndyBakcsy-she** [comment] 2021-04-05 20:03
The same is true also for Phone Numbers.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-13 12:51
Just to clarify: the expected behaviour is that, if there is just one email address and/or one phone number for a person, this should be used. No matter if primary or not. 

An error message should just be shown to the user when the registration is not possible because there are no primary, but several non primary contact details of the same type for a person.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-13 12:53
I think we should also not allow registration when there is a primary email address and no primary phone number but several non primary phone numbers (and vice versa).

**Comment by jkheise** [comment] 2021-04-13 14:14
@FredrikSchaeferVitagroup You are right regarding the expected behaviour. It is not necessary for the email provided to be marked as primary in order to use the symptom diary. And I agree with the error message. 
Regarding the 2end comment: for the registration in PIA you don´t need a telephone number. An email address, whether primary or not is fine.

**Closed** 2021-04-16 11:00 UTC
Labels: backend, bug, integration

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-16 11:41
For testing, just check if the expected behaviour in the issue description shows on an instance connected to PIA (https://test-de2.sormas.netzlink.com/) and to climedo (https://ga1.sormas-oegd.de/)
