### ISSUE TITLE
Develop Linelist for contacts just as we have for cases

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1614] opened 2020-03-19 13:45 UTC
### Situation Description
Can we have the linelist for contact listing developed just as we have for cases? This will greatly help contact officers entering data for contacts as well as data for passengers of interest (we plant to migrate the entire passenger of interest data into SORMAS). 
### Feature Description
Same variables as we have for the case linelist (inclusive of symptoms with a drop-down for multiple select option, and temperature collection, type of contact)...we can further discuss to agree on other variables that are most important to be collected on a linelist.

**Comment by bernardsilenou** [comment] 2020-03-19 19:23
* Concerning passenger of interest, this means we need a possibility to create a contact person without  the contact having an associated case, We will include the option of a case category called 'unknown' and link these contacts with. This unknown category will not account for any statistics shown in SORMAS and will be latter be possible to reclassify it to a known case

**Comment by MateStrysewske** [comment] 2021-01-29 15:11
Duplicate of #1521

**Closed by MateStrysewske** 2021-01-29 15:11 UTC
Labels: contacts, refine
