### ISSUE TITLE
Task assignment for cases and contacts

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1688] opened 2020-03-30 00:32 UTC
### Bug Description
 - Surveillance supervisor (SS) in region X can assign task (case task ) to another SS in region Y. The default SS in region Y should normally not have assess to the case information in region X, so how should this be possible? is this a bug? If the task of this case it assigned to the SS in region Y, does this mean the SS will then have assess to the case data even though the case is in region X?
- A case in region X can have a contact in region Y ( in district P). The CO in district P does not automatically see the contact information and the SS in region Y cant assign a task to the CO in district P. Must the SS in region X assign the task to the SS is region Y before the SS in region Y then assigns it to the CO in district P?

### Steps to Reproduce
1.
2.

### Expected Behavior
- SS in region X should be able to assign general task to all the SO and CO in region X
- For a case in district P belonging to Region X, the SS should be able to assign task to all the SOs in district P including the associated SO of the case
- When a contact is created in district P (belonging to region Y),  The COs in district P together with the CS in region Y should automatically get notified and also get assess to the case data but limited to be able to only add contacts and do visits. The CS in district P should then be able to assign the associated CO to the contact in addition to task assignment.

### System Details
* Device:
* SORMAS version: 1.36.2
* Android version/Browser: web

**Comment by MateStrysewskeSym** [comment] 2020-03-30 05:40
@bernardsilenou I don't really understand your second point. The CO should be possible to see all contact information on this contact because the contact is assigned to their district. Also, CASE tasks should not be assigned to contact officers in the first place. The SS in region Y should absolutely be able to assign tasks associated with the contact to the SO in district P. Is any of that not working?

Concerning your first point, I'll double check how that works. It's definitely not a bug though, but maybe something we have to talk about.

**Comment by bernardsilenou** [comment] 2020-03-30 11:38
@MateStrysewskeSym I think this in not a bug but something we did  not think about in the first place while making contacts to be registered in a district outside that of the case, since contact initially where bound to the district of their cases.
Concerning my second point, the problem is that when the contacts of a case in region X is in district P located in region Y, the CO in district P does not automatically have asses to the contact on their tablet. Normally, the contact officer in district P does not see the case information, but since a contact of the case (located anywhere in the country) is in their district, I though we should make the case public to the CO in district P and also the CS in region Y by default so that they will be able to create more contacts if  needed and do visits but not change case information. In addition, if I am the CS in region X, in the drop down of any task related to the contacts in district P who has a case in region X, all CO in the district of the case and in district P should appear. This mean a CS should be able to assign task to a CO in a district outside the region of the CS as long as the contact  is linked to a of a case in one of heir district, I think this might not be possible? what do you think please?
In the current setting, a CS can only assign task to another CS outside their region,

**Comment by MateStrysewskeSym** [comment] 2020-04-02 14:27
- [ ] Certain tasks (e.g. case tasks) can be assigned to supervisors from other regions, but their user filter does not allow them to see the linked cases from within the directory (only by clicking on the direct link on the task); is this a good logic or should we prevent supervisors from other regions from receiving these tasks?

**Comment by MateStrysewskeSym** [comment] 2020-04-02 14:49
@bernardsilenou I can't reproduce what you described concerning COs in district P not seeing those contacts. It works fine for me. 

Also, I don't quite understand why Contact Supervisors should be able to assign tasks for a contact in district P to in region Y to COs from district O in region X, even when the case is from district O; the contact officer from district P won't be able to perform these tasks because they are working in a different jurisdiction.

There is, however, the problem that right now, users within the jurisdiction of the contact case are prioritised over users within the jurisdiction of the contact itself. We'll change that.

**Comment by bernardsilenou** [comment] 2020-04-02 16:37
@MateStrysewskeSym  This is the answer to my question: "Use the contact region and district before the contact case region and district when determining the users that can be assigned to a task", If this is the logic to automatically assign task to CO and also assigning responsible CO to contacts, then all is fine. 

As you mentioned above, for cases we priorities users in the district followed by region of the case and vise versa for contacts.

Thanks

**Closed** 2020-04-07 14:03 UTC
Labels: Task Management, minor
