### ISSUE TITLE
Converting a Contact to a Case | Follow-up Comment | Having the Follow-up field filled to it's limit (4096 characters) will produce a server error

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7876] opened 2022-02-03 13:54 UTC
### Bug Description
Having a Contact with a follow-up comment field filled to the maximum (i.e. 4096 characters) and converting the contact to a case will make produce a server error.

### Steps to Reproduce

1. Create a Contact and add 4096 characters to the Follow-up comment field. Make the contact Confirmed.
2. Convert the Contact to a Case
3. Check what happens on the Case creation pop-up window 

### Expected Behavior
When this situation occurs, display a pop-up with the following text:

"Performing this action will automatically cancel follow-up and append the following message to the follow-up comment: 

{insert message that would be appended to the comment field}.

The maximum length of the follow-up comment field would be exceeded by appending this message. Please choose whether you want to cancel the action, reduce the length of the follow-up comment and try it again, or omit the message displayed above."

Add two options: "Adjust comment" (closes the popup without saving the contact) and "Omit message" (closes the popup, removes the automatic message from the follow-up comment field and saves again)

### Actual Behavior
The automatic system message is exceeding the comment field limitation
There is a server error message displayed in this case

### Note: 
Deleting some of the characters from the follow-up field will enable the Contact to Case conversion

### System Details

* Device: windows
* SORMAS version: 1.68.0-snapshot
* Android version/Browser: chrome
* Server URL: local-environment
* User Role: natuser

### Additional Information
This issue is related to #7818 
Attached is the server error 
[server log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7995057/server.log.txt)

**Comment by MateStrysewske** [comment] 2022-02-04 11:09
@kwa20 We need to specify what the behaviour should be in this case. Probably a good topic for our next refinement meeting :)

**Comment by AndyBakcsy-she** [comment] 2022-04-15 09:01
Attaching server log for version 1.71.0-snapshot
[server error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8495058/server.error.txt)

**Comment by kwa20** [comment] 2022-04-19 13:53
The pop-up message is not complete and the heading is cut off:

<img width="407" alt="followUpComment" src="https://user-images.githubusercontent.com/70317594/164009799-0ec72991-bda6-4c0b-8a79-58f8df8632f1.PNG">

Missing text in the message:

> {insert message that would be appended to the comment field}.

> The maximum length of the follow-up comment field would be exceeded by appending this message. Please choose whether you want to cancel the action, reduce the length of the follow-up comment and try it again, or omit the message displayed above."

**Comment by roxanamlendea** [comment] 2022-04-19 14:01
Besides Kay's finding I have found some further problems: 

A.
Steps to reproduce:
1.Create a new Contact or open a Contact that has not been yet converted into a Case;
2. Insert a text that contains 4015 characters (4096, which is the maximum number of characters - 81, which is the number of characters of the automatic message = 4015 characters) into the 'Follow-up Status Comment' field;
3. Set the 'Contact Classification' to 'Confirmed Contact' and click on 'Create a case for this contact person';
4. Fill in the mandatory fields in the 'Create new case' form and Save

-> The system throws an error message:

![image](https://user-images.githubusercontent.com/89522688/164021022-a38e2aa7-2577-4e5a-a424-6f10a71d2ece.png)

B.
Steps to reproduce:
1.Create a new Contact or open a Contact that has not been yet converted into a Case;
2. Leave the 'Follow-up Status Comment' field empty;
3. Set the 'Contact Classification' to 'Confirmed Contact' and click on 'Create a case for this contact person';

-> The system throws an error message:

![image](https://user-images.githubusercontent.com/89522688/164021154-d4300fcc-bb33-4d02-b4c7-ee089c6ce0c8.png)

C.
The pop-up is missing 'the following message'.
'[System] Follow-up automatically canceled because contact was converted to a case'

![image](https://user-images.githubusercontent.com/89522688/164021428-43870c57-800f-48c7-a58c-9f89c8f5f35c.png)

![image](https://user-images.githubusercontent.com/89522688/164021530-d1a3d48f-4fd0-418a-b2d8-2cf2b9120c15.png)

**Comment by roxanamlendea** [comment] 2022-04-21 12:58
Reopening the ticket because the following issues are still reproducible:

A.
Steps to reproduce:
1.Create a new Contact or open a Contact that has not been yet converted into a Case;
2. Insert a text that contains 4015 characters (4096, which is the maximum number of characters - 81, which is the number of characters of the automatic message = 4015 characters) into the 'Follow-up Status Comment' field;
3. Set the 'Contact Classification' to 'Confirmed Contact' and click on 'Create a case for this contact person';
4. Fill in the mandatory fields in the 'Create new case' form and Save

-> The system throws an error message:

![image](https://user-images.githubusercontent.com/89522688/164462661-a2e5eb92-5fc1-4b2d-ad05-777b65db59fb.png)

B.
The pop-up message is not complete and the heading is cut off:

![image](https://user-images.githubusercontent.com/89522688/164462976-33d279e6-a5c8-47c1-a5ba-51a844a4cf2f.png)

C.
Missing text in the message:

{insert message that would be appended to the comment field}.

The maximum length of the follow-up comment field would be exceeded by appending this message. Please choose whether you want to cancel the action, reduce the length of the follow-up comment and try it again, or omit the message displayed above."

**Comment by dbe21** [comment] 2022-04-27 09:16
Issue cannot be approved on test-de2 Snapshot 1.71.0 (98dcdef)
I found 3 issues while testing this feature on german language settings: 

1. When the characters in the follow-up comment exceeds the maximum of 4096 characters, the pop-window does not display the system message that will be entered and the heading is cut off:
![image](https://user-images.githubusercontent.com/83459190/165481907-f9ae915d-ce1c-41e8-9262-03dc9b454dde.png)

2. also the sentence to inform the user about the choices to cancel and change the commet or omit the message is missing: 
![image](https://user-images.githubusercontent.com/83459190/165483822-db0a8bea-36de-4094-82a4-3d08b6704d15.png)

3. Furthermore the translation for the message: "[System] Follow-up automatically canceled because contact was converted to a case" is missing: 
![image](https://user-images.githubusercontent.com/83459190/165482079-78bf876f-341e-4a7f-81f0-e05d20b7805a.png)

**Comment by roxanamlendea** [comment] 2022-04-27 12:31
I tested this issue again on my local machine on the latest version of Sormas from the development branch, Sormas 1.71.0-SNAPSHOT (af0201e). Two of the issues (no.2 and no.3) that @dbe21 mentioned above are fixed on the newest version, however, I'm reopening the ticket because when German is selected as language, the heading is cut off.

![image](https://user-images.githubusercontent.com/89522688/165517999-ee27a0ef-d83d-45b0-bfc4-0536a3e12774.png)

**Closed** 2022-04-28 11:39 UTC
Labels: bug, contacts, cases, backend, major

**Comment by roxanamlendea** [comment] 2022-05-03 14:41
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (f48c389) from the development branch.
