### ISSUE TITLE
Basic export fails because bulkOperationsDropdown is accessed even if it's null

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4677] opened 2021-03-08 13:50 UTC
### Steps to Reproduce
1. Open test.sormas.netzlink.com and go to Events
2. Click on Export and choose basic export (this is happening also for detailed export)

### Expected Behavior
The downloaded file should contain events related data and no error message should be displayed
### Actual behavior:
The user receives an empty file + an error message
### Screenshots

[server error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6101747/server.error.txt)
### System Details
* Device: windows
* SORMAS version:SORMAS Version: 1.58.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NatUser

**Comment by MateStrysewske** [comment] 2021-03-08 14:39
It's possible that this affects every basic export. @AndyBakcsy-she no need to create separate issues for other basic export failures if there are any.

**Comment by MateStrysewske** [comment] 2021-03-08 14:40
Caused by #4044, so I'll close this one.

**Closed by MateStrysewske** 2021-03-08 14:40 UTC
Labels: bug, import & export, vaadin-app
