### ISSUE TITLE
Button overlaps text in super-/subordinate events sideboxes

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#4162] opened 2021-01-28 14:13 UTC
### Bug Description

In German, button and text overlap in the super-/subordinate events sideboxes.
The position of the button is also inconsistent between both boxes

### Steps to Reproduce
1. select German language
2. navigate to an event

### Expected Behavior
Elements should not overlap. Button positioning should be consistent.

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/106149613-c1303b00-617a-11eb-82b7-0c2a8f2a5811.png)

### System Details
* Device: Linux PC
* SORMAS version: 1.55.0-SNAPSHOT
* Android version/Browser: Firefox 84.0.2
* Server URL: localhost
* User Role: Contact Supervisor

**Comment by Marko-ilmkreis** [comment] 2021-01-29 05:34
@syntakker  That is a duplicate of #4127

**Closed** 2021-01-29 07:30 UTC
Labels: duplicate
