### ISSUE TITLE
Give community officer the right to see archived cases

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5023] opened 2021-04-08 16:29 UTC
### Feature Description

Add CO to CASE_VIEW_ARCHIVED

### Additional Information

Based on a user request

**Comment by bernardsilenou** [comment] 2021-04-09 01:45
@DavidBaldsiefen  This is a duplicate of #4838
I think we should instead implement #4838 for all web users.

**Closed** 2021-04-09 08:53 UTC
Labels: feature, users
