### ISSUE TITLE
[CLIMEDO Integration] Contacts > Contact Person > Same telephone number for multiple Contact Persons error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4288] opened 2021-02-08 09:52 UTC
### Bug Description
In SORMAS it is possible to have more than 1 person (contact persons) with the same telephone number, and the same email address (for example, a parent's details displayed on each of their children's entries [family feature]).

Currently, this family feature (same email address or mobile phone number for contact persons) is not working for the mobile phone number (works fine for email address) for the Climedo eDiary.

If we want to start it for a family member with the same mobile phone number as the main member, the error pops up "already existing", even though the first name is different.

Note: The error message appears only in German, although SORMAS is set to English (further bug or intended response?). 

### Steps to Reproduce

1. Open Contact Person A, with telephone number 1 > Click "Climedo eDiary" > Works as Expected
2. Open Contact Person B, with telephone number 1 > Click "Climedo eDiary" > Error Message (not expected)

### Expected Behavior
No error message (further behaviour same as that of same email address for multiple contact persons). 

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/107201917-e124f180-69f9-11eb-8fb2-5d0b8f1114e4.png)

### System Details
* Device: Web/PC
* SORMAS version: 1.54.1
* Android version/Browser: Chrome
* Server URL: https://test1402.sormas-oegd.de/sormas-ui/#!about
* User Role: admin

### Additional Information
Occurs with test person U5FDU3 on test1402 server for example.

**Comment by MateStrysewske** [comment] 2021-02-08 10:31
@FredrikSchaefer Anything we can or should do about it?

**Comment by Candice-Louw** [comment] 2021-02-19 12:48
@FredrikSchaeferVitagroup - please could you asisst?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-02-19 13:15
@Candice-Louw 
This particular error message we can internationalize. Other error messages are transmitted from climedo and then displayed to the user. Those are always german.

I am currently verifying with the climedo developers that the familiy feature (same contact data for several persons) is also available for phone number only on climedo side.

**Comment by Candice-Louw** [comment] 2021-02-19 13:25
@FredrikSchaeferVitagroup - thank you!

**Comment by FredrikSchaeferVitagroup** [comment] 2021-02-24 11:33
I have added a fix that should make it possible to use the family feature with the phone number.

Regarding the language issue: that is a quite strange phenomenom that I so far just reproduced on https://test1402.sormas-oegd.de/. On the other systems I tried it on (my local machine as well as https://ga1.sormas-oegd.de/) it seems to already be internationalized correctly. Maybe it has been resolved by something I am not aware of. That's why I suggest to move this problem out of this issue, as it is not as high in priority and quite hard (and maybe not even necessary) to trace. @Candice-Louw I you agree, I will create a new bug report for that, so we can follow up on this.

**Comment by markusmann-vg** [comment] 2021-02-24 14:22
Consider: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2744

**Comment by MateStrysewske** [comment] 2021-02-24 17:01
@FredrikSchaeferVitagroup Levi has recently worked on a bug that sounds similar to this: #4403

**Comment by FredrikSchaeferVitagroup** [comment] 2021-02-25 06:37
The Issue referenced by @MateStrysewske might have solved the I18n problem for 1.57.0. This would match my impression that the problem does not occur on my local machine and on https://ga1.sormas-oegd.de/, as both are on 1.58.0-SNAPSHOT.

**Closed** 2021-02-25 11:05 UTC
Labels: backend, bug, de

**Comment by AndyBakcsy-she** [comment] 2021-03-02 08:20
Validated this ticket on the latest SORMAS Version: 1.58.0-SNAPSHOT on ga1 environment. 
No error message displayed anymore.

**Comment by kwa20** [comment] 2021-04-06 14:44
@FredrikSchaeferVitagroup @AndyBakcsy-she Could not verify on test1402.sormas-oegd.de (1.58.2). Am I missing something?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-08 11:44
@kwa20 I could not check on https://test1402.sormas-oegd.de/, because the instance was down the last 24 hours.
Instead I tried on https://ga1.sormas-oegd.de/, and there it seems to work just fine.
Did you consider that persons using the same phone number still need to have the same last name? This will be changed by #4809 , but is not yet implemented.
