### ISSUE TITLE
Adopting or dropping of case-ID for event participants does not occur after case addition or deletion

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2749] opened 2020-08-31 08:59 UTC
### Bug Description

When adding an existing case to event participants, the case-ID will not be adopted. "Create" will remain. 

When an into a case converted event participant is deleted, the case-ID will not be dropped. 

### Steps to Reproduce
1. In the event participant tab, add a person that is already a case. Select person when duplicate recognition is triggered and save.
2. In cases, delete a case that is saved as an event participant. After deletion, check case-ID in related event participant list.

### Expected Behavior

Case-ID is expected to be adopted after adding a case as an event participant while deletion of a case should lead to the case-ID in event participants to revert back to "create".

### Screenshots

![image](https://user-images.githubusercontent.com/70317594/91701698-f3ac1c80-eb77-11ea-95a1-7bb60a322d78.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment] 2020-08-31 09:50
@kwa20 which sormas version are you using please? This point you you raised "*When adding an existing case to event participants, the case-ID will not be adopted. "Create" will remain*" is not present in version 1,46.
-This is a duplicate of issue #2473, so i will link both issues and delete this one.

**Comment by bernardsilenou** [comment] 2020-08-31 09:50
Duplicate of #2473

**Closed by bernardsilenou** 2020-08-31 09:50 UTC
Labels: bug
