### ISSUE TITLE
Sorting list of countries results in wrong order

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#5022] opened 2021-04-08 14:33 UTC
Error description:
When sorting the list of countries by name (both ascending & descending) the entries are not sorted correctly.

Expected result:
Table should be sorted according to the localized country names.

Actual result:
Table of countries is sorted using their english names, regardless of localization.

Steps to reproduce:
1. Login as admin
2. Change language of UI to german if it is set to something else
3. Click on "Einstellungen" --> "Länder"
4. Click on column "Name" once to enable sorting by name ascending
5. Observe the resulting sort order

Issue encountered on test401 using the admin user. Version was 1.58.2

<img width="978" alt="2021-04-08_16h18_48" src="https://user-images.githubusercontent.com/6122778/114044567-a0c1e280-9887-11eb-820f-d6882f928bc3.png">

**Comment by MateStrysewske** [comment] 2021-04-09 08:52
@Jan-Boehme Yes, we're aware of this. The problem is that the list is lazy-loaded from the database (to improve performance), and thus we can only sort based on the values in the database - which are always the default, so English, names of the countries. Unfortunately we're not aware of a way to fix this (other than making lists eager-loaded).

I'll leave this issue open anyway because we might find a solution for this at some point, but I don't expect that to happen anytime soon.

**Comment by DavidBaldsiefen** [comment] 2021-07-19 11:02
Will be fixed with #6091 (PR #6114 )

**Closed** 2021-07-19 11:31 UTC
Labels: duplicate
