### ISSUE TITLE
Automated Window scrolling in contact/events handicaps workflow

### ISSUE THREAD

**Issue by Lucas-Walter-GA-Tuebingen** [hzi-braunschweig/SORMAS-Project#3850] opened 2020-12-21 09:04 UTC
### Bug Description
Window scrolls to the top automatically in section "contacts" when doing some entries below Responsible Region. 
Similar in the event section. 

### Steps to Reproduce
1. Go to contacts
2. Fill in First Name of Contact Person, Last Name of Contact Person, Sex, Report Date, Disease of Source Case, Date of Last Contact, Responsible Region, Responsible District
3. Scroll down to type of contact
4. Select one of the Contact Reasons. 

### Expected Behavior
Window should not scroll to top as this . 

### System Details
* Device: Windows 10 64-Bit
* SORMAS version: 1.52.1
* Android version/Browser: Chrome
* Server URL:
* User Role: Admin

**Comment by kwa20** [comment] 2020-12-21 10:14
duplicate of #2447

**Closed** 2021-01-04 09:39 UTC
Labels: duplicate
