### ISSUE TITLE
Add option to set all epidemiological data to "no"

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1973] opened 2020-05-05 12:52 UTC
### Situation Description
When the user is editing symptoms of a case, he is able to set all symptoms to 'no' by clicking on a button (underlinded blue text: 'Set cleared to No'). This option is missing in the tab epidemiological data.

### Feature Description
Introduce button on the epidemiological data page of cases to set all answers to no. Maybe it is best to have an independent button for animal contacts below.

### Possible Alternatives
Open to suggestions.

### Additional Information
n/a

**Comment by bernardsilenou** [comment] 2020-05-05 20:00
@max-hzi O am hesitant to buy the ideas that we give users this option because users might missus it and set values to "NO" which are suppose to me "Missing" or "Unknown". Since it is not a required field, I will recommend that we allow it at it is but reposition some of the tabs as you suggested.

**Comment by MateStrysewskeSym** [comment] 2020-05-06 06:17
Duplicate of #1744 

@max-hzi Please search the repository for already existing (open) issues that match your request before creating new ones.

**Closed by MateStrysewskeSym** 2020-05-06 06:17 UTC
