### ISSUE TITLE
[Merging] Merge persons via bulk actions [5]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#5606] opened 2021-06-01 13:45 UTC
### Situation Description

It happens again and again that a single person is created several times in Sormas as a new person. It is not yet possible to unite them with each other.

### Feature Description

- [x] Add a bulk action option on the person directory
- [x] Add the option "Merge" as a bulk action
- [x] Add the user right `PERSON_MERGE`
    - [x] Only users with this right should have this option in bulk actions
    - [x] Add this to the default user roles Admin, National User and Admin Surveillance Supervisor
- [x] When "Merge" is selected in the bulk action, open a pop-up to choose the leading person
    - [x] Heading: "Pick or merge persons"
    - [x] Display the following info text:

_"Please select one of the persons below as the leading person. You have the following options to continue._

_Merge: Data of the discarded person will be linked and/or added to the remaining person but not overwritten. You will not be able to undo this action._

_Pick: Data of the remaining person will not be changed and the data of the other person will be discarded. However, entities linked to the discarded person will be linked to the remaining person. You will not be able to undo this action."_

- [x] Display the person list underneath the info message. Show both selected persons and add checkboxes in front of the rows.
    - [x] Only one person should be selectable at one time.
    - [x] Add `DISCARD`, `PICK` and `MERGE` buttons at the bottom right of the pop-up. `MERGE` and `PICK` should be disabled until the user selects one of the persons as leading.
        - [x] Pressing `DISCARD` should close the pop-up without any further action
        - [x] Pressing `PICK` should result in the following:
            - Keep the person selected as leading and discard the other one without editing any of them.
            - Link all entities of the discarded person to the remaining person.
        - [x] Pressing `MERGE` should result in the following
            - Keep the person selected as leading and discard the other one.
                - In the person table, add information from the discarded person where variables of the remaining person are null
                - Addresses: Add addresses of the discarded person to the remaining person without any duplicate checks for simplicity
                - Person contact details: Add contact details of the discarded person to the remaing person without any duplicate checks for simplicity. However, make sure that there cannot be multiple primary contact details per type and if details were labled as primary in the discarded person, don't add them as primary in the remaining person unless there is not already and primary contact detail of the respective type.
            - Link all entities of the discarded person to the remaining person.
            - Don't copy immunizations over to the leading person anymore when doing direct person merging, but simply re-link them to the leading person like all other entities
    - [x] When either `PICK` or `MERGE` are selected, trigger a confirmation pop-up emphasizing that this action will be impossible to reverse. Provide options to procede or cancel the action. When canceling the action, close the pop-up but leave the 'Pick or merge person' window open.
    - [x] Do a duplicate check of the selected persons (i.e. first and last name similarity, birthdate, sex - same pattern as we use e.g. in CaseFacadeEjb:getCasesForDuplicateMerging) when the user clicks on the "Merge" bulk action; if they would not pass this duplicate check, show a popup with the following message before opening the "Merge or pick" popup: "The two selected persons do not match the similarity requirements used by SORMAS to detect duplicate persons. Please ensure that the selected persons are indeed identical and supposed to be merged before proceeding." - Buttons: "Cancel" and "Proceed"
    - [x] Make sure that the non-leading person is no longer linked to any entities afterwards and is deleted.

**Error handling**
- [x] If more than 2 persons have been selected when pressing "Merge" an informative error should tell the user that only 2 persons can be selected and merged at one time.

### Additional Information

Person merging bulk action
![Person Merging](https://user-images.githubusercontent.com/70317594/170684354-21be5c0e-aadf-4d74-987b-38e732f39dd0.png)

Pick or merge persons
![Person merge leading selection](https://user-images.githubusercontent.com/70317594/170685007-2457771e-68a3-4dcf-8540-55a238097366.png)

Person Merging Error
![Person Merging Error](https://user-images.githubusercontent.com/70317594/170684393-19c8d96a-8d06-4106-bbbd-56af66ff20b9.png)

**Comment by ChristopherRiedel** [comment] 2021-06-01 13:45
@kwa20 This issue is one of the results of the admin exchange. It would be good if you could keep it in mind.

**Comment by kwa20** [comment] 2021-06-03 13:00
@MartinWahnschaffe We were thinking of introducing duplicate merge options also for infrastructure data before, since programming full merge duplicate views for each infrastructure data type seems like a lot of effort, do you think this could be a good alternative for that as well?

**Comment by bernardsilenou** [comment] 2021-06-03 13:09
Is this issue not a duplicate of #5576 ?

**Comment by kwa20** [comment] 2021-06-03 13:23
@bernardsilenou This one is about a merge process via bulk actions while the other one mentions a separate merge duplicate view etc.

**Comment by ChristopherRiedel** [comment] 2021-06-03 13:24
@bernardsilenou @kwa20 #5576 is also about autodetected duplicates

**Comment by bernardsilenou** [comment] 2021-06-03 13:44
OK, if they are clearly distinct, then perfect.

**Comment by MartinWahnschaffe** [comment] 2021-06-04 10:08
> @MartinWahnschaffe We were thinking of introducing duplicate merge options also for infrastructure data before, since programming full merge duplicate views for each infrastructure data type seems like a lot of effort, do you think this could be a good alternative for that as well?

Just to make sure: The idea of this issue is to be able to merge persons in the existing persons view - in contrast to creating a new view that is dedicated to identifying duplicates. This means users have to rely on the existing filters to identify potential duplicates and then are able to merge them.

I think this is a reasonable approach that would also make a lot of sense for infrastructure data. 

The biggest question is probably how the leading person is defined. Maybe users select two or more entries first. In the next view they get a list of the selected entries and can pick the leading one.

**Comment by ChristopherRiedel** [comment] 2021-06-04 10:37
@MartinWahnschaffe The idea would be, that we would have both (#5576). This functionality would only be accessible for admins. If the detect duplicate persons in e.g. a helath department (which they already do), they want to merge these tow explicit persons (independent from the system recognizing them as potential duplicates. But maybe you're right and they shouldn't have to filter for them in the directory. Maybe we just introduce a button, wich opens a window where you can state two IDs and then click on "start merge".

**Comment by kwa20** [comment] 2021-06-04 11:33
@ChristopherRiedel @MartinWahnschaffe I think being able to select the persons in bulk edit mode, select e.g. "merge" in bulk actions and then select the leading person in a pop-up would actually be quite intuitive

**Comment by ChristopherRiedel** [comment] 2021-06-04 11:38
@kwa20 but I guess it could be a problem to filter for two persons with different values (so that you could select them both)

**Comment by fritz-raphael** [comment] 2021-06-09 10:02
**Hi everyone!** Hope it's okay if I just barge in. I am currently working in the public health department of Tempelhof-Schöneberg, Berlin, Germany and have been using and managing the use of SORMAS for some time now.

Foremost: The possibility to merge existing persons into one would be great. For me personally, the idea mentioned above (being able to select to person-entries in the bulk-mode of the person-view) sounds totally adequate. 

Considering the problem @ChristopherRiedel stated: 
> 
> 
> @kwa20 but I guess it could be a problem to filter for two persons with different values (so that you could select them both)

But **how often do we want to merge two persons that have entirely different names?** Almost never. And if so, we can easily edit the persons' names so that we can find and isolate the entries in the persons view.

**Comment by kwa20** [comment] 2022-05-27 10:43
@ChristopherRiedel I've edited the original description with more detailed specifications. I hope that's fine.

This issue should also be done in favour of https://github.com/hzi-braunschweig/SORMAS-Project/issues/5576 since it's quite user friendly and less extensive.

**Comment by SahaLinaPrueger** [comment] 2022-10-28 17:43
I have two more tasks in connection with S2S
- [ ] would be nice if you could adapt/ add the option to go directly to the 'person merge' if the message: _There is at least one similar person in your system. If you accept the request the case/contact maybe will create a person in your system as a duplicate. Please check this after accepting._ (#9527) appears. So would be nice if _okay, and continue to person directory_ would be replaced by _okay, and continue to merge overview_ 
- [ ] please note that person merge have to function like case/contact merge in connection with S2S. So the leading person in target system can only be the person, who is getting into the target system if the request was shared _with ownership_ . 
If the request was sent _without_ hand over the ownership you cannot merge a case/contact in target system. But I think it is okay for person merge: the only prerequisite has to be, that at least one of the entity of the person who already is in target system has to be there with ownership. Then the person has to be editable after the merging, (leading person is the person, who is getting into the target system from source system) but the shared case/contact _without_ hand over the ownership is still not editable.
Also: We have to think about how the person/case/contact should be mergable in source system. I did not tested this yet, but it is important that S2S Sync not breaks.

**Comment by BarnaBartha** [comment] 2022-10-31 10:23
@kwa20 @ChristopherRiedel @MateStrysewske 

Can you please clarify what "all entities" and "link" means ? from "Link all entities of the discarded person to the remaining person."
The logical assumption for:
- all entities  = Case / Contact / EventParticipant / Visit / Immunization / TravelEntry / Location / PersonContactDetail
- link = it references the lead person and not the old one

Of course if i go by these assumptions the feature description is conflicting within itself and is a mess again :)

**Comment by MateStrysewske** [comment] 2022-11-01 09:12
@BarnaBartha Exactly what you've written down. All entities that have a person association and are associated to discarded person need to be re-associated to the leading person. In which way does the feature description conflict with itself in this regard though?

**Comment by kathsievers** [comment] 2022-11-02 04:51
ISSUE TRACKER COMMENT
<!-- ### Issuetracker-Description-DE[Personen über den Massenbearbeitungsmodus zusammenführen] Diese Funktion ermöglicht es, Personen im Massenbearbeitungsmodus zusammenzuführen. Diese Funktion wird im Personenverzeichnis für die Standardbenutzerrollen Admin, National User und Admin Surveillance Supervisor hinzugefügt.
![personmerge1_issuetracker](https://user-images.githubusercontent.com/97029882/199401023-881bb6a8-44e1-4350-b07a-e07fce4095d3.png)
![personmerge2_issuetracker](https://user-images.githubusercontent.com/97029882/199401026-016de9c4-7de6-4bed-8130-fc7943f9f9c8.png)
![personmerge3_issuetracker](https://user-images.githubusercontent.com/97029882/199401027-57585d4d-0421-4f72-ab5f-fe8ff91ac93d.png)
[GitHub Issue (#5606)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5606) ### End-Description-DE →

**Comment by JaquM-HZI** [comment] 2022-11-02 07:54
ISSUE TRACKER COMMENT

**Comment by BarnaBartha** [comment] 2022-11-07 08:09
> I have two more tasks in connection with S2S
> 
> * [ ]  would be nice if you could adapt/ add the option to go directly to the 'person merge' if the message: _There is at least one similar person in your system. If you accept the request the case/contact maybe will create a person in your system as a duplicate. Please check this after accepting._ ([[S2S] Add a duplicate detection warning when sharing a case with another instance [5] #9527](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9527)) appears. So would be nice if _okay, and continue to person directory_ would be replaced by _okay, and continue to merge overview_
> * [ ]  please note that person merge has to function similar but not identical to case/contact merge in connection with S2S:
> * Target System: The leading person in target system can only be the person, who is getting into the target system if the request was shared _with ownership_ .
> * Target System: The leading person in target system can only be the person, who is getting into the target system if the request was shared _without hand over the ownership_ . But attention: the only prerequisite has to be, that at least one of the entity of the person who already is in target system has to be there with ownership. After merging, (leading person is the person, who is getting into the target system from source system) the person is editable, but the shared case/contact _without_ hand over the ownership is still not editable.
>   For cases/contacts the behavior is different: If the request was sent _without_ hand over the ownership you cannot merge a case/contact in target system and that is good.
> * Source System: The leading person in source system can only be the person, who's entity was shared with the target system.
>   Source System: If an entity of the person was shared _with ownership_ : The leading person in source system can only be the person, who's entity was shared with the target system. The only prerequisite has to be, that at least one of the entity of the person who already is in _source system_ has to be there with ownership. After merging, (leading person can only be the person, who was shared with the target system) the person is still editable, but the shared case/contact _with_ hand over the ownership is still not editable.
> 
> Note: If I speak of _shared persons_ I mean a person, who's entity was shared. I know persons cannot be shared. @JaquM-HZI FYI

Please open a separate ticket for this.

**Comment by kwa20** [comment] 2022-11-08 08:42
ISSUE TRACKER COMMENT

**Comment by JaquM-HZI** [comment] 2022-11-09 10:05
Testing comments (testing ongoing):
- For S2S if I want to merge two persons, one shared with ownership and one entered manually, trying to merge the shared person in the manually one ends up in an error. Merging with having the shared case as leading works, but in the sending system, opening the shared case shows an error: 
![image](https://user-images.githubusercontent.com/78568406/200800547-c6c96f42-7f9c-46f0-98d9-7600e25a16e6.png)

**Comment by adinaflorea9** [comment] 2022-11-09 10:55
I am reopening the ticket due to @JaquM-HZI 's comment.

**Comment by SahaLinaPrueger** [comment] 2022-11-16 20:26
If I select to completely different persons, the headline of the pop-up window is cut:
![image](https://user-images.githubusercontent.com/100844689/202286859-30210bf7-714e-44b6-b8e7-6482d9bc7743.png)

**Comment by adinaflorea9** [comment] 2022-11-17 07:21
I am reopening the ticket based on Saha's comment and that the same can be observed when picking one of the persons from the 'Pick or merge person' pop-up and then clicking 'Pick' or 'Merge':
![image](https://user-images.githubusercontent.com/96909231/202381723-66080ce6-d6db-4bd0-a65d-635cba81631f.png)

**Comment by JaquM-HZI** [comment] 2022-11-17 07:42
Not beeing able to do Person merge with S2S is a bug as well, this needs to be handled within this issue, cause this is not extra, but a regular feature.

**Comment by adinaflorea9** [comment] 2022-11-17 10:06
Additional to the comment from above: in the same pop-up displayed in my comment, the question mark '?' should be added at the end of the first sentence instead of the comma ',' as that is a question. For the second sentence, it should then start with a capital letter.

**Comment by adinaflorea9** [comment] 2022-11-17 13:17
Navigation between the person pages and the main list of the 'Persons' directory when the user is in bulk edit mode is not consistent with the way that the navigation in bulk edit mode is done in the other directories. 

Steps:
1. Enter bulk edit mode in the 'Persons' directory;
2. Click on the UUID of any person;
3. Click 'Back' in the browser or on the 'Persons list' heading.
Actual behavior:
The user is no longer in bulk edit mode.
Expected behavior:
The user should still be in bulk edit mode (as the behavior is currently in the other directories - cases, contacts, events, event participants, travel entries).

**Comment by BarnaBartha** [comment] 2022-11-18 08:02
@markusmann-vg @JaquM-HZI @SahaLinaPrueger @adinaflorea9 S2S parts of this ticket will not be solved here because it was twice specifically asked if we should extend this ticket and solve that and the other 2 step process - that is due it properly, of course it was not wanted - you want a quick solution as always :)
I have extended the current functionality to not be able to merge persons that have been shared.
<img width="955" alt="Screenshot 2022-11-17 at 15 01 54" src="https://user-images.githubusercontent.com/8166805/202650490-1b35d303-3671-42d6-86b0-c4a1b024280d.png">

Of course you decide what i have to work on, and if you confirm that i should focus on the S2S part here i will do that.
But not in an unorganised matter as you have done until now with s2s & interactions team. If i need to do this i need 3 weeks, to:
- setup my S2S, fix the existing S2S testbed
- understand and correct design decisions of the overall S2S
- fix the S2S problem that results in the merge of persons and address the extra tasks that were required.
I hope it helps with your decision.

**Comment by adinaflorea9** [comment] 2022-11-18 08:39
@JaquM-HZI and @markusmann-vg I have re-tested the behavior reported in comment (https://github.com/hzi-braunschweig/SORMAS-Project/issues/5606#issuecomment-1308509570) this morning. The error that appears on the sending system when navigating between the tabs of cases is not related to the fact that the persons were merged, so it tis not due to this ticket.

The behavior is reproducible under the following steps:
1. on test-de2 create a case (with an associated person);
2. on test-de3 create a case with the exact same details as the case from step 1 (and the exact person details as well);
3. from test-de2 share with ownership handover the case into tehst-de3;
4. on test-de3 accept the case;
5. on test-de2, go and open the case that was shared, and navigate between it's tabs.
Actual behavior: An error message appears. 
![image](https://user-images.githubusercontent.com/96909231/202656954-d55871ed-69de-4f4f-8d72-36edb467799e.png)

As you can see from the steps, the persons were not merged, so the error that appears on the case page has nothing to do with the person merge functionality.

Regarding this part of the comment (the highlighted one):
![image](https://user-images.githubusercontent.com/96909231/202657153-52a6607e-b4c2-4733-915c-746b49703623.png)
That error was not reproducible for me under any scenario. If you could please provide more detailed steps for that part (including the exact users used, and testing instances used) I will be happy to further look into this.

Instances used for testing: https://test-de2.sormas.netzlink.com/ and https://test-de3.sormas.netzlink.com/
Users: Admin+NationalUser (the default ones that we have on all systems)
SORMAS version: 1.77.0-SNAPSHOT(6aa9136)

**Comment by markusmann-vg** [comment] 2022-11-18 09:14
Hi @BarnaBartha ,
I agree and I would decide that we close this ticket here and @adinaflorea9 : Please create a bug ticket from your comment and add it to the Sprint Board of the interactions Team.

**Comment by adinaflorea9** [comment] 2022-11-18 09:34
@markusmann-vg ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10957 was created as a finding and it currently is in our backlog as @sergiupacurariu is looking into it in case it might be due to #8463. If he lets me know that it is not due to #8463 I'll move the ticket to the Interactions team. 

Is it ok like this?

**Comment by adinaflorea9** [comment] 2022-11-22 10:03
I am reopening the ticket due to the following:
![image](https://user-images.githubusercontent.com/96909231/203283304-4f011d3f-34bd-4b36-848e-bcf59fa10381.png)
Persons that have different genders are not considered as different when one of the values in 'Unknown' - which is not consistent with the behavior that is in 'Cases' or 'Contacts' directory where persons that have different genders and one of the values is 'Unknown' are considered different persons even if all other information matches.

Steps to compare the behaviors:
In the 'Cases' directory:
1. Create a case for Millie Brown - gender female;
2. Create a second case for Millie Brown - gender unknown;
->person duplicate detection is not triggered as the genders are differed (just as the behavior would be for instance is the genders used were male and female);

In the 'Persons' directory:
1. Have 2 persons with the same data but one has the gender female and one has the gender unknown;
2. From the bulk edit mode, select the two persons;
3. Click 'Merge';
-> the pop-up that should say that the 2 persons are different is not triggered (when the genders used are male and female, or female and other, and so on, the pop-up is triggered and the 2 persons are considered to not be duplicates).

![person gender detection](https://user-images.githubusercontent.com/96909231/203285468-72f520af-bfab-4c03-93fe-69581bc744cf.gif)

**Comment by BarnaBartha** [comment] 2022-11-22 13:01
> Additional finding - error appears when trying to merge 2 persons and only one of them has 'Type of occupation' specified:
> 
> 1. For 1 person set the 'Type of occupation' to any value from the dropdown;
> 2. For 1 person leave those fields empty;
> 3. Pick the 2 persons for merge;
> 4. Select as leading person the one that does not have occupation type specified (the one from step 2).
>    -> error appears and the persons can not be merged
> 
> Logs from the local machine: [logs error merge.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10066339/logs.error.merge.txt)

This was introduced with #5015, that is the problem was there for other flows, nonetheless i addressed it now within this ticket.

**Comment by BarnaBartha** [comment] 2022-11-22 13:04
In the 'Cases' directory: point 2.
`
Create a second case for Millie Brown - gender unknown;
->person duplicate detection is not triggered as the genders are differed (just as the behavior would be for instance is the genders used were male and female);
`
But it is actually triggered that is why you are presented with the option to choose the similar person or create a new one. You cerate a new one - which by the logic is similar and thus of course the person merge logic shows no warning - it would show warning if the two persons were not similar.

**Comment by adinaflorea9** [comment] 2022-11-23 11:03
I am reopening the ticket due to the following:

Error appears when trying to merge 2 specific persons where one has travel entries associated.
Local machine logs:
[travel.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10074805/travel.txt)

**Comment by adinaflorea9** [comment] 2022-11-24 12:35
I am reopening the ticket for a minor UI change - text in the pop-us should be fully displayed in other languages as well:

![image](https://user-images.githubusercontent.com/96909231/203785803-ad322e1c-aff9-4693-a634-2fae8058c660.png)

**Comment by adinaflorea9** [comment] 2022-11-24 15:21
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(50745d6).

The following tickets have been logged as the behaviors have either been not covered by the specifications of the current ticket, or the behaviors observed while testing need to be discussed and refined:
#11016 
#11017 
#10881 (behavior logged there was initially reported by @SahaLinaPrueger)
#10992 (by @SahaLinaPrueger)

The buttons display issue logged in https://github.com/hzi-braunschweig/SORMAS-Project/issues/5606#issuecomment-1318197296 for how the button is displayed in other languages was discussed with @BarnaBartha but it could not be fixed.

**Comment by SahaLinaPrueger** [comment] 2022-12-01 13:10
@adinaflorea9 just a minor/cosmetic finding: only PERSON_MERGE visible under user roles:
![image](https://user-images.githubusercontent.com/100844689/205060913-2c3b6912-3504-473d-823c-fc21d3ddf2c2.png)

![image](https://user-images.githubusercontent.com/100844689/205060753-c9474525-3dd2-4eb1-a098-4e63e97e55f3.png)

**Comment by adinaflorea9** [comment] 2022-12-01 13:26
@SahaLinaPrueger are you referring to the fact that it is written differently than the rest of the user rights, or to the fact that the translation is missing?

**Comment by SahaLinaPrueger** [comment] 2022-12-01 14:47
@adinaflorea9 to the fact that it is written differently than the rest of the user rights

**Comment by adinaflorea9** [comment] 2022-12-01 14:49
@SahaLinaPrueger ok, I'll move this into a separate change since it is a minor UI display issue, as we are so close to the release and this current ticket needs to be included. Would that be alright with you?

**Comment by SahaLinaPrueger** [comment] 2022-12-01 15:17
@adinaflorea9 unfortunately I have no rights for crowdin, is this available there? Then we could translate it there as we want (_Personen zusammenführen_) and after that would it be possible to do a pull request and then deploy it? Especially with the new introduction of the right, many users will notice it and unfortunately the word "merge" is not familiar in German.

**Closed** 2022-12-02 08:41 UTC
Labels: backend, vaadin-app, feature, verified by qa, de-public, persons
