### ISSUE TITLE
Archived or old contacts without a case should be archived and removed from the mobile app db

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6840] opened 2021-09-29 21:59 UTC
### Bug Description

This is a collection of point about deleting entities in the mobile db. Since most of the point are related, I though one issue can be fine. 
@MateStrysewske  you can change if needed please.

Contact are dependent entities of cases, thus when a case is archived, the contacts are also archived. However, we also have contacts without a case in the system. Such contacts are not being archived and they stay on mobile app indefinitely. If a contact is converted to a case, the case gets archived and removed from mobile db but contact remains on mobile db. This would affect performance over time.

Entities that are archived with report date less than server specified archived duration (90 days by default) do not get deleted from mobile app db.
### Steps to Reproduce

1. Create a contact without a case that was reported more that 3 months
2. Convert contact to case and of report date also more than 3 months
3. Contacts does not get removed on mobile app
4. Case does not get removed on mobile app even after manual archiving.

### Expected Behavior

- Contacts without source case should be archived and removed from mobile app db . Automatic (if older that archived duration configured) and manual archiving should be possible.
- There should be an option to manually archive contacts with no case, just as we have for cases.
- Archived entities (case, contacts, events, etc) should be deleted from mobile db even if the duration is less than date specified in configuration. In addition, when an archived case is de-archived and report date changed to less than 90 days, the case sync to the mobile app (expected behavior). But when later archived while maintaining the new report date, it remains on mobile app (they should be deleted).
- Removal of archived entities can be done during background sync  in order not to affect the use of the mobile app. @MateStrysewske this is just a side comment and I could not test the order in which the activities are executed during sync. If this is not the case, then we can create another issue for it.

### System Details

* Device: web
* SORMAS version: 1.63.2
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: National user + admin

**Comment by MateStrysewske** [comment] 2021-09-30 07:28
Duplicate of #1664

**Closed by MateStrysewske** 2021-09-30 07:28 UTC
Labels: bug, change

**Comment by bernardsilenou** [comment] 2021-09-30 09:55
@MateStrysewske 
The third point in the expected behavior section should be a bug, right?
I would open another issue for it.
