### ISSUE TITLE
Deleted case shared via S2S still accessible through its contacts

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10138] opened 2022-08-16 11:15 UTC
### Bug Description

A case has been deleted, but is still visible.
### Steps to Reproduce

1. not reproducible
2. i sent a case and an associated contact both with hand over the ownership to a target system and in the target system i deleted the case. I repeated the steps, but the bug is not reproducible. 

### Expected Behavior

Deleted case should not be visible.

### Screenshots

![image](https://user-images.githubusercontent.com/100844689/184864847-d0e8dd4b-d629-451c-b37f-9df9f41f459d.png)

case can not be found in case directory, nor in person directory. You have to open the associated contact to find the deleted case.
Pls do not get confused i named the case and contact the same because of testing-workflow. Case and contact are different persons.
![S2S_no deletion_strage](https://user-images.githubusercontent.com/100844689/184862663-2d3b8974-8c06-4d31-a2c8-420a451fe32c.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.74.1
* Android version/Browser: Edge
* Server URL: release- x to release-de
* User Role: admin

### Additional Information

I have the application logs and the syslogs of release-de and release-sormas-x.
I can pass them if you tell me to whom.

case ID: RX75I4-R7RLT3-3EECK5-4HQKCDZE 
person ID of case: QOTJCG-WY647X-KH4Y26-XPYKCJHU
share request of case: VTXJAZ 
![image](https://user-images.githubusercontent.com/100844689/184863654-043f74f7-d216-477e-86ba-7940e557c27c.png)

contact ID: TWXO3H-JMEYIK-WDNTCL-GKZM2LBY
person ID of contact: RZ2FNP-ZYNDPG-DDJWCZ-LXQR2EJU
share request of contact: XADSNJ
![image](https://user-images.githubusercontent.com/100844689/184864232-6ad83686-b3ed-4da6-8458-642d73d5b1df.png)

**Comment by SahaLinaPrueger** [comment] 2022-08-16 11:15
@JaquM-HZI

**Comment by MateStrysewske** [comment] 2022-08-18 07:41
There are two possible solutions for this:

a. Remove cases that are deleted as source cases from all contacts
b. Keep the case as the contact's source case, but don't show it in the contact form; could be misleading and confusing to users because they might wonder why they can't see the source case, but still have the option to remove it

@SahaLinaPrueger @JaquM-HZI What would be your preferred solution?

**Comment by bernardsilenou** [comment] 2022-08-18 17:52
@MateStrysewske @JaquM-HZI 
* Is there a reason/ use case not to delete contact when deleting source case?
* My though is that child entities of a case like contact, samples should also be deleted when deleting cases. If users need to keep the contact, then it may be good to instead archive the parent entity.
* If this should stay as in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10138#issuecomment-1219142686, then i think point a. is good, since the contacts would then be interpreted as contacts without a source case.

**Comment by MateStrysewske** [comment] 2022-08-19 07:14
@bernardsilenou Yes, definitely. The case could've been created by mistake, but the contact could still be absolutely relevant. Contacts aren't necessarily a child entity of cases since they can also be created without a source case, so they're independent.

**Comment by SahaLinaPrueger** [comment] 2022-08-19 07:45
@MateStrysewske How do you reproduce this? What steps are you taking?

**Comment by JaquM-HZI** [comment] 2022-08-24 06:21
@MateStrysewske we need to be able to delete a case without his contacts so lets go with option a.

**Comment by MateStrysewske** [comment] 2022-08-25 06:51
@JaquM-HZI @SahaLinaPrueger I've checked the code and we already remove the case as the source case of all its contacts when it's deleted; So maybe there's an issue with that logic that we have to look into.

**Comment by MateStrysewske** [comment] 2022-08-26 10:39
Not reproducible on my system - handing this over to the Interactions team because maybe there's some kind of a side effect with S2S.

**Comment by SahaLinaPrueger** [comment] 2022-08-26 12:05
@MateStrysewske Let me know who to send the logs to if you need them.

**Comment by ChristopherRiedel** [comment] 2022-09-09 10:20
@SahaLinaPrueger I have tried to reproduce the whole thing several times in different settings, including in the Sormas2Sormas context. The described behavior is not reproducible. Also in the source code I don't see how the described behavior could occur. Therefore I close this issue.

**Closed by ChristopherRiedel** 2022-09-09 10:20 UTC
Labels: bug, contacts, cases, backend, major
