### ISSUE TITLE
Interface & process model for border control

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#677] opened 2018-06-25 09:33 UTC
We should make sure SORMAS gets optimally adapted to application at border control and airport.
It will probably result in an interface that is quite similar to the hospital informant and possibly also have some components of the event officer. However it would be good to have a proper design thinking workshop with people actually working at borders and airports.

**Comment by MateStrysewskeSym** [comment] 2019-08-07 11:26
Duplicate of #985

**Closed by MateStrysewskeSym** 2019-08-07 11:26 UTC
