### ISSUE TITLE
Add an Import functionality for the GERMAN DEA-Einreiseanmeldung to the Travel Entry directory

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5881] opened 2021-06-21 12:06 UTC
### Situation Description

The German health departments have access to DEA from the Bundesdruckerei so that they can download csv files of returning travellers for which they are responsible. To be able to import these files into SORMAS, we have to implement the features of "Travel Entry" Travel entries and port health refactoring #5489 so that a mapping can be made. 

### Feature Description

Add a new button "Import" to the travel entry entity where you can import a file from the DEA, which is generated there.
A mapping and an example file will be added to this story as soon as possible.
Currently the foreign countries and regions are in free text as strings in the file but will be adjusted asap to fit the needs of SORMAS and SurvNet, which means the country and regions lists will have externalIDs which are known to both systems.

**Comment by Marko-ilmkreis** [comment] 2021-06-21 12:19
This is a duplicate of #4019

**Comment by Marko-ilmkreis** [comment] 2021-06-21 12:19
@marius2301 This is a duplicate of #4019

**Comment by MateStrysewske** [comment] 2021-06-22 07:48
@Marko-ilmkreis Thanks for the hint!

**Closed by MateStrysewske** 2021-06-22 07:48 UTC
Labels: feature, refine
