### ISSUE TITLE
[S2S] The sync between target instance and  source instance is broken when was handed over

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11886] opened 2023-04-21 12:16 UTC
### Problem Description

After sharing case with the sample I can change the "date of sample collection" in the target instance and the updated date should be shown in the source instance but it doesn't (remains the old date of collection).
Obs: The same problem appears also for  Vaccination, Surveillance reports, Person

### Reproduction Steps

1. Login as a Admin user on the source instance (https://test-de1.sormas.netzlink.com)
2. Create a case with sample
3. Share case with hand over the ownership to the target instance (https://test-de2.sormas.netzlink.com)
4. Accept the case in target instance
5. Go to the shared case in target instance and edit the sample collection date
6. Save and go to the source instance
7. Check in the case if sample collection date is updated
 -> sample collection date in the source instance is not updated
...

### Expected Behavior

The sample collection date in the source instance should be updated.

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.83.0-SNAPSHOT (561c5a3)

### Android version/Browser

Chrome

### User Role(s)

Admin

### Server URL

https://test-de1.sormas.netzlink.com and https://test-de2.sormas.netzlink.com

[S2S-syncDateSampleError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11295764/S2S-syncDateSampleError.txt)

**Comment by hms-sgent** [comment] 2023-04-21 12:35
I noticed that same incorrect behavior for vaccination date

**Comment by abrudanancuta** [comment] 2023-04-27 13:47
After having a deep investigation together with @adinaflorea9 we found out that the problem is only at sample level between test-de1 being the source and test-de2 being the target.

Once the Case has a Sample linked and was accepted on the target system, all the changes made on Person, Sample, Vaccination, Case are **not** transferred to the source system

Once the Case has no Sample linked and was accepted in the target system, all the changes made on Person, Vaccination, Case are transferred to the source system

The Case must be sent with Handover to the target system to be able to see the problem with the sync.

**Comment by ChristopherRiedel** [comment] 2023-05-05 10:33
Unfortunately, the problem can no longer be reproduced.
I have tried extensively with versions 1.83.0 and 1.84.0-SNAPSHOT. I can't get it reproduced locally or on the test instances where the problem was originally discovered.
It was therefore decided to pass the ticket to testing (@abrudanancuta) and check again there with 1.83.0 to see if the problem has really disappeared.

**Comment by abrudanancuta** [comment] 2023-05-08 13:46
I tested the sending as having test-de1 as source and test-de2 as target => the data is not synced

Obs: In test-de1 when creating a sample to the case, please create also a pathogen positive test and then make a handover share to the test-de2

[syncS2S.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11421669/syncS2S.txt)

**Comment by leventegal-she** [comment] 2023-05-10 13:05
The sync go t fixed by removing the annotation in https://github.com/hzi-braunschweig/SORMAS-Project/issues/11922

But the changes in PR https://github.com/hzi-braunschweig/SORMAS-Project/pull/11945 are still needed to avoid the loss of labUser of the original Pathogen test

**Closed** 2023-05-12 08:15 UTC
Labels: bug, backend, major, s2s
