### ISSUE TITLE
[Ediary Integration] Family function not working for persons with different last names [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4809] opened 2021-03-17 22:58 UTC
Final summary of work to do: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4809#issuecomment-811657419

### Bug Description
The Climedo family function (using same email address for multiple persons) is not working for persons with different last names. This is relevant for families where persons are also filling in the questionnaire for their grandparents with different last names, or in patch-work families, for example.

### Steps to Reproduce
1. Register patient A A with email address X - working.
2. Register patient B A with email address X - working.
3. Register patient C B with email address X - not working.

According to https://github.com/hzi-braunschweig/SORMAS-Project/issues/3718, this is planned behaviour.

### Expected Behavior
Family function (multiple usage of same email address) works with users for different last names too.

### System Details
* Device: Web
* SORMAS version: 1.56.2
* Android version/Browser: NA
* Server URL: https://test1402.sormas-oegd.de/
* User Role: all

### Additional Information
@FredrikSchaeferVitagroup @vlad-ciucescu - this seems to be intended behaviour.  Is there an alternative approach/solution to this, please?

Add a popup to inform the user that this email-adress is already used (if so) ;-)

**Comment by FredrikSchaeferVitagroup** [comment] 2021-03-18 06:12
@Candice-Louw How shall SORMAS then know if persons belong to the same family or not? Shall we completely ommit checking if an email address is already in use? Maybe an alternative would be that responsible users create eMail addresses in such cases.

If we decided to change the behaviour of the system here, this would also require changes on climedo side.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-03-18 06:13
As the current state represents intended behaviour, this is not a bug.

**Comment by vlad-ciucescu** [comment] 2021-03-23 08:51
Is there a decision here? The story is in the backlog but it is not clear to me what we have to do. If we make this change we need a clear definition of how we determine what a 'family' is in SORMAS.

**Comment by Candice-Louw** [comment] 2021-03-23 11:39
@vlad-ciucescu - no feedback from Climedo yet... will follow-up again.

**Comment by JaquM** [comment] 2021-03-23 16:34
@vlad-ciucescu @Candice-Louw 
Couldn't it be used with the new input options, so that when the user enters "Collect contact details of another person or facility", they can access exactly this information while connection to Climedo?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-03-24 05:27
> @vlad-ciucescu @Candice-Louw
> Couldn't it be used with the new input options, so that when the user enters "Collect contact details of another person or facility", they can access exactly this information while connection to Climedo?

@JaquM Currently not. As far as I know Climedo blocks the creation of a new patient when it finds that a phone number or email adress is already used, unless persons have the same last name. That's why I wrote above that changes on climedo side are probably necessary.

**Comment by mariusclimedo** [comment] 2021-03-30 15:15
Hi, @FredrikSchaeferVitagroup this is not correct. We do allow duplication as long as the "filledFor" field for us is different. The filledFor field is passed from you using the first name. Thus, it should work on our end the way it is implemented. Can you please check on your end why it is still not allowed? Thx

**Comment by FredrikSchaeferVitagroup** [comment] 2021-03-31 06:48
> @vlad-ciucescu @Candice-Louw
> Couldn't it be used with the new input options, so that when the user enters "Collect contact details of another person or facility", they can access exactly this information while connection to Climedo?

In my understanding "Collect contact details of another person or facility" means that one person has additional contact information that does not strictly belong to that person. So there is an additional contact detail. In the case of the family function, there is one contact detail used several times, so it's rather a lack of contact details. That should not be mixed up.

**Comment by DraganMileski** [comment] 2021-03-31 14:17
> Hi, @FredrikSchaeferVitagroup this is not correct. We do allow duplication as long as the "filledFor" field for us is different. The filledFor field is passed from you using the first name. Thus, it should work on our end the way it is implemented. Can you please check on your end why it is still not allowed? Thx

A small clarification here, filledFor is not passed by Sormas to Climedo but rather is being created from the firstName passed from Sormas. Therefore the Sormas' check should be focused on the First Name rather than the Last Name because for the Climedo logic, lastName is not important at all.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-01 05:42
Okay, so it shows that a person to be registered in climedo need to have a unique first name among the people using the same email address and phone number.

So there will probably pop up a bug report complaining about the family function not working for father and son with the same first name. 🤔 

Anyway, what we shoud do in this ticket is to 
- [ ] not check for identical last name, but for unique first name in the [ExternalJournalService.isEmailAvailable(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/2d787283d102bd2d107b2cc1cf4f0a1415248986/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L431) and [ExternalJournalService.isPhoneAvailable(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/2d787283d102bd2d107b2cc1cf4f0a1415248986/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L453). 
- [ ] adapt the validation messages related to already used email addresses and phone numbers to clarify the requirement that each person needs to have a unique first name.

Open question to @DraganMileski and @mariusclimedo : What happens in the following scenario? A person that shall be registered in climedo has an email address and a phone number. The phone number is already used by one person, the email address by another person.

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-01 08:39
> Open question to @DraganMileski and @mariusclimedo : What happens in the following scenario? A person that shall be registered in climedo has an email address and a phone number. The phone number is already used by one person, the email address by another person. Any additional checks necessary here?

We just discussed this. It seems that Climedo will not allow to register the person and return an according error message which will then be shown to the user in SORMAS. This should not require any changes or create any problems.

**Comment by mariusclimedo** [comment] 2021-04-16 14:00
Hi @FredrikSchaeferVitagroup What is the status here?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-16 15:10
@mariusclimedo This is not yet implemented. I hope to get this into the next sprint.

**Comment by markusmann-vg** [comment] 2021-04-22 12:23
Add a popup to inform the user that this email-adress is already used (if so) ;-)

**Comment by Candice-Louw** [comment] 2021-05-31 11:06
@FredrikSchaeferVitagroup - do you need anything additional to be able to implement this, please?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-05-31 13:02
@Candice-Louw No, it probably is ready to implement. There are just many other tickets with higher proiritization, so this ticket was moved to a future sprint (105). If you find that unappropriate, please communicate it to @markusmann-vg.

**Comment by ChristopherRiedel** [comment] 2021-06-07 12:20
Commits were cherry picked and directly committed to the hotfix branch.

**Closed** 2021-06-07 12:20 UTC
Labels: backend, change, de, hotfix, integration
