### ISSUE TITLE
[Contacts - Line listing] Date validations for 'Date of First Contact', 'Date of Last Contact' and 'Date of Report' are not triggered

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8309] opened 2022-03-09 12:21 UTC
### Bug Description

Date validations for invalid date combinations between 'Date of First Contact', 'Date of Last Contact' and 'Date of Report' are not triggered on the 'Line listing' form from the 'Contacts' directory.

### Steps to Reproduce

1. Navigate to the 'Contacts directory' and open the 'Line listing' form;
2. Input information in the mandatory fields;
3. Set the 'Date of report' to the 1th of March;
4. Set the 'Date of first contact' and 'Date of last contact' to the 9th of March;
5. Click 'Save'.

### Actual Behavior

The contact created via 'Line listing' is saved successfully and the date validation is not triggered.

### Expected Behavior

User should not be able to save the contact successfully.

Date validations should be displayed - date fields should be highlighted in red.

When hovering over the date fields highlighted in red and/or when trying to save the form, the user should see an informative note stating that 'Date of First and Last Contact have to be before or on the same day as Report date'.
 
### Screenshots

![image](https://user-images.githubusercontent.com/96909231/157440086-9ed9867b-bb58-4752-b3cc-2f850e8aa8ae.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(bb551be)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by syntakker** [comment] 2022-03-18 08:45
Duplicate of #8122.

**Closed by syntakker** 2022-03-18 08:45 UTC
Labels: bug, contacts, vaadin-app, major
