### ISSUE TITLE
Cases are not sendable after merging

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#11413] opened 2023-01-30 16:04 UTC
### Bug Description
After merging, the case who was set as "Don't share this case with the external reporting tool" can not be edited. This means that the case can not ever be send again to reporting tool.

#### Steps to Reproduce
1. Create a new case
2. Create a new case with the same data (confirm to create a new person after the message of possible dublicate appears).
3. Check for one case the checkbox "Don't share this case with the external reporting tool"
4. Click Button More --> Choose "Merge duplicates"
5. Enter report date of the created cases
6. Confirm filters --> Cases should appear
7. Choose leading case (case with the checkbox "Don't share this case with the external reporting tool")
8. Click on merge.
9. After merge check if checkbox is not editable

#### Screenshots
![image](https://user-images.githubusercontent.com/91321821/215528906-734d5790-fe03-45c6-be48-51c28bc002d9.png)

#### System Details
* Device: Laptop
* SORMAS version: 1.77.8
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior
Checkbox should be editable even if you mage cases with checkbox active.

**Comment by adinaflorea9** [comment] 2023-01-31 08:19
@AliciaRaber I the behavior described is not reproducible on SORMAS versions 1.78.0 and 1.80.0.

Would you please be able to provide more details:
1. On which exact instance were you able to reproduce this? Was it one of the release instances, was it a local environment? Or a health department instance?
2. On which version did you test, as 1.77.8 does not exist. Was it 1.77.5? Or perhaps another version?

**Comment by AliciaRaber** [comment] 2023-02-01 11:56
Hello @adinaflorea9 

I could'nt either reproduce this error in test1402 1.78.X

> 1. On which exact instance were you able to reproduce this? Was it one of the release instances, was it a local environment? Or a health department instance? I only have two tickets according to this bug.
> 2. On which version did you test, as 1.77.8 does not exist. Was it 1.77.5? Or perhaps another version?
I've checked version for ticket 2023004362 in Grafana: V 1.77.5

If bug can't reproduce in actual RC 1.78.0 and 1.80.0 than the release of the new version should solve the issue. Has to be determined afterwards.

**Comment by adinaflorea9** [comment] 2023-02-01 12:24
@AliciaRaber on which testing environment did you test where version 1.77.5 is available?

**Comment by AliciaRaber** [comment] 2023-02-01 12:31
> @AliciaRaber on which testing environment did you test where version 1.77.5 is available?

I have only tested on test1402 V 1.78.0 and was not able to reproduce the behaviour. The only indicator for this behaviour is through the tickets.
If we can ensure that the issue is fixed with any version higher than 1.77.5 than this issue is obsolete.
So my suggestion is to wait for RC 1.80.0 and test again. If test runs with desired result the issue can be closed.

**Comment by adinaflorea9** [comment] 2023-02-01 13:08
@AliciaRaber Thank you for clarifying this! 

As you have mentioned:
![image](https://user-images.githubusercontent.com/96909231/216051562-616f58e6-efa3-4554-82a3-af56e0093f6b.png)

Since on the versions higher than 1.77.5, namely, 1.78.0, 1.79.0 and 1.80.0 this behavior is not reproducible, then I will be closing the current ticket.

**Closed by adinaflorea9** 2023-02-01 13:08 UTC
Labels: bug, cases, feedback, major
