### ISSUE TITLE
🤷‍♂️ using/pasting emojis in person/comment-section >> server connection lost

### ISSUE THREAD

**Issue by SormasTheGreek** [hzi-braunschweig/SORMAS-Project#9099] opened 2022-05-06 10:32 UTC
### Bug Description
Using windows shortcut for entering emojis into the comments-section (tested on "person tab") can make the client lose connection. When pasting emojis from the clipboard its a 100% connection lost

### Steps to Reproduce
1. use or paste emojis into the comment section

### Expected Behavior
No connection loss

### System Details
* Device: Desktop-PC
* SORMAS version: 1.70.3
* Android version/Browser: Chrome (Version 100.0.4896.60 (Offizieller Build) (64-Bit))
* User Role: ?

**Comment by MateStrysewske** [comment] 2022-05-10 09:17
@SormasTheGreek Are you by any chance a user of one of the systems hosted by ITZ Bund? If so, this might be caused by those characters being blocked. @fhauptmann

**Comment by SormasTheGreek** [comment] 2022-05-10 10:01
Indeed I am, but I didnt knew that there is something being blocked. I can access emojis on my pc tho. 
Whats suspicious: I *can* add emoji into e.g. a persons name.
If I edit or paste in the comments section, it disconnects me before I can hit any save button.

**Comment by MateStrysewske** [comment] 2022-05-11 07:33
@SormasTheGreek Yes, there are known issues with using specific characters (such as emojis) in comment fields; this is currently being looked into internally, but I don't know yet what a possible solution will look like.

**Comment by MateStrysewske** [comment] 2022-05-11 07:34
I'll close this issue because we're aware of this problem and are currently discussing it.

**Closed by MateStrysewske** 2022-05-11 07:34 UTC
Labels: bug
