### ISSUE TITLE
Unsaved changes prompt triggered on event forms when geo coordinates entered

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5648] opened 2021-06-03 08:27 UTC
### Bug Description

The bug described in the issue below is reproduced in the events directory.
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3014

When an event is opened with an establishment and the geographical coordinates entered, a window requests the recording of information even though no modification has been made.

While waiting for the bug to be resolved, we will ask the technical teams to redeploy the docker image but this remains of course a short-term solution. 

thanks a lot for your help

### Steps to Reproduce
1. 
2.

### Expected Behavior
Absence of the window requesting registration when the record is not modified

### System Details

* Device:
* SORMAS version: 1.59 but probably 1.58 
* Android version/Browser: chrome
* Server URL: https://sormas.bfc-sante.fr/sormas-ui/#!about
* User Role:

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by carolinverset** [comment] 2021-06-09 09:55
@MateStrysewske @BarnaBartha @syntakker @bernardsilenou 
This bug is a bit problematic in France. since you have been working on issue #3014, maybe you have a chance to have a look? thank you so much

**Comment by bernardsilenou** [comment] 2021-06-09 18:29
@carolinverset 
Thanks for the feedback, we would investigate this further and work on it in  1.62 .
@kwa20 @VitaliHZI

**Comment by MateStrysewske** [comment] 2021-06-15 10:45
@carolinverset This should have been resolved with 1.59.0. Can you please confirm that this is indeed happening on 1.59.0 or later as well?

**Comment by carolinverset** [comment] 2021-06-15 12:11
@MateStrysewske 
I just tested in a 1.59.1 environment (docker version) and unfortunately I have this bug when browsing the event files (going from the event tab to the EP tab for example)

**Comment by ChristopherRiedel** [comment] 2021-06-23 10:34
@carolinverset I have tested this with 1.61.0 and 1.59.2 and I cannot reproduce this.

**Comment by carolinverset** [comment] 2021-06-23 15:53
@ChristopherRiedel 
We had already encountered this problem with cases. This bug only occurs on French servers because the geographic coordinates are indicated with a comma (xx, xx) and not a point (xx.xx) as in other countries (Germany for example).
Below is a comment from @ftavin which exposes the solution that was found but which is not satisfactory in the long term.

https://github.com/hzi-braunschweig/SORMAS-Project/issues/3014#issuecomment-762042997

**Comment by ChristopherRiedel** [comment] 2021-06-24 06:06
@carolinverset I talked a lot with @MateStrysewske about it and he told me how to reproduce it (changing the locale on my system etc.) and the error doesn't occur on my system.

**Comment by MateStrysewske** [comment] 2021-06-24 06:47
@carolinverset Germany uses the same decimal separators as France :) we reproduced this in the past, including for the event form, and even fixed it in #5039 which is why I'm confused that it still happens for you.

**Comment by carolinverset** [comment] 2021-06-24 06:57
@MateStrysewske @ChristopherRiedel 
Thank you for your answers ... I will redo a series of tests very quickly. I hope not to have made a bad manipulation which would have misled me and led to remake a tocket on the github. I will tell you again as soon as possible. thank you for everything

**Comment by BarnaBartha** [comment] 2021-09-08 08:24
No longer reproducible was fixed in #5039 with the solution from #3014

**Closed by BarnaBartha** 2021-09-08 08:24 UTC
Labels: bug, events, vaadin-app, fr, minor
