### ISSUE TITLE
Add variant specific Nucleic acid detecion methods [2]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#5029] opened 2021-04-09 10:44 UTC
### Situation Description
In Germany, testing procedures are adapted to the circumstances due to the Covid mutations. Therefore, these procedures should be supplemented. For this it is important to move the mutation field into the sample part. 

### Feature Description

- [ ] when _PCR/RT-PCR_ selected, a new field should appear next to it with the following choices: 
       - Variant specific PCR
       - PCR-detection of the mutation "N501Y"
- [ ] only show the subsequent drop-down field when COVID is selected as the tested disease
- [ ] Add disease variant to pathogen test and either link it to the old place at the case but do not make it editable on the case overview
- [ ] Take the informations from the Lab Message (DEMIS) aswell 
- [ ] Add this for Germany only 

### Additional Information
![Proben ergänzung](https://user-images.githubusercontent.com/78568406/114168843-17ff8100-9931-11eb-8004-33342059f648.JPG)

### Development Specifications
(The additions are NOT Germany-specific)
* Add a new `pcrTestSpecification` field to PathogenTests (varchar(255); caption: "PCR/RT-PCR test specification")
* Add a `PCRTestSpecification` enum with the following values:
    * VARIANT_SPECIFIC
    * N501Y_MUTATION_DETECTION
* Add the new field to the sample creation and pathogen test forms and fragments; only show the field when tested disease = CORONAVIRUS and test type = PCR_RT_PCR
* Add a `diseaseVariant` field to PathogenTests (similar to the already existing field in Case)
* Add the new field to the sample creation and pathogen test forms and fragments next to the tested disease field (similar logic to the case forms)
* When a POSITIVE pathogen test with confirmed by supervisor = YES with a disease variant != the disease variant of the case is saved, display a popup message that asks the user to update the disease variant of the case: "You have saved a positive pathogen test of a different disease variant than the variant specified in the case. Do you want to update the disease variant of the case?" - options "Yes" and "No"

@FredrikSchaeferVitagroup Can you add instructions on how to extend the sample creation process when processing lab messages to also include these new fields if that's possible?

**Comment by kwa20** [comment] 2021-04-09 10:54
Something I would add:

- only show the subsequent drop-down field when COVID is selected as the tested disease

**Comment by MateStrysewske** [comment] 2021-04-09 12:19
Questions:
* Is renaming the test type to Nucleic acid amplification fine for all other diseases we have in the system as well?
* Why do we need this new field with those two choices? Can't that be fully generated based on the selected disease variant?

**Comment by bernardsilenou** [comment] 2021-04-09 12:36
Comments:
* Nucleic acid amplification is the technical name but short form often used by lab users in the field is PCR. I would suggest we just  translate PCR to Nucleic acid amplification on DE instance. 
* The lab management is another part that we have been trying to keep it general and not disease specific. Reason being that a test like PCR can be done on any  disease as long as the causative agent has a DNA.
*  Since this is not a bug and we already have many similar issues on the changes to the lab management, it would be good if we refine this changes under refinements of the lab management module.

**Comment by JaquM** [comment] 2021-04-09 12:43
@bernardsilenou  @MateStrysewske 
We need to have these enums for SurvNet. So if you don't want to add the extra field, include them in "Type of Test" and make this German only.
Please do the disease variant part anyway.

**Comment by MateStrysewske** [comment] 2021-04-09 13:52
@JaquM That's why my question was whether this information can be generated based on the selected disease variant. The two value of this new field are basically "variant N501Y" and "selected variant", which is pretty much redundant in my eyes. Shouldn't the SurvNet converter be able to map the disease variant specified in the pathogen test to one of these two values?

**Comment by kwa20** [comment] 2021-04-09 15:35
@bernardsilenou I agree that this is the approach we need to pursue in the long run but I'm not sure about the best and easiest solution yet.

@MateStrysewske That's what the converter already does but there apparently have been complaints that this isn't enough. Apparently, the two subsequent values are test methods.

**Comment by MateStrysewske** [comment] 2021-04-12 07:46
@kwa20 And there are other test methods as well that aren't part of this list?

**Comment by kwa20** [comment] 2021-04-13 08:09
@MateStrysewske Thus far, only the two subsequent values exist.

**Comment by MateStrysewske** [comment] 2021-04-13 08:15
@kwa20 Okay, so I still don't really understand why the current mapping isn't sufficient

**Comment by JaquM** [comment] 2021-04-13 08:19
The current selection gives information that is not available. If you have the evidence of N501Y, no statement can be made about the actual variant. Therefore, the selection is relevant.

The variant field should be updated, but in my opinion not editable but thats less important than the fields for me.

**Comment by kwa20** [comment] 2021-04-13 08:20
@MateStrysewske The problem we have is that the method field is only mapped, when the corresponding variant has been entered. Often enough however, the PCR method to narrow down variants has already been completed and reported before the sequencing has been finalized to determine the exact variant. During that time, this information is not available since it cannot be mapped.

**Comment by MateStrysewske** [comment] 2021-04-13 08:31
@kwa20 But if you're entering a PCR test result, that test will have been done specifically based on a specific variant, right? So`shouldn't whoever documents the test put in the disease variant that the sample has been tested for?

@JaquM Is N501Y not an official variant that is present in the database?

**Comment by MateStrysewske** [comment] 2021-04-13 08:31
Ah nvm, just figured out that N501Y is a mutation that can be present in three individual variants. That makes more sense to me.

**Comment by MateStrysewske** [comment] 2021-04-13 08:35
I can see the necessity of this field now. An additional question: If we add the disease variant to pathogen tests, that should probably impact the logic that asks users to confirm the case if a laboratory result of the same disease as the case is positive. I suppose that this prompt should pop up independent of the variant, but if the user saves a positive pathogen test of a different variant than the one that's specified in the case, we should probably update the disease variant of the case as well, right?

**Comment by JaquM** [comment] 2021-04-13 08:56
@MateStrysewske Yes please

**Comment by bernardsilenou** [comment] 2021-04-13 10:21
@MateStrysewske @JaquM @kwa20 
- I am still not clear with this need.
- If I understand you well, the users want to document the mutation (501Y) in the variant. By knowing the variant we already know the mutations, then whey document what we already know?
- If the goal is to map the mutations, then users can document the variant and we can then map all possible mutations
- We can build a table in the db with mutations for all the variants and use for mapping.

**Comment by bernardsilenou** [comment] 2021-04-13 10:25
> The current selection gives information that is not available. If you have the evidence of N501Y, no statement can be made about the actual variant. Therefore, the selection is relevant.
> 
> The variant field should be updated, but in my opinion not editable but thats less important than the fields for me.

@JaquM Is this possible that their lab test is limited to know the exact variant but can only know the mutations?
If yes, then then it make sense to add another variable to capture mutations, but this variable should have multiple options, right?

**Comment by MateStrysewske** [comment] 2021-04-15 10:27
@JaquM I've added development specifications to the initial issue description, are you fine with them/did I miss something?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-04-15 13:15
> @FredrikSchaeferVitagroup Can you add instructions on how to extend the sample creation process when processing lab messages to also include these new fields if that's possible?

- [ ] The labMessageDto and -Entity need to be extended by a `testPcrTestSpecification` field holding the enum value `PCRTestSpecification`
- [ ] In the demis-adapter, the value needs to be extracted from a DEMIS-Notification. For this we need to know where this information is stored. [This](https://confluence-demis.gematik.de/download/attachments/76579105/image2021-2-17_15-1-19.png?version=1&modificationDate=1613570479862&api=v2) and [this](https://simplifier.net/covid-19labormeldung/laboratorytestsarscov2) information indicates to me that the values might be extracteable from the Observation.code.coding.code (because the valueSet seems to be used there according to [this](https://simplifier.net/covid-19labormeldung/pathogendetectionsarscov2)). We need @kwa20 or @JaquM to provide a confirmation and the mapping though (e.g. code `94307-6` = VARIANT_SPECIFIC or something like that). 
- [ ] The value needs to be transferred from the labMessageDto to newly created or selected PathogenTest when processing a labMessage
- [ ] (ideally the existing unit tests in the adapter need to be extended to also consider the new field).

**Comment by bernardsilenou** [comment] 2021-04-15 13:17
@MateStrysewske @JaquM 
- Adding this single point only is also very important to international instance. Suggest not to make it DE only.
- ` Add disease variant to pathogen test and either link it to the old place at the case but do not make it editable on the case overview`
- Additional refinement: 
     *  Add disease variant (same as on case) to pathogen test
     * Map the disease variant from pathogen tests of sample to that of cases of the sample if variant of pathogen test apply to the disease.  Make it non editable if recorded in the pathogen test.
     * If non of the samples of the case has  any of the disease variant of the case, then is should be possible to edit the disease variant of the case only, but not map it back to the pathogen test. This is needed because not all instances document lab results in SORMAS but need to document the variant.
     *  OR: If any of the pathogen tests of the samples of the case has  a disease variant but different from that of the case, we do not pat the variant to the case and user van edit variant of case.
- Is this refinement fine for DE also?

**Comment by kwa20** [comment] 2021-04-15 13:55
> When a POSITIVE pathogen test with confirmed by supervisor = YES with a disease variant != the disease variant of the case is saved, display a popup message that asks the user to update the disease variant of the case: "You have saved a positive pathogen test of a different disease variant than the variant specified in the case. Do you want to update the disease variant of the case?" - options "Yes" and "No"

I'd like to go with Maté's specification because I think it reduces potential problems we could have if we make the field uneditable through logic.

**Comment by bernardsilenou** [comment] 2021-04-15 15:53
@kwa20  @JaquM  I also agree with this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/5029#issuecomment-820441359
- My question is that if there is no pathogen test having a variant recorded, then users should be able to record it directly to the case. If this fine by you? This is what they are already doing now.
- ie editable when NA and non-editable when lab test  variant is not NA
- There are instances that that do not use sormas to document sample and test results, but still want to know about the variant, reason why it was added to the case in the first place. Thus forcing users to always create sample and test would not be user friendly.

**Comment by kwa20** [comment] 2021-04-15 16:05
@bernardsilenou just scratch the non-editable. It would follow the same logic as we have for final laboratory test result

**Comment by bernardsilenou** [comment] 2021-04-15 16:12
@Whats the final summary pls?
- We show the variables + logic as long as the disease has a variant in system, NOT  when disease == COVOD, right? 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/5029#issuecomment-816599783

**Closed** 2021-04-21 11:48 UTC
Labels: android-app, backend, feature, important, laboratory, vaadin-app

**Comment by kwa20** [comment] 2021-04-22 07:12
I've noticed that the prompt to update the variant of the case if another variant was entered in the pathogen test result is not triggered when a lab message is processed.

Steps to reproduce:
1. Process a lab message
2. Get to the point of selecting an existing sample
3. Enter a pathogen test result that has a different variant than the previously chosen case, save.

**Comment by AndyBakcsy-she** [comment] 2021-04-22 17:39
Validated the web implementation on the latest version of sormas 1.60.0-snapshot
