### ISSUE TITLE
contact detail view shows blank page

### ISSUE THREAD

**Issue by RobYed** [hzi-braunschweig/SORMAS-Project#3215] opened 2020-10-19 07:06 UTC
I am currently testing the SORMAS PIA integration within the Sormas-SB-Schweiz Develop stage.

Today and also last thursday (15.10.) I only got a blank page (menu and header still showing) after clicking on any contact within the contacts overview (https://sb-ch.sormas.netzlink.com/sormas-ui/#!contacts/?dateFilterOption=DATE). I did nothing special. Logged in with user "ContSup", clicked on "Kontakte" and then on any contact id.

I also cannot see any warn or error logs within the dev tools.

Interestingly everything worked fine at friday (16.10.).

This issue currently is a blocker for testing a PIA story. Would be nice to get some help here. Thanks 😃

**Comment by MateStrysewske** [comment] 2020-10-19 08:34
Duplicate of #3214

**Closed by MateStrysewske** 2020-10-19 08:34 UTC
