### ISSUE TITLE
Mobile App fails to synchronize with server after manual update

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7499] opened 2021-12-12 09:13 UTC
### Bug Description
1.	Normally, following a new release, opening the mobile app should prompt a user to update (i.e., auto-update alert). The app detected that there was a new version on the server and asked the user to update. However, the app tried to auto-update and failed, presenting the same pop-up window asking the user to update.
2.	If the auto-update does not work (as in the present situation), the next solution is that the user can manually download the .apk file and install the latest version to override the old version.  In this case, re-installation was successful and the new version of the app was installed on the mobile device, and the app remained connected to the server (i.e., the user does not manually type in the server url) and the user remain logged in. This is the expected result but even with the new version of the app on the mobile device, the mobile app could not synchronize with the server.
3.	When the app was completely uninstalled and a new version installed + setting the url of server + login, the app worked fine. 

### Steps to Reproduce
1.	Install version 1.66.1 on the mobile app + login with a surveillance officer account and connect to a server on the same 1.66.1
2.	Synchronize to make sure that all works fine
3.	Upgrade the server to 1.66.2 (or higher)
4.	Check if mobile app could auto-update and synchronize
5.	If auto update fails, keep the old version with the user logged in + Install new version from .apk. Check that user is not logged out and the new version is installed on the mobile app.
6.	Check if new version of app works fine.

### Expected Behavior
Auto-update and manual-update should synchronize with the server just as a fresh (new) setup.

### System Details

* Device: Android
* SORMAS version:1.66.2
* Android version/Browser: 11, Knox API level 33
* Server URL: https://release-international.sormas.netzlink.com/sormas-rest/
* User Role: Surveillance officer contact officer

**Comment by BasilKaburi** [comment] 2021-12-12 09:23
@JaquM @kwa20 For your updates

**Comment by MateStrysewske** [comment] 2021-12-13 08:07
@BasilKaburi Do you have logs from the mobile app that you could send us? It's possible that the problems are related to actual data on the server and that we can't reproduce it locally, so that would be very helpful.

**Comment by MateStrysewske** [comment] 2022-01-10 13:52
@BasilKaburi Any update?

**Comment by BasilKaburi** [comment] 2022-01-10 15:06
@MateStrysewske: As discussed earlier, I'm not familiar with android studio from which log files are retrieved. If you are able to help further, I will come over with my device so we retrieve them together. Thanks!

**Comment by bernardsilenou** [comment] 2022-01-11 15:41
@MateStrysewske 
We did the test as described in this issue on https://release-international.sormas.netzlink.com/:
1. App could sych after the new version  1.66.2 was manually installed 
2. Auto-update from 1.66.1 to 1.66.2 failed. Attached are the logs from the tablet (Samsung Galaxy Tab A, A11, KNOX API level 33)
[autoUpdateFailLogs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7847844/autoUpdateFailLogs.txt)

**Comment by MateStrysewske** [comment] 2022-01-12 08:30
@bernardsilenou The auto-update will continue to fail on the Netzlink servers, there's nothing I see we can do about it right now. What I'm interested in in the context of this issue is whether the issue that the synchronisation no longer works after automatically OR manually updating to a newer version still persists.

**Comment by bernardsilenou** [comment] 2022-01-12 10:57
@MateStrysewske 
Manual update works well now. 
Since the auto-update is out of scope for this issue, I would close the issue now.

**Closed by bernardsilenou** 2022-01-12 10:57 UTC
Labels: bug, android-app, technology, feedback
