### ISSUE TITLE
Extend facilities infrastructure

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3390] opened 2020-11-04 17:13 UTC
### Situation Description
Recently, facility fields have been added to the person forms and are now associated to addresses. When selecting a facility in the address section that has previously been entered in the facility infrastructure data, addresses still have to be entered each time the facility is selected. It would reduce the entry effort immensely when addresses could be deposited for facilities as part of the infrastructure data. The deposited data should then be adopted in respective address fields.
### Feature Description
The data that can be provided as part of the facility infrastructure data could be extended to include addresses. This would require additional fields in the facility creation form, import template and columns in the facilities configuration overview.

- Add address fields to facilities creation/edit form

- Add address field additions as columns in the facilities configurations overview excluding area type

- add address fields in the import template and export file

- adopt deposited addresses in respective fields when a deposited facility is selected. These include home address and addresses on person forms (cases, contacts, event participants) plus the event location. (#3394) 

### Additional Information
<img width="414" alt="Screen Shot 2020-11-04 at 4 39 20 PM" src="https://user-images.githubusercontent.com/70317594/98143088-f523f900-1ec8-11eb-9bb0-dbc26b415472.png">
<img width="779" alt="Screen Shot 2020-11-04 at 5 06 29 PM" src="https://user-images.githubusercontent.com/70317594/98143103-f9e8ad00-1ec8-11eb-985e-aca95ffdd7c5.png">
<img width="1105" alt="Screen Shot 2020-11-04 at 6 03 36 PM" src="https://user-images.githubusercontent.com/70317594/98143120-fe14ca80-1ec8-11eb-8d7c-5d29208a0df0.png">

**Comment by ChristopherRiedel** [comment] 2020-11-05 08:35
@kwa20 Normally this would be a duplicate of #2509.
Since this issue is way more detailed I've closed #2509.

The following shouldn't be part of this issue because it's such a big thing itself 
> * adopt deposited addresses in respective fields when a deposited facility is selected. These include home address and addresses on person forms (cases, contacts, event participants) plus the event location. This should also apply when entering facilities in creation forms.

**Comment by kwa20** [comment] 2020-11-05 08:56
@ChristopherRiedel I'll create a separate issue for the address adoption and link it to this one as a second step.

**Comment by kwa20** [comment] 2020-11-24 10:16
@ChristopherRiedel It would also make sense to provide the function to generate geo coordiantes with the geo button since facilities are also shown and can be filtered by on the case status map. I don't know how difficult that would be to consider in this issue. Otherwise I could create a separate issue with this one as the prerequisite.

**Comment by markusmann-vg** [comment] 2020-11-26 12:42
**out of scope:**

- adopt deposited addresses in respective fields when a deposited facility is selected. These include home address and addresses on person forms (cases, contacts, event participants) plus the event location. => as it is treated in (#3394)

**Comment by Lucas-Walter-GA-Tuebingen** [comment] 2021-01-07 09:26
this is an issue for us aswell. 

Additional the phone number of the institution and the possibility to add an email adress for contact should be useful for the end user.

**Comment by kwa20** [comment] 2021-01-07 09:50
@Lucas-Walter-GA-Tuebingen Thanks for the feedback, I agree that this will be very useful. I would create another Issue for adding "facility contact information" as infrastructure data and additional fields in respective entities. 

Just to clarify, this would merely be a general phone number and email address of the facility without an additional person information.

**Comment by Lucas-Walter-GA-Tuebingen** [comment] 2021-01-07 11:06
@kwa20 Yes exactly. Thank you alot for creating this issue.

**Comment by MateStrysewske** [comment] 2021-01-29 13:22
This is currently taken care of in #4027

**Closed by MateStrysewske** 2021-01-29 13:22 UTC
Labels: feature, refine
