### ISSUE TITLE
Dashboard: Deads are still shown deads, even after editing to "recovered"

### ISSUE THREAD

**Issue by Mimsel** [hzi-braunschweig/SORMAS-Project#1807] opened 2020-04-14 14:35 UTC
### Bug Description
In the dashboard, dead persons are still shown as dead persons, even after ediditing.

### Steps to Reproduce
1. Generate a case, only enter with *-marked variables and with Outcome as "deceased"
2. Change from "deceased" to "recovered"

### Expected Behavior
In the dashboard, the person who was deceased before should not be counted as dead anymore.

### Screenshots
![image](https://user-images.githubusercontent.com/63415956/79236979-ec58d080-7e6d-11ea-847f-33f639a49ca6.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-04-15 09:04
Duplicate of #1792

**Closed by MateStrysewskeSym** 2020-04-15 09:04 UTC
Labels: bug
