### ISSUE TITLE
Untranslated captions  for events and symptoms,

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2209] opened 2020-05-28 18:47 UTC
### Steps to Reproduce
1. log on .symeda server
2. create an event, symptom, ,,,

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/83180770-3519cf80-a124-11ea-82bc-761864db13c6.png)

![image](https://user-images.githubusercontent.com/12996724/83180853-537fcb00-a124-11ea-9dca-51ce79f4485c.png)

### System Details
* Device:
* SORMAS version:1,41,0
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-05-29 06:01
Duplicate of #2198

**Closed by MateStrysewskeSym** 2020-05-29 06:01 UTC
Labels: bug
