### ISSUE TITLE
To develop flexible outbreak source investigation module

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#793] opened 2018-09-21 07:55 UTC
We will contact experts in outbreak source investigation and together design this module in SORMAS. Low priority for now.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-09-24 05:11
@bernardsilenou I think this is a duplicate of #389 . Right?

**Closed** 2018-10-08 09:41 UTC
Labels: duplicate
