### ISSUE TITLE
Date validations don't prevent saving erroneous entries and are sometimes misleading

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4928] opened 2021-03-28 17:49 UTC
### Bug Description
Date validations don't prevent the user from saving erroneous data and are sometimes misleading. Examples are validations for vaccination fields and stay in ICU fields with the addition of admission date. Dates that are in the future can be saved regardless of the error message. When adjusting the date period, the error display remains, when one field was edited.
### Steps to Reproduce
1. Go to hospitalizations 
2. Enter a stay in ICU start date and then an end of stay date that lies in the future.
3. Save the hospitalization
4. Enter dates where the end date is before the start date
5. Change one of the dates so the entry is logical
6. Check the other entry
7. Do the same with the admission date and first/last vaccination date

### Expected Behavior
If the date entry is erroneous, users should be able to save it. If the date period gets corrected to a logical entry, error messages should no longer be displayed.
### Screenshots
**Saving erroneous entry:**
(current date 3/28/2021)
<img width="717" alt="Screen Shot 2021-03-28 at 7 37 26 PM" src="https://user-images.githubusercontent.com/70317594/112762238-e1576b80-8ffe-11eb-8bf8-1a70a0e61b07.png">

**Stay in ICU**
Initial entry:

<img width="473" alt="IcuDateValidation" src="https://user-images.githubusercontent.com/70317594/112762039-16af8980-8ffe-11eb-9b85-349d8b7b2638.PNG">

Change:

<img width="474" alt="IcuDateValidation2" src="https://user-images.githubusercontent.com/70317594/112762042-1911e380-8ffe-11eb-87b5-e0a2a2ebe72f.PNG">

**admission and ICU**
Initial entry:

<img width="371" alt="IcuDateValidation3" src="https://user-images.githubusercontent.com/70317594/112762043-1b743d80-8ffe-11eb-8761-661ea533f9cd.PNG">

Change:

<img width="357" alt="IcuDateValidation4" src="https://user-images.githubusercontent.com/70317594/112762044-1d3e0100-8ffe-11eb-8542-134e251e74a5.PNG">

**Vaccination dates**
Initial entry:

<img width="438" alt="vaccinationDateValidation" src="https://user-images.githubusercontent.com/70317594/112762118-6b530480-8ffe-11eb-97a9-f05d390baa8d.PNG">

Change:

<img width="440" alt="vaccinationDateValidation2" src="https://user-images.githubusercontent.com/70317594/112762120-6d1cc800-8ffe-11eb-97e5-e9a55c3b8f62.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by DavidBaldsiefen** [comment] 2021-04-05 13:57
This is related to / duplicate of #4651

**Closed** 2021-04-15 11:08 UTC
Labels: bug, general, vaadin-app

**Comment by StefanKock** [comment] 2021-04-16 08:33
Was about symtoms and hospitalizations

**Comment by AndyBakcsy-she** [comment] 2021-04-19 19:31
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment.
