### ISSUE TITLE
assignee filter in the lab message directory is reset after processing a lab message

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#8799] opened 2022-04-12 09:44 UTC
### Bug Description

If I set the filter on "Assignee" to "Unassigned" under Samples -> Lab Messages, I can subsequently assign some lab messages to myself for processing in bulk mode. If I now change the filter "Assigned to" to me ,i also see these lab messages assigned to me. However, as soon as I have processed the first one, the filter jumps back to "Not assigned".
### Steps to Reproduce

1. set the filter "assignee" to "unassigned"
2. enter bulk mode
3. assign lab messages to yourself
4. process one of the lab messages
5. after coming back to lab message directory the filter jumps back

### Expected Behavior

filter should stay 
### System Details

* Device:
* SORMAS version: 1.70.2
* Android version/Browser:
* Server URL:1402
* User Role:admin, nat user

**Comment by adinaflorea9** [comment] 2022-04-18 07:37
Tried to reproduce the issue with @cazacmarin; the steps to reproduce from the bug report were not complete.

The issue is reproducible with the following steps:

Steps to Reproduce
1. Navigate to the 'Samples' directory - 'Lab messages' tab and set the "Assignee" filter to "Unassigned";
2. Enter bulk mode and select a couple of unprocessed lab messages;
3. From bulk actions select 'Edit assignee' and choose 'Assign to me';
4. **Edit the 'Assignee' filter and select from the dropdown the user that you are logged in with (the user that the lab messages were assigned to at step 3);**
5. Process one of the lab messages;
=>after coming back to 'Lab messages' tab, the filter jumps back to 'Unassigned' instead of the selection made at step 4.

**Closed** 2022-04-21 06:24 UTC
Labels: bug, laboratory, vaadin-app, major

**Comment by abrudanancuta** [comment] 2022-04-25 08:58
Validated on local environment with the version: 1.71.0-SNAPSHOT (2372c23)
