### ISSUE TITLE
System becomes extremely slow when other diseases are turned off

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3404] opened 2020-11-05 14:52 UTC
### Bug Description
Since France uses only the covid module in sormas for now, we though it would be good to deactivate the other diseases and hoping to gain in performance.
When we did this, then system was very slow, takes about 5 min to open a page.

### Steps to Reproduce
1.  UPDATE diseaseconfiguration SET active = false WHERE disease != ‘CORONAVIRUS’;
2.

### System Details
* Device: 
* SORMAS version: 1.50
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment] 2020-11-05 14:53
@fhauptmann

**Comment by MateStrysewske** [comment] 2020-11-06 08:34
I'd be very surprised if turning off diseases would be related to performance problems. @MartinWahnschaffeSymeda can you think of any explanation for this behaviour?

**Comment by bernardsilenou** [comment] 2020-11-06 08:37
We finally activated all the diseases back

**Comment by MartinWahnschaffeSymeda** [comment] 2020-11-06 08:58
Which page took 5 minutes to open? Was it the dashboard or the cases directory or something else?

**Comment by bernardsilenou** [comment] 2020-11-06 09:27
At log in state, thus the dashboard. We waited for more than 5 min but system could not open and decided to turn it off and activated the diseases. @TomHutter was also surprised and he suggested that we can change the default landing page not to fall on the dashboard but on the case directory or any other page that load easily.

**Comment by MartinWahnschaffeSymeda** [comment] 2020-11-10 08:23
We will have to investigate on this.

**Comment by MateStrysewske** [comment] 2020-11-16 08:52
@bernardsilenou Do they have a problem with the performance in the WHOLE system or only on the dashboard? If it's only on the dashboard and they have a lot of cases with geo coordinates, I think the problem is that the dashboard tries to load the map markers for all these cases, which takes a lot of time. The reason why this didn't happen before, when all diseases were active, is that AFP is automatically selected as the first disease then and they don't have any AFP cases in the system.

They can check this by activating all diseases again and then selecting Covid-19 in the disease carousel layout on the dashboard; it should then again take as long to load as it takes them when the other diseases are deactivated.

If this is the problem, it's fixed in 1.51.0 because we added logic that doesn't automatically display the map markers if there are too many.

**Comment by bernardsilenou** [comment] 2020-11-16 09:11
@MateStrysewske  I can not tell because we waited for a very long time but could not login to the system after entering user name and password. Our hypothesis was that since the login page falls on dashboard, then  the cause can be the dashboard.

Your point on AFP and recommendations are very vital.
The idea of changing the landing page to a simple repository like case directory may be a good idea. In order to test what you proposed, I think we need to upgrade to 1,51 first because with the current version, we are unable to login.

**Comment by bernardsilenou** [comment] 2020-11-16 12:17
@MateStrysewske This is the result of the testing Annick did.
Maté's analysis matches what we found.
I timed the accesses:
- "Antrax" or "FHV" dashboard: 6 seconds
- Covid dashboard: more than 10 minutes => the display was not successful

**Comment by MateStrysewske** [comment] 2020-11-16 12:19
@bernardsilenou Okay, that means that updating to 1.51.0 will resolve the problems in terms of the dashboard being able to load again. However, they will not be able to use the map component (which is very likely the reason for the dashboard not loading in the first place). We need to find solutions to drastically improve the performance of the map component.

**Comment by MateStrysewske** [comment] 2020-11-18 13:06
The main fix for this was done in #3167

**Closed by MateStrysewske** 2020-11-18 13:06 UTC
Labels: bug, performance
