### ISSUE TITLE
Error when erasing a case or a contact (french language)

### ISSUE THREAD

**Issue by OlivierLeuci** [hzi-braunschweig/SORMAS-Project#2342] opened 2020-06-18 08:47 UTC
### Bug Description
When we try to erase a case (with the right user profile to do this), we have an error message and the action is canceled.

### Steps to Reproduce
1.Choose a case or a contact an edit it
2.Click on Erase at the end of the form

### Expected Behavior
To be able, for users with the good rights to erase a case or a contact.

### Screenshots
![image](https://user-images.githubusercontent.com/66824660/84998393-0e155300-b150-11ea-87ba-8ddd059790f7.png)

### System Details
* Device: Desktop Computer
* SORMAS version: 1.42.3
* Browser: Chrome Version 83.0.4103.106 (Build officiel) (64 bits) but its also the case with different other web browser (Firefox, Edge, ...)

**Comment by bernardsilenou** [comment] 2020-06-18 12:26
@OlivierLeuci  @MateStrysewskeSym  I tried on many servers and could not reproduce the error, only to realize that it happens when the language setting if French only. 
@OlivierLeuci  Please change the language to English and see if you get the same error.
@MateStrysewskeSym  set language to Français on symeda server and error pups up.

**Comment by OlivierLeuci** [comment] 2020-06-18 12:27
Hello Bernard,

Ok I’ll try ASAP.

BR

Olivier


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D6457C.A22E68A0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D6457C.A22E68A0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D6457C.A22E68A0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D6457C.A22E68A0]

03.81.53.21.23

[cid:image006.png@01D6457C.A22E68A0]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 18 juin 2020 14:26
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci> @MateStrysewskeSym<https://github.com/MateStrysewskeSym> I tried on many servers and could not reproduce the error, only to realize that it happens when the language setting if French only.
@OlivierLeuci<https://github.com/OlivierLeuci> Please change the language to English and see if you get the same error.
@MateStrysewskeSym<https://github.com/MateStrysewskeSym> set language to Français on symeda server and error pups up.

**Comment by OlivierLeuci** [comment] 2020-06-18 12:31
Bernard,

You’re right, it’s a bug when I’m in french configuration. We don’t have any problem with a previous version.

@MateStrysewskeSym<https://github.com/MateStrysewskeSym> if you need, we can provide a log access to our servers for you If you need.

Thanx for your reply.

BR


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D6457D.2A6DB630]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D6457D.2A6DB630]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D6457D.2A6DB630]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D6457D.2A6DB630]

03.81.53.21.23

[cid:image006.png@01D6457D.2A6DB630]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 18 juin 2020 14:26
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci> @MateStrysewskeSym<https://github.com/MateStrysewskeSym> I tried on many servers and could not reproduce the error, only to realize that it happens when the language setting if French only.
@OlivierLeuci<https://github.com/OlivierLeuci> Please change the language to English and see if you get the same error.
@MateStrysewskeSym<https://github.com/MateStrysewskeSym> set language to Français on symeda server and error pups up.

**Comment by OlivierLeuci** [comment] 2020-06-18 12:37
Bernard,

Ich habe nur getestet, wir haben keine probleme mit der deutschen oder italienischen Sprache (viele danke Google 😊)

BR


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D6457D.EC86BCD0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D6457D.EC86BCD0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D6457D.EC86BCD0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D6457D.EC86BCD0]

03.81.53.21.23

[cid:image006.png@01D6457D.EC86BCD0]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 18 juin 2020 14:26
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci> @MateStrysewskeSym<https://github.com/MateStrysewskeSym> I tried on many servers and could not reproduce the error, only to realize that it happens when the language setting if French only.
@OlivierLeuci<https://github.com/OlivierLeuci> Please change the language to English and see if you get the same error.
@MateStrysewskeSym<https://github.com/MateStrysewskeSym> set language to Français on symeda server and error pups up.

**Comment by bernardsilenou** [comment] 2020-06-18 13:04
Dear Olivier,

Pas souci

________________________________

**Comment by OlivierLeuci** [comment] 2020-06-18 13:07
Bernard,

Do I put a comment on the #2342 Issue to give to new precision that it’s just in FR that the error arrives ?

BR


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D64582.34B795C0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64582.34B795C0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64582.34B795C0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64582.34B795C0]

03.81.53.21.23

[cid:image006.png@01D64582.34B795C0]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 18 juin 2020 15:05
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)

Dear Olivier,

Pas souci

________________________________

**Comment by bernardsilenou** [comment] 2020-06-18 13:12
No all is fine, Maté will take care of it. Thanks

**Comment by StefanKock** [comment] 2020-06-19 05:48
The translation has to contain a `%s` as placeholder. `%d` is supposed to be for numbers. 
```
confirmationDeleteEntity = Are you sure you want to delete this %s? This action can not be reversed.
```

It seems that #2139 has popped up again. I think the downstream merge from Crowdin is the problem, because my fix was deleted by a later merge.

Solution: Provide a proper translation for `confirmationDeleteEntity` via Crowdin with `%s` as placeholder and then this has to be merged to the project.

**Comment by MateStrysewskeSym** [comment] 2020-06-19 06:50
@bernardsilenou Please take care of this and notify us once it's done. Thanks!

**Comment by OlivierLeuci** [comment] 2020-06-19 07:02
Hello,

I pick up an account to Crowdin but I need to be approved to contribute.

Is it possible to someone to manage my approval and I’ll give you ASAP another account to approve

Thank you.


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D64618.58137D40]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64618.57F59500]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64618.57F59500]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64618.57F59500]

03.81.53.21.23

[cid:image006.png@01D64618.57F59500]

olivier.leuci@esante-bourgogne.fr



De : StefanKock <notifications@github.com>
Envoyé : vendredi 19 juin 2020 07:49
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


The translation has to contain a %s as placeholder. %d is supposed to be for numbers.

confirmationDeleteEntity = Are you sure you want to delete this %s? This action can not be reversed.

It seems that #2139<https://github.com/hzi-braunschweig/SORMAS-Project/issues/2139> has popped up again. I think the downstream merge from Crowdin is the problem, because my fix was deleted by a later merge.

Solution: Provide a proper translation for confirmationDeleteEntity via Crowdin with %s as placeholder and then this has to be merged to the project.

**Comment by ChristopherRiedelSymeda** [comment] 2020-06-19 12:03
@OlivierLeuci 
At present there is no uniform way to be approved. Please contact the HZI.
Maybe @fhauptmann can also help you directly otherwise.

**Comment by bernardsilenou** [comment] 2020-06-19 12:27
@OlivierLeuci  your are invited to translate French, please let us know if all went fine.

**Comment by hzi-old** [comment] 2020-06-19 12:31
@OlivierLeuci 
Hi, My name is @danieltomaba , I have approved you. 
![575C5AC2-6CE4-4A82-B4D9-E5E65F88DDDE_1_105_c](https://user-images.githubusercontent.com/19344651/85132675-4166e900-b207-11ea-808c-8a97cfd27905.jpeg)

**Comment by OlivierLeuci** [comment] 2020-06-19 12:33
Thank you,

Now I must find the good item in the files of Crowdin.

Is there a search engine to explore the files ?


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D64646.914FF600]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64646.914FF600]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64646.914FF600]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64646.914FF600]

03.81.53.21.23

[cid:image006.png@01D64646.914FF600]

olivier.leuci@esante-bourgogne.fr



De : Sormas-open <notifications@github.com>
Envoyé : vendredi 19 juin 2020 14:32
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci>
Hi, My name is @danieltomaba<https://github.com/danieltomaba> , I have approved you.
[575C5AC2-6CE4-4A82-B4D9-E5E65F88DDDE_1_105_c]<https://user-images.githubusercontent.com/19344651/85132675-4166e900-b207-11ea-808c-8a97cfd27905.jpeg>

**Comment by OlivierLeuci** [comment] 2020-06-19 12:33
Oups….

Best regards Sir 😊



Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D64646.9A935450]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64646.9A935450]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64646.9A935450]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64646.9A935450]

03.81.53.21.23

[cid:image006.png@01D64646.9A935450]

olivier.leuci@esante-bourgogne.fr



De : Sormas-open <notifications@github.com>
Envoyé : vendredi 19 juin 2020 14:32
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci>
Hi, My name is @danieltomaba<https://github.com/danieltomaba> , I have approved you.
[575C5AC2-6CE4-4A82-B4D9-E5E65F88DDDE_1_105_c]<https://user-images.githubusercontent.com/19344651/85132675-4166e900-b207-11ea-808c-8a97cfd27905.jpeg>

**Comment by bernardsilenou** [comment] 2020-06-19 14:24
@OlivierLeuci  Click on French icon and this screen will open:
![image](https://user-images.githubusercontent.com/12996724/85142826-3634ad00-b249-11ea-9e97-f84d21f771fc.png)

**Comment by OlivierLeuci** [comment] 2020-06-19 14:25
Yes Bernard, it works now I’m approved by your colleague 😊


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image001.png@01D64656.2BA12080]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64656.2BA12080]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64656.2BA12080]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64656.2BA12080]

03.81.53.21.23

[cid:image006.png@01D64656.2BA12080]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : vendredi 19 juin 2020 16:24
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci> Click on French icon and this screen will open:
[image]<https://user-images.githubusercontent.com/12996724/85142826-3634ad00-b249-11ea-9e97-f84d21f771fc.png>

**Comment by bernardsilenou** [comment] 2020-06-19 14:26
Super!

**Comment by OlivierLeuci** [comment] 2020-06-19 14:36
Hello,

I did the change in Crowdin from the french translation.

Wa’ve seen some other translations that aren’t exactly what we find more efficient. I wil do the change in Crowdin as we’ll see them.

Thankx.

Last question, we’ll do a local change to manage the issue but when do the file will be changed in the SORMAS ?

Best regards and have a good end of week.

Olivier


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D64657.C6E2CDE0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64657.C6C86810]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64657.C6C86810]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64657.C6C86810]

03.81.53.21.23

[cid:image006.png@01D64657.C6C86810]

olivier.leuci@esante-bourgogne.fr



De : Olivier Leuci
Envoyé : vendredi 19 juin 2020 09:02
À : 'hzi-braunschweig/SORMAS-Project' <reply@reply.github.com>; hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Mention <mention@noreply.github.com>; Silenou, Bernard <Bernard.Silenou@helmholtz-hzi.de>
Objet : RE: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)

Hello,

I pick up an account to Crowdin but I need to be approved to contribute.

Is it possible to someone to manage my approval and I’ll give you ASAP another account to approve

Thank you.


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image009.png@01D64657.C6E2CDE0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64657.C6C86810]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64657.C6C86810]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64657.C6C86810]

03.81.53.21.23

[cid:image006.png@01D64657.C6C86810]

olivier.leuci@esante-bourgogne.fr<mailto:olivier.leuci@esante-bourgogne.fr>



De : StefanKock <notifications@github.com<mailto:notifications@github.com>>
Envoyé : vendredi 19 juin 2020 07:49
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com<mailto:SORMAS-Project@noreply.github.com>>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr<mailto:Olivier.Leuci@esante-bfc.fr>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)


The translation has to contain a %s as placeholder. %d is supposed to be for numbers.

confirmationDeleteEntity = Are you sure you want to delete this %s? This action can not be reversed.

It seems that #2139<https://github.com/hzi-braunschweig/SORMAS-Project/issues/2139> has popped up again. I think the downstream merge from Crowdin is the problem, because my fix was deleted by a later merge.

Solution: Provide a proper translation for confirmationDeleteEntity via Crowdin with %s as placeholder and then this has to be merged to the project.

**Comment by bernardsilenou** [comment] 2020-06-19 14:43
Yes please, you can change but remember to use phrases and terminologies that are application to other French countries which are not France. If you latter find out that there are many terminologies specific to France surveillance system, then we can create a new language "French France".

Any translation you do (including errors if they happen)  will be included in the next release. There is no next step validation.

Best,

Bernard

________________________________

**Comment by OlivierLeuci** [comment] 2020-06-19 15:16
Bernard,

That’s a ggod Idea, it’s often that there is different french languages for the same OpenSource project.

I’ll talk about your idea to our team FR but I think that we will do so on because we have seen a lot of strings that we would like to change in their forms but you’re right, it could not be shared by every french spoken countries.

Thank you.

BR

Oliier


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D6465D.6870BCD0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D6465D.68551E80]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D6465D.68551E80]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D6465D.68551E80]

03.81.53.21.23

[cid:image006.png@01D6465D.68551E80]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : vendredi 19 juin 2020 16:44
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (#2342)

Yes please, you can change but remember to use phrases and terminologies that are application to other French countries which are not France. If you latter find out that there are many terminologies specific to France surveillance system, then we can create a new language "French France".

Any translation you do (including errors if they happen) will be included in the next release. There is no next step validation.

Best,

Bernard

________________________________

**Comment by StefanKock** [comment] 2020-06-23 08:33
@MateStrysewskeSym please have this in mind when merging translations.

**Comment by StefanKock** [comment] 2020-06-23 11:15
This defect is fixed for `fr-FR`, but is still present in `fr-CH`.

**Closed** 2020-06-24 08:49 UTC
Labels: Translation, bug, sormas-ui

**Comment by StefanKock** [comment] 2020-06-24 10:35
> This defect is fixed for `fr-FR`, but is still present in `fr-CH`.

Is now fixed.

**Comment by OlivierLeuci** [comment] 2020-06-24 12:10
Hello,

Just a question.
The translation bug was identified for 1.42.3 version and it’s now seems to be fixed with the nexw tanslation I’ve done in Crowdin.

My question is when does it’ll appear in the next SORMAS stable version, in a hotfix ?

Thank you for yoour reply.

Best regards


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D64A31.2A4B7710]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64A31.2A394EA0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64A31.2A394EA0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64A31.2A394EA0]

03.81.53.21.23

[cid:image006.png@01D64A31.2A394EA0]

olivier.leuci@esante-bourgogne.fr



De : StefanKock <notifications@github.com>
Envoyé : mercredi 24 juin 2020 12:36
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (french language) (#2342)


This defect is fixed for fr-FR, but is still present in fr-CH.

Is now fixed.

**Comment by bernardsilenou** [comment] 2020-06-24 12:23
@OlivierLeuci  It will be available in the new release. You can upload it on the test server and  test before migration to productions server

**Comment by StefanKock** [comment] 2020-06-24 12:26
The next regular release is already running and to be published soon: https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.43.0

**Comment by OlivierLeuci** [comment] 2020-06-24 13:36
Hello Bernard,

As we’d discuss in a french workshop, your idea to manage a FR_fr translation seems to be attractive to manage our specificity. My question is, if we’ll do so, we naturally need to manage the translation process for this French-French language files ?

Thanx for your reply.

BR.

Olivier


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D64A3D.227D3620]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64A3D.226B0DB0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64A3D.226B0DB0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64A3D.226B0DB0]

03.81.53.21.23

[cid:image006.png@01D64A3D.226B0DB0]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : mercredi 24 juin 2020 14:24
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Error when erasing a case or a contact (french language) (#2342)


@OlivierLeuci<https://github.com/OlivierLeuci> It will be available in the new release. You can upload it on the test server and test before migration to productions server
