### ISSUE TITLE
Overall Mobile app user experience is not smooth and app keep crashing 

### ISSUE THREAD

**Issue by SORMAS-ZohaibHassan** [hzi-braunschweig/SORMAS-Project#9436] opened 2022-06-07 09:54 UTC
### Bug Description
The mobile app does not work smoothly. It keeps crashing randomly. Sometimes, if you open a specific case, then it crashes otherwise not. It's the same with synchronization. Randomly syncopation gets failed. Even while crashing/syncing, it restarts automatically. I have tried it on different devices and getting the same results. And My current device is brand new.

### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.72.1
* Android version: 1.72.1
* Android Version: 11
* User Role: Hospital Informant

### Additional Information

Screenshots and screen recordings are attached for reference. 

![Screenshot_20220531-155232_APMIS](https://user-images.githubusercontent.com/8872102/172352007-a185d257-7172-4afc-bdf6-603f74b17823.jpg)
![Screenshot_20220531-155224_APMIS](https://user-images.githubusercontent.com/8872102/172352008-ecfc08a0-b07c-4176-8ed3-af4518304fc7.jpg)
![Screenshot_20220601-113254_APMIS](https://user-images.githubusercontent.com/8872102/172351999-03eca880-bf6c-43dd-83f6-0186f18ef571.jpg)

https://user-images.githubusercontent.com/8872102/172352011-7ba802de-38f2-4d91-812a-3865ac8fe54f.mp4

**Comment by zohaibhassan122** [comment] 2022-06-07 09:58
Hi @MateStrysewske,
Can you please look into this issue and I will try to make sure that this issue should be part of the next sprint.

**Comment by MateStrysewske** [comment] 2022-06-09 13:40
@zohaibhassan122 We'll investigate, but I don't think that any of us have experienced such things so far. Would be very helpful if you could send us some error logs with the exception messages that should occur when the app crashes.

**Comment by zohaibhassan122** [comment] 2022-06-09 14:27
@MateStrysewske, You mean error logs from the SORMAS Server?

**Comment by MateStrysewske** [comment] 2022-06-14 10:21
@zohaibhassan122 By enabling developer mode and connecting the device to an Android Studio installation, yes

**Comment by MateStrysewske** [comment] 2022-06-22 07:30
@zohaibhassan122 Thanks! I don't see any crash reports in there, strangely - can you set the debugged process to the sormas app and the log level to "Error" in the Logcat window, reproduce the crash and send the logs again? You might need to select the crashed appliation in the process dropdown afterwards in order to see the error messages.

**Comment by zohaibhassan122** [comment] 2022-06-22 12:41
Hi @MateStrysewske
Please find the attached only error level log as you requested. 
[Only Error level log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8957581/Only.Error.level.log.txt)

**Comment by MateStrysewske** [comment] 2022-06-22 13:18
Thanks - can't find anything suspicious in there unfortunately - we'll have to see whether anyone in our team can reproduce the problems.

**Comment by zohaibhassan122** [comment] 2022-06-22 13:25
Just FYI: @MateStrysewske, it mostly happens when you try to setup the application first time on a physical device. Once you have setup it somehow, then crashes are reduced.

**Comment by bernardsilenou** [comment] 2022-07-04 20:17
Just to confirm that I also experience what is explained here on A11, Galaxy tab A, SM-T515. App begins sync when you try to create a case followed by crashing and asking you to enter pin, then crash after entering the pin.

**Comment by bernardsilenou** [comment] 2022-07-12 23:08
This comment is about testing version  1.73.2 on release-international using Informant or SO:
 1. Installing a fresh version through manual download resulted in a stable app, there was no crash
 2. Installing a fresh version through changing server URL and was printed by sormas to download a new version + accepting to install the new version + login resulted in an unstable app with sync issues.

@bernardsilenou @zohaibhassan122 Please can you install a new version as in point 1. and comment on what you found?

**Comment by zohaibhassan122** [comment] 2022-07-13 12:35
Hi @bernardsilenou,
As this issue is already being taken care of by Mate and is part of release 1.75.0. I am waiting for Mate's response once he has done all his investigations and debugging.

**Comment by zohaibhassan122** [comment] 2022-08-10 09:26
Hi @MateStrysewske ,

just for your information, Today, I was trying to use 1.74 version with the mobile app(all other environment variables are the same as mentioned in the issue description) and I am still facing the issue and I cannot syn the data. I have attached the error log and screenshot as well.


![Screenshot_20220810-111334_APMIS](https://user-images.githubusercontent.com/8872102/183865065-95ed3b20-40b7-4716-a184-bfa4cee83182.jpg)
[sync_error_log_1_74.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9298672/sync_error_log_1_74.txt)


FYI:  @bernardsilenou  @BasilKaburi

**Comment by MateStrysewske** [comment] 2022-08-11 09:48
@zohaibhassan122 This does not really look like an issue of the mobile app to me, actually, because the exception that I see in the error logs is a timeout exception, which hints at the server not responding in time. Can you check whether connecting to a different server fixes the issues you're experiencing?

**Comment by MateStrysewske** [comment] 2023-02-28 11:15
I'll close this issue because we still can't reproduce it and there hasn't been any activity/response in several months.

**Closed by MateStrysewske** 2023-02-28 11:15 UTC
Labels: android-app, needs-response, general, major, finding
