### ISSUE TITLE
Tasks > Filtering on empty "task status" results in error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3705] opened 2020-12-06 22:56 UTC
### Bug Description
Tasks > Clicking on the "apply filters" when the null "task status" is selected, results in an error for "All tasks".

### Steps to Reproduce
1. Tasks > Set a Context
2. Set "Task status" to null
3. [Optional] Set a Region
4. Apply Filters
5. Select "All tasks" > error

### Expected Behavior
No error message.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/101295284-f8d6d280-381c-11eb-9ae3-62e1b8c9f6d9.png)
![image](https://user-images.githubusercontent.com/65529128/101295051-73065780-381b-11eb-8bc2-33a377fcf74a.png)

### System Details
* Device: Web
* SORMAS version: 1.52.0
* Android version/Browser: Chrome
* Server URL: https://release-ch.sormas.netzlink.com/
* User Role: admin

### Additional Information
Related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/3683

**Comment by bernardsilenou** [comment] 2020-12-14 19:27
Since this issue is still open, I would like add additional minor refinement.

The introduction of the feature to double click and set the categories of certain values to NA has introduced bug in the system, eg this and #3771. 
Generally, variables that has the unknown option do not  need the feature to reset to NA.
NA = default value = user did not click on the cell or read the question
Unknown = user clicked on the cell but does not know the right answer

Can we dis-activate this feature for the following variables?
* case.investigation status
* action.action status #3771 
* event.investigation status
* contact.investigation status
* task.task status

Some of these ma have already been implemented but not all.
can be implemented together with #3771

**Comment by MateStrysewske** [comment] 2020-12-15 12:57
@bernardsilenou That has nothing to do with this issue.

Closing this because it was fixed in #3683.

**Comment by bernardsilenou** [comment] 2020-12-15 14:01
i will create another issue after testing 1,53

**Comment by MateStrysewske** [comment] 2020-12-15 16:38
Looks like this error still happens, though I can't reproduce it on my system:

```
Caused by: java.lang.NullPointerException
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:162)
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:115)
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:105)
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:162)
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:115)
	at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.render(CompoundPredicate.java:105)
	at org.hibernate.query.criteria.internal.QueryStructure.renderWhereClause(QueryStructure.java:351)
	at org.hibernate.query.criteria.internal.QueryStructure.render(QueryStructure.java:238)
	at org.hibernate.query.criteria.internal.CriteriaQueryImpl.interpret(CriteriaQueryImpl.java:297)
	at org.hibernate.query.criteria.internal.compile.CriteriaCompiler.compile(CriteriaCompiler.java:165)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:742)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:498)
	at de.symeda.sormas.backend.task.TaskFacadeEjb.count(TaskFacadeEjb.java:366)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4791)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4763)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4751)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
	... 126 more
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4557)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2108)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2078)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
	at com.sun.proxy.$Proxy882.count(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)
	at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:128)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:259)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:189)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
	at de.symeda.sormas.api.task.__TaskFacade_Remote_DynamicStub.count(de/symeda/sormas/api/task/__TaskFacade_Remote_DynamicStub.java)
	at de.symeda.sormas.api.task._TaskFacade_Wrapper.count(de/symeda/sormas/api/task/_TaskFacade_Wrapper.java)
	at de.symeda.sormas.ui.task.TaskGrid.lambda$setLazyDataProvider$b88b9d74$1(TaskGrid.java:234)
	at com.vaadin.data.provider.CallbackDataProvider.sizeInBackEnd(CallbackDataProvider.java:142)
	at com.vaadin.data.provider.AbstractBackEndDataProvider.size(AbstractBackEndDataProvider.java:66)
	at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
	at de.symeda.sormas.ui.utils.FilteredGrid.getItemCount(FilteredGrid.java:67)
	at de.symeda.sormas.ui.task.TaskGridComponent.updateAssigneeFilterButtons(TaskGridComponent.java:251)
	at de.symeda.sormas.ui.task.TaskGridComponent.updateFilterComponents(TaskGridComponent.java:259)
	at de.symeda.sormas.ui.task.TaskGridComponent.reload(TaskGridComponent.java:235)
	at de.symeda.sormas.ui.task.TasksView.enter(TasksView.java:124)
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
	at com.vaadin.navigator.View.beforeLeave(View.java:79)
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
	at de.symeda.sormas.ui.utils.AbstractView.navigateTo(AbstractView.java:142)
	at de.symeda.sormas.ui.utils.AbstractView.navigateTo(AbstractView.java:126)
	at de.symeda.sormas.ui.task.TaskGridComponent.lambda$createAssigneeFilterBar$8abe941a$1(TaskGridComponent.java:164)
	at jdk.internal.reflect.GeneratedMethodAccessor611.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:712)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1189)
	at com.vaadin.v7.ui.AbstractField.fireValueChange(AbstractField.java:1134)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:545)
	at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
	at com.vaadin.v7.ui.ComboBox.changeVariables(ComboBox.java:745)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:625)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:471)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:414)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
	at jdk.internal.reflect.GeneratedMethodAccessor379.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4791)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
```

**Comment by raghupola-vg** [comment] 2020-12-16 16:21
Tested and easily reproduced on Chrome and Firefox browser. Login as National User.
If not reproduced. Please try below steps:
- Login as National User
- Select Tasks in the navigation pane
- On the right corner, filter by All tasks
- Select a Task Context
- Remove the Task status selection(empty/null)
- Click on Apply Filters

**Closed** 2020-12-21 14:52 UTC
Labels: bug

**Comment by raghupola-vg** [comment] 2020-12-22 12:18
Tested on latest version and issue is Fixed.
