### ISSUE TITLE
Hide home based quarantine possible and supply ensures form sormas international ui

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2184] opened 2020-05-26 15:56 UTC
### Proposed Change
- hide home based quarantine possible
- add "Other"  +  free text to the list of quarantine type to all instances

**Comment by MateStrysewskeSym** [comment] 2020-05-28 05:50
@bernardsilenou This is an exact duplicate of #2095 which is in the current sprint.

**Closed by MateStrysewskeSym** 2020-05-28 05:50 UTC
Labels: change
