### ISSUE TITLE
Synchronization with mobile app is not working since 1.77.0 is released

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#11187] opened 2022-12-15 09:56 UTC
### Bug Description

Whenever you try Synchronization  in mobile, it gets failed. 

#### Steps to Reproduce

1. Go to the case directory and try to sync. 

#### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.72.1
* Android version: 1.72.1
* Android Version: 11
* User Role: Hospital Informant
* Server URL: release-international.sormas.netzlink.com

### Expected Behavior

Data should be synchronized. 
### Additional Information

Screenshot and logs are attached.
![Screenshot_20221206-094134_APMIS](https://user-images.githubusercontent.com/8872102/207829043-8f44dc3a-d3be-4940-be81-dfbfa7522229.jpg)
[sync_fail_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10235855/sync_fail_log.txt)

**Comment by zohaibhassan122** [comment] 2022-12-15 09:56
@MateStrysewske FYI

**Comment by MateStrysewske** [comment] 2022-12-15 12:00
@zohaibhassan122 Found the issue, I believe. Will be fixed in 1.77.4.

**Comment by MateStrysewske** [comment] 2022-12-15 15:06
Has to be moved out of 1.77 because it broke 1.77.4. 1.77.4 will be skipped as a result and 1.77.5 will be released which reverts the changes made in this issue.

We have to move this to 1.78.0 because it has a lot of side effects that we have to take care of.

**Comment by MateStrysewske** [comment] 2022-12-16 08:49
The issue here is that the hospital informant does have access to case visits (which are not implemented in the mobile app in the first place right now), but not to contact visits; however, we're using the contact user filter to determine which visits need to be synced to the mobile app, and the contact user filter in turn uses the case user filter to determine which contacts the user has access to, but without checking whether the user has access to contacts in the first place. This leads to visits being synchronized to the mobile app that the user should not have access to, and consequently, saving the visit to the database fails because the person of the associated contact has not been synchronized at all.

To reproduce this, simply create a case in the hospital informant's facility (in the web app), add a contact to it and add visits to that contact. This should break the synchronization for the hospital informant.

It's not easy to fix unfortunately because simply adding the user right check to the contact user filter breaks other parts of the software.

**Closed** 2022-12-19 11:42 UTC
Labels: bug, android-app, technology, critical

**Comment by adinaflorea9** [comment] 2022-12-21 11:52
Verified ticket on https://test.sormas.netzlink.com/ where SORMAS version is 1.78.0-SNAPSHOT(fe71891) using the Hospital Informant and Surveillance Officer user roles.

The mobile app was downloaded from: 
APK download: https://test.sormas.netzlink.com/downloads/release/ 

Server URL: https://test.sormas.netzlink.com/sormas-rest/
