### ISSUE TITLE
Full-Export for Switzerland to SEDEX [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2975] opened 2020-09-24 09:36 UTC
### Situation Description

**Minimum Essential Dataset**
[Metadata_MED_21082020_mapping.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5274892/Metadata_MED_21082020_mapping.xlsx)

**Current** solution
[sql.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5274900/sql.zip)

### Feature Description
As a result a fullexport (new right) should be triggered in SORMAS
The result should look like this: 
[KT_1595579590_case.csv.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5274922/KT_1595579590_case.csv.zip)

@Candice-Louw Please provide a sample Export for the contacts as well

As soon as: 
2959 Cases > Minimal Essential Data (MED) for Switzerland
2960 Contacts > Minimal Essential Data (MED) for Switzerland
are implemented, this can be done.

The changes and updates within the db-scheme should be communicated to Netzlink asasp, so that they can update the sql-scripts.

Use the custom export as a starting point for the BAG Export

### Possible Alternatives

Create a new "BAG Export" for cases and contacts in the UI

### Additional Information
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/52

**Comment by markusmann-vg** [comment] 2020-10-12 07:53
We are preparing the export for contacts now as well. However, there is no example for the full export for contacts. Based on the example we have for cases and the fields we have from the minimal essential data set, we do the implementation. If there is a certain order of the fields needed, pls. provide them.

**Comment by leventegal-she** [comment] 2020-10-13 07:36
Waiting for final version of contacts csv content.
Following columns in case export needs to be defined: contact_confirmed_case_yn, contact_confirmed_case_date ,contact_confirmed_case_fall_id_ism, activity_mapping_yn, infection_country, infection_location, other_infection_location
Waiting for #2979 to have names of locations

**Comment by vidi42** [comment] 2020-11-02 06:41
@markusmann-vg can you please provide the final contact CSV or mention someone who can?

**Comment by Candice-Louw** [comment] 2020-11-02 07:00
[SORMAS_Schweiz._Contact_Tracing_Database_MEDS.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5473222/SORMAS_Schweiz._Contact_Tracing_Database_MEDS.zip)

@vidi42 - Could you see if the "CT_AA_20201708_contact.csv" file would be sufficient, please?

**Comment by leventegal-she** [comment] 2020-11-02 07:30
@Candice-Louw can you please explain what are the following fields in the case export? 
contact_confirmed_case_yn, contact_confirmed_case_date ,contact_confirmed_case_fall_id_ism, activity_mapping_yn, infection_country, infection_location, other_infection_location

**Comment by Candice-Louw** [comment] 2020-11-02 16:56
@leventegal-she - I got an updated list from the BAG: 
[Metadata_MED_06102020_fin_de_corr.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5476632/Metadata_MED_06102020_fin_de_corr.xlsx)


As far as I can tell, the following applies:
Your var Question | Response
|--|--|
contact_confirmed_case_yn | This is an old variable and is replaced by the variable "case_link_yn" in the current dataset.
contact_confirmed_case_date | This is an old variable and is replaced by the variable "case_link_contact_dt".
contact_confirmed_case_fall_id_ism | This is an old variable and is replaced by the variable "case_link_fall_id_ism".
activity_mapping_yn | This means that possible contacts during the infectious period and the incubation period of the COVID-19 case, as well as possible sites of infection, were tried to be identified. *This is planned to be part of the new epidemiological data refinement, I believe.*
infection_country | This is an old variable and is replaced by the variable "exp_country".  Associated with the new Person.addressType: "Place of exposure".
infection_location | This is an old variable and is replaced by the variable "exp_loc_type"
other_infection_location | This is an old variable and is replaced by the variable "other_exp_loc_type"

**Comment by leventegal-she** [comment] 2020-11-03 07:59
The case export example (KT_1595579590_case.csv.zip) also contains the columns `contact_confirmed_case_yn`, `contact_confirmed_case_date` and `contact_confirmed_case_fall_id_ism`.

I think those should be **only** in the contact export.

@Candice-Louw does it make sense to have them in the contact export?

**Comment by Candice-Louw** [comment] 2020-11-03 10:45
@leventegal-she - If a Contact is converted to a Case (captured as a Contact and then later converted to a Case in SORMAS), the request is to have all of these variables included in both the Case and Contact export, please.  

This would make it easier for the data analysts to keep track of Contact data that gets transferred/is applicable to converted Cases.

**Comment by leventegal-she** [comment] 2020-11-04 09:49
@Candice-Louw the problem is that it can happen that some contacts result in the same case, for example because of the duplicate detection, so there is not a clear way to identify the right contact to get its case link related fields.

So I would say it's better not having those columns in the case export than having wrong values.

**Comment by Candice-Louw** [comment] 2020-11-15 22:12
@leventegal-she 

Further info from CH colleague (I know it's late, but could maybe still be of some interest/relevance):
"Our index cases receive an ID that is generated through our own database (the Swiss database that has all the positive lab results as a basis). These cases' close contacts are then assigned the same ID.

This ID is also used for communication purposes between contact tracing centers, e.g. as a priority list who to call next."

**Comment by leventegal-she** [comment] 2020-11-24 12:16
Closing with a followup ticket: [Followup - Full-Export for Switzerland to SEDEX](https://github.com/hzi-braunschweig/SORMAS-Project/issues/3570)

**Closed by leventegal-she** 2020-11-24 12:16 UTC
Labels: SBC2, ch, feature, sormas-ui
