### ISSUE TITLE
Translation of the categories using German SORMAS ÖGD

### ISSUE THREAD

**Issue by MallerBeach** [hzi-braunschweig/SORMAS-Project#4746] opened 2021-03-12 10:50 UTC
### Problem Description
The Statistics Export from SORMAS ÖGD contains for some variables categories that are not in line with categories in the drop-down list, for example in persons.csv see occupationtype (for example HUNTER_MEAT_TRADER, MINER vs. for example drop-down list Angestellter, Selbstständiger). 

### Proposed Change
Would it be possible to translate the categories?

**Comment by MateStrysewske** [comment] 2021-03-12 10:58
@kwa20 I think I need your input here before I can make an educated comment. Can you give me some additional context?

**Comment by kwa20** [comment] 2021-03-12 11:10
@MateStrysewske I think that this is basically caused by #2718 and cannot easily fixed by translations alone.

**Comment by MallerBeach** [comment] 2021-03-12 11:54
Sorry, I obviously didn't thoroughly search the existing issues. At the moment the overview of the mapping of the occupations is sufficent.

**Closed** 2021-03-12 13:27 UTC
Labels: duplicate
