### ISSUE TITLE
SurvNet Adaptations - Create new field “Suspicious case” to cases [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3419] opened 2020-11-06 07:26 UTC
### Feature Description
Create new field “Suspicious case” to cases

Case > case information

New field (DE only) –
“Verdachtsfall (de – de) | “Suspicious case” (en) [SurvNet field names: SuspicionNotConf; SuspicionNotDat; SuspicionNotPhysician; SuspicionNotPathOther]

If the answer is “suspicion not confirmed” then change case classification to “no case”.

Data Type: check box, date
Values (de-de) | (en)

Verdacht nicht bestätigt am | suspicous not confirmed
o Information durch Arzt/Ärztin| information provided by physician
o Nachweis eines anderen Erregers| detection of other pathogen
Data Type: Datum |date

- [ ] Add to export

**Comment by GabrielePoggensee** [comment] 2020-11-18 10:49
IfSG relevant: § 11 (1) 1 c: Indication when a suspicion has not been confirmed

Data are transmitted to RKI

**Comment by kwa20** [comment] 2020-12-15 21:20
I would actually like to refine this issue so it makes more sense in Sormas.

Only show this checkbox if 'suspect case' is selected as the case classification. Only when 'suspicion not confirmed' is checked, show the date field and the two further check boxes. Also change the classification to 'no case' as already mentioned above.

<img width="807" alt="Screen Shot 2020-12-15 at 10 02 38 PM" src="https://user-images.githubusercontent.com/70317594/102273936-65d81f80-3f23-11eb-8ef4-7c9ae8dff698.png">

**Comment by MateStrysewske** [comment] 2020-12-16 08:25
Why do we need this checkbox in the first place? Shouldn't setting the case classification to "Not a case" be enough? This will also update the date of classification, so we'd basically only need the two additional checkboxes for German systems.

**Comment by kwa20** [comment] 2020-12-16 08:58
@MateStrysewske I'd like that solution because it's minimalistic. We could also then only show the two additional checkboxes when 'no case' is selected and use 'suspicion not confirmed' as a heading for the two.

**Comment by bernardsilenou** [comment] 2020-12-16 09:42
@kwa20 I think we need to first investigate what is the epidemiological definition of suspicious case in term of RKI. In some countries, suspicious case == suspected case.
I am more in line of thinking as @Maté, this may be a category of case classification and it is a very sensitive topic.
Please lets have a call and followup on it

**Comment by MateStrysewske** [comment] 2020-12-16 09:56
@bernardsilenou I didn't write anything like that. I don't think we need a new classification for this.

**Comment by kwa20** [comment] 2020-12-16 17:14
After discussing with @bernardsilenou and considering @MateStrysewske's comment, we suggest this solution:

<img width="923" alt="Screen Shot 2020-12-16 at 6 08 41 PM" src="https://user-images.githubusercontent.com/70317594/102381665-cb7ee700-3fc9-11eb-88a9-edd20d2de83c.png">

We map 'no case' to 'suspicion not confirmed' and use the date of classification for mapping to the date field in SurvNet. When a user sets the case classification to 'no case', the drop down field 'reason for this classification' should appear. There you can select the variables shown in the mock-up ('information provided by physician' and 'verification of different pathogen' are mapped to SurvNet). If other is selected, a free text field appears to specify the reason further. Since multiple options can be chosen in SurvNet, we would need to be able to do it in Sormas too. We thought that if we have checkboxes, it could get messy when more variables are added later on. Would something as displayed in the mock-up even be possible?

We also suggest to make this field available for everyone, not just the german servers since everyone can benefit from this. Generally, we are not quite happy with 'verification of different pathogen' because that doesn't necessarily mean, that the person can not be a case in regards to that disease, but we could not think of another way to properly map it to SurvNet.

**Comment by MateStrysewske** [comment] 2020-12-17 09:42
@kwa20 We don't have such a component right now and I don't know whether it makes sense to build one for the Vaadin application. Because of that, my current feeling is that we should probably go with checkboxes for now and do it in a more user-friendly way when using the new technology.

**Comment by kwa20** [comment] 2020-12-17 09:57
@MateStrysewske Ok, let's use checkboxes with the option of multiple entries then with the heading "Reason for this classification". We then have a free text field when other is selected. @bernardsilenou We should probably not give too many options for selecting the reason for now then, because it will get messy with very many checkboxes.

**Comment by MateStrysewske** [comment] 2021-02-01 13:31
* Add new fields to cases (all only for Germany):
    * `notACaseReasonNegativeTest`, `notACaseReasonPhysicianInformation`, `notACaseReasonDifferentPathogen`, `notACaseReasonOther`: boolean, displayed as checkboxes
    * `notACaseReasonDetails`: text
* Show the checkboxes only when the case classification is "Not a case"
* Show the text field only when `notACaseReasonOther` is selected
* Add new fields to export

**Comment by cazacmarin** [comment] 2021-02-04 07:41
@MateStrysewske - for disease Monkeypox we have 1 more button, INFO which appear in the right side of Case Classification. Is it OK if I will use the design as in the next screenshot?
![image](https://user-images.githubusercontent.com/6985315/106860333-eb2eb380-66cc-11eb-8d2a-a330c1507eba.png)

**Comment by MateStrysewske** [comment] 2021-02-11 17:33
App is broken because the database upgrade script is faulty. Please repair this as soon as possible.

**Comment by cazacmarin** [comment] 2021-02-11 18:47
Fixed missing column in android app.

**Comment by AndyBakcsy-she** [comment] 2021-02-12 17:16
Validated ticket on the latest version of Sormas version 1.57.0-snapshot
Following elements of the ticket have been validated.
Show the checkboxes only when the case classification is "Not a case"
Show the text field only when notACaseReasonOther is selected
Show the new fields directly below the case classification and add a small heading "Reason for this classification"
Add new fields to export

**Comment by raghupola-vg** [comment] 2021-02-12 17:28
Imports doesn't work as expected when the newly added check boxes are marked with Yes.

**Comment by cazacmarin** [comment] 2021-02-13 13:41
@raghupola-vg - please provide more details about how to reproduce import issue.
For now @markusmann-vg asked only for export. And not for import. Markus - should we also cover the import for this?

**Comment by markusmann-vg** [comment] 2021-02-15 08:25
@cazacmarin Yes, pls. also add it to import functionality

**Comment by cazacmarin** [comment] 2021-02-16 06:57
Another case linked to Import was opened (as the import is working generically and is not a part of the development of this CR. Export is working as expected + all other conditions).
As discussed yesterday with @raghupola-vg  - we can close this CR and another one, linked only to Import functional, will be opened (was actually was already done)

**Closed by cazacmarin** 2021-02-16 06:57 UTC
Labels: android-app, backend, cases, de, feature, import & export, refine, vaadin-app
