### ISSUE TITLE
sormas-rest/persons permission? problem 403/500

### ISSUE THREAD

**Issue by freezweb** [hzi-braunschweig/SORMAS-Project#4122] opened 2021-01-25 13:26 UTC
### Bug Description
We have set up a corresponding Docker instance and started operating the test environment for development. In doing so, we discover a problem that we have not yet been able to solve, so we turn to you.

Problem Description:
With the support of Mr. Lambracht (formerly Netzlink, in contact since mid-December), we have not yet been able to solve the following problem. Neither the rest of the API user nor the admin user gives us the opportunity to access / persons / uuid / (error 403), nor to persons / all (error 500). Where can errors lie here? User rights?
### Steps to Reproduce
1. Install Sormas Docker
2. Change user to all the roles
3. going to the api and test...

### Screenshots
![grafik](https://user-images.githubusercontent.com/11458733/105711522-f3daf900-5f18-11eb-9312-beff8eadd4bb.png)
![grafik](https://user-images.githubusercontent.com/11458733/105711538-f9d0da00-5f18-11eb-8c3d-79146c61d4ae.png)
![grafik](https://user-images.githubusercontent.com/11458733/105711548-fdfcf780-5f18-11eb-940c-1cfc8da3d42e.png)

### System Details
* Device: Sormas Docker on Debian
* SORMAS version: SORMAS-Version: 1.52.1
* Android version/Browser:
* Server URL: https://sormas.cov19.digital/sormas-rest/users/all/2020 (only via VPN)
* User Role:  Administrator, ReST Benutzer*in, Sormas zu Sormas Kunde, Nationale*r Benutzer*in

**Comment by JonasCir** [comment] 2021-01-25 13:42
Hi @freezweb thanks for opening the issue:
```
        configuration = sormas_api.Configuration(
            host=f'http://{host}:6080/sormas-rest',
            username='SurvOff',
            password='SurvOff'
        )
```
Can you try this config?

**Comment by JonasCir** [comment] 2021-01-25 13:43
The 500 error looks worth investigating, though

**Comment by freezweb** [comment] 2021-01-25 13:58
> 
> 
> Hi @freezweb thanks for opening the issue:
> 
> ```
>         configuration = sormas_api.Configuration(
>             host=f'http://{host}:6080/sormas-rest',
>             username='SurvOff',
>             password='SurvOff'
>         )
> ```
> 
> Can you try this config?

where should I enter that?

**Comment by freezweb** [comment] 2021-01-25 14:05
Only for info, the cases and other is functionaly

![grafik](https://user-images.githubusercontent.com/11458733/105716126-b6796a00-5f1e-11eb-92ce-1c45fe16d3a7.png)

**Comment by JonasCir** [comment] 2021-01-25 15:04
The snippet was from my own project, it was just about `SurvOff` as username + password :) Is it working now? Are you still encountering 500? If yes, please share the request :)

**Comment by freezweb** [comment] 2021-01-25 15:36
That's fine.

what permissions does the interface need that I can syncronize EVERYTHING?


![grafik](https://user-images.githubusercontent.com/11458733/105727333-432a2500-5f2b-11eb-9c3b-1d7911072481.png)

**Comment by freezweb** [comment] 2021-01-25 15:40
oh it's not good yet ...
![grafik](https://user-images.githubusercontent.com/11458733/105728005-f3982900-5f2b-11eb-9c75-332682b9b42a.png)

**Comment by freezweb** [comment] 2021-01-27 11:35
why you remove the bug flag?
the complete permission system is a bug...

**Comment by MateStrysewske** [comment] 2021-01-27 12:11
@freezweb Because most of the time these problems are the result of a wrong configuration. We can reliably confirm that these interfaces are working properly because they're constantly used by the mobile apps to synchronize data.

@JonasCir is currently very busy, but I'm sure he'll get back to you as soon as he's got a free minute.

**Comment by freezweb** [comment] 2021-01-27 13:32
The problem is that the interface MUST run in Bavaria on 02/01/2021.

**Comment by JonasCir** [comment] 2021-01-27 14:26
I hear you and I'm looking into this

**Comment by JonasCir** [comment] 2021-01-27 15:43
@freezweb 
Ok so all the URLs I could find in your screenshots work for me locally via SORMAS-Docker with 
`user:SurvOff, password: SurvOff` (`Surveillance Officer` role that is)
``` 
https://sormas-docker-test.com/sormas-rest/persons/uuids'

https://sormas-docker-test.com/sormas-rest/persons/all/2020

https://sormas-docker-test.com/sormas-rest/cases/all/2020
```
To be fair, I tested Version 1.54.0 but I'm certain this won't make a difference.

So the problem is likely `Change user to all the roles` as you described above, this is not necessary. Standard `SurvOff` role is sufficient, at least for the operations you mentioned in this issue.

**Comment by JonasCir** [comment] 2021-01-27 15:45
I did not investigate the 500 error but I guess this is a direct result of mixing the roles and us not checking for a certain illegal combination

**Comment by freezweb** [comment] 2021-01-27 15:47
the SurvOff can ony 1 Landkreis (area), right?

**Comment by freezweb** [comment] 2021-01-27 15:53
![grafik](https://user-images.githubusercontent.com/11458733/106016399-b82e6380-60bf-11eb-9bd4-a9fa2711d4c4.png)
![grafik](https://user-images.githubusercontent.com/11458733/106016467-ca100680-60bf-11eb-9dde-a2dc15cc72a4.png)
![grafik](https://user-images.githubusercontent.com/11458733/106016575-e449e480-60bf-11eb-80c3-5892b0a82565.png)


uuids = 403

all on SurvOff user 

![grafik](https://user-images.githubusercontent.com/11458733/106016669-fd529580-60bf-11eb-82b9-fd7ff8c27f68.png)

Do I have to create a RestApi / SurvOff user for each individual district so that I can syncronize everything?

**Comment by JonasCir** [comment] 2021-01-27 15:56
Ok this is is a different story. Let me check quickly what role is capable to do the reads cross jurisdiction.

**Comment by JonasCir** [comment] 2021-01-27 17:12
@freezweb ok, please create a user and assign the `national user` and `rest user` role to it. With this, you should be able to fetch all the data across districts.
**Note: This will only work with 1.54.0 onward**

**Comment by MateStrysewske** [comment] 2021-01-28 07:22
For further reference: The problem when trying to retrieve all persons with a national user (i.e. a user without any accessibility restrictions) was fixed in issue #3821 for 1.54.0.

**Comment by JonasCir** [comment] 2021-01-28 09:02
And FYI @bernardsilenou regarding our call: national user and rest user _does_ work, my setup was outdated :D

**Comment by JonasCir** [comment] 2021-01-29 15:05
I go ahead and close this issue. If anything is unclear open an issue or reach out on Gitter.

**Closed by JonasCir** 2021-01-29 15:05 UTC
Labels: support
