### ISSUE TITLE
umlauts and country variables produce errors during imports

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4050] opened 2021-01-16 20:40 UTC
### Bug Description
When using umlauts in free text fields in the import templates a critical error appears upon importing the data. This is quite problematic since the reason of the error is not easily identifiable and users rely more and more on the import function with rising case numbers. Furthermore, importing the newly added person.birthCountry and person.citizenship variables results in a partially failed import with only a generic error message also.

Applicable across all import options.
### Steps to Reproduce 
1. import data with either umlauts being entered in text type fields and country variables in the birthCountry and citizenship fields.
2. check errors upon importing the data.

### Expected Behavior
umlauts in text type fields should be ignored during the import and importing birthCountry and citizenship fields should be able to do with country infrastructure data as variables.
### Screenshots
Sorry for the german error messages. They didn't change when switching languages.
<img width="426" alt="criticalErrorFreeTextUmlauts" src="https://user-images.githubusercontent.com/70317594/104821832-ea79ce80-583e-11eb-9470-34c52f2ab760.PNG">

umlauts:
"Import failed! Import failed because of a critical error. Please contact your admin..."

<img width="417" alt="importFailBirthcountryCitizenship" src="https://user-images.githubusercontent.com/70317594/104821834-ebaafb80-583e-11eb-873d-b47e8f61c868.PNG">

birthCountry, citizenship:
"Import partially successful! The import was partially successful but some of the data could not be imported due to erroneous data."

### System Details
* Device:
* SORMAS version: 1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

**Comment by JonasCir** [comment] 2021-01-17 14:48
@syntakker Is this fixed by your PR?

**Comment by syntakker** [comment] 2021-01-18 09:18
No, this might be related to #3747 (fixed in #3816)

**Comment by JonasCir** [comment] 2021-01-18 09:20
Alright :)
@AndyBakcsy-she 
Can you confirm this is fixed in the most recent version?

**Comment by vlad-ciucescu** [comment] 2021-01-19 12:40
Tested a line listing import with umlauts on test.sormas.netzlink and it didn't work.

**Comment by vlad-ciucescu** [comment] 2021-01-20 08:44
Update: if the import file is encoded in UTF-8 or UTF-8-BOM, the import should work with umlauts. With other encodings, such as ANSI, it doesn't work. 
@kwa20 Please check the file encoding (you can open it in notepad and see in the lower right corner)
![image](https://user-images.githubusercontent.com/65336966/105149620-652b3e00-5b0c-11eb-8fd9-85f93b122df6.png)

If the problem persists please send me the import file which is causing the problem so that I can also test locally.

**Comment by kwa20** [comment] 2021-01-20 11:27
@vlad-ciucescu you're right! I explicitly tried importing a file with the encoding UTF-8-BOM and it worked for cases. Strangely, when I initially save the excel file with the encoding UTF-8, it changes it to ANSI automatically every time. 

For a contact import on the contact directory, however, I receive this error message when using BOM:
<img width="150" alt="importContactsBOM" src="https://user-images.githubusercontent.com/70317594/105168000-c60d4300-5b19-11eb-95e6-8b32821f37ee.PNG">
<img width="417" alt="importContactsBOMerror" src="https://user-images.githubusercontent.com/70317594/105168248-28664380-5b1a-11eb-8910-1283fc68f463.PNG">
It reads: Invalid column! The column "caseIdExternalSystem" is not part of the imported Data type or one of its units.

**Comment by vlad-ciucescu** [comment] 2021-01-20 11:58
@kwa20 
I could not reproduce this locally, on test.sormas.netzlink.com or on ga1.sormas-oegd.de, which all are up to date.
It seems to me that this is the behaviour we had before implementing #3747, meaning you are testing this on a system on which this was not released. Please keep in mind that #3747 will be included in version 1.54

**Comment by kwa20** [comment] 2021-02-02 14:58
@vlad-ciucescu I could now verify that UTF-8 with BOM is accepted (1.54.1). The problem I had was that excel 2016 automatically saves files as ANSI instead of the specifically selected UTF-8. Another problem however is that after I've changed the encoding of the file  with Notepad++ once, editing the file, saving, and re-encoding again does not seem to work because the layout automatically changes. All entries are then in column A. Trying to transfer them to a column format does not seem to work because of missing delimiters:

<img width="341" alt="importProblem" src="https://user-images.githubusercontent.com/70317594/106617838-3fbc1c80-656f-11eb-822d-defeadbc2085.PNG">
<img width="436" alt="importProblem2" src="https://user-images.githubusercontent.com/70317594/106617847-4185e000-656f-11eb-8f7c-782c32d6ec47.PNG">

We might need to think about accepting ANSI too because I think many health departments with the same excel version might face this problem. Would there be anything to contradict this? 

I could also not import fields with country references thus far.

**Comment by syntakker** [comment] 2021-02-22 08:32
A solution would be to analyse the charset of the import file and to adjust the encoding accordingly. This would allow to import in any charset.

**Comment by vlad-ciucescu** [comment] 2021-02-22 09:38
It generally isn't possible to determine the encoding of a file with 100% confindence, but instead the best guess is taken. This is also true when trying to differentiate between ANSI and UTF-8. UTF-8-BOM in particular is easy to recognize thanks to some special characters and for this reason I was able to also make the export handle UTF-8-BOM. 
The safest option for supporting multiple encodings is for the user to manually choose the encoding when importing or exporting.

**Comment by syntakker** [comment] 2021-02-23 08:59
Unit tests on cornercases can clarify how well a best guess approach would work. I would estimate that this would do for an easy handling of most of the cases.
A way to go might be a selectable import format with an option "auto", so if the guessed charset is erroneous, the user can give it a second try with a chosen encoding.

**Comment by vlad-ciucescu** [comment] 2021-02-23 09:38
These are not corner cases unfortunately. 
Example of ANSI import file:
```
defaultName,externalId,isoCode,unoCode,archived
Deutschland,10100017,DE,,
Frankreich,10100527,FR
```

Example of UTF-8 import file:
```
defaultName,externalId,isoCode,unoCode,archived
Deutschland,10100017,DE,,
Frankreich,10100527,FR
```

Both are identical until an umlaut appears, in which case the import crashes if the wrong encoding was guessed. 
I would be fine if we default to UTF-8 and then let the user choose another one in a dropdown or something.

**Comment by syntakker** [comment] 2021-03-04 22:52
@vlad-ciucescu I've given it a try using icu4j. Import of ISO-8859-1 files works in unit tests and on a local instance. However, I've not tested with large files yet.
See PR #4640.

**Closed** 2021-03-16 16:13 UTC
Labels: SSD, bug, import & export, vaadin-app
