### ISSUE TITLE
SurvNet Adaptations - Create new field “Reinfection” for cases [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3831] opened 2020-12-18 11:21 UTC
### Feature Description
Create new field “reinfection” for cases
Cases > Open Case information

New field (only DE) –
„Re-Infektion“ (de – de) | „reinfection“ [SurvNet field name: [Disease71CVD].[Reinfection]]

Values (de-de) | (en)
Data Type: Dropdown/enum

• -nicht erhoben- | data not collected
• -nicht ermittelbar- | unknown
• Ja | yes
• Nein | no

Additional Information
No dropdown but switches will be used in the UI
position of the new field: ???
should also be available in the detailed/custom export

**Comment by bernardsilenou** [comment] 2020-12-18 12:25
Suggestions:
- position of "reinfection" variable == some where at the top since its important information for covid. Just above quarantine would be good
- We only show this variable for diseases that reinfection is possible. Just for covid for now, but should be programmed such that we can easily activate it for other diseases
- It would be good to activate it for all instances @Candice-Louw @kwa20 can you confirm this?
- One important variable to add is the date of last infection. This would help to determine on average how long it takes for people to get reinfected. Since people may not remember the exact date, we may ask them of date/year/month just as in date of birth.
- If reinfection == yes, ask for "Previous infection date" with option to choose date or just year and month
- enmums at front end = yes , no, unknown, default back end NA (data not collected) @markusmann-vg hope this is what you meant?

- Last point that we can add after implementing this story is a method for reinfection case detection. The system would call for the normal duplicate person detection and apply a duplicate case detection using disease only. User can then validate possible reinfections (can be many for one person) and link them. Just mentioning it here not to forget

**Comment by MateStrysewske** [comment] 2020-12-18 12:34
@bernardsilenou I actually think that we shouldn't add a field like this because it disrupts the process that SORMAS is supposed to be used for. A "reinfection" should basically result in a new case being created, not the last one being updated and labeled as a reinfection, right?

**Comment by bernardsilenou** [comment] 2020-12-18 18:47
@MateStrysewske I absolutely agree with you that a new case should always be created.
- I thought this issue is focusing on the fact that we label and possibly link the new case to the old one.
- No matter the use case, users can still misuse it by just updating the old case.
I think the best way would be to create a new case and we can automatically do the linking if person and disease are the same and difference in onset dates is more than a pre-defined number of days d == disease configuration

**Comment by kwa20** [comment] 2021-01-18 15:19
@bernardsilenou @MateStrysewske I also agree that a reinfection should always lead to the creation of a new case. Technically, an initially existing case should therefore never be labeled as reinfection. However, a case to a person might be documented where the person is aware of having had this disease before at some point, but it might've never been documented. Therefore, it would still be valuable information.

**Comment by kwa20** [comment] 2021-01-26 20:47
@bernardsilenou @MateStrysewske What if by selecting yes for the reinfection field, users get the option to link the current case to an existing previous case of that person with the same disease and allow navigation.

<img width="661" alt="Screen Shot 2021-01-26 at 9 43 00 PM" src="https://user-images.githubusercontent.com/70317594/105903207-e2304900-601f-11eb-9acf-a1f811f712bd.png">

**Comment by bernardsilenou** [comment] 2021-01-26 22:27
@kwa20 
- For the solution to link the two cases, as long as the duplicate person detection was applied when creating the second case, then we already know the previous cases, right? To me, no need to ask the user for information that we can derived from the db. I think we can check if both cases in sormas are lab confirmed and we just tag the new case as reinfection.
- another practical challenge i see is how to link cases if there more than one previous case (should we take the recent one only) OR if the user is limited by pseudonymization (more rules need to be specified) OR if previous case was deleted or migrated to another database (reinfection of diseases often happen after some time, 6 months or even 12, thus users may not use the feature to link cases often since older cases are not in the system)

- I have not yet understand the motivation for tagging cases as reinfected with out having evidence (data on the previous case). 
- I can only recommend that we do not ask users to decide if a case is reinfected because there is no laboratory evidence of the firs case in the system. But, for cases of the same person that we have a lab confirmation in SORMAS, we can compute the reinfection variable by using the logic you proposed. case with earliest date == source case + subsequent cases are ordered as reinfection generation 1, 2, ... depending on the report of each case.

**Comment by MateStrysewske** [comment] 2021-01-27 09:57
@kwa20 With the new person page that contains a list of cases and contacts, I don't think this feature will be really necessary anymore because the information will already be there and visible for the user.

**Comment by kwa20** [comment] 2021-01-27 18:24
Ok, a link might not be needed then indeed. If we compute the reinfection by looking for previous cases with this disease for the same person, what do you think about this approach? The date of previous infection takes the latest infection with that disease if multiple exist in the database already.

<img width="490" alt="Screen Shot 2021-01-27 at 7 19 23 PM" src="https://user-images.githubusercontent.com/70317594/106035908-ef5b3f80-60d4-11eb-98da-39a76f2128b4.png">

**Comment by bernardsilenou** [comment] 2021-01-27 19:41
@kwa20 I think this is a great idea to show it like this.

**Comment by MateStrysewske** [comment] 2021-02-01 11:50
@kwa20 @bernardsilenou @markusmann-vg After our discussion today I suggest the following:

* Add new fields to cases:
    * `reinfection` (YesNoUnknown)
    * `previousInfectionDate` (date)
* Both fields should only be visible for Covid-19 right now (because the information is probably not relevant for all diseases)
* Add those fields as editable fields to the case edit forms (not creation form)

I think we should NOT add any automatic calculation to this field right now because that could have negative effects on the case creation/saving process. We probably need a follow-up issue for this, because it's of course still important.

**Comment by kwa20** [comment] 2021-02-01 12:05
@MateStrysewske This solution would also be fine with me with a follow-up issue later. We would then map it to SurvNet so that reinfection gets checked if "yes" was selected in SORMAS. Otherwise it stays unchecked.

**Comment by bernardsilenou** [comment] 2021-02-01 19:00
@MateStrysewske @kwa20 @markusmann-vg 
Minor suggestions:
- For `previousInfectionDate` 95% or more of people would not remember this date and I am one of them. They may remember the year or month. I suggest we split it to month day year. 
- Validation: Year should  not be NA if month and day is provided. If year is provided, month and day can be NA. We need this for birth date also, do you agree?
- The followup issues to auto compute this variable is more important in my point of view. It would be good to not close this ticket without implementing it OR carry it over when closing this ticket not to forget.

**Comment by kwa20** [comment] 2021-02-01 19:47
@MateStrysewske @bernardsilenou Could we not automatically adopt the symptom onset date or report date of the previous case if there is an existing one for the same person? Considering that health departments process hundreds of cases per day, I doubt people would really remember any dates of previous cases to the same specific person. This field would probably mainly be filled by users if they've asked about this information when getting in contact with the case person so I don't think splitting it is necessary.

**Comment by bernardsilenou** [comment] 2021-02-01 22:09
@kwa20 @MateStrysewske  My biggest worry is the challenge with memory bias, I think Kay is right.
Its better we auto compute reinfection.
Since the person has already been merged, we just need to look to other confirmed cases of the same person with  the same disease with report date in the past of the current case. 
@MateStrysewske What is the challenge of auto computation please?

**Comment by MateStrysewske** [comment] 2021-02-02 08:18
As I've written above:

> I think we should NOT add any automatic calculation to this field right now because that could have negative effects on the case creation/saving process. We probably need a follow-up issue for this, because it's of course still important.

Since France has significant performance issues already, putting even more stuff that requires to query the database into the saving process would only make that worse. That's why this automatic process is out of question right now until we have a solution for the performance issues, and we will introduce it with a follow-up issue as soon as possible.

**Comment by bernardsilenou** [comment] 2021-02-02 10:39
@MateStrysewske Thanks, I understand you.

This means this is the best option for now
Add new fields to cases:
`reinfection (YesNoUnknown)`
`previousInfectionDate (date)`   @kwa20 does SurvNet require that we map a complete date, or juse the reinfection variable ?
@MateStrysewske  can we splint this in month day and year?

**Comment by MateStrysewske** [comment] 2021-02-02 11:17
@bernardsilenou Splitting this into month, day and year doesn't make much sense if we later find a way to introduce the automation, I think, because in that case the date should be filled in automatically most of the time anyway, right?

**Closed** 2021-02-11 07:54 UTC
Labels: android-app, cases, feature, vaadin-app

**Comment by AndyBakcsy-she** [comment] 2021-02-12 17:44
Verified ticket on the latest version of Sormas Version 1.57.0-snapshot
Add new fields to cases:
reinfection (YesNoUnknown)
previousInfectionDate (date)
Both fields should only be visible for Covid-19 right now (because the information is probably not relevant for all diseases)
Add those fields as editable fields to the case edit forms (not creation form)
