### ISSUE TITLE
Can not save sample data

### ISSUE THREAD

**Issue by shaneelprakash2910** [hzi-braunschweig/SORMAS-Project#2326] opened 2020-06-16 00:46 UTC
### Bug Description
SORMAS is currently generating an error when the users are trying to update the sample data for cases.

This occurs to some cases even when all the Mandatory fields are updated.

Refer screenshot below.

### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/63214786/84719309-23af3f00-afcf-11ea-8fef-61253f5cff40.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment] 2020-06-16 06:14
@shaneelprakash2910 Can you attach the errors that are logged when this bug occurs?

**Comment by shaneelprakash2910** [comment] 2020-06-16 06:17
Its attached in the Log.

**Comment by MateStrysewskeSym** [comment] 2020-06-16 06:21
@shaneelprakash2910 I don't see any attachments. I don't mean the error that is presented to the user, but the errors that are logged in the log file on the server. You might need to contact the server administrator to retrieve it if you don't have access to it yourself.

**Comment by shaneelprakash2910** [comment] 2020-06-16 06:25
Ok.

This access currently rest with Frank.

@Frank, can you forward this information to Mate please.

Kind regards,
SP

**Comment by fhauptmann** [comment] 2020-06-16 11:35
Hi @MateStrysewskeSym ,

I sent the logs via email. 

Best, 
  Frank

**Comment by shaneelprakash2910** [comment] 2020-06-17 09:03
Thanks Frank.

**Comment by MateStrysewskeSym** [comment] 2020-06-17 10:53
@shaneelprakash2910 Can you have a look at the case that you were trying to create the sample for and tell me:

1) whether it has a district set
2) whether it has a surveillance officer set
and if 2 is true, then
2a) whether the surveillance officer has a district set?

**Comment by bernardsilenou** [comment] 2020-06-18 00:08
@MateStrysewskeSym I tested for many and all works fine for me.

**Comment by MateStrysewskeSym** [comment] 2020-06-18 06:07
@bernardsilenou Yeah, my suspicion right now is that it generally works, but there's at least one case or user in the system @shaneelprakash2910 is using that for some reason has missing data. I'd like to confirm this though.

**Comment by shaneelprakash2910** [comment] 2020-06-18 06:24
Hi Bernard and Mate,

Can we have a Skype call in 2hours time.

The save button works but  for some record it giving out that error message.

We did the check for missing districts but seems like that is not the case.

This error is for both Sample and contact data and we are yet to check
others.

Kind regards,
SP

**Comment by MateStrysewskeSym** [comment] 2020-06-18 07:02
@shaneelprakash2910 I'm not available in two hours, unfortunately. Later today would work for me. Are you using a publicly available demo system that I could have a look at or is it a production server/local system?

**Comment by shaneelprakash2910** [comment] 2020-06-18 07:18
Ok thanks Mate.

This happens to some cases in the production server.

Test server seems to be working fine.

Kind regards,
SP

**Comment by MateStrysewskeSym** [comment] 2020-06-18 07:37
Please run the following SQL queries and tell me whether they produce any results. The log files suggest that this is where the problem lies, so I want to make absolutely sure that it's not the case:

`SELECT DISTINCT ON (users.id) users.id FROM users LEFT JOIN cases ON cases.surveillanceofficer_id = users.id WHERE cases.surveillanceofficer_id = users.id AND users.district_id IS NULL;`

`SELECT id FROM cases WHERE cases.district_id IS NULL;`

**Comment by fhauptmann** [comment] 2020-06-24 06:47
@MateStrysewskeSym : I sent you the query results via email.

**Comment by MateStrysewskeSym** [comment] 2020-06-24 09:47
@fhauptmann Thanks! The problem is that you have five users (those with the IDs that the first query returned) in the database that apparently once were surveillance officers and were assigned to cases, but that aren't surveillance officers anymore. Because of that, these users don't have a district assigned to them anymore, but the system assumes that everyone who's set as the surveillance officer of a case (and these users still are) must have a district.

The quick solution for you is to remove these users as surveillance officers from all cases they are assigned to. You can use the following query to identify these cases and then open them in the web view and assign a new (or no) surveillance officer:

SELECT uuid FROM cases WHERE cases.surveillanceofficer_id IN (133, 137, 139, 485, 665);

**Comment by MateStrysewskeSym** [comment] 2020-06-24 09:50
The solution we need to provide to make sure that this doesn't happen again is:

- [ ] When changing the user roles of a user in a way that removes the district jurisdiction from them and clicking on "Save", search for any cases that the user is assigned to as surveillance officer or any contacts that they are assigned to as contact officer and display a warning that the user will be removed from these cases/contacts. Let the user abort the saving process.
- [ ] If the user continues, remove the edited user from any cases/contacts they are assigned to

**Closed** 2020-06-25 07:14 UTC
Labels: Users & Rights, bug

**Comment by StefanKock** [comment] 2020-07-08 06:13
Reviewed

**Comment by StefanKock** [comment] 2020-07-17 06:18
Typical StackTraces:
```
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.caze.CaseFacadeEjb.onCaseChanged(CaseFacadeEjb.java:1324)
at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1218)
at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1192)
```
```
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.caze.CaseFacadeEjb.onCaseChanged(CaseFacadeEjb.java:1328)
at sun.reflect.GeneratedMethodAccessor2456.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```
