### ISSUE TITLE
Error is thrown on the Dashboard of a non-German instance when the user selects a Disease that has a Case with one of the Germany-exclusive confirmed classifications

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9839] opened 2022-07-13 18:53 UTC
### Bug Description
When creating a Case with one of the Germany-exclusive confirmed classifications on an instance configured with locale de-DE, then switching to another locale (e.g. EN or FR), an error is thrown when the user selects the Case's disease on the Dashboard if the Case is part of the selected epi week.
It was probably caused by #9659.

### Steps to Reproduce

1. Log in on an instance configured with de-DE country locale.
2. Create at least one Case for Anthrax and select a  Germany-exclusive confirmed classifications (eg. Confirmed with unknown symptoms or Confirmed with no symptoms).
3. Switch the country locale to EN or FR.
4. Navigate to the Dashboard;
5. Select the epi week that the Case is part of, and then click on the Anthrax disease;

### Expected Behavior
The disease should be selected and the values should be displayed accordingly;

### Actual Behavior
An error is thrown.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/178809036-e4877589-3399-4ee9-8cfc-b0c20a0780f9.png)
![image](https://user-images.githubusercontent.com/89522688/178809050-bc1e01e4-c66b-4bff-b590-59d7a64e1b0d.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.74.0-SNAPSHOT (57c7fde)
* Android version/Browser: Chrome
* Server URL: local instance
* User Role: Admin, NatUser

**Comment by syntakker** [comment] 2022-07-19 14:24
This is issue is a duplicate of #9850, fixed by PR #9890 on branch [hotfix-1.74.1](https://github.com/hzi-braunschweig/SORMAS-Project/tree/hotfix-1.74.1).

**Comment by MateStrysewske** [comment] 2022-08-03 08:57
@roxanamlendea Can you please confirm that this issue has been resolved by merging the hotfix branch into development (i.e. on 1.75.0-SNAPSHOT)?

**Closed** 2022-08-03 13:30 UTC
Labels: duplicate
