### ISSUE TITLE
Merge duplicate functionality in contacts directory

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2350] opened 2020-06-19 04:46 UTC
### Feature Description
There should be a merge duplicate functionality in the contact directory same as it exists for the case directory @MateStrysewskeSym @bernardsilenou

**Comment by MateStrysewske** [comment] 2021-06-25 10:05
Duplicate of #2409

**Closed by MateStrysewske** 2021-06-25 10:05 UTC
Labels: duplicate
