### ISSUE TITLE
SEVERE log entry after upgrading to payara 5.2021.10: No valid EE environment [2]

### ISSUE THREAD

**Issue by nliakm** [hzi-braunschweig/SORMAS-Project#7705] opened 2022-01-18 15:02 UTC
### Bug Description
After updating to payara 5.2021.10, following log message occurs every minute:
```
[2022-01-18T15:58:27.171+0100] [Payara 5.2021.10] [SEVERE] [] [] [tid: _ThreadID=206 _ThreadName=http-thread-pool::http-listener-1(13)] [timeMillis: 1642517907171] [levelValue: 1000] [[
  No valid EE environment for injection of org.glassfish.cdi.transaction.TransactionScopedCDIEventHelperImpl]]
```
Can anybody tell what this means and how to get rid of it.

### Steps to reproduce
1. Deploy SORMAS with payara version 5.2021.10
2. Follow the logs. After some time this message will show up every minute
### System Details

* SORMAS version: 1.67-SNAPSHOT (dockerized with Payara version 5.2021.10)
* Came with Payara update #4601

**Comment by JonasCir** [comment] 2022-01-19 08:33
I saw this locally as well, it mostly (not exclusively) shows up for me after an transaction rollback exception.

**Comment by MateStrysewske** [comment] 2022-01-20 12:26
@StefanKock Can you help here?

**Comment by StefanKock** [comment] 2022-01-20 12:28
I did not find the cause, any negative consequence or way to suppress this.

**Comment by StefanKock** [comment] 2022-03-02 11:12
I found two mentionings about this log message:
- https://github.com/payara/Payara/issues/3155 (fixed with 5.192)
- https://github.com/payara/Payara/pull/5369 (fixed with 5.2022.1)

I tested with Payara 5.2022.1, but the message still pops up with every backend invocation (by `vaadin-app` or directly after successful deployment of `sormas-ear`). It does not happen when `CronService.calculateCaseCompletion` runs.

**Comment by StefanKock** [comment] 2022-03-02 13:50
The only `javax.transaction.TransactionScoped` usage is in `AuditContextProducer`.

1. Excluding `ConfigFacadeEjb` did not help.
2. Removing the `@TransactionScoped` helps to get rid of the log message, but it's unclear what now fails.

**Comment by StefanKock** [comment] 2022-03-03 07:40
I tested what effect the removal of `@TransactionScoped` has: The transactionId is then changing with every `AuditLogEntry` persisted, and the `Auditor` is not shared within the transaction which leads to every `AuditLogEntry` as CREATE event with full attributes logged as changed even when I only changed one Case attribute via the `vaadin-app`.

**Comment by StefanKock** [comment] 2022-03-03 07:42
Since there's currently no clear path how to proceed, I changed this ticket to a ' task'

**Comment by rdutu-vg** [comment] 2022-03-18 15:15
@MateStrysewske  @MartinWahnschaffe  @StefanKock @markusmann-vg  
I would like to flag that this fix would be helpful.
Had to investigate API failures from automated tests across test-auto and test-performance environments, and we weren't able to understand the issue due to poor logging level caused by this.
Both environment are affected, and we can't use the logs to determine the failures.

**Comment by StefanKock** [comment] 2022-03-22 15:01
I see currently two possible approaches:
1. Override the weld-integration.jar/[InjectionServicesImpl.class](https://github.com/payara/Payara/blob/master/appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java) without the `System.err`.
2. Change the audit log to not trigger that error message.

**Comment by JonasCir** [comment] 2022-03-23 08:43
If we think it is a bug, we should go for 3. I guess?

**Comment by StefanKock** [comment] 2022-03-24 07:34
I tried to move the `@TransactionScoped` annotation directly to the injected classes, but that did not solve the problem. I will now proceed with providing a patched `weld-integration.jar` that does not print the undesired message.

**Comment by StefanKock** [comment] 2022-03-25 11:44
Due to failing unit tests this ticket cannot make it for 1.70.0

**Comment by StefanKock** [comment] 2022-03-29 13:12
The integration in `sormas-backend` did not work due to conflicts with `bean-test`. I agreed with @MartinWahnschaffe that we will provide directly the patched `weld-integration.jar` into the setup routine. This patch will not needed anymore when the `AuditLog (de.symeda.sormas.backend.auditlog)` is removed within the next months (see #7402).

**Closed** 2022-03-30 09:07 UTC
Labels: backend, technology, change

**Comment by mario-kuehne** [comment] 2022-03-30 13:46
Reproduction of the bug: Reproduced that the error happens before bugfix by testing locally (branch hotfix-1.70.1; commit hash ab25a874ec27bf226f590ba25ce919bb6becbe7e)

Verified ticket in peer testing with @JonasCir on (branch hotfix-1.70.1; commit ed20b1a19e68eb005efbbf4b26bcd57417f0b4ec). SEVERE log entry does not occur anymore in application logs (if `weld-integration.jar` is included in modules folder of Glassfish Path)
