### ISSUE TITLE
Missing strings for custom export of cases & contacts

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4803] opened 2021-03-17 13:14 UTC
### Bug Description
Many strings for the selectable export components are missing so far. 
### Steps to Reproduce
1. create a new custom case or contact export
2. click "new export configuration"
3. view clickable components which are written as variables with missing strings.

### Expected Behavior
All clickable components should be properly translated and not shown as dd variables
### Screenshots
Looks like this for case export:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/76884029/111470409-1c68bd80-8728-11eb-90ad-6ce47a7229e9.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/76884029/111470787-81bcae80-8728-11eb-8846-2872127c8960.png">
Looks like this for contact export:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/76884029/111471850-a2d1cf00-8729-11eb-9020-7605c9b2088e.png">

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/76884029/111472214-0956ed00-872a-11eb-8dcc-433fd2f2d11b.png">

### System Details
* Device: 
* SORMAS version: 1.57.2
* Android version/Browser: chrome
* Server URL:test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment] 2021-03-17 13:36
Duplicate of #4647

**Closed by MateStrysewske** 2021-03-17 13:36 UTC
Labels: bug
