### ISSUE TITLE
Error message when epi data tab is opened

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4072] opened 2021-01-18 19:07 UTC
### Bug Description
- On https://release-international.sormas.netzlink.com/sormas-ui/, the epi data does not have the box for "contact with source case"
- A random error shows up when the tab is opened. This mainly happen for contacts converted to cases.
- Even when the contact resulted from a case, the tab "contact with source case known" can be set to NA, this should not be possible with out unlinking the resulting case from the contact.
### Steps to Reproduce
1. Convert a contact to a case
2. Open the epi data tab of the case
3. It is impossible to edit this tab

### Expected Behavior
- This does not happen on https://test1401.sormas-oegd.de/sormas-ui/

### System Details
* Device: web
* SORMAS version: 1.53
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: Natinal user + admin

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/104954495-9e5a9580-59c8-11eb-9982-89a5ee978af7.png)

**Comment by MateStrysewske** [comment] 2021-01-19 08:03
Duplicate of #3826

**Closed by MateStrysewske** 2021-01-19 08:03 UTC
Labels: bug
