### ISSUE TITLE
Changes in target system are not synced back to source system

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10932] opened 2022-11-16 18:20 UTC
### Bug Description

Sync between target and source system broken.
### Steps to Reproduce

1. share a case/contact with hand over the ownership from release-sormas-x to release-de
2. accept case/contact in target system
3. change something in target system in the case (for example disease variant) / contact
4. observe if sync works in source system
5. change something is target system in the person (for example person name)
6. observe if sync works in source system

### Expected Behavior

Sync works
### System Details

* Device:
* SORMAS version: 1.76.5
* Android version/Browser: Edge
* Server URL: release-sormas-x to release-de
* User Role: admin

**Comment by dragosb-vg** [comment] 2022-11-17 11:04
Unable to replicate issue on reported live environments (**sormas-x** vs. **release-de**).
- checked sharing with ownership cases+contacts.
- modified details both on case/contact info (ex. variants, samples, vaccinations)  and person info (names, gender etc.)
- checked sharing in both directions.

In some rare cases there was an up to 2 mins. delay between the changes in the target system and the update of details in the source system. 


@SahaLinaPrueger, can you please check if the issue is still replicating on your end? Are there any other steps that need to be followed?

I've set up 2 cases with attached contacts already shared (one for each direction):
- sormas-x to release-de: XSLFY4-Q6P62H-M6LH5W-MZ272KIQ
- release-de to sormas-x: QL3XXV-CMOVAF-3AHALV-LTIT2FTA

I also attached a video with the working sync following the steps in the ticket.

https://user-images.githubusercontent.com/111864167/202429789-5a6c3dec-5158-4ede-ac91-8df2af52c0fc.mp4

**Comment by leventegal-she** [comment] 2022-11-17 14:34
I couldn't reproduce on my local system.

**Comment by JaquM-HZI** [comment] 2022-11-18 09:08
it was a problem with server configurations, so I close this. Thanks

**Closed by JaquM-HZI** 2022-11-18 09:08 UTC
Labels: contacts, cases, backend, hotfix, feedback, s2s, finding
