### ISSUE TITLE
Hide the item "if quarantine is possible" for international users

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2096] opened 2020-05-14 06:57 UTC
### Situation Description
@bernardsilenou 
Please add some more info.
What does international users mean? and how do we ensure, that we don't have to make it visible again or confuse users that are currently using it.

**Comment by MartinWahnschaffeSymeda** [comment] 2020-05-14 06:59
Duplicate of #2095

**Closed by MartinWahnschaffeSymeda** 2020-05-14 06:59 UTC
