### ISSUE TITLE
contact dashboard takes very long to load

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1915] opened 2020-04-24 11:38 UTC
### Bug Description
Most of the times, it keeps displaying "Server connection lost, trying to reconnect" and nothing happens. Few times, it loads completely albeit taking so long. On average, it takes about ten minutes.

### Steps to Reproduce
1. Go to the Contacts Dashboard

### Expected Behavior
Content should load completely without error

### Screenshots
![image](https://user-images.githubusercontent.com/1176692/80205271-d7243480-8619-11ea-8b12-33ef5df71c74.png)

### System Details
* Device: labtop
* SORMAS version: 1.38.0
* Android version/Browser: Chrome

### Additional Information
I think it has to do with the ever-growing database, because this issue only happens on the production server but not on the test server. The test server doesn't have much data.

**Comment by ChristopherRiedelSymeda** [comment] 2020-04-24 12:32
Is duplicate of #1839

**Closed by ChristopherRiedelSymeda** 2020-04-24 12:32 UTC
Labels: duplicate

**Comment by MateStrysewskeSym** [comment] 2020-04-24 13:37
@faatihi Please have a look at the existing issues first before opening new ones to avoid duplicates.
