### ISSUE TITLE
User rights should be not defined indivdually, not by pre-defined roles

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3748] opened 2020-12-11 06:42 UTC
### Feature Description

The rights for users should be defined individually, by groups like this excample from another software:

![Anmerkung 2020-12-11 073614](https://user-images.githubusercontent.com/74791118/101871307-a16d9500-3b83-11eb-802e-4bcda74aea50.png)

Every user get a membership in one or more group, depending on their duties in the health office.

### Problem Description

Currently the user rights are bounded to pre-defined roles. This causes that mostly the user gets more rights as needed, if they only one right of a higher role.  (e.g. they get the National user to see cases/contacts without a filled field for responsible district). This was also mentioned in another issue already.

This is not conform with the data protection. 

### Proposed Change

Changing the user rights model from pre-defined to an individual rights management.

**Comment by bernardsilenou** [comment] 2020-12-11 20:17
@Marko-ilmkreis Thanks for raising this issue. I have this in our road map.

**Comment by bernardsilenou** [comment] 2020-12-11 20:18
Duplicate of #898

**Closed** 2020-12-11 20:18 UTC
Labels: change
