### ISSUE TITLE
Dashboard for Contact Supervisor [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#460] opened 2018-01-08 10:58 UTC
The contact supversior wants to see a summary on contacts and visits.

- [x] Clarify on how and why the contact supervisor uses this.

This should be added to the existing dashboard and be visible together with tasks, epi curve and contacts map.

Design Mockup for unfiltered view (default):
![grafik](https://user-images.githubusercontent.com/23217632/34668043-f131fd4a-f46b-11e7-970e-5398690a960a.png)

Design Mockup for filter view (disease selected):
![grafik](https://user-images.githubusercontent.com/23217632/38880433-045fd688-4266-11e8-8431-ff2592fa4808.png)

**Comment by hzi-braunschweig** [comment] 2018-01-08 12:30
@MartinWahnschaffeSymeda 
Everyday, during an outbreak, a contact supervisor would like to see all contacts currently under follow up and which contact officers are assigned to them. 
He would like to know how many days are left for follow up for each contact with respect to the proportion of visits conducted vs visits not conducted. 
Based on the above information, he is able to also assign and reassign contact officers as the case maybe especially if he is able to see contacts who have been lost to follow up and those who have completed followup.

Also on the dashboard, it is important to show contacts who have become symptomatic with a notification to the contact supervisor and an email plus text if possible. But it is important to have this on the dashboard as well. A red marker showing contacts who have become sick as well.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-01-23 15:05
@hzi-braunschweig 
Please provide details on the contact bar chart needed for the contact supervisor dashboard.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-04-17 15:37
![grafik](https://user-images.githubusercontent.com/23217632/38880433-045fd688-4266-11e8-8431-ff2592fa4808.png)

Some additional notes:

- [ ] use contact classificaiton and status (separate now)

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-27 13:52
#597 may also be relevant for the contact supervisor dashboard.

**Comment by hzi-braunschweig** [comment] 2018-08-06 09:38
I think we should think about the chains of transmission looking at variables of interest (VOI) like date of last contact, contact vs case relationship (source case vs contact), date of contact converted to case and date of onset etc. We can show on the dashboard a chart with these relationships.  lets discuss this further tommorow @bernardsilenou @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-07 14:17
Diagram with 4 options:
- [ ] epi curve as-is (cases by date)
- [ ] contacts by date of last contact (contactDate)
- [ ] number of contacts by district (LGA) and case (allow user to select the grouping; probably auto select cases when filterted to a district)
- [ ] contacts that finished follow-up by "follow-up until"

**Comment by FredrikSchaefer** [comment] 2018-08-27 07:06
I've created new mockups based on above comment. There are a few things to be discussed, though, which I'll bring up in the next meeting. Maybe you also have questions or remarks? @MateStrysewskeSym  @bernardsilenou

![sormas mockup 1920x1080 dashboard contact supervisor - all v3_epicurve_cut](https://user-images.githubusercontent.com/39280314/44645290-69a0aa80-a9d7-11e8-98ee-4e0991199fa5.jpg)

![sormas mockup 1920x1080 dashboard contact supervisor - all v3_contactsper_cut](https://user-images.githubusercontent.com/39280314/44645294-6b6a6e00-a9d7-11e8-9d45-57566d1b2d9e.jpg)

![sormas mockup 1920x1080 dashboard contact supervisor - all v3_contactdate_cut](https://user-images.githubusercontent.com/39280314/44645304-6d343180-a9d7-11e8-9ad2-154a44f14f10.jpg)

![sormas mockup 1920x1080 dashboard contact supervisor - all v3_followupuntil_cut](https://user-images.githubusercontent.com/39280314/44645306-6e655e80-a9d7-11e8-956a-b8d3d6674ff1.jpg)

![sormas mockup 1920x1080 dashboard contact supervisor - filtered v3_cut](https://user-images.githubusercontent.com/39280314/44645308-6f968b80-a9d7-11e8-881b-e64cf390a7cb.jpg)

**Comment by FredrikSchaefer** [comment] 2018-09-14 08:37
There are some things to be clarified here:

* The choice for the diagram type currently is realized with buttons. Shall it be a dropdown-menu instead?
* For the diagram type "Contacts per Disctrict": What is the reference date/timeframe for the contacts? It should be compatible to numbers in the upper view (I call it sections).
* For the diagram type "F/U Until": Should it involve numbers for days in the future? If not, this should be emphasized with a small infotext or with a caption like "Followed Up". 
* For the diagram type "F/U Until":  Should a classification (Completed F/U, converted to case...) be included for days in the past?
* For the "Important Contacts" section: which time reference is to be used? One contact can be "not seen for last 24 h" and then later symptomatic in the same day/week/month.
*In the view for just one disease. some information appears twice. Sections "Important Contacts" and "Contact Visits" both have "Not Cooperative"/"Available, Uncooperative", for example. What to  do about it?

**Comment by MartinWahnschaffeSymeda** [comment] 2018-09-20 13:16
Use "Key Contacts" instead of "Important Contacts"

**Comment by MartinWahnschaffeSymeda** [comment] 2018-09-25 14:52
Additions from Bernard and the last review:

== General
- [ ] "From onset week" should be changed to "from week" and to onset week changed to "to week" because contact do not have onset date like cases.
- [ ] date filter uses follow-up period of contacts
- [ ] Delete "for week 44" below each icon because it takes more space. The Surveillance dashboard does not have this.
- [ ] ALL numbers should have proportions added if possible with denominator used. eg "by contact status" do not have proportions but just numbers
- [ ] add tooltips for items that need explanation

== Key contacts
- [ ] Use "Key Contacts" instead of "Important Contacts"
- [ ] Delete not cooperative ~and symptomatic~ because they appear in other sections. This we can replace later with other indicators
- [ ] don't display workload
- [ ] Display not cooperative contacts in a line on their own: Contacts with uncooperative visits: 1, 2, 3, >3

== All contacts
- [ ] "By contact status" changed to "contact status", we can delete by in classification also, to gain more space
- [ ] delete "contact conversion" and "conversion to case" this is bc they already apear under contact status
 
== Follow-up status
- [ ] Change "contacts follow up" to "follow-up status" just as in the app
- [ ] Add fourth category called "cancel follow-up" or "cancel f/u" just as in app
- [ ] Use lines instead of circles as items. This is because each of these categories can't be 100% is complete circle. OR we can use one circle with the different categories colored differently
 
== Follow-up visits
- [ ] Contact visits changed to "follow-up visits" # generally we should use the same names as in the app 
- [ ] the follow-up visits column can be divided into 2 sub columns, one for "visited" and another for "missed". The "visited" column will further be classified as
"cooperative", "uncooperative" and "unavailable". the denominator in calculating proportions of "cooperative", "uncooperative" and "unavailable" will 
only be the number of visit- ie exclude the missed visits.

== Diagrams
- [ ] Add another category "completed follow-up"
- [ ] change follow up to "under follow-up"
- [ ] Rename "Follow-up until" to "Follow-up completed"
- [ ] add another diagram: Number of contacts being followed up stacked by: cooperative, uncooperative, not available, no visit done

== Other ideas of graphs to add
* bar plot or distribution (mean, max , min, etc) of number of contacts per case
* bar plot or distribution of number of contacts per contact officer
* Bar plot of number of visits per contact person colored on categories of "visits done, missed, remaining visits"

== Not clear
* Date used for time on the main page should be by default the current date, not onset or date of last contact. user should be able to choose by date of last contact if the want but Never by onset date.  because onset date is for cases.
* Change default today in search icon to last 24 hours at back end so that we can remove "not seen for the last 24 hours icon"
* Date search should be customized based on date of last contact with case OR by calendar date. Default should be calendar date.
The calendar date can be broken down into: today () ie last 24 hrs, yesterday, last week etc as in the SS dashboard

**Comment by FredrikSchaefer** [comment] 2018-10-05 09:49
### All Diseases

![sormas mockup 1920x1080 dashboard contact supervisor - all v4](https://user-images.githubusercontent.com/39280314/46528313-d8eda200-c893-11e8-9e69-21cff54e4e3e.png)

### All Diseases (Custom Box Expanded)

![sormas mockup 1920x1080 dashboard contact supervisor - all v4 custom_box_expanded](https://user-images.githubusercontent.com/39280314/46528316-dc812900-c893-11e8-9bcb-945100a8e62c.png)

### One Disease

![sormas mockup 1920x1080 dashboard contact supervisor - detailed v4](https://user-images.githubusercontent.com/39280314/46528321-dee38300-c893-11e8-981c-fe99e8dfd0c2.png)

These are preliminary mockups which should include all changes of above comments that I could implement alone. The rest can be done after I clarified with Symeda.

**Comment by MateStrysewskeSym** [comment] 2018-10-19 11:11
- [ ] make sure that creating more visits than the follow-up period days doesn't result in negative missed visits
- [ ] add info to dashboard on how follow-up status is calculated

**Closed** 2018-10-22 12:53 UTC
Labels: 10250, Contact Tracing, Dashboard, discuss

**Comment by bernardsilenou** [comment] 2019-03-22 12:11
Here are some suggestions to consider when reviewing contact officers dashboard that came up during the meeting with Nigerian team on March 18, 2019 :

1) Delete the whole section on "Follow-Up Situation" because it classify contacts person based on visits attributes.
2) All Contacts: Delete "NEW" since it has no reference calendar date point. Delete "SYMPTOMATIC"  or do not classify it as part on contact classification because a person can be both confirmed contact and symptomatic at the same time, in this way the portions do not add up to 100%
3) "Under follow up proportions" are not well calculated
4) more on figure, eg under "All Contacts" SYMPTOMATIC is 1 person and under "Contact Follow-Up" converted to case is 0
5) contacts cannot be selected by diseases, we need to add this filter

[contactDashboardNigearia.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2996368/contactDashboardNigearia.docx)
