### ISSUE TITLE
Create zero report function for DSNO

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#876] opened 2018-11-09 16:18 UTC
In order to evalute the use of SORMAS in Nigeria, it is **urgent and imprtant** to have the  zero reports functionality for DSNO's.

**Comment by foyiri** [comment] 2018-11-19 16:13
please when can we have this i think it critical for the performance indicator we are looking at for the 8 state we have deployed so far

**Comment by hzi-braunschweig** [comment] 2018-11-21 08:04
@MartinWahnschaffeSymeda We should also discuss this at 15:00 even for Ghana it is important

Thanks

**Comment by MartinWahnschaffeSymeda** [comment] 2018-11-23 07:44
Duplicate of #610

**Closed by MartinWahnschaffeSymeda** 2018-11-23 07:44 UTC
