### ISSUE TITLE
Unify pathogen test saving logic between cases, contacts and event participants [1]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#5816] opened 2021-06-16 10:45 UTC
### Bug Description

Process a positive pathogen tests on contacts does not trigger the question of whether the entire sample is updated to positive.
### Steps to Reproduce

1. Proceess a positive pathogen test via LBDS with creating a contact
2. Save the positive pathogen test
3. The sample result stays pending and updating window does not appear.

### Expected Behavior

With cases it works fine, that the systems ask whether you want to update the sample to positive as well or not.
### Screenshots

![bug Probe Ausstehend](https://user-images.githubusercontent.com/78568406/122205545-a7309400-cea0-11eb-9319-c8cdfe8e9d17.PNG)

### System Details

* Device:
* SORMAS version: 1.60/1.61 (test-de1)
* Android version/Browser:
* Server URL:
* User Role: admin, National User

### Developer Specifications

The implementation follows the rules of [this comment](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5816#issuecomment-909094352)

**Comment by MateStrysewske** [comment] 2021-06-16 10:55
@JaquM This is not a bug, but simply a feature that has not yet been introduced for contact samples :)

**Comment by JaquM** [comment] 2021-06-16 10:58
@MateStrysewske so the feature is just implemented for cases and event participants, but not for contacts?

**Comment by MateStrysewske** [comment] 2021-06-16 11:06
@JaquM If I'm not mistaken (judging by the code), we ask the user whether to update the pathogen test result of the sample for cases, and we simply update it for event participants; seems like the logic is not really consistent between cases, contacts and event participants.

**Comment by JaquM** [comment] 2021-06-16 11:09
Alright, so I'll add it to prioritization and maybe we'll have it consistent at the end :-)

**Comment by DavidBaldsiefen** [comment] 2021-08-23 09:50
@JaquM @MateStrysewske could you maybe specify? I get the expected popup both for cases, contacts and eventparticipants. The only case where I am not asked to update the entire sample is when creating sample&pathogentest in one go, which seems like intended behaviour to me

**Comment by kwa20** [comment] 2021-08-23 10:07
@DavidBaldsiefen The main goal is to make the process of updating samples and pathogen tests consistent across the entities. For contacts this would mean:

- If the user enters a positive pathogen test result for an existing sample, prompt the user and ask if they want to update the final laboratory test of the sample accordingly
- If the final lab result is positive, prompt the user if they want to create a case for that disease for that contact person

- If a user creates a sample and a pathogen test at the same time, prompt the user with the same messages as when they do it consecutively

**Comment by DavidBaldsiefen** [comment] 2021-08-24 08:56
@kwa20 Alright, thanks for the clarification!
I have a followup question: Should the "Convert eventparticipant/contact to case" popup only appear if the final *sample* result is positive? In practice, if I create a new sample and also pathogentest, and I am prompted whether or not I want to change the final _sample_ result, AND I select _no_, should the conversion-popup still appear? 

In any case, the conversion-popup currently only appears if `TestResult==Positive  && testResultVerified`, while the "change sample result" popup always appears when `sampleResult!=pathogenTestResult`

**Comment by kwa20** [comment] 2021-08-24 10:46
@DavidBaldsiefen 

> I have a followup question: Should the "Convert eventparticipant/contact to case" popup only appear if the final sample result is positive? In practice, if I create a new sample and also pathogentest, and I am prompted whether or not I want to change the final sample result, AND I select no, should the conversion-popup still appear?

I think asking the user as long as a pathogen test is positive is fine. The only problem I see currently is that the final lab result will stay pending if the user starts to create a case. I suggest to change the final lab result to positive if the user creates a case through the pop-up (this information should be added in the pop-up like "Creating a case will automatically set the final lab result of the sample to positive." 
- If users choose to not create a case, the pop-up if the final lab result of the sample should be changed can appear with the above condition.

**Comment by bernardsilenou** [comment] 2021-08-24 11:59
@kwa20
Quentin please: Its about `if I create a new sample and also pathogentest, and I am prompted whether or not I want to change the final sample result, AND I select no, should the conversion-popup still appear?`
- Is there a reason to prompt the creation of a case when the user refuse to update the final result of the sample? 
- If not, then would suggest we prompt the creation of case if final results of sample is updated to "positive" only, not based on the pathogen test results
- If user manually update the final result of the sample to positive, without creating a pathogen test, then we can also prompt the creating of a case (suggest we add this to the specification)
- In this way, we do not need to change the final result of the sample; Is this fine by you?

**Comment by kwa20** [comment] 2021-08-24 12:13
@bernardsilenou I think the way I described it above would reduce the amount of pop-ups needed by assuming that if someone creates a case for a contact or event participant, the final lab result for the sample should be positive. If they decline, they'll manually have to adjust it.

**Comment by bernardsilenou** [comment] 2021-08-24 15:34
@kwa20 Maybe I now understand you, if not then lets have a short call pls.
Do you mean that when the user record a positive test, then we automatically ask them to convert the ep or contact to case, without first asking if they need to edit the final lab result of the sample?
- if they accept, then create case and set final lab result of sample to +
- if they refuse to create a case, then ask if they want to up final lab result of sample to + ?
- Any option is fine, the only drawback i can see with this design is that some users may not read all text in pop up to know that final result would be updated. Is having this extra step too much? the final result of a sample is a very sensitive information and it is good that users actively check it.
- We should have a logic that applies the suggested method when the disease of sample entity and that of test result are not the same, but if the diseases are the same, then it would be good to first update the final result before taking further actions: update classification (for case) or create case (for contact and ep)
- eg if a sample from a covid contact is tested + for influenza, then we trigger the creation of influenza case based on test result and maintain sample for covid as pending. But if tested + for covid, we update final result of sample to + and create a covid case

**Comment by DavidBaldsiefen** [comment] 2021-08-30 11:36
To sum up what I understood, for clarification:

Assuming the user adds a negative pathogentest (confirmed by lab supervisor):
- pathogentest-disease equals disease of current entity:
  - ask user if sample result should also be changed to negative
- pathogentest-disease differs from disease of current entity:
  - do nothing

Assuming the user adds a positive pathogentest (confirmed by lab supervisor):

- pathogentest-disease equals disease of current entity:
  - Cases: Ask user if sample-result should also be changed, update classification
  - Contacts/EPs: Suggest creating a case. If YES: set sample result to positive automatically. If NO: Ask user wether sample result should be changed to positive.
- pathogentest-disease differs from disease of current entity:
  - Cases: Suggest creating a new case for that disease. Sample result remains pending
  - Contacts/EPs: Suggest creating a case. Sample result remains pending


In any case, creating a sample and pathogentest in one go should behave identical to creating them in two steps.


@bernardsilenou @kwa20

**Comment by bernardsilenou** [comment] 2021-08-30 15:15
@DavidBaldsiefen  @kwa20  This specificatioin https://github.com/hzi-braunschweig/SORMAS-Project/issues/5816#issuecomment-908269347 looks good. I would just add some few comments that may be obvious
> 
> Assuming the user adds a negative pathogentest (confirmed by lab supervisor):
> 
> * pathogentest-disease equals disease of current entity:
>   
>   * ask user if sample result should also be changed to negative  `If previous state of sample result differs from current test result`
* `Cases: ask user if sample result should also be changed to negative  If previous state of sample result differs from current test result, but only update case classification if sample collection date - most relevant date < 30. The reason for this additional constrain is that once a case is confirmed, it should stay confirmed, ie a second sample of the the case person with a negative test should not result in reclassifying the case as not-a-case`
> * pathogentest-disease differs from disease of current entity:
>   
>   * do nothing
> 
> Assuming the user adds a positive pathogentest (confirmed by lab supervisor):
> 
> * pathogentest-disease equals disease of current entity:
>   
>   * Cases: Ask user if sample-result should also be changed, update classification `if sample collection date - onset/ most relevant date <30. For all updating case classification, we can additionally check for this condition, and if false, we update sample result only`
>   * Contacts/EPs: Suggest creating a case. If YES: set sample result to positive automatically ` and case classification to confirmed`. If NO: Ask user whether sample result should be changed to positive.
> * pathogentest-disease differs from disease of current entity:
>   
>   * Cases: Suggest creating a new case for that disease  `and set case classification to confirmed`. Sample result remains pending. `Here we have to 'clone the sample'`@MateStrysewske `can add more about this. However, the initial sample would stay pending and the cloned sample would be linked to the new case and stay positive.`
>   * Contacts/EPs: Suggest creating a case. Sample result remains pending `The same as for contact, we need  a way to clone the sample and assigned a positive sample result to the cloned copy of the sample linked to the new confirmed case created`
> 
> In any case, creating a sample and pathogentest in one go should behave identical to creating them in two steps.
> 
> @bernardsilenou @kwa20

**Comment by bernardsilenou** [comment] 2021-08-30 15:17
Since this issue is only about contacts, then maybe most  of the comment that I added does not apply here!

**Comment by DavidBaldsiefen** [comment] 2021-08-31 07:57
I think the whole "cloning samples" is out of scope for this issue, and should be handled in #4472

The other stuff is somewhat in scope, as this issue is also about streamlining the process, however it is much more than what was originally estimated.

**Comment by DavidBaldsiefen** [comment] 2021-08-31 10:09
This is what I'll implement:

**Cases:**
```
// 1. If pathogentestresult negative AND confirmed
// 1.1 If Diseases equal: ask user whether to update sampleResult (if sampleResult != pathogenTestResult)
// 1.1.1 if yes, update case classification if (sampleCollectionDate - mostRelevantDate < 30)
// 1.2 if Diseases do not Equal: do nothing

// 2. If pathogentestresult positive AND confirmed
// 2.1 If Diseases Equal: ask user if sampleResult should be updated, change classification if (sampleCollectionDate - mostRelevantDate < 30)
// 2.2 If Diseases do not Equal: Suggest creating new case for that disease and set classification of the new case to confirmed. SampleResult remains unchanged
```

**Contacts:**
```
// 1. If pathogentestresult negative AND confirmed
// 1.1 If Diseases equal: ask user whether to update sampleResult (if sampleResult != pathogenTestResult)
// 1.2 if Diseases do not Equal: do nothing

// 2. If pathogentestresult positive AND confirmed
// 2.1 If Diseases Equal: Suggest converting to Case. 
// 2.1.1 If Yes, set sampleResult to positive & caseClassification to confirmed
// 2.1.2 If No, ask user whether to update sampleResult to positive
// 2.2 If Diseases do not Equal: Suggest creating new case for that disease and set classification of the new case to confirmed. SampleResult remains unchanged
```

**Event Participants:**
```
// 1. If pathogentestresult negative AND confirmed
// 1.1 If Diseases equal: ask user whether to update sampleResult (if sampleResult != pathogenTestResult)
// 1.2 if Diseases do not Equal: do nothing

// 2. If pathogentestresult positive AND confirmed
// 2.1 If Diseases Equal: Suggest creating a case
// 2.1.1 If Yes, set sampleResult to positive & caseClassification to confirmed
// 2.1.2 If No, ask user whether to update sampleResult to positive
// 2.2 If Diseases do not Equal: Suggest creating new case for that disease and set classification of the new case to confirmed. SampleResult remains unchanged
```



@bernardsilenou your requests regarding cloning samples would require some further discussion and should be handled in #4472

**Comment by bernardsilenou** [comment] 2021-08-31 19:18
@DavidBaldsiefen 
This specification looks structured and organised. Thanks

I also agree that we drop the cloning part. I just have some minor comments to make:

> 1.1.1 if yes, update case classification to probable  `probable is not based on a confirmed negative lab result but on epi link (exposure, contacts, etc)`

1.1.1 if yes, ask user if they want to update case classification to `not a case`.  
          If yes, set to not a case, if not, maintain current state of case classification.

> 2.1 If Diseases Equal: ask user if sampleResult should be updated, change classification if yes & (sampleCollectionDate - mostRelevantDate < 30)

2.1 If Diseases Equal: ask user if sampleResult should be updated, change classification to confirmed if yes & (sampleCollectionDate - mostRelevantDate < 30)

> 2.1.1 If Disease Variant does not equal: show dialogue suggesting changing the variant

This is a delicate feature to add at this point because if a disease variance has been added to the case and the pathogen test have unknown or Null variant, this would then override the existing one. I wold suggest we change to " if (disease variant of case is NA or Null and that of pathogen test is not NA or Null)".  
I did a test with 1.63 and realized that for each pathogen test saved, the user has to respond to many pop ups (update sample results, case classification, disease variants, ...), more than 2 popups may not be user friendly since the initial goal of the user is just to record sample result. 
Since the sample is linked to the case,  do we need to boarder about updating variant at this point when it can be updated at any time? I would prefer  we do not include this feature here but add it as a bulk edit action for cases, ie update variant of case with that of the pathogen test of the samples of the case.

If the final decision is to add it here, then we also need to add this validation when converting contact or ep to case (Contacts: 2.1.1, 2.2 and  Event Participants: 2.1.1, 2.2 ) in order that all cases have a variant that matches with that of the test results.
 @kwa20  What do you think?

**Comment by MateStrysewske** [comment] 2021-09-01 08:39
Additional changes that I'll implement:
- Remove the classification changes (because those are handled in the classification calculation of the case)
- Extend the text when asking user to convert contact to case with information that sample result will be updated to positive
- For event participants, if the event has no disease and there's a positive and confirmed pathogen test result, ask the user to set the sample result to positive

**Closed** 2021-09-02 16:35 UTC
Labels: contacts, laboratory, vaadin-app, feature

**Comment by maxiheyner** [comment] 2021-09-20 07:32
ISSUE TRACKER COMMENT
