### ISSUE TITLE
Leap year error: Unable to save date of birth (29.02.1988)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2266] opened 2020-06-05 09:36 UTC
### Bug Description
As described above, if 29.02.1988 is entered as date of birth, the day remains empty.

### Steps to Reproduce
1. Create case or contact, or change date of birth of existing person to 29.02.1988
2. Save changes
3. See that day field remains clear

### System Details
* Device: Web
* SORMAS version: 1.41

**Comment by bernardsilenou** [comment] 2020-06-05 20:53
Funny bug!

**Comment by MateStrysewskeSym** [comment] 2020-06-08 09:54
@max-hzi What exactly is the problem here? 1998 was no leap year, so it's expected that 29.02.1998 can't be selected as the 29 isn't part of the dropdown.

**Comment by bernardsilenou** [comment] 2020-06-08 17:18
@MateStrysewskeSym ur right, 1988 is a false leap year.
read this link:
<https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-a-leap-year#:~:text=Any%20year%20that%20is%20evenly,and%201996%20are%20leap%20years.>

**Comment by max-hzi** [comment] 2020-06-18 07:32
@MateStrysewskeSym Yes, sorry, I meant 1988. The request I received was for 1988, I confirmed it in sormas with 1988 but incorretly typed 1998 in this Issue.
The problem remains in 1.42.3. Please re-open.

**Comment by xavier-calland** [comment] 2020-06-19 06:06
What I see, `PersonEditForm.updateListOfDays()` is called twice during loading.

The first time (when the month is set in the form) with year=null and month=2. That sets the list with 1 to 28 (it uses year 2010 https://github.com/hzi-braunschweig/SORMAS-Project/blob/89ab3c4b334a8197d05649f3fb59ee53f2d06e62/sormas-api/src/main/java/de/symeda/sormas/api/utils/DateHelper.java#L256) → when the select is updated https://github.com/hzi-braunschweig/SORMAS-Project/blob/89ab3c4b334a8197d05649f3fb59ee53f2d06e62/sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java#L455 sets the value to `null`

The second time (when the year is set in the form) with year=1988 and month=2. That sets the list with 1 to 29, but the value is has been lost previously → the value is still `null`.

**Comment by StefanKock** [comment] 2020-06-22 12:34
Edited the original post to match the reported problem.

**Comment by StefanKock** [comment] 2020-06-22 14:17
The problem is happening after binding and persisting on the re-bind to update the view (or opening the view with data loade from the backend)
The binding binds in this order `birthdateDD` (1), `birthdateMM` (2), `birthdateYYYY` (3) (alphanumeric order), and step 2 resets `birthdateDD` prior the year can be evaluated in the form.
Possible workaround: Allow "Feb 29" when `year == null`  in `DateHelper.getDaysInMonth`.

**Comment by StefanKock** [comment] 2020-06-22 14:49
> Possible workaround: Allow "Feb 29" when `year == null` in `DateHelper.getDaysInMonth`.

Agreed with @MateStrysewskeSym that is the way to go.

**Comment by StefanKock** [comment] 2020-06-23 06:09
I tested it successfully for create and edit. It is already merged on development.
@MateStrysewskeSym please review.

**Closed by StefanKock** 2020-06-23 06:09 UTC
Labels: bug, sormas-ui
