### ISSUE TITLE
[CLIMEDO Integration] Automatically authenticate in CLIMEDO when opening the page for a registered patient [0.5]

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3201] opened 2020-10-15 13:40 UTC
### Feature Description
After registering a person from SORMAS as a CLIMEDO patient, we may click the Patient Diary button in the contact page the access the related CLIMEDO page for that patient.

### Problem Description
When the button is clicked, the user is first redirected to a login page for CLIMEDO. This means that the user needs to either have a CLIMEDO account with sufficient rights or use the generic SORMAS account to access the patient page.

### Proposed Change
When redirecting to the CLIMEDO patient page, automatically authenticate using the access token obtained from the backend. In this way, the switch between the two systems becomes seamless and the user doesn't need any additional accounts.

### Additional Information
Currently, when clicking the button the redirect is done to the following URL:
`https://<<subdomain>>.climedo.de/de/studies/5f60d22772f71c001158cea6/enroll?personUuid=<<personUuid>>`

After the update, the redirect should be done the the following URL:
`https://<<subdomain>>.climedo.de/de/studies/5f60d22772f71c001158cea6/data?q=<<personUuid>>&token=<<tokenValue>>`

**Comment by AndyBakcsy-she** [comment] 2020-11-20 12:46
Tried to verify this issue on SORMAS Version: 1.52.0-SNAPSHOT  from the Environment: https://ga1.sormas-oegd.de/sormas-ui/
![image](https://user-images.githubusercontent.com/70562142/99801558-eaab6580-2b3e-11eb-963a-126462ae0cf8.png)

It might be an issue of configuration or the user has not enough rights

**Comment by vidi42** [comment] 2020-11-24 11:52
Issue was caused by an older version of Climedo being deployed. It should be fixed now.

**Closed** 2020-11-24 11:52 UTC
Labels: SSD, change, sormas-ui
