### ISSUE TITLE
"Ok" button on previous hospitalization form on Mobile app (SO user account) not behaving ideally

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2825] opened 2020-09-07 00:16 UTC
### Bug Description
Ideally, on tapping the "ok" button after data entry on the previous hospitalization form shown in the arrow in the image below, the form should exit while the entered data is stored. Currently, when the user taps on the "ok" button, the form refuses to exit and multiple entries keeps getting stored (without the user's knowledge) as the user continuously taps on "ok" button. 

![image](https://user-images.githubusercontent.com/50739609/92338381-e3c89700-f0a7-11ea-9664-9d8143b19cc9.png)

  
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version: 1.47.1
* Android version/Browser:

**Comment by MateStrysewske** [comment] 2020-09-07 09:25
Duplicate of #2774

**Closed by MateStrysewske** 2020-09-07 09:25 UTC
Labels: bug
