### ISSUE TITLE
Logging of the user which made the follow-up-call

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3910] opened 2021-01-05 07:38 UTC
### Situation Description

Currently it is not shown who made the follow-up-call. 

### Feature Description

It should be shown which user made the call if there are upcoming questions afterwards.

**Comment by kwa20** [comment] 2021-01-05 10:40
@Marko-ilmkreis Thanks for your contribution! This is technically a duplicate of #3621. I suggest we comment there.

**Closed by kwa20** 2021-01-05 10:40 UTC
Labels: feature
