### ISSUE TITLE
Contact with source case does not show in the contact directory

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7527] opened 2021-12-15 13:30 UTC
### Bug Description

As the heading states, a contact with a source case does not seem to show show in the contact directory.

### Steps to Reproduce

1. Open the contact directory
2. Click on `NEW CONTACT`
3. Instead of selecting a responsible region and disctrict, add a source case via `CHOSE CASE`
-> The contact shows as a case contact, but can not be found in the contact directory.

### Expected Behavior

Users with according rights should be able to find the contact in the contact directory

### System Details

* Device: Windows
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://ga1.sormas-oegd.de/
* User Role: National User

### Additional Information

The bug occured for me with [this contact](https://ga1.sormas-oegd.de/sormas-ui/#!contacts/data/SNMEGX-COCH63-5QY3AL-FSPHCD3Q) having [this source case](https://ga1.sormas-oegd.de/sormas-ui/#!cases/data/XOPTZH-D5WF33-NB7CZA-P5JMCKNE). It was created with the steps described above.

When searching for the contact via filters in the contact directory (e.g. via last name), it does not show.

**Comment by MateStrysewske** [comment] 2021-12-20 13:25
@FredrikSchaeferVitagroup Interestingly, though you demonstrated the bug to me, I'm not able to reproduce this on my system, nor on other test instances. Could you try to do so on yours?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-12-21 07:49
@MateStrysewske Aside the example linked in the issue description, I can not offer much.

When searching in the case directory on ga1, I can not find the case either. Probably it's a deleted one. 
The contact linked in the description is editable, so it should not be deleted.

I tried on my local system. The only two things I noticed are that:
- contacts related to a source case get deleted when the case is deleted. But I guess that this is desireded behaviour, and
- one can select deleted cases as source case when creating a contact. 

Both I could not use to reproduce the bug, though. Nor could I reproduce it any other way.

**Comment by MateStrysewske** [comment] 2021-12-21 09:31
@FredrikSchaeferVitagroup I also can't reproduce being able to select a deleted case as a source case when creating a contact - the method in the backend that retrieves the case list also explicitely uses the default filter that should rule out deleted cases. Are you sure that's possible?

**Comment by FredrikSchaeferVitagroup** [comment] 2021-12-21 09:46
@MateStrysewske If I'm not mistaken, I just did it again twice. So yes, I'm quite certain.

**Comment by MateStrysewske** [comment] 2021-12-22 09:37
@FredrikSchaeferVitagroup Strange. I can't reproduce that behaviour...

**Comment by FredrikSchaeferVitagroup** [comment] 2021-12-22 09:49
I was just about to show it to you, but now I can't reproduce this either. Sorry for that. Maybe some fix made it into development recently.

**Comment by MateStrysewske** [comment] 2021-12-22 10:28
Okay, gonna close this issue then for now. If the problem reappears, we can have a look at it again.

**Closed by MateStrysewske** 2021-12-22 10:28 UTC
Labels: bug, contacts, vaadin-app, feedback, major
