### ISSUE TITLE
Default import of Continent/Subcontinent/Country doesn't show any progress

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#4945] opened 2021-03-30 06:32 UTC
### Bug Description
Sometimes import default continents/subcontinents/countries does not show any progress, but after closing the import dialog the data is imported/changed

### Steps to Reproduce
1. Login as `admin` at https://test-de1.sormas.netzlink.com/sormas-ui/#!configuration/continents
2. Delete the `external id` of any continent
3. Do `Import default continents` with *override existing entries* checkbox checked
4. The progress dialog doesn't show any progress
5. Close the import dialogs
=> The continent list gets refreshed and the `external id` is restored for the modified entry.

### Expected Behavior
The progress dialog should show the import progress
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2021-03-30 07:21
Duplicate of #4905

**Closed by MateStrysewske** 2021-03-30 07:21 UTC
Labels: bug
