### ISSUE TITLE
Linelisting mode for contacts

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2715] opened 2020-08-26 16:28 UTC
### Situation Description
- just as we have for cases, add this option to create contacts from:
- contact directory and from contact list while in a case

**Comment by kwa20** [comment] 2020-11-04 22:13
Is this a duplicate of #1521?

**Comment by MateStrysewske** [comment] 2020-11-05 07:42
@kwa20 Yes!

**Closed by MateStrysewske** 2020-11-05 07:42 UTC
Labels: de, feature
