### ISSUE TITLE
Add a ReST endpoint to retrieve case visits

### ISSUE THREAD

**Issue by LandmannWo** [hzi-braunschweig/SORMAS-Project#5755] opened 2021-06-10 14:01 UTC
### Bug Description
Hi,
when calling the rest-api to read data e.g. for quality check or statistical purposes, not all rows are fetched. E.g. in our local test environment, both database table [visit] and database export of "contact->calls" from frontend statistics menu show 237 records. But when calling all visits e.g. in MS Powerquery, only 49 records are returned (which are a subset of the 237).

I understood there can be some limitation depending on the user roles assigned, but in this case the frontend administrator has assigned "Administrator" and "National User", while the rest user has assigned "Administrator", "National User", "Importing User" and "Rest User". Also when disabling "Administrator", "National User" or "Importing User" roles for the rest user, not all records are retrieved. Any idea what needs to be changed in order to retrieve all rows via rest API?

Thanks a lot
Wolfgang

### Steps to Reproduce
1. Log into postgreSQL database as an administrator and get "select count(1) from visits"
2. Log into Sormas Frontend web application as an administrator, click menu statistics -> database export -> Contact -> Calls and check row count of resulting file
3. Retrieve recordset via rest-api with an rest-enabled user account from https://[my-server]/sormas-rest/visits/all/0 and check row count

### Expected Behavior
All 3 steps 1, 2 and 3 above provide the same number of records and same details

### Screenshots
![image](https://user-images.githubusercontent.com/85682275/121521141-fd5e8c80-c9f3-11eb-9892-a6b81c7a193a.png)
![image](https://user-images.githubusercontent.com/85682275/121521336-3b5bb080-c9f4-11eb-8b45-d541c26677c0.png)

### System Details
* Device: local Sormas test installation in docker container
* SORMAS version: 
* Android version/Browser: Edge Chromium (Windows)
* Server URL: (internally hosted server)
* User Role:

**Comment by LandmannWo** [comment] 2021-06-10 14:04
additional Info: SORMAS version is 1.60.0, for user roles see bug description

**Comment by LandmannWo** [comment] 2021-06-14 15:00
not sure how this got closed (not intentionally). Could you please advise on possible solutions to above scenario? Help is appreciated - many thanks!

**Comment by MateStrysewske** [comment] 2021-06-15 07:54
Hey @LandmannWo, my first suspicion would be that some of the contacts that these visits are associated to (associations are tracked in the contacts_visits table) are archived or deleted, which excludes those visits from the ReST call because it only returns actually active data. The database export, on the other hand, does not perform such calculations, but is a straight export of the raw database content. Can you please check whether that's the case?

**Comment by LandmannWo** [comment] 2021-06-15 12:01
Hi, thanks for your response. I have just verified that the missing tasks largely do have references to active cases. Even in the frontend when opening the corresponding sub tab of a case, there are visits shown that are included in the DB extract but not visible in the rest API results. Any other ideas?

**Comment by MateStrysewske** [comment] 2021-06-15 12:04
@LandmannWo Ah, that explains a lot more - so you have visits for both contacts and cases? It seems like the visit endpoint currently only retrieves visits associated with contacts, not with cases, because the ReST interface is primarily designed to be used with the mobile app, and the mobile app doesn't support case visits yet. Can you confirm that all 49 visits you get from the endpoint are associated with contacts, and the others are associated with cases?

**Comment by LandmannWo** [comment] 2021-06-15 15:17
Hi, thanks for the hints, I wasn't aware that only visits related to contacts are shown in the REST API. Our team is planning to use the visits in the standard functionality of the Sormas web application as "tracking" (I guess, German is 'NACHVERFOLGUNG') tab of cases to log check-ins with quarantined persons. In such scenarios apparently a reference to the case is created.  
![image](https://user-images.githubusercontent.com/85682275/122077860-667f3f00-cdfc-11eb-9b94-5840688150ed.png)
Such entries are exactly the ones I'm not seeing in the REST API results (my REST API count currently is 50, still 10 less than the 60 in the database without case reference). 43 of the 50 REST API ones are included in the 60 DB ones without caze_id.

I was actually assuming that the reference is visit - person - case and not visit - case directly for the above standard usage of the web application. But apparently not, as I'm not seeing the ones with caze_id set in the database, the web application is unfortunately not creating the connection in the right way in order to retrieve the visits via REST API correctly? Please advise on a possible solution scenario. 
Thanks!

**Comment by MateStrysewske** [comment] 2021-06-16 07:38
@LandmannWo Visits are treated differently for cases and contacts. That's because semantically (not technically however), one person can not have more than one case of a specific disease at the same time, so we can make a direct association of visits to that case and don't need to use the person. For contacts, one person can have a lot of contacts to cases of a specific disease at the same time. In the past, we indeed used the person as the basis for this association, but that logic was pretty problematic in the backend, which is why we're using a generated table that is updated whenever visits or contacts are saved and stores all relations between visits and contacts.

In any case, the ReST endpoint for visits currently is not capable of retrieving visits associated with cases via /all/{since}. There are two possible solutions for this - implementing case follow-up visit for the mobile app, which would then also extend /all/{since} with case visits, or adding a (temporary) endpoint that allows the retrieval of case visits. The latter is definitely the quicker solution, but I'm not sure whether it's possible to integrate it into the upcoming release - I'll make sure that this is discussed. I'll turn this issue into a respective feature request.

**Comment by MateStrysewske** [comment] 2021-06-16 07:56
@LandmannWo The issue is unfortunately out of scope for the upcoming release, but I've forwarded it to HZI who will discuss how and when they can prioritise it.

**Comment by MateStrysewske** [comment] 2021-06-16 11:54
@LandmannWo I just realised that our Angular team will be taking care of this in #5710, so I'll close this issue as a duplicate. The functionality should be added in the near future.

**Closed by MateStrysewske** 2021-06-16 11:54 UTC
Labels: backend, cases, discuss, feature

**Comment by LandmannWo** [comment] 2021-06-18 07:24
Thank you Mate for your assessment, we'll be looking forward to this functionality being implemented.
Best regards
Wolfgang
