### ISSUE TITLE
Inability of two SORMAS nigeria users to synchronize their mobile app

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1239] opened 2019-07-27 03:17 UTC
There have been complaints of two users not being able to synchronize after submitting weekly reports and entering cases for about two weeks now. This problem has been checked and confirmed by the admins using the strongest of networks, the message given is "Synchronization failed. Pls try again later". The name of the users are TAFAWA_SO and ATBU_INFO who are surveillance and hospital informant officers respectively.

**Comment by MartinWahnschaffeSymeda** [comment] 2019-07-29 07:29
I have had a look into the log files. 

@Iheanacho2027 User ATBU_INFO (uuid QTDKPR) did have one of the bugs we solved with the latest update (#1123). With the new app version the only exception I can see is a connection time out (see #1237). He should be able to synchronize now.

For user TAFAWA_SO (uuid VWVX63) there are a lot of connection errors. 

- [ ] we have to make sure a connection error does NOT trigger a repull of data - this would not make any sense and even worsen the situation.

In addition I found this error that is not related to any other crash in the log and may be the actual exception relevant here:

> NullPointerException - Root cause: java.lang.NullPointerException: Attempt to read from field 'de.symeda.sormas.app.rest.DistrictFacadeRetro de.symeda.sormas.app.rest.RetroProvider.districtFacadeRetro' on a null object reference - Stack trace: de.symeda.sormas.app.rest.RetroProvider:getDistrictFacade:471 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalidInfrastructure:464 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:115 -> de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:523 -> android.os.AsyncTask$2:call:333 -> java.util.concurrent.FutureTask:run:266 -> android.os.AsyncTask$SerialExecutor$1:run:245 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1162 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:636 -> java.lang.Thread:run:764 - Root cause stack trace: de.symeda.sormas.app.rest.RetroProvider:getDistrictFacade:471 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalidInfrastructure:464 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:115 -> de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:523 -> android.os.AsyncTask$2:call:333 -> java.util.concurrent.FutureTask:run:266 -> android.os.AsyncTask$SerialExecutor$1:run:245 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1162 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:636 -> java.lang.Thread:run:764 - User: VWV6X3-DGWX3N-PMLCLM-O3TBKLRI - System: https://sormas.org.ng/sormas-rest/

**Comment by Iheanacho2027** [comment] 2019-07-31 10:58
As a follow-up on this issue, some other users having synchronization failure issues have been identified namely: AKURE_S_SO, ABAKALIKI_SO, IKWO_SO, ISHIELU_SO, IZZI_SO, OVIA_NE_SO, ESAN_NE_SO, ETSAKO_W_SO, OWAN_WEST_SO

I believe the bug affecting the identified users is also common to many users on the system whom havent yet been identified, pls can we get a fix that resolves all bugs relating to synchronization failure?

**Comment by MartinWahnschaffeSymeda** [comment] 2019-07-31 14:33
We have a lot of connection problems that result in a ServerCommunicationException which is not handled as "cannot connect to SORMAS server", but instead as "synchronizaton failed" or similar. This needs to be changed.

The result is that the users still wont be able to synchronize, but will at least get the correct message informing them that there is a connection problem.

- [ ] Improve handling of connection problems 

Here are the most common exceptions:

1. ServerCommunicationException - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException: connect timed out - Stack trace: de.symeda.sormas.app.rest.RetroProvider:throwException:713 -> de.symeda.sormas.app.rest.RetroProvider:checkCompatibility:251
2. ServerCommunicationException - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException: Unable to resolve host "sormas.helmholtz.hzi.de": No address associated with hostname - Stack trace: de.symeda.sormas.app.rest.RetroProvider:throwException:713
3. ServerCommunicationException - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException: Connection closed by peer - Stack trace: de.symeda.sormas.app.rest.RetroProvider:throwException:713
4. ServerCommunicationException - Root cause: java.net.SocketTimeoutException: connect timed out - Stack trace: de.symeda.sormas.app.backend.common.AdoDtoHelper:pullMissing:259 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalidInfrastructure:475
5. ServerCommunicationException - Root cause: java.net.SocketTimeoutException: connect timed out - Stack trace: de.symeda.sormas.app.rest.SynchronizeDataAsync:executeUuidCall:487 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalidInfrastructure:446

**Comment by Iheanacho2027** [comment] 2019-07-31 14:43
Ok, can we get a resolution to these connection problems that would stop the inability to connect to the SORMAS server and the synchronization failure errors in the next release?. These connection problems occur even in locations that have strong networks

**Comment by MartinWahnschaffeSymeda** [comment] 2019-07-31 15:31
I'm still figuring out, what we can do. This will need some trial and error.

1. Connection time out (1200 times with the latest version): We need a way to figure out why this happens. Is the connection too bad or is the server response much too slow? Same for "connection closed by peer".
What can be done now is:

- [ ] increase connection timeout to 20 seconds (currently 10)
- [ ] when connection still can't be established show a proper message to the user
- [ ] find a way to monitor the responsiveness of the server

2. Socket time out (300 times with the latest version): All of this happens when a "CompleteAndRepull" sync is done. Sometime it's during pullMissingAndDeleteInvalidInfrastructure, sometimes during pullInfrastructure and sometime during repullData. 

- [ ] check whether the timeout is reset whenever a request is over (likely not)
- [ ] log the error that lead to doing the repull sync (to avoid such errors)
- [ ] minimize the amount of data pulled from the server

**Comment by Iheanacho2027** [comment] 2019-07-31 15:53
@Chinedar @foyiri

**Comment by MartinWahnschaffeSymeda** [comment] 2019-08-05 07:28
I have extended the apache access log of the server to log the request duration:

> LogFormat "%h %l %u %t \"%r\" %>s %b _%D_ \"%{Referer}i\" \"%{User-agent}i\"" combined_ext
> CustomLog /var/log/apache2/access.log combined_ext

**Comment by MartinWahnschaffeSymeda** [comment] 2019-08-06 15:17
Status: We have fixed a few related issues (#1245, #1246) and added log information for the app to server communication. Once the next version is publishes and rolled-out we have to check the logs again.

In addition we will add some measure to the app to have a big picture of the synchronization (#1240).

**Comment by Iheanacho2027** [comment] 2019-08-06 18:07
Ohk, this is good. We will equally test-run from our end

**Comment by MateStrysewskeSym** [comment] 2019-09-03 10:36
@Iheanacho2027 I've checked our logs and it seems like the connection ids in the server communication errors we receive in Firebase don't appear in our Apache logs. If I don't misinterpret it, that should mean the errors indeed occur because the tablet can't connect to the SORMAS server, very likely because it does not have a reliable internet connection available. These users should now receive a proper error message though ("Can't connect to SORMAS server" instead of "Synchronization error"), so the cause of the problem should be more clear to them. I'll close this issue now, if you have a feeling that it's still not resolved, feel free to re-open it and add additional details.

**Closed by MateStrysewskeSym** 2019-09-03 10:36 UTC
Labels: Synchronization, bug, sormas-app
