### ISSUE TITLE
Synchronization of the mobile app triggers an error message

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9131] opened 2022-05-11 12:32 UTC
### Bug Description

When trying to synchronize the mobile app, an error message is displayed stating that 'Could not communicate with SORMAS server. Try again later'. 

If the user creates an entity in the mobile app and tries to do the synchronization, this error message appears but the synchronization is done (the entity is visible in the web app).

However, if the user creates an entity in the web app, and then tries to synchronize he mobile app, the same error message appears and the synchronization is not done (the new entity does not appear in the mobile app).

### Steps to Reproduce

I:
1. Log in with the same user into the web and into the mobile app;
2. Create a new case in the mobile app and trigger the synchronization;

II:
1. Log in with the same user into the web and into the mobile app;
2. Create a new case in the web app and trigger the synchronization in the mobile app.

### Actual Behavior

I, II:An error message is displayed in the mobile app after the synchronization is triggered.

I: The synchronization seems to work as the new entity is visible in the web app.
II: The synchronization is not working as the new entity is not visible in the mobile app.

### Expected Behavior

No error message should be displayed and the synchronization should be successful.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/167849874-685bc792-cbae-4e14-9aef-ff1482037504.png)

### System Details

* Device: Huawei P20 lite
* SORMAS version: 1.72.0-SNAPSHOT - mobile app; 1.72.0-SNAPSHOT(0866879) - web app
* Android version - 9 /Browser: Chrome
* Server URL: test.sormas.netzlink.com; test-de1.sormas.netzlink.com
* User Role: Surveillance Officer, Community Officer, Hospital Informant

### Additional Information

The mobile app has been downloaded from:
APK download: https://test.sormas.netzlink.com/downloads/release/ 
Server URL: https://test.sormas.netzlink.com/sormas-rest/

APK download: https://test-de1.sormas.netzlink.com/downloads/release/
Server URL: https://test-de1.sormas.netzlink.com/sormas-rest/

**Comment by StefanKock** [comment] 2022-05-11 14:09
@adinaflorea9 can you provide logs what goes wrong?

**Comment by MateStrysewske** [comment] 2022-05-12 09:47
@adinaflorea9 The bug is caused by #8747. I'll close this issue and have already reopened the other one and assigned you to it so that you can verify that the synchronisation is working again once the issue is moved to the Testing lane.

**Closed by MateStrysewske** 2022-05-12 09:48 UTC
Labels: bug, android-app, technology, feedback, critical
