### ISSUE TITLE
Show date and responsible user of last follow-up status change [2]

### ISSUE THREAD

**Issue by TheGaHTK** [hzi-braunschweig/SORMAS-Project#4138] opened 2021-01-26 18:11 UTC
Dear Sormas-Team,

most of the time the Follow-up date is to long and can not be adjusted. Actual we monitor people 14 days after there tests or extend till 24h after recovery. The Problem, the follow-up date is calculated automaticly 14 Days after the Date of Report or when the first symptoms started. This does not belong to our procedure. 

Please let us change the Follow-up date on our own.

Thank you very much and stay healty

Best regards

Julian

### Development Specifications
* Add two new fields to cases and contacts:
    * `followUpStatusChangeDate` (caption: "Date of follow-up status change")
    * `followUpStatusChangeUser` (caption: "Responsible user")
* When a user manually changes the follow-up status of a case or contact, store the date and the user into these new fields
* Vaadin app: Show the two fields below the "Follow-up status" field only if they are filled
* Vaadin app: Add a read-only text field to the follow-up form in between follow-up until and the checkbox to override the follow-up until date that contains the expected end date of follow-up (based on the calculations in the `updateFollowUpUntilAndStatus` methods in CaseFacadeEjb and ContactFacadeEjb; very likely makes sense to move the calculation of the until date to a helper method in the API to be able to access it from the UI); caption: "Expected follow-up until"

**Comment by bernardsilenou** [comment] 2021-01-26 23:29
@TheGaHTK  Thanks for creating this issue.
I have a question please. 
The rule in SORMAS is that if you configure the followup to 14 days, then the system does not allow you to do a follow up for less than 14 days. This rule is not made by SORMAS but from the epidemiology of COVID-19.  This is necessary to make sure that we do not followup for lesser days then expected.

However, it you think a person should not be followed up again, you can always cancel the followup anytime.

Please can you explain how you would like the system to function?
Do you cant that for every case or contact your import in SORMAS, you then have to set the followup period your self? would this not cause more work for you?
If you forget to set the followup period for a case, what should the system to?  exclude the case from the followup view?
Any further comment would be helpful for us to now exactly what to change to suit your needs.

**Comment by Marko-ilmkreis** [comment] 2021-01-27 06:22
@bernardsilenou I think it goes in the same direction as  #3243

**Comment by MateStrysewske** [comment] 2021-01-27 09:54
This requires a feature configuration that allows to turn this on/off for individual servers.

**Comment by TheGaHTK** [comment] 2021-01-27 11:41
@bernardsilenou Thank you for your quick response. 14 days are correct but according to the date when the sampe was collected, not when we got the information. Most of the time we get the medical report at least one day later. Would be nice if it would be calculated with the date when the sample was collected or could get reduced manualy. Actualy we are not able to reduce the date for less then 14 days after day of report, same problem with the onset of symptoms.

@MateStrysewske @Marko-ilmkreis it is a bit diffrent but i think both could be solved if it would be feasible to set this parameters inside of the setting section. Could be helpfull in future either.

**Comment by bernardsilenou** [comment] 2021-01-27 16:54
@TheGaHTK 
Thanks for this informative feedback.
As @MateStrysewske mentioned, we would definitely need a configuration on how the followup is calculated.
Some question that i raised in issue #3243 that also applies here are:
1. In your scenario, sample is collected  before the date of report. However is also possible to have the date of report before the date that the sample was collected.  What should happen here, should we still calculate based on date of sample collection? 
2. Some cases may not have the a sample or even date of sample collation registered in sormas, should the system set  followup for them?
3. If a second sample is collected from the same case which often happen to confirm with a negative result that the case has recovered. Should the system use only date of first sample collections to calculate followup duration even if the second sample result to a positive test?
4. What about contacts, should we also use the date of sample collections?
5. There is an option to set the followup duration to 10 instead of 14, with the assumption that you only get informed 1 to 4 days after the expected start of followup (in this case sample collection) which you could not do since you were not informed. Can this be a quick solution for you?

I asked all of these questions because in real life, things may not happen as expected and we end up with retrospective data management. A usual case is: a contact/ suspected case reported, followup done and samples are collected 4 days latter. This mean in your system, followup would start all over from 0 because this is the first sample collected.

**Comment by bernardsilenou** [comment] 2021-01-27 17:14
@MateStrysewske @Marko-ilmkreis  @Candice-Louw 
@TheGaHTK Dont know if this is fine by you:
One option is to merge your specification to the current setting by using the earliest date among: (sample collection, symptom onset, report date). This  would  mean we only use the sample collection date if it is provided and it is earlier than report date and symptom onset date. This configuration may also solve the needs for #3243

If we all agree on this, then we may need another grey grid (in addition to "Not performed") on the followup view to note dates that the followup data was missing by design. Missing by design just mean if a sample was collected on 1 Jan and health department were informed on 3 Jan, then followup on 2 Jan is missing by design because the GE could not have followed up on the contacts if they were not even aware of.

**Comment by bernardsilenou** [comment] 2021-01-27 18:27
@ All
Is the goal of this issue to allow users to lower the followup duration to less than the default value OR it is about the way it is computed but maintaining the number of days to the default value?

**Comment by Marko-ilmkreis** [comment] 2021-01-28 06:04
@bernardsilenou in my opinion the user should able to set the follow-up duration less then the default. Because there could always be individual reasons for this. But it would be good if he/she has then to fill in a reason in the current "Follow-up-status Comment"-field. Thats one thing an maybe must handeld in a seperate issue?

The other question is by what initial date is the follow-up-duration calculated. I haven't found a definition by the RKI yet and will ask our doctors later today.

**Comment by TheGaHTK** [comment] 2021-01-28 16:47
@bernardsilenou we agree with @Marko-ilmkreis, there should be no limitation and we calculate the date like:

**Case:**
1. Date of Sample collection
2. if unknown onset of symptoms

**Contact:**
1. Last relevant contact with case

**Multiple medical reports:**
By adding an additional test result, it will be decided on a case-by-case basis according to the specific characteristics, a prompt message would be helpful I guess.

**Comment by Candice-Louw** [comment] 2021-01-28 18:43
@rafaelpaffenholz @cschmutzLU - please feel free to contribute to the discussion.

**Comment by bernardsilenou** [comment] 2021-01-28 23:17
Woww! wonderful ideas are sprinting up, I feel we are almost getting to the optimum solution.
@TheGaHTK 
For cases, if Date of Sample collection and onset of symptoms are missing, then we can use report date, right?
For contact, if "Last relevant contact with case" is missing, then we use report date, right? 

Since we all agree that we need to allow users to be able to reduce the follow up to be lesser than the default value. In order not to have a lot to checks and popups that may affect performance, what do you think about calculating the end of followup always based on the most recent sample. Users can then decide to reduce if they want. We can also add bulk action to reduce expected end of followup.

**Comment by bernardsilenou** [comment] 2021-01-28 23:29
By clicking on "Override follow-up until date", no matter if increased or decreased, show a required txt box called "Override follow-up reason" for users to specify the reason.
@TheGaHTK When followup is increased, system asked if quarantine should also be increases. Hope it is fine that the same popup show when followup is set lower that expected?

**Comment by Marko-ilmkreis** [comment] 2021-01-29 06:33
@bernardsilenou I think we can use the current comment box for follow ups, but make it required if someone sets the follow-up-period lower then the calculated one.

To help ths users to understand on what basis the follow-up-period is calculated, would it be possible to have a hoverbox, when the mouse is over the "follow-up to"? That box could have the text:
"follow up until XX.XX.XXXX bases on the [date-reference for calculating] (XX.XX.XXX)". So in excample:
"follow up until 29.01.2021 based on the Onset of symptoms (15.01.2021)"

That makes it more understandable how the period was calculated.

**Comment by MateStrysewske** [comment] 2021-01-29 07:46
@bernardsilenou Using the sample collection date as the default would need to be discussed with @Chinedar because I could imagine that it doesn't make sense for some of the diseases we have in our system.

**Comment by Marko-ilmkreis** [comment] 2021-01-29 08:18
@TheGaHTK @bernardsilenou @MateStrysewske 

I asked our doctors how they would calculate the follow up for cases.
The would 
1. take the onset date for symptoms if that is not set then 
2. the date of the positive test instead and if this is not set 
3. the report date

According to them we have to make sure, that the follow-up date is updated when an earlier date is entered.
e.g. the case does not have symptoms and is reported on 20.01.2021 to us. The positive test was taken on 19.01.2021, but he/she forgets to tell us about the symptom or it wasn't entered. So its calculating from th 19.01.2021 onwards. If then the onset for symptoms is entered for 18.01.2021, the follow-up must recalculated on that basis.

**Comment by bernardsilenou** [comment] 2021-01-29 11:45
@MateStrysewske Totally agree with you and no need to discuss, the default stays as it is. This is about the configuration.

**Comment by bernardsilenou** [comment] 2021-01-29 12:13
> @TheGaHTK @bernardsilenou @MateStrysewske
> 
> I asked our doctors how they would calculate the follow up for cases.
> The would
> 
> 1. take the onset date for symptoms if that is not set then
> 2. the date of the positive test instead and if this is not set
> 3. the report date
> 
> According to them we have to make sure, that the follow-up date is updated when an earlier date is entered.
> e.g. the case does not have symptoms and is reported on 20.01.2021 to us. The positive test was taken on 19.01.2021, but he/she forgets to tell us about the symptom or it wasn't entered. So its calculating from th 19.01.2021 onwards. If then the onset for symptoms is entered for 18.01.2021, the follow-up must recalculated on that basis.

@TheGaHTK Thanks for this informative reply.

What if the test is missing (or pending) but sample is collected and onset date for symptoms is missing (if case is asymptomatic)?, should we skip point 2? or use the sample collection date?

Considering the fact that sample may be collected but test result is out the next day or more, don't you think it may be better to use the date of sample collection? + we do not need to worry about samples with negative result. We begin followup based on sample collection and if negative, we stop followup.

If you agree to use sample collection date, I think it boils down to a comment I made to this issue or a related one saying:
We take the earliest of the 3 dates (symptom onset, sample collection, report date)

**Comment by TheGaHTK** [comment] 2021-01-29 16:46
@bernardsilenou @MateStrysewske @Candice-Louw @Marko-ilmkreis 

According to our corona regulations we are allowed and supposed to monitor cases and contacts while they are in quarantine. I think it would make sense if both periods are similar, the start may could be the day of report.

If there are issues with other disease I would recommend applying this rule if Covid-19 is selected as disease.

**Comment by bernardsilenou** [comment] 2021-01-29 22:14
@TheGaHTK 
What do you say about using date of sample collection for point .2, rather than date of pathogen test result? Is this fine by you?

**Comment by TheGaHTK** [comment] 2021-01-31 14:57
@bernardsilenou the date of pathogen test result is irrelevant for our procedure. The main value is date of sample collection. So would be fine.

**Comment by bernardsilenou** [comment] 2021-01-31 16:04
@TheGaHTK Thanks, I also think that is fine.

**Comment by TheGaHTK** [comment] 2021-01-31 17:08
Thank you. How long do you think does it takes to make these changes?

**Comment by bernardsilenou** [comment] 2021-01-31 17:32
@MateStrysewske @kwa20 @Candice-Louw  @ All who participated in this refinement: I would summarize and including points from #3243, Please have a look if I forgot something:

1. Configurations: Add 2 parameters to configure server on:
  * when (which date type) the computation of followup  should begin 
  * If users can override the expected duration to be less that the incubation period (d) of the disease,  d = 10  or 14 fro COVID.  
2. **For cases**, 
4. start fo followup ==  earliest of the available 3 dates  in this order of priority (symptom onset, sample collection, report date) 
4. expected end of followup == star of followup + d 
5. When new data on dates are provided, do not automatically recompute followup but show a warning  for the user to decide if a new computation is needed (according to @Candice-Louw from #3243 ). @TheGaHTK, @Marko-ilmkreis Do you wan it like this or the system should automatically recompute based on this order of dates: symptom onset, sample collection, report date. i.e if symptom onset date is provided after followup has been done for about 3 days based on sample collection or report date,  
10. should the system automatically recompute followup based on symptom onset date OR 
11. show a warning sign for the user to manually change? 
13. if user forgot to change, what should the system uses, maintain old date or recompute?
14. Would this cause much work for the users? 
6. When users override expected end of followup by supplying a new end of followup date, then validate and save only when the new d' >0
7.  We can use the current comment box for follow ups to specify the reason for overriding expected followup, but make it required when ever the expected followup is changed (this is implemented already).
8. **For contacts:**
9. Follow up should use the following dates in this order of priority (date of last contact, sample collection, report date) 
8. Similar to cases, there should be no auto-computation (according to @Candice-Louw from #3243 )  @TheGaHTK @Marko-ilmkreis  Please can you also verify and comment if followup should be automatically recomputed?
9. Since followup begin at symptom onset date but visits can only be done on the same day or after the report date, and since symptom onset of most diseases is often before the report date, then on the "follow-up visit" chart, there would be some gray cells which would correspond to "not performed" visits by design. One solution is to add the "start of followup date" as a column on the table so that users can compare with the followup until date to know why some visits are missing.
10. To help the users to understand on what basis the follow-up-period is calculated, add a hoverbox, when the mouse is over the "follow-up until" with a text like:
"follow up until XX.XX.XXXX bases on the [date-reference for calculating] (XX.XX.XXX)". So in example:
"follow up until 29.01.2021 based on the Onset of symptoms (15.01.2021)",
"follow up until 29.01.2021 based on the report date (15.01.2021)" etc (this feature should be added to all configurations and instances. It would be good if can maintain such a practice for all derived variables, nice suggestion @Marko-ilmkreis )
12. **For quarantine**
13. No matter the entity, case, contact, ep, we maintain the start of quarantine using report date and end of quarantine using followup until date. We maintain the popup to match quarantine to end of followup and vice versa. According to this new configuration, then number of days in quarantine would be shorter than number of days in followup since quarantine would always begin on or after report date (you can't put a case in quarantine that has not been reported to you).

**Comment by bernardsilenou** [comment] 2021-01-31 18:27
> Thank you. How long do you think does it takes to make these changes?

If we all agree and complete the refinement before Fen 5, then we can consider these changes for the next sprint, ie about 4 weeks from today in total time.

**Comment by Marko-ilmkreis** [comment] 2021-01-31 19:04
@bernardsilenou great work. Thank you!!

I fully agree with all.

To the questions:

There should be a pop up, if the user wants the follow up to be recomputed or not. This is the best way in my opinion.

The quarantine/isolation should be automatically changed if the follow up is extended over the current end of quarantine/isolation. Maybe also with a pop up, but I doubt that too many pop ups are confusing the users.

If someone cancel or changing the follow up manually an we are showing the date, is it possible to show the user made this also?

Sorry for the short answer, but I hate writing long texts on my mobile.

**Comment by kwa20** [comment] 2021-01-31 22:39
@bernardsilenou Just some comments:

- expected duration (d) can be any number of days that are configured in the disease configuration. It is not limited to 10 or 14 per se.
6. if option to overwrite expected period is not configured, the re-computation should be done automatically because e.g. setting the symptom onset date on a later date than the report date results in an error on the case information form when trying to save changed data. This is due to the follow-up duration not conforming to the expected duration when initially calculated with the report date. This should include an informative prompt I suppose. Otherwise I agree that there should be a notification with a manual change option.

In your mock-up it looks like the change date would be editable. I assume it's just computed though? I made a mock-up to also include the last editing user:
<img width="719" alt="Screen Shot 2021-01-31 at 11 29 33 PM" src="https://user-images.githubusercontent.com/70317594/106400042-69b0fa00-641c-11eb-90c1-6fd4c31a17b9.png">

14. If overwriting the extended period is not configured, we would not be able to shorten the follow-up date according to a shortened quarantine end date if the period will be smaller than the configured standard follow-up duration. The user should then be informed accordingly.

**Comment by bernardsilenou** [comment] 2021-02-01 02:50
@Marko-ilmkreis @kwa20 Nice suggestions.
- @Marko-ilmkreis mentioned the point I am reluctant that we ass popups all the time. If many test results of cases are imported after the cases has been on followup based on report date,then each time the user open the form, there would be at least 2 popups (followup + quarantine change) which may be boring to the user. What about using a red (!) sign, when user hover over the field, then information box appears with message of why date may need to be changed. We maintain pop up for quarantine. Users would not be blocked in doing their job. 
- If  date type is the same but have changed, e.g initial followup was based on report date on Jan 1. When changes to Jan 3, then we do not need to ask the user but automatically recompute followup. But when changed to another date type with high priority in the vector of date (symptom onset, sample collection, report date), eg symptom onset, then show a warning massage asking user to recompute. If user decide not to recompute, then continue with the report date. If user recompute, then show a popup asking it they want to adjust quarantine.
- @kwa20 Yea, point 6. is only valid if symptom onset <sample collection <report date, since we take the smallest. Onset date can be after report date, of this happen, we use report date to calculate end of followup. But it cant be in future of the current date.
- @kwa20 All these specifications only holds when configuration parameter is set to true, if not, the default stays as it is now nu always auto computing based on report date and do not permit d to be less than 14.
- @kwa20 Perfecto! Change date should not be editable, I did not think of that.

**Comment by Marko-ilmkreis** [comment] 2021-02-01 04:56
@bernardsilenou is it possible to do it two waya: If a date is changed manually by the user then show a pop-up and if the date is imported, then show the (!). Are imported data marked as imported?
Otherwise only the (!) is fine with a hover-message with the right date.

**Comment by bernardsilenou** [comment] 2021-02-01 10:47
@Marko-ilmkreis at the back end we can know how the data was changed but we do not track and manage this within the app for now. 
So we can go with plan B "Otherwise only the (!) is fine with a hover-message with the right date." and then keep in mind the other option in a further refinement stage.

**Comment by bernardsilenou** [comment] 2021-03-05 03:07
### In summary:
- When followup for cases and contacts is cancelled on a calendar date <= expected followup until date, show the date of interruption  and user name on form.
- Add an information icon beside the followup until date. If user hover over this date, show a  message like
- `Expected follow up until 29.01.2021`

![image](https://user-images.githubusercontent.com/12996724/110060749-b151db00-7d66-11eb-9314-bced22533a5a.png)
![image](https://user-images.githubusercontent.com/12996724/110060514-54562500-7d66-11eb-8bd4-d0267ac3ef49.png)

**Comment by bernardsilenou** [comment] 2021-03-05 03:09
- The need to add more information to the error massage would be implemented  here #4642

**Comment by maxiheyner** [comment] 2021-04-06 12:35
Issue Tracker Comment

**Comment by ChristopherRiedel** [comment] 2021-04-16 09:29
Information is not shown when follow-up is resumed

**Closed** 2021-04-19 13:26 UTC
Labels: backend, cases, change, contacts, de-public, vaadin-app
