### ISSUE TITLE
Non-consistent  date formats and issues with searsh cases by date on web [0]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#764] opened 2018-08-13 14:54 UTC
On Case list in web version, "Date of report" and  sorting cases "By date" do no thave the same date format.
The sort function has a bug as it does not present cases with creation date in the interval chosen.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-14 13:53
The format will be fixed.
We can't reproduce the filter problem, though. By creation date you probably mean date of report?

**Comment by MateStrysewskeSym** [comment] 2018-08-29 05:47
@bernardsilenou That's not entirely true. We use the same logic for these fields that we use e.g. in the dashboard. Onset date has priority, but for cases that don't have this date set, it's either the reception date or, if that's not available as well, the report date as the final fallback. That's why we can't simply call it "Date of symptom onset from ... to ...". However, we might need to add an info icon to that view as well (the same that's already present in the dashboard).

**Comment by MateStrysewskeSym** [comment] 2018-09-04 14:12
- [ ] add another field that allows users to choose the date to filter by (or "all") to the case directory

**Comment by MateStrysewskeSym** [comment] 2018-09-10 07:18
- [ ] Info text should be shorter

**Closed** 2018-09-14 08:11 UTC
Labels: Case Surveillance, bug, sormas-ui
