### ISSUE TITLE
Region selector is empty when editing Campaign Data Form

### ISSUE THREAD

**Issue by danRosca** [hzi-braunschweig/SORMAS-Project#3334] opened 2020-10-29 10:06 UTC
### Bug Description
In Campaign Data Form view the Region dropdown is empty
### Steps to Reproduce
1.Go to Campaign Data view
2. Edit a Campaign Data Form

### Expected Behavior
Region drop down should already have a value (like the rest of the mandatory fields)
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2020-11-02 08:37
Duplicate of #3336

**Closed by MateStrysewske** 2020-11-02 08:37 UTC
Labels: bug
