### ISSUE TITLE
Not possible to delete vaccinations after merging duplicate cases

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#8096] opened 2022-02-23 05:49 UTC
### Bug Description

When merging duplicate cases the vaccinations are copied into the selected case from the other own. This causes into many duplicate entries (see #8011).

The duplicate vaccinations must be deleted manually by the user, but this is only possible for the vaccinations that were already existing in the case. The copied vaccinations cannot be deleted. 

### Steps to Reproduce

1. merge cases with vaccination details
2. try to delete one of the vaccinations.

### Screenshots

![Animation](https://user-images.githubusercontent.com/74791118/155267783-75bc91e3-3e6f-4a51-8441-8f5c9367572a.gif)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment] 2022-03-21 15:29
I tested the ticket on my local machine using the latest version of Sormas 1.70.0-SNAPSHOT (c02a38f) and I'm reopening it because of an issue that I have found:

Currently, if you have 1 Vaccination in the Preserved Case and 1 Vaccination in the Unpreserved Case, after the merging, there are 3 Vaccinations, because the Vaccination of the Unpreserved Case gets duplicated.

![merging cases vaccination gets duplicated](https://user-images.githubusercontent.com/89522688/159294680-fef46746-4d99-433f-904a-d92c9b65de6c.gif)

**Comment by roxanamlendea** [comment] 2022-03-22 07:19
@MateStrysewske Apparently, the issue from my comment was already included in a bug report opened by @carina29 #8333

**Comment by MateStrysewske** [comment] 2022-03-22 11:36
Closing this issue in favour of #8333 because it doesn't seem like this bugfix here was the root cause to me.

**Closed by MateStrysewske** 2022-03-22 11:36 UTC
Labels: bug, cases, backend, major, immunizations
