### ISSUE TITLE
Campaigns/APMIS > "Persons" menu item should not be visible

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4718] opened 2021-03-10 16:03 UTC
### Bug Description
The new "Persons" menu item is visible on the Afghanistan server, although not part of the project. (Not sure if this is a programming adjustment or Netzlink configuration adjustment that needs to be made?)

### Steps to Reproduce
1. Log in to the APMIS system.
2. View menu items.

### Expected Behavior
Persons menu item should not be visible.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/110658527-0d32be80-81c2-11eb-8f3b-9a1fa41830c7.png)

### System Details
* Device:
* SORMAS version: 1.58.0 Snapshot
* Android version/Browser:
* Server URL: https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!about
* User Role: admin

**Comment by MateStrysewske** [comment] 2021-03-11 08:45
Duplicate of #4649

**Closed by MateStrysewske** 2021-03-11 08:45 UTC
Labels: bug
