### ISSUE TITLE
Exposure Details are not transferred from contact to case

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10786] opened 2022-10-28 10:26 UTC
### Bug Description

When creating a case out of a contact person the Exposure Details are not visible at the case any more.  

### Steps to Reproduce

1. Create a Contact
2.  Add a new entry at Exposures  (Epidemiological tab)
3.  Create a case for this contact person
4.  Check the Exposures

### Expected Behavior

The epidemiological date are transferred and visible at case and contact. 

### Screenshots

![epid-details](https://user-images.githubusercontent.com/101708230/198565852-218ccad9-8475-4122-bd1a-d3efca8ac713.gif)

### System Details

* Device: Laptop
* SORMAS version:  1.77.0 ba98b49
* Android version/Browser:  Chrome
* Server URL:  https://test-auto.sormas.netzlink.com/ and https://test-de.sormas.netzlink.com/
* User Role: Admin

**Comment by roxanamlendea** [comment] 2022-11-15 08:17
This bug was caused by #10208. The ticket was reopened and the bug will be fixed there.

**Closed by roxanamlendea** 2022-11-15 08:17 UTC
Labels: bug, contacts, cases, vaadin-app, major
