### ISSUE TITLE
S2S_exclude personal data broken on 1.75.4

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10595] opened 2022-10-11 08:20 UTC
### Bug Description

If you want to share a request via S2S and exclude personal data, you can share in source system but you cannot accept in target system: '500 internal server error'.
### Steps to Reproduce

1. create a case/contact in source system
2. check the checkbox 'exclude personal data'
3. try to accept in target system

### Expected Behavior

share request can be accepted
### System Details

* Device:
* SORMAS version: 1.75.4
* Android version/Browser: edge
* Server URL: release-x to release-de
* User Role: admin

### Additional Information

On 1.76. it seems to work (tested on nightly test-de1 to test-de2)

**Comment by SahaLinaPrueger** [comment] 2022-10-11 08:41
@JaquM-HZI @Jan-Boehme

**Comment by JaquM-HZI** [comment] 2022-10-12 09:51
@markusmann-vg @JonasCir @leventegal-she please double check for 1.76.

**Comment by AndyBakcsy-she** [comment] 2022-10-12 11:56
@SahaLinaPrueger @markusmann-vg There is a ticket already fixed and verified on 1.76 which seems to be the same problem.
The issue is #10225 
Do we need to create another HotFix for this issue?

**Comment by JaquM-HZI** [comment] 2022-10-12 12:24
@AndyBakcsy-she  we are fine in 1.75 as long it is fixed in 1.76

**Comment by leventegal-she** [comment] 2022-10-12 14:22
Could not reproduce on local environment nor on test-de1 ->  test-de2,  test-de2 -> test-de3

@SahaLinaPrueger Can you please provide some logs with the error?

**Comment by SahaLinaPrueger** [comment] 2022-10-13 10:38
@leventegal-she Grafana is currently broken, so NLI provided me the logs:
[release-de_sormas_logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9775746/release-de_sormas_logs.txt)
[release-de_syslogs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9775748/release-de_syslogs.txt)
[release-sormas-x_sormas_logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9775750/release-sormas-x_sormas_logs.txt)
[release-sormas-x_syslogs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9775752/release-sormas-x_syslogs.txt)

**Comment by SahaLinaPrueger** [comment] 2022-10-13 16:52
Please notice: As described under additional Information: I can not reproduce the bug on 1.76 neither.
If everything is fixed with #10225 in 1.76 everything is ok. You do not need to fix this in 1.75. I have provided the logs so you can see if this is the problem that has already been fixed. If so, everything is ok.

**Comment by leventegal-she** [comment] 2022-10-13 19:18
The error I found in the logs provided is fixed in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10225

**Closed by leventegal-she** 2022-10-13 19:18 UTC
Labels: bug, duplicate, feedback, s2s
