### ISSUE TITLE
Import of traveler submitted by https://www.einreiseanmeldung.de

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4019] opened 2021-01-15 07:26 UTC
### Situation Description

All travelers returning to Germany must enter their details on the website [https://www.einreiseanmeldung.de/#/](https://www.einreiseanmeldung.de ). The local health authorites can view the entered datas and download them from a website as a csv.

### Feature Description

As this csv has always the same structure it should be possible to import them easily in contacts without any converting. As it affects all health authorities it would help them all.

Maybe this is mor for the support of HZI and they provide a tool/Excel with Macro then for implementing a new import function.

I attached a sample-file, but note that is a csv. I changed the extension to txt, so that it could upload here.

[Einreiseanmeldungen-2021-01-13.csv.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5819020/Einreiseanmeldungen-2021-01-13.csv.txt)

**Comment by bernardsilenou** [comment] 2021-01-17 22:29
@JonasCir  What about having a script that do this? Since users may not have R or Python on their local system, we can just have a small app that users can load the data and export it in the form identical to the contact import template we have. We can call it "sormas-import-converter" and include it in the collection of sormas toolkit apps.
@Marko-ilmkreis The file you attached in not a .csv; Is this the original file are there are other options?

**Comment by Marko-ilmkreis** [comment] 2021-01-18 05:16
@bernardsilenou Guthub doesn't allow csv-files :-) Therefore I just added the ".txt" to the name. The original name is Einreiseanmeldungen-2021-01-13.csv. 
The only thin what I changed within the file are the personal details for data protection. The change was done in Notepad++ so there shouldn't be a change of the file-format itself.
A script would be great.

**Comment by JonasCir** [comment] 2021-01-18 08:52
Maybe we do it different and we ask einreiseanmeldung to provide _us_ with a sormas compatible import format (its already working for other apps). It's a minor implementation effort for them, and we do not need to clutter our system with functionality for one country :) @syntakker

**Comment by Candice-Louw** [comment] 2021-01-18 08:55
@JonasCir - this would be great, please.  Please let us know if/how we could assist with this?

**Comment by Marko-ilmkreis** [comment] 2021-01-18 08:56
@JonasCir Please let us also know if we can assist you from our side.

**Comment by JonasCir** [comment] 2021-01-18 08:59
@Candice-Louw and @Marko-ilmkreis thank you for the offer and much appreciated :)
First, we need contact to the engineers/project manager of einreiseanmeldung.de and second, @syntakker has already experience with simple CSV import from 3rd parties :smiley:

**Comment by MateStrysewske** [comment] 2021-07-22 11:43
Duplicate of #6031

**Closed by MateStrysewske** 2021-07-22 11:43 UTC
Labels: backend, feature, import & export, refine, travel entries, vaadin-app
