### ISSUE TITLE
Add backend validation for primary contact details

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5005] opened 2021-04-07 06:14 UTC
### Bug Description

Since the update to 1.58.2 this morning, when applying a filter by the name it results in an error on our own instance:

![grafik](https://user-images.githubusercontent.com/74791118/113818514-25254000-9778-11eb-9fa3-61c49f0e96d6.png)

![grafik](https://user-images.githubusercontent.com/74791118/113819201-49cde780-9779-11eb-8436-6e8a89fd16ee.png)

This happens to all directories (case, contact, person).

It was possible to use the search an hour ago as I used it. But now, every search in the field "Name, EPID-ID..." runs into an error. 

It was not reproducable on https://test-de1.sormas.netzlink.com, but maybe there are not enough data sets to run into an error.

### System Details
* Device: Win10
* SORMAS version: 1.58.2
* Android version/Browser: FF
* Server URL: own instance
* User Role: ReST Benutzer*in, Nationale*r Benutzer*in, Administrator, Nationale*r Arzt/Ärztin

**Comment by Marko-ilmkreis** [comment] 2021-04-07 06:26
@markusmann-vg as Sormas is not usable if the directories could not filtered, is there any way to get it earlier fixed then with 1.59?

**Comment by markusmann-vg** [comment] 2021-04-07 06:33
@Marko-ilmkreis If it is reproducable, and it happens in the current version 1.58.2 (Can you pls. recheck, that this is the version which is installed) we will definitely not wait until 1.59 and provide a hotfix when needed.

**Comment by Marko-ilmkreis** [comment] 2021-04-07 06:44
@markusmann-vg yes, we are on 1.58.2 since yesterday evening.
![grafik](https://user-images.githubusercontent.com/74791118/113821843-f198e480-977c-11eb-8931-1491c430da82.png)

We haven't had this error before, so it could be caused by the update. But it could also be a coincidence that the error has happened right now. 

Unfortunately, the error could not be traced on the test-de1 server, but this could probably be because of the very few datasets there(?).

We have no problem with you checking the log files on our server. I would also be happy to set up a user for tests.

**Comment by Marko-ilmkreis** [comment] 2021-04-07 06:59
@markusmann-vg I called Netzlink to request a restart of the server and they reported to me that there were several health officed (e.g. Augsburg) which are also reported the same error.

**Comment by kwa20** [comment] 2021-04-07 07:11
@Marko-ilmkreis This might possibly occur if multiple contact details are set as primary. This should not be possible so the directory seems to crash when trying to display multiple primary information on the respective directory columns.

**Comment by Marko-ilmkreis** [comment] 2021-04-07 07:49
@kwa20 

![grafik](https://user-images.githubusercontent.com/74791118/113830084-87853d00-9786-11eb-94a4-1f928e1b4184.png)

**Comment by MateStrysewske** [comment] 2021-04-07 08:02
@kwa20 Do you know how this happens? Is it something related to retrospective case merging?

**Comment by kwa20** [comment] 2021-04-07 08:27
@MateStrysewske I can't say for sure but I don't suspect it to be the problem since the example given here was not merged. I think this happened somehow during the migration from existing data to the table format. Some further details @Marko-ilmkreis and me could identify are the following:
- The person had a case and a contact
- An error only occurred on default views when filters were applied whereas it happened by merely navigating to the detailed view (likely due to the primary phone number column being displayed on detailed views and person directory)
- Deleting the additional phone number was not possible and even though the system verified the deletion and saving, the phone number reappeared when navigating back to the person tab
- However, the additional contact detail could be unchecked for being primary

**Comment by ophcode** [comment] 2021-04-07 10:32
Same problem here (Berlin Friedrichshain-Kreuzberg).
Our instance was updated to 1.58.2 yesterday, all seemed to work fine until around 10AM.
(We did a small case transfer from Survnet afterwards, might be a probable cause)

**Comment by MateStrysewske** [comment] 2021-04-07 12:02
@kwa20 Moved the problem that person contact details can't be deleted to a separate issue: #5012 

This issue is mainly about figuring out why multiple primary contact details of the same type were created in the first place and fixing that for 1.59.0. Netzlink will have to run a migration script on servers that are already on 1.58.2 to get rid of the duplications (or they need to be resolved manually if that's feasible).

**Comment by MateStrysewske** [comment] 2021-04-07 12:38
@Marko-ilmkreis @kwa20 I've re-checked the database migration script and I can more or less guarantee that it's not the cause of this problem. Was there a data import from SurvNet after upgrading to 1.58.2 and before these errors started to appear?

**Comment by kwa20** [comment] 2021-04-07 12:46
@MateStrysewske The problem is actually independent of the SurvNet interface. This problem occurs in many instances that don't use the interface yet.

**Comment by kwa20** [comment] 2021-04-08 14:20
@Marko-ilmkreis @ophcode We suspect that the symptom diaries might have an impact on this behaviour. Could you have a look if these entities are registered in a symptom diary? 

Further, are the numbers that are blackened in your screenshots divided by any kind of delimiter?

**Comment by Marko-ilmkreis** [comment] 2021-04-08 14:36
@kwa20 no, there are no delimiter and the case was not registered at Climedo.

**Comment by kwa20** [comment] 2021-04-08 16:47
@MateStrysewske @FredrikSchaeferVitagroup @Marko-ilmkreis After further investigation I could finally reproduce the problem and think that I know how this happen:

Steps to reproduce:
1. Create a contact (or case, shouldn't matter) and enter primary contact details (phone number, email). (Ideally save the Id or link the entity to another entity that allows access apart from the directory since the eventually produced error might prevent you from easy access)
2. go to the person tab of the created entity
3. Try adding either another primary email or phone number. - The system should prevent you from doing so by asking you to either choose the new entry as primary or keep the other one.
4. Now, delete the initial primary entry.
5. Create the new entry as primary.
6. Select Done and save the person form.
7. Navigate to the person form... an error should occur.

**Comment by Marko-ilmkreis** [comment] 2021-04-09 04:00
@kwa20 Thanks for the analysis. This is how the error can happend for the future, but for our case it happens and no one touched that case. But its good to know how we can prevend it in the future and many thanks for your support!!

**Comment by MateStrysewske** [comment] 2021-04-09 07:49
The main fix for this issue has already been done in #5012 (contact details weren't properly deleted). Additionally, I will add some backend validation in this issue to make sure that there's an error message when saving a person with multiple primary contact details of the same type.

**Closed** 2021-04-09 08:39 UTC
Labels: backend, change, important, persons
