### ISSUE TITLE
'Responsible Contact Officer' dropdown is not populated for contacts that take the responsible jurisdiction from their source case

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9859] opened 2022-07-14 14:28 UTC
### Bug Description

The 'Responsible Contact Officer' dropdown is not populated for contacts that have their responsible jurisdiction set by the source case. 
 
### Steps to Reproduce

1. Open a contact that has a source case (and no values set on the contact page for 'Region' and 'District');
2. Open the 'Responsible Contact Officer' dropdown.

### Actual Behavior

The 'Responsible Contact Officer' dropdown is not populated.

### Expected Behavior

The 'Responsible Contact Officer' dropdown should be populated with the Contact Officers from the jurisdiction set by the contact's source case.
 
### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(7e4e9eb)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by adinaflorea9** [comment] 2022-07-20 14:07
I am reopening the ticket due to the following: when changing the jurisdiction of the 'Source Case' (associated with a contact that does not have their own jurisdiction) the field 'Responsible Contact Officer' is not cleared.

Expected behavior: the field 'Responsible Contact Officer' should be cleared when the jurisdiction of the 'Source Case' is changed.

**Comment by syntakker** [comment] 2022-07-25 10:14
> I am reopening the ticket due to the following: when changing the jurisdiction of the 'Source Case' (associated with a contact that does not have their own jurisdiction) the field 'Responsible Contact Officer' is not cleared.
> 
> Expected behavior: the field 'Responsible Contact Officer' should be cleared when the jurisdiction of the 'Source Case' is changed.

@adinaflorea9 This behaviour seems somewhat counterintuitive, since changing a case's jurisdiction would cause all its contacts to lose their responsible officer without a new one being assigned. Where is this logic specified?

**Comment by adinaflorea9** [comment] 2022-07-25 10:21
@syntakker when the jurisdiction of the source case is changed, the responsible contact officer that was assigned to the associated contact has already lost the jurisdiction (if they try to access the contact it is read only), but the user remains listed in the respective field. I think that this might be confusing as other users might think that someone is already assigned to the contact, but in reality that user has lost access to it.

My description of the behavior is based on the similar behavior for the responsible officers assigned to cases (where if a case's jurisdiction is changed, the field for responsible officer is cleared). 

I believed it to be within scope of the issue, as since we are taking into consideration the jurisdiction of the source case when filling the 'Responsible Contact Officer' field, we should also take it into account when clearing it; as it also currently happens when the contact jurisdiction is changed form the contact's page.

@MateStrysewske perhaps you would be able to let us know if this would be an appropriate behavior or not?

**Comment by MateStrysewske** [comment] 2022-07-27 11:12
@adinaflorea9 @syntakker Tricky question, but I'd vote for keeping it like it is right now. Clearing the responsible officer without any notice might result in the contact not being properly managed anymore; it's better if the user still has access to it, even if it's read-only access, because then they can inform a supervisor that action is supposed to be taken. A more sophisticated solution might be possible here, but would be out of scope for this issue.

**Comment by adinaflorea9** [comment] 2022-07-27 11:20
@MateStrysewske Thank you for taking a look over this! 

In that case, then it should be noted that currently, if the contact's actual responsible jurisdiction is changed, the field for 'Responsible contact officer' is cleared (as this is partly on what I based the expected behavior when I reopened the ticket.)

If this should be changed, please let me know and I'll create a separate change request for that.

**Comment by syntakker** [comment] 2022-07-27 14:29
Closing the issue as the reason for reopening is out of scope of the original bug.

@MateStrysewske, @adinaflorea9 please open a new change issue if the intended behaviour is specified to be different from what is currently implemented.

**Closed by syntakker** 2022-07-27 14:29 UTC
Labels: bug, contacts, backend, vaadin-app, major

**Comment by adinaflorea9** [comment] 2022-07-29 11:37
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(e540253). 

Behavior mentioned in the comments above regarding the clearing of the 'Responsible Contact Officer' field has been moved to a separate issue #9995 so that it can be discussed and clarified.
