### ISSUE TITLE
Epidemiologic data: Contacts with index case cannot be created again after discarding once

### ISSUE THREAD

**Issue by ThomasVitus** [hzi-braunschweig/SORMAS-Project#6561] opened 2021-08-31 15:12 UTC
### Bug Description
After deleting the index case once, no new index case can be created. The relevant buttons will only be grayed out and can no longer be pressed. See screenshot.
![Screenshot_2021-08-31 SORMAS](https://user-images.githubusercontent.com/86602055/131527957-032a0b7f-12bc-4c02-ba1d-75713436d2ff.png)

### System Details

* SORMAS version: 1.62.3
* Browser: Firefox 78.13.0
* User Role: National User, Administrator

**Comment by kwa20** [comment] 2021-08-31 15:24
@ThomasVitus Do you maybe know the steps to reproduce this bug? When I tested it, I deleted the created contact between the cases but the result was this: (expected)
<img width="597" alt="contactsWithSourceCase" src="https://user-images.githubusercontent.com/70317594/131530568-43e0560b-c040-4dbe-92d6-9c9a64419d0f.PNG">

I found this issue which existed in the past: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5841

Do you know if this case might fall into the creation period where this was still an issue?

**Comment by ThomasVitus** [comment] 2021-08-31 15:46
> Do you maybe know the steps to reproduce this bug?
> Do you know if your case might fall into the creation period where this was still an issue?

Unfortunately, I cannot currently reproduce the error. It happened to a colleague, who could not explain what happened. It is a current case from August without reference to an event.

**Comment by MateStrysewske** [comment] 2021-09-01 09:20
I can't reproduce it as well - same outcome as @kwa20.

@ThomasVitus Please see whether it occurs again and ask your colleague to note down what they've done in order to produce this situation; I'll add the "Feedback" label to this issue for now and will close it when there are no updates for more than a week.

**Comment by ThomasVitus** [comment] 2021-09-07 12:49
Steps to Reproduce(?)
The colleague now explained to me that she accidentally pressed "discard" when linking to the index case. After that, it was no longer possible for her to create a contact to an index case.

And it happened to this colleague again today. This time, when creating the "Contact to index person", the error message "Saving not possible, because someone else has changed the case file" came up. After that, all entered data was gone, but a new creation was not possible, because the button "New contact" is completely missing again since then.

**Comment by kwa20** [comment] 2021-09-07 16:31
@ThomasVitus @MateStrysewske I think I managed to reproduce it:

A user seems to have deselected the contacts with source case field and saved the form while another one was busy entering a contact to a source case.
<img width="1090" alt="Screen Shot 2021-09-07 at 6 28 09 PM" src="https://user-images.githubusercontent.com/70317594/132379538-5f010084-bfeb-4718-b2b0-cd53a620d84c.png">

Steps to reproduce:
1. log in with user A and enter the epi data form of a case not yet having any contacts to source cases entered.
2. log in with user B and go to the epi data tab as well.
3. Create a new contact with user A
4. In the meantime, deselect (or select no, unknown) in contacts with source case known with user B and save the form
5. Finish entering contact data with user A and save the contact
6. An error appears that prevents saving, only option that remains is to discard
7. check contacts without source cases field (> will be disabled as seen on the screenshot)

**Closed** 2021-09-20 14:25 UTC
Labels: bug, cases, backend, vaadin-app

**Comment by roxanamlendea** [comment] 2021-09-24 11:44
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
