### ISSUE TITLE
Mobile app- Campaign list deleted on AFG Abkhamari

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#5768] opened 2021-06-11 14:53 UTC
### Bug Description

~~The campaign defaults to December 2021 as the latest data- Means it shows based on date created. We should default it to the current month we are in the way the web app defaults.~~ -> https://github.com/hzi-braunschweig/SORMAS-Project/issues/5941

The campaign list disappeared while making a presentation on the mobile app. Dont know what caused it
See log file. I restarted the app, resynchronized and every thing. But the campaign list is still blank
[log file.docx.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6639308/log.file.docx.zip)

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2021-06-15 11:35
@tomabadaniel .docx is a very bad file format for logs. Can you please re-upload the logs as a .txt file?

As for the first part of the issue, please open a separate change request for that.

**Comment by MartinWahnschaffe** [comment] 2021-06-24 12:01
@tomabadaniel  I have now taken care of splitting this into two issues.
Is the bug something you can reproduce? Does it happen when connecting to the test system at https://test-afghanistan.sormas.netzlink.com with the mobile app?
Can you provide user credentials for a test user, please (not via Github)?

**Comment by tomabadaniel** [comment] 2021-06-25 15:48
> @tomabadaniel I have now taken care of splitting this into two issues.
> Is the bug something you can reproduce? Does it happen when connecting to the test system at https://test-afghanistan.sormas.netzlink.com with the mobile app?
> Can you provide user credentials for a test user, please (not via Github)?

Hi Martin @MartinWahnschaffe I got this error while demonstrating to the country folks. So it only happened on my device. What i did was to do a hard pull or deep sync from settings and I lost all the campaign lists. Now when I created a new campaign form element, its the only one that shows on the directory. The user is MobiUser. You can change the password and test it. But on the web all the elements for that user exists but not on the mobile. It just disappeared from the mobile app. I think it has something to do with the hard sync I did. It happened when connecting to  https://test-afghanistan.sormas.netzlink.com

**Comment by MartinWahnschaffe** [comment] 2021-06-29 07:51
I have tried to reproduce this by doing the following:

1. Connected with MobiUser to https://test-afghanistan.sormas.netzlink.com/sormas-rest
2. Sync shows all campaings. Campaign data is available for June.
3. Pressed re-sync data in settings -> all works fine

I also created a new campaign, synced it to the device and then deleted it, because I thought this might be a problem. But this worked also without a problem.

Looking at the log I found the following types of log information:
[log file.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6731531/log.file.txt)

1. NullPointerException at de.symeda.sormas.backend.common.AbstractCoreAdoService.delete(AbstractCoreAdoService.java:19). Happens because the delete button can be used in the campaign creation form
2. No enum constant de.symeda.sormas.api.campaign.form.CampaignFormElementType -> invalid campaign form definition
3. OutdatedEntityException: UserDto is older than current version on server -> when editing user and having the same user form open multiple times
4. ValidationRuntimeException -> form validation
5. RuntimeException: Campaign diagram data map already contains grouping -> invalid campaign chart definition
6. URISyntaxException: Illegal character in fragment at index 71: https://test-afghanistan.sormas.netzlink.com/sormas-ui/login#!dashboard#7s8d6f87 -> no idea how the #7s.. made it's way in the URL - probably a typo
7. GridLayout$OverlapsException: com.vaadin.v7.ui.TextField@714ef30f( type = com.vaadin.v7.ui.TextField, caption = "<h3>Cluster number</h3>") is already added to 0,0,1,1(column1, column2, row1, row2). -> same field used multiple times in a form definition
8. javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted -> follow-up error for 1

None of these errors is related to the data sync to the mobile device.

I guess there was a local error on the mobile device that let to the sync not properly working anymore. Without being able to reproduce it or having more details on this there is nothing we can do though.

@danieltomaba Any additional ideas on this? Otherwise I would suggest to close this issue.

**Comment by MartinWahnschaffe** [comment] 2021-07-05 14:13
Closed, because it's not reproducable

**Closed by MartinWahnschaffe** 2021-07-05 14:13 UTC
Labels: android-app, bug, campaigns, feedback
