### ISSUE TITLE
Entities do not load in the 'Cases', 'Contacts' and 'Samples' directories

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8373] opened 2022-03-14 12:11 UTC
### Bug Description

Cases, contacts and samples associated with them are not loaded.

### Steps to Reproduce

1. Navigate to either of the following directories: cases, contacts, samples;
2. Click on an entity's ID to open it.

### Actual Behavior

Page is blank and the entity is not loaded. If the user clicks to reload the page, an error message appears:
![image](https://user-images.githubusercontent.com/96909231/158170580-8c3043b9-1292-43cf-a15c-1fc9c1dfa378.png)

### Expected Behavior

Entity page is loaded and visible to the user.

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(d64ad2b)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information

Logs from the server:
[Logs from the local machine.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8244593/Logs.from.the.local.machine.txt)

**Comment by MateStrysewske** [comment] 2022-03-14 12:18
Whoever picks up this issue - please check whether this is caused by a recent change; if so, close this issue and reopen the responsible issue.

**Comment by BarnaBartha** [comment] 2022-03-14 18:34
This is caused by #7323, because of the changeUser join for all entities, somewhere there is a join explosion probably and thus we reach the maximum limit of columns in postgres:
org.postgresql.util.PSQLException: ERROR: target lists can have at most 1664 entries

**Comment by MartinWahnschaffe** [comment] 2022-03-15 08:02
I have re-opened #7323.

**Closed by MartinWahnschaffe** 2022-03-15 08:02 UTC
Labels: duplicate, critical
