### ISSUE TITLE
Android app falls back to wrong language files by design

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#5428] opened 2021-05-13 12:10 UTC
### Bug Description

Mobile application shows APMIS server without afghan locale.
### Steps to Reproduce

1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/8166805/118123718-54753f80-b3fd-11eb-86dd-e8b2799ff297.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment] 2021-05-14 13:21
The problem is that since N, Android is using an in my opinion pretty stupid fallback mechanism that will search for ANY en locale if it doesn't find a specific strings.xml for en (without any additional locale). Because of that, if the user's language is set to en, it falls back to en-AF instead of the default strings.xml.

I'm not sure about the correct way to solve this problem. Introducing an empty strings.xml for en might be a solution, but I'm not sure whether that will survive a Crowdin synchronization. It's worth a try I guess.

**Comment by MateStrysewske** [comment] 2021-05-14 13:24
See https://developer.android.com/guide/topics/resources/multilingual-support

**Comment by MateStrysewske** [comment] 2021-05-14 13:29
Creating a dummy strings.xml for en doesn't seem to work - probably because Android searches for the particular string in there, doesn't find it, and thus falls back to en-AF again...

**Comment by DavidBaldsiefen** [comment] 2021-05-17 07:08
This seems unrelated, but just FYI, I worked on the language settings for the androidapp [here](https://github.com/hzi-braunschweig/SORMAS-Project/pull/5364) recently..

**Comment by MateStrysewske** [comment] 2021-05-17 07:26
@DavidBaldsiefen Yes, it's unrelated. The problem we have is by design, i.e. Android developers thought it would be a good idea.

**Comment by richardbartha** [comment] 2021-05-17 18:37
Still writes sync with APMIS server if you have English(Nigeria) or English(Ghana) selected 
![image](https://user-images.githubusercontent.com/83635257/118539314-9250cb80-b74f-11eb-867d-fd45624bf97b.png)

**Comment by BarnaBartha** [comment] 2021-05-18 05:37
@MateStrysewske the mobile app does not have Ghana or Nigeria specific english resources, thus the issue mentioned by @richardbartha.
Was this wanted until now, not to have specific values-en-NG and values-en-GH? AFIS adding these is the solution.

**Comment by MateStrysewske** [comment] 2021-05-18 07:31
The solution here is probably to finally add en-GH and en-NG to Crowdin. That would be the cleaner solution anyway. I'll take care of that.

**Comment by MateStrysewske** [comment] 2021-05-18 15:27
Fixed by integrating en-GH and en-NG into Crowdin

**Closed by MateStrysewske** 2021-05-18 15:27 UTC
Labels: android-app, bug, general, important, major
