### ISSUE TITLE
Cases | Contacts | Events | Admin user is unable to see the cases

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#8823] opened 2022-04-13 16:01 UTC
### Steps to Reproduce
1. Log in with Admin user and go to Cases Directory (observe what is displayed, if anything is displayed)
2. Click on New Case and complete the process of creating a new case
3. Go to Contacts and back to Cases and check if the new case is displayed
4. Log in with NatUser and go to Cases directory

### Expected Behavior
Users with Case_View right should be able to see cases ( Admin user, although has the Case_View right, cannot see any of the cases)

### Actual Behavior
No Cases are displayed for the Admin user 

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL: localhost sormas version 1.71.0-snapshot
* User Role: Admin NatUser

### Additional Information
The same behavior is reproducible also for NatUser

**Comment by bernardsilenou** [comment] 2022-04-13 16:07
Do admin users need to have a case-view right in the first place? 
I think we can remove all the person related sensitive data view rights from admins

**Comment by MateStrysewske** [comment] 2022-04-14 07:13
Duplicate of #8689.

This is not an urgent issue because users with only the Admin user role aren't supposed to do any active work in the system. Bernard might also be correct that Admins shouldn't have all these rights in the first place, but that's something we'd need to discuss further.

**Closed by MateStrysewske** 2022-04-14 07:13 UTC
Labels: bug, contacts, cases, events, vaadin-app

**Comment by carina29** [comment] 2022-04-20 07:31
Another problem related to this bug would be the fact that even if the Cases List is shown as empty to the Admin user, when the merge duplicates is clicked and there are duplicates, the cases will appear from the Merge duplicates view but in Cases list view the number of cases will be 0 and the cases will not be displayed.
