### ISSUE TITLE
Trigger the 'Confirm navigation' pop-up sooner on entity pages

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8607] opened 2022-03-29 12:36 UTC
### Problem Description

When changes are made on entity pages and the user clicks 'Delete' at the bottom of the page, the 'Confirm navigation' pop-up is triggered after the 'Confirm deletion' pop-up and an error message appears.

Steps to reproduce:
1. Log in with a user that has 'Deletion' rights (Admin+NatUser);
2. Open an existing case;
3. Edit any information on the case page;
4. Click 'Delete' at the bottom of the page
=> 'Confirm Deletion' pop-up is triggered;
5. Click 'Yes' in the pop-up;
=> 'Confirm navigation' pop-up is triggered;
6. Click 'Save changes' in the pop-up
=> error message appears.

![image](https://user-images.githubusercontent.com/96909231/160611770-13c17e38-0621-4dcc-a50b-f1a01fa106c6.png)

This is reproducible on the following pages:
- [ ] case page;
- [ ] contact page;
- [ ] event page;
- [ ] event participant page;
- [ ] sample page;
- [ ] immunization page;
- [ ] travel entry page;

In the 'Samples' directory, the same error message is reproducible if the user clicks 'Refer to another laboratory' instead of 'Delete'.

### Proposed Change

Trigger the 'Confirm navigation' pop-up before the 'Confirm deletion' pop-up.

**Comment by MateStrysewske** [comment] 2022-06-09 13:38
Duplicate of #9435

**Closed by MateStrysewske** 2022-06-09 13:38 UTC
Labels: contacts, cases, events, laboratory, change, immunizations, travel entries
