### ISSUE TITLE
Error in EPI week filter on the case directory

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1322] opened 2019-09-19 21:56 UTC
In the case directory, when filtering by EPI week as shown in the first image, the result returned is in date instead of EPI week as shown in the second image. Although the date range returned matches with the chosen or selected EPI weeks, many users will prefer to see the results returned be in EPI weeks they selected earlier and not date range

![image A7](https://user-images.githubusercontent.com/50739609/65284130-9c609800-db30-11e9-8688-eaef94748df7.JPG)

![Image A8](https://user-images.githubusercontent.com/50739609/65284143-a4b8d300-db30-11e9-8ea8-99b9b2f3b377.JPG)

**Comment by MateStrysewskeSym** [comment] 2019-09-20 11:26
This is a duplicate of #1311.
@Iheanacho2027 Please check the existing issues first before submitting new ones in case something similar already exists (like this one).

**Closed by MateStrysewskeSym** 2019-09-20 11:26 UTC
Labels: duplicate

**Comment by Iheanacho2027** [comment] 2019-09-20 11:32
Ohk great
