### ISSUE TITLE
Cases > Filter by `Outcome of Case` makes column disappear in filtered results

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#7267] opened 2021-11-15 10:36 UTC
### Bug Description

Cases > Filter by `Outcome of Case` > Column displaying `Outcome of Case` disappears in filtered results (in the table).

### Steps to Reproduce

1. Cases > View Case directory with all entries. Also visible is column `Outcome of Case`
2. Filter by `Outcome of Case` and apply
3. Filtered results are shown, but `Outcome of Case` column disappears from results table.

### Expected Behavior

`Outcome of Case` column should still be visible after filter is applied.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/141766182-eaf7db6b-1c59-40aa-9e82-af5fed9bea70.png)
![image](https://user-images.githubusercontent.com/65529128/141766547-651100f2-5d5e-4cbf-8dcf-cd1f5c3f1862.png)

### System Details

* Device: Web
* SORMAS version: 1.65.0
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: admin, natuser

**Comment by MateStrysewske** [comment] 2021-11-15 12:59
Duplicate of #7174

**Closed by MateStrysewske** 2021-11-15 12:59 UTC
Labels: bug
