### ISSUE TITLE
Identify performance problems in detailed export

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4316] opened 2021-02-09 12:32 UTC
### Problem Description
The detailed case and contact exports can be very slow on some systems, with export of a few thousand entries taking more than 10 minutes which results in a timeout on those servers. We need to investigate this, identify performance problems and fix them.

**Comment by AxelNennker** [comment] 2021-02-11 08:01
As this issue only occurs only on some systems, it seems to be a problem that is caused by not enough memory. So, the easiest fix would be to give the VM more memory or run it on bigger HW or both. Maybe too many VMs or Sormas Server and Sormas DB are running on the same machine?! Separating them might help too.

Looking at the OS monitoring data should reveal quickly if memory shortage is the cause.

Apart from the above "not a software problem" strategy of tackling this issue ... 

Sormas **GridExportStreamResource** is holding the data in memory.
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java#L139
The export data is in memory at least once, probably more often.

I think **DownloadUtils** is somewhat better in memory consumption
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DownloadUtil.java#L526
because it uses **CsvStreamUtils**
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/utils/CsvStreamUtils.java#L46
which pages the database data and uses DelayedInputStream.

**Comment by MateStrysewske** [comment] 2021-02-11 10:43
@AxelNennker Thanks for the input! We'll consider it while working on this.

Concerning database performance, these are some of the slow queries according to the logs:
* SELECT COUNT(contact) => 200.686 ms
* SELECT DISTINCT contact => 52.158 ms, 195.708 ms, 286 ms, 445 ms, 525 ms
* SELECT exposures => 22.886 ms, 112.488 ms, 127 ms
* SELECT SORMASTOSORMAS.contact_id => 38.330 ms, 179.934 ms, 200 ms
* SELECT DISTINCT task => 79.334 ms
* SELECT DISTINCT sample => 133.133 ms, 179 ms
* SELECT therapy.id => 50 ms
* SELECT clinicalcourse.id => 51 ms
* SELECT cases => 166 ms
* SELECT contacts.visit_id => 93 ms
* SELECT cases.id... (huge query) => 68 ms

It seems like there's one symptoms query per contact entity even though we already tried to put this all into one additional query. Hibernate seems to do some under-the-hood "optimisation" there. Also, there are a lot of additional queries in between; I don't know whether they're from the exports or from other users using the system at the same time. We'll definitely have to test this on our local systems as well, ideally on a system with 1000+ contacts so we can check whether our measures actually make a difference.

On the system that we have the logs from, exporting one batch of contacts (50) takes 1.5 seconds.

**Comment by cazacmarin** [comment] 2021-03-01 06:38
[Measurements.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6059543/Measurements.xlsx)
Measurements for Cases and Contacts with proposal for optimization is inside on attached excel file. 
-> For Cases, has been obtain in the best case, up to 2-2.5 time faster (if all will come with 1 call and data are transmitted to the network in only 1 call, it can be even faster)
-> For Contacts, has been obtain in the best case, up to 5-6 time faster (if all will come with 1 call and data are transmitted to the network in only 1 call, it can be even faster)
For more details please contact attached excel file.

**Comment by StefanKock** [comment] 2021-03-01 15:01
Discussed with @MartinWahnschaffe.
Get bigger chunks of the sorted data to avoid overhead of in database sorting.

Proposal:
- STEP_SIZE = 5_000 as default
- Make STEP_SIZE configurable via sormas.properties
- Be sure nothing gets worse on events and samples.

**Comment by StefanKock** [comment] 2021-03-02 07:05
We already ran sometimes in exceeding parameter limit of 32K for PostgreSQL, but I think with 5_000 as default we are quite safe. In #2894 I introduced `IterableHelper.executeBatched` to easily split large collections that go into IN statements.

**Comment by cazacmarin** [comment] 2021-03-04 06:34
[Measurements_including_Events.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6081300/Measurements_including_Events.xlsx)
Events tab with detailed measurement has been added as well.
In process of Events creation, number of Contact and Cases has been changed. Last tab, test_5k, is showing the results based on code which will be committed soon.

**Closed** 2021-03-04 14:17 UTC
Labels: backend, change, import & export, performance, vaadin-app

**Comment by cazacmarin** [comment] 2021-03-05 05:37
Adding 3 big DBs:
1. with 4226 events, 28826 contacts and 9370 cases

[sormas_dump_02.03.2021_4226_events+4250contacts+4216cases.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6088302/sormas_dump_02.03.2021_4226_events%2B4250contacts%2B4216cases.zip)

**Comment by cazacmarin** [comment] 2021-03-05 05:39
2. 4216 Cases only
[sormas_dump_23.02.2021_4216Cases.sql.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6088316/sormas_dump_23.02.2021_4216Cases.sql.zip)

**Comment by cazacmarin** [comment] 2021-03-05 05:41
3. 4250 Contacts and 4216 Cases
[sormas_dump_28.02.2021_4250_contacts_and_4216_cases.sql.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6088323/sormas_dump_28.02.2021_4250_contacts_and_4216_cases.sql.zip)

**Comment by cazacmarin** [comment] 2021-03-05 05:45
Exception log is attached. Sometime, export dies at 5+ minutes, another time, only on 1+ minutes. I was able to reproduce it only with STEP_SIZE set to 50 for the 1st biggest DB for 28826 Contacts Detailed Export.
[exception_LOG.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6088331/exception_LOG.txt)

**Comment by AxelNennker** [comment] 2021-03-05 19:40
Vaadin DownloadStream calls InputStream.read(byteButter) here
https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/DownloadStream.java#L306
That is the InputStream that Sormas created.
Vaadin Server's DownloadStream has its own buffer which is between 0 and 65k (default 32k).

I think Sormas should retrieve the next chunk of rows from the database when read(byte[]) is called.
Currently Sormas reads the whole stream into memory.
