### ISSUE TITLE
Enable follow-up of cases and visualization of follow-up visits [FRENCH CONTRIBUTION]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1886] opened 2020-04-22 06:58 UTC
### Situation Description
At this time, follow-up and calls are only availible for contacts. It is not possible to conduct the aquivalent for cases.

### Feature Description
Provide the functionality to follow-up and track calls for cases.

### Possible Alternatives
n/a.

### Additional Information
n/a.

**Comment by max-hzi** [comment] 2020-04-28 08:36
I am aware that this is a bigger undertaking, but also Gérard Krause asks for this.

**Comment by MartinWahnschaffeSymeda** [comment] 2020-04-28 08:43
Yes, I can see that this will be very helpful. This needs some clarification, though:

1. What data do the users typically collect during a call?
2. Do they also ask for symptoms? If so, why?
3. What is the quarantine in the name of the issue about? We already have quarantine information for cases, right?

**Comment by max-hzi** [comment] 2020-04-28 08:45
Thank you for your reply, I will optain aswers to those questions asap.

**Comment by bernardsilenou** [comment] 2020-04-28 21:10
@max-hzi Follow up for cases is done under clinical course tab

**Comment by max-hzi** [comment] 2020-06-02 09:16
Handing on some more info I received:

- Similar to the overview for follow-up visits for contacts, an overview for the follow-up visits of cases should be incorporated in the case directory. 
- The overview for the follow-up visits of the cases should look similar, but the following aspects need to be exchanged:

Heading of the table
Contact ID = Case ID
Contact Person = Case
Responsible Contact Officer = Responsible Case Officer
Date of Last Contact = Date of First symptom
Add: Date of first positive lab result
(Aspects not mentioned here should remain the same)

Fields above table
All = All (here all cases)
Active contact = case with no outcome yet
Converted to a case = Case recovered
Dropped = Case deceased
Add: Case outcome unknown

Fields below title 
Remove “contact classification”

Colored fields representing the visits/calls

Mark them according to what is chosen for the case under “clinical course” when a “new clinical assessment” is generated. 

In “clinical course”in “clinical assessment”
Add the option if the patient was “unavailable”, “available, but uncooperative”, “available, but not responsive”, “available and cooperative”. 
Add discharge from hospital and hospitalization.

Give only a clinician the right to use this new feature.

**Comment by ManuelaHa** [comment] 2020-06-02 15:12
> Yes, I can see that this will be very helpful. This needs some clarification, though:
> 
> What data do the users typically collect during a call?
> Do they also ask for symptoms? If so, why?
> What is the quarantine in the name of the issue about? We already have quarantine information for cases, right?



> Yes, I can see that this will be very helpful. This needs some clarification, though:
> 
> What data do the users typically collect during a call?
> Do they also ask for symptoms? If so, why?
> What is the quarantine in the name of the issue about? We already have quarantine information for cases, right?



> Yes, I can see that this will be very helpful. This needs some clarification, though:
> _Hospitalisation and Symptoms_
> What data do the users typically collect during a call? 
> Do they also ask for symptoms? If so, why? _To see the clinical course. If they get worse, they need to go to a hospital and it is also good to now when the person releases the hospital if he/she develops futher symptoms_
> What is the quarantine in the name of the issue about? We already have quarantine information for cases, right? The quarantine is only the time slot in which to follow up with the cases

**Comment by bernardsilenou** [comment] 2020-06-24 22:25
This a summary of the changes to be done on the clinical  assessment and the overview. Ready for implementation

![image](https://user-images.githubusercontent.com/12996724/85633753-29192300-b67a-11ea-8979-1c3b8428b8d9.png)


![image](https://user-images.githubusercontent.com/12996724/85633764-2f0f0400-b67a-11ea-9b15-0aa777ce7caf.png)

**Comment by OlivierLeuci** [comment] 2020-06-30 06:23
Hello,
Does it mean that this is already done and committed for the next version of SORMAS HZI.
Thank you for your reply.

Best regards.

**Comment by OlivierLeuci** [comment] 2020-06-30 06:25
@MateStrysewskeSym @MartinWahnschaffeSymeda sorry, the above question was for you. B.R

**Comment by MateStrysewskeSym** [comment] 2020-06-30 06:32
@OlivierLeuci No, otherwise the issue would be closed.

**Comment by OlivierLeuci** [comment] 2020-06-30 06:48
@MateStrysewskeSym Sorry, I watch the closed label for our issue #2407.
So my question is when do you think it will be developped and in stable release?
Thank you for your answer.
BR

**Comment by MateStrysewskeSym** [comment] 2020-06-30 06:52
@OlivierLeuci Unfortunately I can't answer that question; it depends on the priorities we're getting. Please get in touch with HZI.

**Comment by OlivierLeuci** [comment] 2020-06-30 07:38
@MateStrysewskeSym We've done a dev on this purpose and it's in test on our environnement. Maybe we can adapt what we've done to your needs and manage a pull request about our code to you?

**Comment by MateStrysewskeSym** [comment] 2020-06-30 08:34
@OlivierLeuci That would be great if it matches the requirements by HZI!

**Comment by bernardsilenou** [comment] 2020-06-30 12:39
@OlivierLeuci This issue was on the top on our planning to go into the next sprint beginning next week. Since you have started the implementation, this is really great. I can make myself available any time you need so that we can have a short meeting to add points from our side that may not have need considered.

Please lets continue by email with calendar appointment.

**Comment by OlivierLeuci** [comment] 2020-06-30 13:36
Dear Bernanrd,

The problem is that the way you see the implementation of the follow up for Cases is different from the one we build from our workshop request. So as it, we can’t use what we’ve already done and it’s a problem for us.
If possible, we must talk about it tomorrow during the meeting with Odile.

BR


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image007.png@01D64EF4.35D24DD0]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image003.png@01D64EF4.35B48CA0]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image004.png@01D64EF4.35B48CA0]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image005.png@01D64EF4.35B48CA0]

03.81.53.21.23

[cid:image006.png@01D64EF4.35B48CA0]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : mardi 30 juin 2020 14:39
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Enable follow-up of cases and visualization of follow-up visits (#1886)


@OlivierLeuci<https://github.com/OlivierLeuci> This issue was on the top on our planning to go into the next sprint beginning next week. Since you have started the implementation, this is really great. I can make myself available any time you need so that we can have a short meeting to add points from our side that may not have need considered.

Please lets continue by email with calendar appointment.

**Comment by bernardsilenou** [comment] 2020-06-30 13:50
@OlivierLeuci OK, we will discuss tomorrow.
Please can you send the specification or mockup of what you have programmed to that I can also compare with what we have before the meeting tomorrow?
No need to translate it,

**Comment by bernardsilenou** [comment] 2020-07-01 19:38
@MateStrysewskeSym @markusmann-vg 
 We had a meeting with the French team today and they are ready to program this module, I suggest we assign it to them.
The transitional specifications that will be added is the follow up status as we have for contacts. This will be by default 14 days with extension if needed.

![image](https://user-images.githubusercontent.com/12996724/86284247-c9bf9380-bbe2-11ea-8a3d-3342f7d653fc.png)

**Comment by bernardsilenou** [comment] 2020-07-01 19:42
@markusmann-vg Please confirm that we are not programming this issue. The time line is one week from now to do a pull request as the French team has already started development.

**Comment by MateStrysewskeSym** [comment] 2020-07-02 09:11
@bernardsilenou Please confirm with Gérard that we actually want this to be a part of SORMAS because I don't really agree with it (after discussions with HZI two days ago). We already have clinical management that allows to document clinical visits and I don't really see regular follow-up of cases to be a necessary part of the core SORMAS project because it really blurs the line between cases and contacts. My feeling was that Gérard had a similar opinion when we talked, but I might have misunderstood him.

**Comment by bernardsilenou** [comment] 2020-07-02 12:57
@MateStrysewskeSym The fact that we need to keep methods to specific entities is the way to go. For follow up for cases, we are using the  modified " new clinical assessment" entity not the " follow up visit" entity for contact. So this cause no conflict.
Using the same module for contacts, we can then have a visualization of the daily follow up of the cases on the case directory.
The only limitation i found her is adding the followup status and fixed duration of followup to cases. Follow up of cases is until the outcome of the case, some can be 7 days, others 7 weeks. However, this is an optional feature and causes no harm. System can calculate the default based on incubation period and users can change if needed. It can be an disease configuration parameter on the server. For diseases like COVID that cases may some times show no symptom, this feature is needed and i see why the users in Germany and France need it. 
I will discuss with Gérard next Monday about this.

**Comment by bernardsilenou** [comment] 2020-07-08 18:42
@OlivierLeuci  @carolinverset We decided to go with the implementation discussed today. We can keep the clinical course tab as it was and rename the "followup visit" tab "follow up" to the cases and put them side by side.
@MateStrysewskeSym We did a review today and the French team has completely implemented the  follow up module for  cases using the same as we had for contacts. Even though we initially wanted to update and use the clinical course module, we think this is a good way to go about it. 
So we now have an additional tab to cases called followup, exactly as we have for contacts.

**Comment by MartinWahnschaffeSymeda** [comment] 2020-08-13 15:13
See https://github.com/hzi-braunschweig/SORMAS-Project/pull/2646#issue-467435303 for current status.

Things that will not be part of the implementation yet and moved to separate issues:

* case follow-up in the mobile app
* taking over visits from a contact to a converted case
* updating the symptoms of the case based on the symptoms of the visit
* handling the visits when merging a case

**Comment by bernardsilenou** [comment] 2020-08-13 15:55
@MartinWahnschaffeSymeda  Good decision

**Comment by MartinWahnschaffeSymeda** [comment] 2020-08-14 11:19
@xavier-calland I have merged your and my changes to the development branch. I would highly appreciate if you could have a look at my changes in #2646 and give feedback. Thanks a lot for your work on this!

**Closed by MartinWahnschaffeSymeda** 2020-08-14 11:19 UTC
Labels: Case Surveillance, ch, feature

**Comment by leventegal-she** [comment] 2020-08-14 11:36
Code review https://github.com/hzi-braunschweig/SORMAS-Project/commit/aa289bd0eebce6dd3fefffab8ce1abe27dfbc4d8: OK

**Comment by xavier-calland** [comment] 2020-08-24 07:23
@MartinWahnschaffeSymeda Thanks for your work. I'm not sure to see all impacts of code changes, however it looks good to me.

**Comment by bernardsilenou** [comment] 2020-08-24 08:26
@xavier-calland Welcome back,
In addition to the 4 issues above created by Martin on August 14, There is also  issue #2678 with stories related to followup of cases obtained after testing the current version. Would you like to continue with any of the stories or we take over completely?
Please have a look at them and send an email including Markus and Maté by tomorrow please. Thanks

**Comment by OlivierLeuci** [comment] 2020-08-26 14:19
@MartinWahnschaffeSymeda @bernardsilenou 
After some discussion with @xavier-calland, we could take some of the new issues mentionned above (#2650 #2651 #2652 #2653 #2678) but we couldn't take all.
For the moment (it could change later on), we prefer not to work on mobile part of SORMAS because nobody use it in FRANCE for the moment. So can you hold this at your level?
For the other issues, Xavier could produce not more than 5/6 days till the 8th of sept (due date to 1.48.0 milestone) of work so we need to do a choice.
I propose that Xavier manage the 4 issues (#2651 #2652 #2653 #2678) but we need to see with you how to plan them in one or more milestone(s) and to qualifie more precisely the way to implement the needs.
Thankx for your reply. We can plan a meeting or speak about it next wednesday (sorry, I miss the one today).

**Comment by bernardsilenou** [comment] 2020-08-26 23:55
@OlivierLeuci @xavier-calland 
Thinks for this wonderful suggestion and I also agree with you that the German team should implement the mobile part.
I suggest we have a meeting (including @MateStrysewskeSym if pssible) this Friday or latest on Monday 31 to agree on the specifications. Our normal Meeting will still take place on Wednesday. I will communicate with Maté and send an invite with different options.
Merci

**Comment by OlivierLeuci** [comment] 2020-08-27 08:43
Bonjour Bernard,

Après concertation, nous pouvons vous proposer une réunion Vendredi possible sur les horaires suivants :
vendredi de 9h30 à 10h30 ou de 15h à 16h.

Nous pouvons fournir un outil de webconférence.

En vous remerciant pour votre retour.

Bien cordialement.

Olivier


Merci de bien vouloir noter mon changement d’adresse mail

[cid:image008.png@01D67C5E.DF195E00]



Groupement Régional d’Appui
Au Développement de la e-Santé (GRADeS)
Bourgogne Franche-Comté



[cid:image004.png@01D67C5E.7B171A50]

16, rue Professeur Paul Milleret, 25000 Besançon

Olivier LEUCI

[cid:image005.png@01D67C5E.7B171A50]

06.35.11.52.44

Directeur Adjoint
( Direction technique et financière )

[cid:image006.png@01D67C5E.7B171A50]

03.81.53.21.23

[cid:image007.png@01D67C5E.7B171A50]

olivier.leuci@esante-bourgogne.fr



De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 27 août 2020 01:56
À : hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com>
Cc : Olivier Leuci <Olivier.Leuci@esante-bfc.fr>; Mention <mention@noreply.github.com>
Objet : Re: [hzi-braunschweig/SORMAS-Project] Enable follow-up of cases and visualization of follow-up visits (#1886)

Attention : Ce courriel a été envoyé depuis l'extérieur du GRADeS. Si vous n'êtes pas certain de l'expéditeur ou du contenu de celui ci, NE CLIQUEZ SUR AUCUN LIEN et N'OUVREZ AUCUNE PIECE JOINTE, ceux ci pouvant renfermer un contenu malveillant.
En cas de doute, NE TRANSMETTEZ PAS LE MAIL et contactez le service technique.



@OlivierLeuci<https://github.com/OlivierLeuci> @xavier-calland<https://github.com/xavier-calland>
Thinks for this wonderful suggestion and I also agree with you that the German team should implement the mobile part.
I suggest we have a meeting (including @MateStrysewskeSym<https://github.com/MateStrysewskeSym> if pssible) this Friday or latest on Monday 31 to agree on the specifications. Our normal Meeting will still take place on Wednesday. I will communicate with Maté and send an invite with different options.
Merci

**Comment by ChristopherRiedelSymeda** [comment] 2020-08-28 05:29
@OlivierLeuci It is not that bad if something like this happens, but it should not happen: Please refrain from such communication on GitHub in the future, it really has no place here. Also, it would be nice if we stay with a language that everyone understands (English).
