### ISSUE TITLE
Trying to save visits results in an error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5988] opened 2021-06-29 08:32 UTC
### Bug Description
Trying to save a new visit results in an error and results in the visit not being able to be saved.
### Steps to Reproduce

1. Go to the follow-up visits tab in cases and contacts
2. create a new visit, enter any combination of required fields and press save

### Expected Behavior

The visit should be able to be saved
### Screenshots

<img width="516" alt="visitsError" src="https://user-images.githubusercontent.com/70317594/123764588-34beab80-d8c5-11eb-8904-07c30c1f0377.PNG">

### System Details

* Device:
* SORMAS version: 1.61-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by kwa20** [comment] 2021-06-29 08:38
tested this also on test.sormas.netzlink.com and could verify the problem

**Comment by MateStrysewske** [comment] 2021-06-29 08:42
Duplicate of #5951

**Closed by MateStrysewske** 2021-06-29 08:42 UTC
Labels: bug
