### ISSUE TITLE
[Cases] Error message regarding file limit size for CSV files imported is not present

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11333] opened 2023-01-12 10:53 UTC
### Problem Description

No response from service, no action appearing while updating file with size more than 20 MB

#### Steps to Reproduce

1. Log in as a automation admin
2. Navigate to Case directory
3. Click Import
4. Click Detailed Import
5. In file picker choose attached file which exceeds 20mb

#### Screenshots

The message that appears when trying to import a file over 20MB in the 'Contacts' directory, that should also appear in 'Cases':
![image](https://user-images.githubusercontent.com/96909231/212307818-3a9b7096-55bb-4133-93a9-830240c5b846.png)

#### System Details

* Device: Win10
* SORMAS version: Version: 1.79.0-SNAPSHOT (50d6548)
* Android version/Browser: Google Chrome 109.0.5414.75
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Automation Admin

### Expected Behavior

Meaningful error message should appear:
![image](https://user-images.githubusercontent.com/96909231/212307842-6330fa52-019c-4f89-b546-09ed854c5a3c.png)

**Comment by adinaflorea9** [comment] 2023-01-13 11:15
Reproduced the behavior on the local machine using SORMAS version 1.79.0-SNAPSHOT(2cf8f52) - the error message regarding the limit of the file size for imports does not appear when attempting a cases import in the 'Cases' directory. Therefore, I converted this ticket into a bug, as this is reproducible not only on the current version but on the 1.78.0 version. 

The error message is implemented and appears in the other directories when attempting to import a file that exceeds 20MB. @sergiupacurariu helped by looking into the code and it appears that the error message was indeed implemented for cases as well, so the issue is that it is just not displayed in the UI.

**Comment by carina29** [comment] 2023-01-16 13:30
Hello all,

I've tried to reproduce this problem by trying to import a larger than 20MB file and locally on my side the message appeared for both contacts and cases page. 
![contacts](https://user-images.githubusercontent.com/47103965/212689176-f2073b31-f42b-4f94-ad82-0c6a848d6a2f.PNG)

![cases](https://user-images.githubusercontent.com/47103965/212689217-93f79e8e-d1ea-4794-b2ab-39ccc26cd091.PNG)

@adinaflorea9 if you want we can have a call to talk about this ticket :)

**Comment by adinaflorea9** [comment] 2023-01-16 14:42
As discussed with @carina29 I will move the ticket in Waiting until the testing instances are updated as well as currently the behavior is no longer reproducible on my local machine but it is still reproducible on https://test-de2.sormas.netzlink.com/. Once the testing instances are up to date will re-test the behavior.

**Comment by carina29** [comment] 2023-01-17 12:29
I've checked the logs received from @adinaflorea9 from test-de2 for case and contact import and also the logs from test-auto.

1) On test instances test-de, test-de2, test-de3, test-auto the problem is reproducible ( the error message that the file exceeds 20MB is not appearing and the selected file name will be reset to "No file chosen").
[case test-de2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10434931/case.test-de2.txt)

[contact test-de2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10434932/contact.test-de2.txt)

[test-auto cases logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10434929/test-auto.cases.logs.txt)

I did not find any error or exception which could cause the above mentioned problem, in one of the logs a TopologyException is present but at a different time and does not have any relation with this problem.


2) Locally the message appears for both contacts and cases ( if the uploaded file exceeds 20MB) and in the log
"UploadException: Upload failed" and "ValidationRuntimeException: File too big. The maximum file size allowed is 20MB"
appears as it should happen based on the implementation. These exceptions are missing from the logs on test instances            ( probably the exceptions are not reached).

[LocalLogsWhenErrorMessageAppears.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10434955/LocalLogsWhenErrorMessageAppears.txt)

We will continue to investigate this problem with @adinaflorea9.

**Comment by carina29** [comment] 2023-01-18 15:38
It looks like the problem is coming from the servers. I've inspected the console and the network calls on the test instances with large file uploads. In all of the cases HTTP 413 which means that the request entity is too large and the size of the client's request exceeds the server's file size limit.

I'll attach some screenshots which proves the above mentioned. 
Till now I've tested the problem on test-de, test-de2, test-de3, test-auto and the same problem is present. This means that the upload limit configuration of these servers ( and maybe other servers too which I did not test yet) should be changed in order to accept a larger upload size.

Test-auto with an upload file of 19.7MB size:
![test-auto-19-7MB](https://user-images.githubusercontent.com/47103965/213215362-b08ab948-56bc-4197-af91-54d8087d42c6.PNG)

Test-de with an upload file of 19.7MB size:
![test-de-19 7MB](https://user-images.githubusercontent.com/47103965/213215203-7ca57cdf-9daa-4cd7-aa46-133a391378bd.PNG)

Test-de2 with an upload file of 41MB size:
![41MB](https://user-images.githubusercontent.com/47103965/213215524-102b405d-d8f1-4fb7-baee-ac9dc4ea43f8.PNG)

Test-de3 with an upload file of 19.7MB size:
![test-de3-19 7MB](https://user-images.githubusercontent.com/47103965/213215285-45cd4bc1-8d17-445f-afc8-65bea3b25cab.PNG)

**Comment by carina29** [comment] 2023-01-19 09:02
**Update:** I wrote to Netzlink ( I've sent the problem description and also the above screenshots) to ask them if the upload file size configuration of the servers could be changed. 

Till we receive an answer, this ticket will be moved to waiting column.

**Comment by carina29** [comment] 2023-01-24 13:26
**Update:** I've retested on test-de, test-auto, test-de1, test-de2, test-de3 instances the import with large files after I've received a confirmation from Netzlink that the upload file size limit was increased.

In case of upload file of 14MB  or 19Mb 413 is still thrown:

![test-auto-14Mb-413](https://user-images.githubusercontent.com/47103965/214297839-ad1e2307-c937-48bf-88c7-51e1703f7f75.PNG)

![test-de2-19 7MB](https://user-images.githubusercontent.com/47103965/214297909-ddb1d7f2-cfb6-442d-8e47-a9209e4421bf.PNG)

![test-de3-14MB](https://user-images.githubusercontent.com/47103965/214298095-050fafd9-87cc-4d61-98f2-61f483f07fb0.PNG)

![test-de-14MB-413](https://user-images.githubusercontent.com/47103965/214298267-de0a42f2-0e43-4659-b700-162d8c567897.PNG)

![image](https://user-images.githubusercontent.com/47103965/214298569-6de6dcd4-fa68-40ac-9e7e-14c1a6b762e0.png)

![test-de1-19Mb](https://user-images.githubusercontent.com/47103965/214298829-8d6147f7-7a58-42bf-9be6-b884e0529024.PNG)

In case of trying to upload a 41MB file , 413 is not thrown but the status for upload will be failed (in Network tab) and the request number will be increasing in the background.
![test-de-41MB-failed-status-counting-requests](https://user-images.githubusercontent.com/47103965/214299001-63cccf83-3dcc-4737-a12e-f2dd99727f32.PNG)

It looks like a server configuration problem. Locally still everything is working fine.
I wrote to Netzlink to reassure that the servers upload limit was changed on all the mentioned test instances and the new value is at least 20MB.

I also talked with @MateStrysewske about this problem, he also thinks that more likely we have a server configuration problem. As a possible solution to overcome the server configuration problem he suggested to try to catch 413 from our code in order to display the same message as we display for larger files than 20Mb. 
The only problem here would be that if we would manage to catch 413,  ( if we assume that the servers were correctly configured related to the increase of the upload limit size) even for smaller files than 10MB the 413 Entity too large is thrown so in order to be consistent we should adjust the message which is thrown locally according to the new threshold.

Which would lead to 3 possible solutions: 
1) Having the certainty that the servers upload limit is adjusted correctly to at least 20MB ( I've sent an e-mail to Netzlink for reassurance) , if it's not adjusted correctly maybe this is the only problem
2) If we get the reassurance from Netzlink that the upload limit was correctly adjusted,  we should adjust our code too, in order to have the lowest accepted upload file everywhere ( locally and on the test instances too) and display the message with too large according to the new threshold ( less than 20MB)
3) Do not upload temporarily the file to the server and then process it - find a better solution

We agreed with @MateStrysewske that based on the above mentioned this would be a change not a bug and the purpose would be to fix the problems related to the server. 
@MateStrysewske  also suggested to take out this task from the sprint since this problem does not look like one with high occurrence ( for smaller files the important is working on test instances too) and in the future if the problem will persist ( the server configuration will not be solved) to create a new change ticket to overcome this problem.

@markusmann-vg Do you agree to take out this ticket from the current sprint ? :)

**Comment by carina29** [comment] 2023-02-07 16:28
**Update:**

-On the below mentioned test instances the upload limit of the servers was adjusted **from default value (20MB) to 60MB**:
1. test-de
2. test-de1
3. test-de2
4. test-de3
5. test-auto

The above mentioned will result in the following testing scenarios:
1) If the **upload file is smaller than 60 MB** 
=> the import will work, the uploaded file will not be deleted. If due to some problems the import will be cancelled , the user will be notified by a message as usually happens.

2) **The upload file is ~ 60MB**
Because the new upload limit is 60 MB, the message "A problem occurred File too big. The maximum file size allowed is 60MB" should appear above 60MB but after 60MB the server configuration will not allow the upload and in the console log 413 (Entity Too Large) will appear.
(I proposed to Netzlink to have 2 upload limits, one for the message and one for the maximum upload limit but they do not want to have 2 upload limits and a range  => With a range it would have had been possible to have for example a working interval for upload files between 0-40MB and another interval 40Mb -60MB in which the message related to the maximum upload file would have had been displayed. )

In conclusion, we will remain with the already configured solution: => upload file < 60MB will work, upload file > 60MB will have the behaviour described in this ticket and in console log 413 (Too Large Entity) will be displayed.

**Note:**
I've found a corner case, when the message  "A problem occurred File too big. The maximum file size allowed is 60MB" will appear and can be reproduced with an upload file of 59.9MB size.

![File too big error-59 9MB](https://user-images.githubusercontent.com/47103965/217302510-3dae9c40-1cf7-43f4-8fc2-72049a384d16.PNG)
Related to this corner case, Netzlink said that probably is possible because a Header will be added to the initial upload request of 59.9MB and probably ~60Mb will be the overall limit and not > 60MB for which the upload request should not work anymore.

3) Upload file >60MB, the behaviour described in this ticket will persist.
The users of the application should know that the upload files larger than 60MB will not work. 
In case of inspecting the console log, 413 (Too Large Entity will be displayed)

Screenshot from testing with an upload file of 63MB:
![image](https://user-images.githubusercontent.com/47103965/217303421-873f63d1-9374-467b-bf05-7e0a2139428e.png)



**Note:** On the Servers from production the upload limit was not adjusted, the default value , 20MB, is configured.
In order to adjust the upload limit on production servers too, a new ticket should be opened on Netzlink's side.

**Closed by carina29** 2023-02-07 16:28 UTC
Labels: bug, cases, vaadin-app, import & export, major

**Comment by adinaflorea9** [comment] 2023-02-13 08:59
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.80.0-SNAPSHOT(9f825d5) - for file sizes up to 20MB the upload is successful. For file sizes over 20MB the warning message regarding the file size appears.

Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version 1.80.0-SNAPSHOT(9f825d5) - behavior is as described by Carina in the comments above as the servers for the testing instances have been configured differently by Netzlink regarding the file sizes supported/allowed.
