### ISSUE TITLE
Duplicate bug on detailed case export

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1548] opened 2020-02-28 14:45 UTC
There is a bug which causes exports to have duplicate cases with same case sn and case ID

![bug ppppaaaa](https://user-images.githubusercontent.com/50739609/75557937-45e17900-5a41-11ea-84bf-023b87410908.JPG)

**Comment by MartinWahnschaffeSymeda** [comment] 2020-03-05 15:54
Hi @Iheanacho2027, can you give us some information on how the export was done? Is it a detailed case export? Any filters active? What kind of user?

**Comment by MateStrysewskeSym** [comment] 2020-03-06 09:06
@Iheanacho2027 Did this happen multiple times or only once?

**Comment by MateStrysewskeSym** [comment] 2020-03-06 09:22
I was able to reproduce this and will have a look into it.

**Comment by Iheanacho2027** [comment] 2020-03-06 13:02
@MartinWahnschaffeSymeda it's a detailed export, filtered by one disease

**Comment by Iheanacho2027** [comment] 2020-03-06 13:04
@MateStrysewskeSym it happened multiple times

**Comment by StefanKock** [comment] 2020-03-09 13:30
Checking in _CaseFacadeEjb.getExportList_ for implicit multi joins due to Collection attributes in joined entities. Suspects: EpiData, Hospitalization

**Comment by StefanKock** [comment] 2020-03-09 17:34
With mwahnschaffe I tried to reproduce the duplication with a manual SQL query, but we did not suceeed. Since we dont have a clue how the duplication happens, I will add a DISTINCT command to avoid case duplication.

**Comment by StefanKock** [comment] 2020-03-10 08:38
The investigation of the by Hibernate produced SQL, the following steps to enrich the export DTOs and the code to produce the CSV data did not show up an implementation flow that results in row duplication.

The defect might occur on data not conforming the Entity model (then there should also miss unique constraints, no prove) or a defect in Hibernate (also no prove).

Changes (on feature branch):
1. Added a unit test that could eventually help to find a defect in the Select-Query, but did no show a defect yet.
2. Added a DISTINCT on case for the export query. Results in the following SQL: `select distinct case0_.id as col_0_0_, ...` ,

I am not sure if it helps to fix the reported and validated defect.

**Comment by StefanKock** [comment] 2020-03-10 10:02
Possible explanations: 
1. The export does query paging with 50 entries on each page. Combined with an unstable sorting (sorting criteria _report date_ might be equal) this may result in not equal pages, when pages of 50 entries per JTA transaction are collected. This is now fixed by sorting secondary by id DESC.
2. When new cases are added while exporting, the new cases are added at the first page, and earlier reported cases are moved over the page end to the next page.

**Closed** 2020-03-10 15:52 UTC
Labels: bug, sormas-backend, sormas-ui
