### ISSUE TITLE
Import template update

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1148] opened 2019-05-20 14:55 UTC
Urgent need for the improved import functionality on the platform. 
Data dictionary update and a sample of an already populated import template would be very helpful.

**Comment by Iheanacho2027** [comment] 2019-05-22 13:12
Please this is very important

**Comment by MateStrysewskeSym** [comment] 2019-05-22 13:51
@Chinedar Please specify what you mean with "improved import functionality". Our current priorities for this and the next sprint are to make SORMAS completely corresponding to the Global Goods Maturity Model and to add Congenital Rubella as a new disease. We'll talk about this topic when we set the next priorities afterwards.

**Comment by Iheanacho2027** [comment] 2019-06-04 11:23
Following up on this @MateStrysewskeSym Some of the problems associated with the import functionality include
i.	The “location” sheet of the data dictionary doesn’t have a “value” column which shows the unique style or example for entering variables associated with location (i.e the “person” sheet and all other sheets have the “value” column that gives unique style or example for entering variables while the “location” sheet doesn’t). This is also the same for some other sheets on the data dictionary.

ii.	Some fields on the respective sheets of the data dictionary do not have the “value” column which gives unique style or example for entering variables. For example, in the “person” sheet, fields like Sex, ApproximateAgeType, PresentCondition, CauseOfDeath, Disease, DeathPlaceType, BurialConductor, EducationType and OccupationType have the ‘’value” column while the remaining fields do not have. All fields in all the sheets of the data dictionary, should therefore have “value” column which gives a unique style or example for entering variables.

iii.	There is no specific guide on how to enter dates in different sheets requiring dates, month of the year in particular i.e should the month of the year be in numbers e.g 01 or letters e.g January ?. A sample value which acts as a guide to enter date variables on every sheet should be given ( for example should it be in dd/mm/yy or otherwise).

iv.	The timeframe for checking the quality of variables during import is too much. Sometimes it could take up to 30minutes and end up producing no result. The import functionality should be a smart functionality which should take more than ten minutes to import or identify errors.


Alternatively, there could be a sample import CSV sheet where all variables to be imported are completely-filled with sample values to guide users on the use of the template.

**Comment by Iheanacho2027** [comment] 2019-06-11 14:14
Hi Mate @MateStrysewskeSym, whats the update on this?

**Comment by MateStrysewskeSym** [comment] 2019-06-11 14:15
@Iheanacho2027 We will review your suggestions in our next Sprint Review (which will be this Friday) and possibly add it to our next sprint.

**Comment by Iheanacho2027** [comment] 2019-06-27 11:37
Hi Mate, due to upsurge of cases coming from Nigerian states where the SORMAS hasnt been deployed and the demand coming from the national institute for all cases to be entered into the system, we request that this be made an urgent priority

**Comment by MateStrysewskeSym** [comment] 2019-06-27 11:39
@MartinWahnschaffeSymeda Please talk about this in the next sprint review and include it in the next sprint.

**Comment by Chinedar** [comment] 2019-06-27 12:14
@danieltomaba please bring up the suggestions I made to you in the discussion at your next sprint review.

**Comment by Iheanacho2027** [comment] 2019-08-07 13:45
@MateStrysewskeSym @MartinWahnschaffeSymeda Pls can you give me an appropriate syntax for inputing "Other health facility" in the health facility column of the import template. I am currently trying to work with the template currently available, i think i may make some progress if i can get an answer to the question i just asked

**Comment by MateStrysewskeSym** [comment] 2019-08-07 14:29
@Iheanacho2027 Do you want to import a case that is situated in a health facility that is not part of the system? In that case, you'll have to put either OTHER_FACILITY for a health facility not in the system or NO_FACILITY if the case is situated at home or somewhere else into the healthFacility column and then specify the name/description in the healthFacilityDetails column.

Is that way you meant or did you have something else in mind?

**Comment by Iheanacho2027** [comment] 2019-08-07 14:32
Thanks "OTHER_FACILITY" is what i have been looking for

**Comment by Iheanacho2027** [comment] 2019-08-07 14:35
Just tried  "OTHER_FACILITY" and the system rejected it saying
OTHER_FACILITY isnt in the database  .

**Comment by Iheanacho2027** [comment] 2019-08-07 14:37
I have also tried OTHER_HEALTH_FACILITY previously and it was also rejected

**Comment by MateStrysewskeSym** [comment] 2019-08-07 15:04
@Iheanacho2027 Seems like this is a bug. I'll fix it and it will hopefully be resolved in our upcoming release.

**Comment by Iheanacho2027** [comment] 2019-08-07 15:06
Alright

**Comment by bernardsilenou** [comment] 2019-08-08 10:07
Hi All,
Has this issue been solved? if not then we can tackle it while implementing the basic import function for line-list

**Comment by MateStrysewskeSym** [comment] 2019-08-08 11:01
@bernardsilenou No, this is still relevant. I agree that we should do this in one go though.

**Comment by Iheanacho2027** [comment] 2019-08-29 07:32
The import function is working fine but just a little issue is needed to be resolved for it to be made perfect. The issue is, when a duplicate is spotted, the sessions keeps loading for a very long time and never stops. This is shown in the image below
![ffffff](https://user-images.githubusercontent.com/50739609/63919890-897a0c80-ca37-11e9-8f3a-2c2f2f6c95b3.JPG)

**Comment by Iheanacho2027** [comment] 2019-08-29 07:34
Also the import template has no sample information data

**Comment by MateStrysewskeSym** [comment] 2019-08-29 07:41
@Iheanacho2027 Samples will be included in the next release that we're working on right now. Concerning the infinite loading issue; does this happen everytime or only on some occasions?

**Comment by Iheanacho2027** [comment] 2019-08-29 07:51
The infinite loading happens every time a duplicate is spotted as shown in
the image

**Comment by Iheanacho2027** [comment] 2019-09-11 16:23
An update on the import functionality from the latest release

1) There is no column variable for "Pathogen test requested" on the import template
2) There is a bug whereby two LGAs ( Bayo LGA and Gubio LGA in Borno state)  are not recognized by the database, i have confirmed that they are properly matched on the district column with the proper region of the import template, I have also confirmed from the database that i properly included the right syntax on the import template.
3) The infinite loading i complained of, in my last comment still exists. I cant comprehensively say if this is due to internet connection but i believe its due to database capacity issues

**Comment by MateStrysewskeSym** [comment] 2019-09-12 05:42
@Iheanacho2027 

1) Do you actually need this? It's more of a variable that mirrors the internal process of SORMAS; if you're importing samples AND pathogen tests at the same time, is it really relevant whether it's filled in or not?
2) Can you please paste me the exact error message from the error report file?
3) Both doesn't really make sense in my eyes; seems more like an issue with UI threading - I'll investigate this again and see whether I can reproduce it on my local system

**Comment by Iheanacho2027** [comment] 2019-09-12 05:53
I agree with you as regards number one, it's not really needed for import.

For number 2, the error given is " district name is not found in the
provided region or available on the database", I carried out all necessary
checks before logging this

For number 3, I really can't say but it takes a long time to load which
could be frustrating. I don't this is due to internet connection because
the duplicate checker that occurs when manually creating a case doesn't act
the same way.

**Comment by MateStrysewskeSym** [comment] 2019-09-12 06:05
@Iheanacho2027 What exactly did you put in the import file? "Bayo" and "Gubio"? Please verify so I can have a look into it, too.

Concerning the infinite loading; The UI logic that is processed during the import is way more complex and we have to use different UI threads to handle everything. This worked fine so far, but maybe some change broke it. I've already opened an issue for it: #1300

**Comment by MateStrysewskeSym** [comment] 2019-09-13 09:02
@Iheanacho2027 I didn't do anything, but I'm glad it's working now, whatever the reason was. Make sure to get back to us should it happen again.

**Comment by Iheanacho2027** [comment] 2019-11-07 23:46
This error exists during import in 1.29.0, pls kindly resolve @MateStrysewskeSym 



![errors](https://user-images.githubusercontent.com/50739609/68437421-2e942c80-01c1-11ea-976d-9483e8e6bf6a.JPG)

**Comment by MartinWahnschaffeSymeda** [comment] 2019-11-15 14:52
As far as I can tell this can be closed.
Contacts import is handled here #1154, samples can be imported with the case and the infinite loading is handled in #1300.

**Closed by MartinWahnschaffeSymeda** 2019-11-15 14:52 UTC
Labels: Case Surveillance, Import & Export, sormas-api, sormas-backend, sormas-ui
