### ISSUE TITLE
Immunization management and immunization status are not reset properly

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7164] opened 2021-11-05 13:31 UTC
### Bug Description

When creating an immunization and select Recovery as means of immunization, management and immunization status are set to completed/acquired. If the means of immunization is changed then to vaccination - without saving - management and immunization status are not reset.

### Steps to Reproduce

1. Create an immunization, select means of immunization "Recovery"
2. select means of immunization "Vaccination"

### Expected Behavior

Management and immunization status should be reset to "Scheduled"/"Pending", if the means of immunization is changed to "Vaccination" in a new immunization.
Whether this reset is legit for already persisted immunizations is debatable, but it should be performed for new ones.

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140517980-5214d14c-7300-4bf9-976c-9ad569d4084f.png)

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Contact Officer & Surveillance Officer

**Comment by roxanamlendea** [comment] 2021-11-16 13:55
@MateStrysewske I'm referencing you here because of the discussion we had today regarding the Means of Immunization and the Management / Immunization Status. The implementation in this ticket is for both newly created and existing immunizations. Can you confirm if it should be only for the new or also for the existing immunizations?

**Comment by MateStrysewske** [comment] 2021-11-17 08:25
@roxanamlendea If @syntakker has implemented it like this, I'm fine with it. The user will be able to change the management status back to completed if they need to. The only thing that's important would be that the behaviour is identical in the web app.

**Comment by roxanamlendea** [comment] 2021-11-17 10:12
If I overwrite the immunization status management, the change doesn't persist after save. 
Steps to reproduce:

- Create a new immunization.
- Select **Vaccination** as Means of Immunization.
- Check the **Overwrite immunization management status** tickbox.
- Select **Completed** / Acquired and **Save**.
- Open the Immunization again.

The status is: Scheduled / Pending. But, if open the Immunizations Listing, the Status is Completed / Acquired.
This behaviour happens for both new immunizations and for the existing ones.
![image](https://user-images.githubusercontent.com/89522688/142181047-b8be791c-d708-43bd-a319-0ccce36db324.png)
![image](https://user-images.githubusercontent.com/89522688/142181075-74807102-4960-4b53-a075-eba7a4852ecd.png)
![image](https://user-images.githubusercontent.com/89522688/142181092-d0ef7525-5b91-4fcb-bc5d-6b4034d37142.png)

**Comment by roxanamlendea** [comment] 2021-11-19 11:36
The last problem that I found (the fact that if I overwrite the immunization status management, the change doesn't persist after save) is now fixed, but now, if I edit an existing immunization and I change the means of immunization, the status is not updated accordingly..![immunization status](https://user-images.githubusercontent.com/89522688/142616492-385be5ec-008e-4a5d-bf1f-566ba17703ca.gif)

**Comment by syntakker** [comment] 2021-11-19 12:16
For editing existing immunizations, this behaviour is intended and it is that of the web app:
- If the means of immunization is changed from `Vaccination` to `Recovery` the status is updated
- If the means of immunization is changed back, however, the status `completed` is never reset to `scheduled`

This is in accordance with @MateStrysewske's requirement of the Android app's behaviour being identical to that of the web app: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7164#issuecomment-971344174

**Comment by MateStrysewske** [comment] 2021-11-19 12:40
Yes, as long as it's consistent between the mobile and web app, I'm fine with the status not being reset when changing from recovery to vaccination.

**Closed by MateStrysewske** 2021-11-19 12:40 UTC
Labels: bug, android-app, hotfix, immunizations

**Comment by roxanamlendea** [comment] 2021-11-19 12:57
Verified ticket on Android Studio connected to the local server, on the hotfix branch 1.65.1-SNAPSHOT
