### ISSUE TITLE
New Login Page Design [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#593] opened 2018-05-09 15:03 UTC

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-27 13:34
@hzi-braunschweig How exactly should the login page look like. Please provide a mockup picture.

**Comment by hzi-braunschweig** [comment] 2018-07-27 13:37
![image](https://user-images.githubusercontent.com/19344651/43323802-e769b336-91b2-11e8-85b7-474217ef1d88.png)
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment] 2018-07-27 13:57
Ok, we will put this into the next sprint. Bugs & stability have priority now

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-14 13:07
- [ ] implement design as in mockup
- [ ] on small screens the left part should be displayed below the form (as in the current design)

Ignore the "remember me" for now.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-08-17 14:16
Just realized that we are still using the oldschool LoginForm. This has to be replaced with our own implementation.

**Comment by MateStrysewskeSym** [comment] 2019-08-07 11:22
Duplicate of #1194

**Closed by MateStrysewskeSym** 2019-08-07 11:22 UTC
Labels: Design & Usability, sormas-ui
