### ISSUE TITLE
Some case persons cannot be saved due to a validation problem

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3451] opened 2020-11-11 12:05 UTC
### Bug Description
I have some cases with a person that I cannot save.
This does not apply to all persons. At the moment I have only one person that I cannot save. I don't know what conditions have to be met for the problem to occur. @FredrikSchaefer suspects that it could be related to the External Journal Interface. But I have not configured an external journal.

Additionally the error message is in German although English is set as language.
### Steps to Reproduce
???
Example Case ID on my local system: UNHB4Z-HOXMPS-IFPIPT-U2BYCKSM

### Expected Behavior
Saving is possible.
Message is in English.

### Screenshots
![Screenshot_005](https://user-images.githubusercontent.com/42139870/98809115-5db92b80-241d-11eb-8532-924966be1fa8.png)
### System Details
* Device: PC
* SORMAS version: 1.52.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL:
* User Role: National User

**Comment by syntakker** [comment] 2020-11-11 14:14
The error occurs in `ExternalJournalService.getValidationMessage` (only use of this error message).
Can you provide a stacktrace or an export of the failing case on your local system?

**Comment by syntakker** [comment] 2020-11-11 14:24
More precisely, it happens here (`PersonFacadeEjb`, L. 323, called whenever an existing person is saved):
```java 
	private void handleExternalJournalPerson(PersonDto existingPerson, PersonDto updatedPerson) {
		SymptomJournalStatus status = existingPerson.getSymptomJournalStatus();
		if (SymptomJournalStatus.REGISTERED.equals(status) || SymptomJournalStatus.ACCEPTED.equals(status)) {
			ExternalPersonValidation validationResult = externalJournalService.validatePatientDiaryPerson(updatedPerson);
			if (!validationResult.isValid()) {
				throw new ValidationRuntimeException(validationResult.getMessage());
			}
		}
		// 5 second delay added before notifying of update so that current transaction can complete and new data can be retrieved from DB
		final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
		Runnable notify = () -> externalJournalService.notifyExternalJournalPersonUpdate(existingPerson, updatedPerson);
		executorService.schedule(notify, 5, TimeUnit.SECONDS);
	}
```
In `ExternalJournalService.validatePatientDiaryPerson` the validation of phone numbers appears to be quite strict:
```java
		if (StringUtils.isNotEmpty(email)) {
			EmailValidator validator = EmailValidator.getInstance();
			validEmail = validator.isValid(email);
		}
		if (StringUtils.isNotEmpty(phone)) {
			validPhone = false;
			PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
			try {
				Phonenumber.PhoneNumber germanNumberProto = phoneUtil.parse(phone, "DE");
				validPhone = phoneUtil.isValidNumber(germanNumberProto);
			} catch (NumberParseException e) {
				logger.warn("NumberParseException was thrown: " + e.toString());
			}
		}
		boolean validBirthdate = true;
```
especially it seems that only valid German phone numbers are accepted?

**Comment by ChristopherRiedel** [comment] 2020-11-12 07:42
Unfortunately I cannot provide a stacktrace because it is not an error.
Here is an export of the example case:

[#3451 example case.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5528950/3451.example.case.xlsx)

**Comment by vlad-ciucescu** [comment] 2020-11-12 12:31
It seems the problem is with generated case persons, which also get a random symptom journal status assigned. I will change the method to generate only persons without a symptom journal status.

The solution if you have this problem (and are not using the CLIMEDO/PIA interface) is to set the `symptomjournalstatus` of each person to `NULL` in the database.

**Comment by syntakker** [comment] 2020-11-12 12:46
@ChristopherRiedel the case export you privided does not include the email address, which might cause the error here, too.

In the above code, `StringUtils.isNotBlank` should be used instead of `StringUtils.isNotEmpty` to avoid blank Strings that are neither empty nor null.

**Comment by vlad-ciucescu** [comment] 2020-11-12 12:48
@syntakker the validation should not take place at all, the persons were falsely marked as being registered in an external symptom journal

**Comment by syntakker** [comment] 2020-11-12 13:01
@vlad-ciucescu true, and in this case, empty phone number and empty email already explains the error.

**Closed** 2020-11-17 09:32 UTC
Labels: bug
