### ISSUE TITLE
Case directory still displays cases shared with the whole country by default

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3461] opened 2020-11-11 18:09 UTC
### Bug Description
Cases and contacts in directories don't seem to be displayed properly by the user's jurisdiction by default. Cases from other jurisdictions are shown as well and when clicking the checkbox 'Include cases from other jurisdictions', most other cases are still hidden. The contact directory seems to properly only show contacts in the jurisdiction but doesn't show all contacts when applying 'Include contacts from other jurisdictions'.
### Steps to Reproduce
1. Log in as a user that has regional restrictions.
2. Go to the case directory and check displayed cases by jurisdiction.
3. Include cases from other jurisdictions and check list again.

### Expected Behavior
Only cases and contacts belonging to the users jurisdiction should be shown by default. Upon including cases/contacts fro other jurisdictions, all cases/contacts (active) should be shown.
### Screenshots
<img width="1264" alt="Screen Shot 2020-11-11 at 6 47 47 PM" src="https://user-images.githubusercontent.com/70317594/98847891-3aa86f00-2451-11eb-8628-2f361d06ca76.png">
<img width="1269" alt="Screen Shot 2020-11-11 at 6 48 58 PM" src="https://user-images.githubusercontent.com/70317594/98847907-3ed48c80-2451-11eb-98c3-6e34c606bdda.png">
<img width="537" alt="Screen Shot 2020-11-11 at 6 50 08 PM" src="https://user-images.githubusercontent.com/70317594/98847924-43994080-2451-11eb-9d24-00a0a7080114.png">

### System Details
* Device:
* SORMAS version: 1.51.0
* Android version/Browser: chrome, firefox
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance Officer

**Comment by MateStrysewske** [comment] 2020-11-12 09:46
* Seems like the reason why the cases are displayed is because cases "shared with the whole country" are still shown by default

**Comment by kwa20** [comment] 2020-11-12 09:53
@MateStrysewske I can confirm this. I've unticked the checkbox with another user and the case is then not shown for the other user anymore.

**Comment by MateStrysewske** [comment] 2020-11-12 10:11
@kwa20 I'll fix this by completely removing the "Exclude shared cases" checkbox. It basically clashes with the new "Include cases from other jurisdictions" checkbox and doesn't really make sense anymore.

What's hard for me to reproduce is your observation that some cases that you should get access to by checking the "Include cases/contacts from other jurisdictions" still don't appear in the directories. Can you give me a bit more detail on that?

**Comment by MateStrysewske** [comment] 2020-11-12 10:20
@kwa20 Please keep in mind that even if you tick this checkbox, you'll only see cases that you have the rights to see, e.g. because you reported them or because there's a contact to that case that is inside your jurisdiction. You'll still not see cases from other jurisdictions that you have absolutely no relation to.

**Comment by kwa20** [comment] 2020-11-12 10:35
@MateStrysewske I've checked again and I think I expected a different behaviour for the filter than what it actually does. The difference of 1 case that you see in the screenshots above is a case that has been created by the same user (TestUser3) but lies in another jurisdiction than what the user is assigned to.

Do you think we should somehow specify this? E.g. naming the filter 'Include cases from other jurisdiction you are allowed to see'? Or is this lengthy?

**Comment by MateStrysewske** [comment] 2020-11-12 10:40
@kwa20 So you think the filter is working fine and the problem is rather that too many cases are displayed in the first place, right?

I'd add a description that is displayed when the user hovers over the checkbox to give a bit more detail, I think that's a good compromise. What do you say?

**Comment by kwa20** [comment] 2020-11-12 10:43
@MateStrysewske Exactly! I think the mouseover is a good solution.

**Comment by raghupola-vg** [comment] 2020-11-13 17:09
tested and verified. The mouse hover now displays the required information both for cases and contacts.

**Comment by kwa20** [comment] 2020-11-14 14:37
@MateStrysewske The cases shared with the whole country are not shown by default anymore. However, cases from other jurisdictions who have a contact in the jurisdiction of the user are still displayed and contradict the filter (description). It seems to fine for contacts though.

<img width="1280" alt="Screen Shot 2020-11-14 at 3 21 56 PM" src="https://user-images.githubusercontent.com/70317594/99149509-c955ff80-268e-11eb-865d-3dd19aaa4fa6.png">

**Comment by bernardsilenou** [comment] 2020-11-14 15:24
@kwa20 Yea, we carry it over to the next sprint.

**Comment by MateStrysewske** [comment] 2020-11-23 08:27
Moved to #3549 because this issue was already merged.

**Closed by MateStrysewske** 2020-11-23 08:27 UTC
Labels: Verified by QA, bug, hotfix
