### ISSUE TITLE
Add lazy loading to event participants grid [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3845] opened 2020-12-21 01:19 UTC
### Problem Description

- Opening the ep tab on with 1040 ep takes 1 min. To Reproduce:
1. connect to test1401
2. open the ep tab for event with uuid = WGYIVS-YEGH3C-K5DAWP-6WTICAKY

Expected Behavior:
- Should take about 2 seconds. 
- This issues may also apply to the all sub tabs like contact within a case. Thus we also need to apply the solution (maybe lazy loading) to the contact tab within a case.

### Proposed Change

- [x] Add support for lazy loading to the event participants grid (this includes adding a button to switch between both alternatives like in other grids)
- [x] Make lazy grid the default for event participants and case contacts

### Additional Information

* SORMAS version: 1,52,1
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/#!events/eventparticipants/WGYIVS-YEGH3C-K5DAWP-6WTICAKY
* @StefanKock: Event participants grid is only concerning one event. It's likely that the user filters cause delays, but not the amount of participants per event.

**Comment by bernardsilenou** [comment] 2020-12-21 01:19
@kwa20

**Comment by kwa20** [comment] 2020-12-21 08:30
I suspect this to occur because the event participant list is not loading lazily.

**Comment by MateStrysewske** [comment] 2021-01-04 09:29
To-Do:
- [ ] Add support for lazy loading to the event participants grid (this includes adding a button to switch between both alternatives like in other grids)
- [ ] Make lazy grid the default for event participants and case contacts

**Comment by roxanamlendea** [comment] 2022-08-24 11:51
Reopening the ticket because the issue needs to be implemented also for Case Contacts

**Comment by roxanamlendea** [comment] 2022-08-25 07:56
As it was decided in today's daily, I'm closing the ticket and the lazy loading for the Case Contacts tab will be implemented in a separate issue. A new ticket will be opened in regards to this.

**Comment by roxanamlendea** [comment] 2022-08-25 11:35
Reopening the ticket because the bulk checkboxes appear, even if Bulk Edit Mode is not enabled.
![image](https://user-images.githubusercontent.com/89522688/186653828-9ae999e1-5a4b-4d24-b807-4326e032df9b.png)

**Comment by roxanamlendea** [comment] 2022-08-26 12:30
I'm reopening the ticket because an error is thrown when bulk edit mode is disabled and the user clicks on 'Case Count', 'Final Laboratory Result' or 'Date Sample was collected'. (the Event needs to have at least one Event Participant in order to reproduce the bug).

![image](https://user-images.githubusercontent.com/89522688/186903539-1e726ba1-bac1-44d4-a43d-fdcd923b0319.png)

**Comment by roxanamlendea** [comment] 2022-08-26 13:51
Bulk Edit mode gets disabled when the user applies a filters or navigates through the other tabs.

![EP tab](https://user-images.githubusercontent.com/89522688/186918688-f4ba2bc0-9edd-4d00-8e79-dc40b6326c9d.gif)

**Comment by roxanamlendea** [comment] 2022-09-07 12:26
I have found another issue regarding the Bulk Edit Mode.
1. User is on the Event Participants tab (Bulk Edit mode is not enabled);
2. User imports Event Participants.
-> After the Event Participants are imported, the Bulk Edit mode is automatically enabled. However, when the user refreshes the page, the Bulk Edit Mode is disabled again.

**Closed** 2022-09-19 11:22 UTC
Labels: refactoring, events, vaadin-app, change, performance

**Comment by roxanamlendea** [comment] 2022-09-20 11:29
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT from the development branch.
